### ISSUE TITLE
Use actual raw line for ParserBot.recover_csv

### ISSUE THREAD

**Issue by wagner-certat** [certtools/intelmq#1011]
@chorsley has a neat solution: https://github.com/chorsley/intelmq/blob/962d630bd2a3eb7991f905d5ab795835ff1e9725/intelmq/bots/parsers/zoneh/parser.py#L15

This way we do not need to reconstruct the raw line.

**Comment by chorsley** [comment]
This code has been submitted in `lib/bot.py` via #1015.

**Comment by wagner-certat** [comment]
@chorsley This adds the code to the zoneh parser, not to the common functions.

**Comment by chorsley** [comment]
@wagner-certat given current time constraints, I'll need to come back to that later, unless someone beats me to it.

**Comment by wagner-certat** [comment]
I'll move the code to the proper place in lib/ once the PR is merged. That involves many other adaptions too.
