### ISSUE TITLE
URL Feeds That Aren't Working

### ISSUE THREAD

**Issue by mf370** [certtools/intelmq#1018]
I was testing the IntelMQ Feeds and I found that some URLs were not available:

Malware Domains:
[http://mirror2.malwaredomains.com/files/domains.txt](url)

OpenBL:
[https://www.openbl.org/lists/date_all.txt](url)

**Comment by wagner-certat** [comment]
Thanks for checking the docs!

malwaredomains' mirror2 has a temporary outage: http://www.malwaredomains.com/?p=4094
I will set another mirror in the docs.

But openbl is offline forever: https://twitter.com/sshblorg/status/854669263671615489
