### ISSUE TITLE
Custom bots couldn't be found by intelmq

### ISSUE THREAD

**Issue by Narzhan** [certtools/intelmq#1038]
Hello, I created some custom bots using the Developers-Guide and I encountered an issue with all of them with the following error _xyz-parser failed to START because the file cannot be found_. The ___init_.py_ file is in the directory of the respective bot. I tried the -e installation with --upgrade after I created the new bots with no result. 
Path to one of the bots: `intelmq/bots/parsers/xyz/parser.py`.
Configuration for the given bot in runtime.conf: 
`"xyz-parser": {
        "description": "xyz parser",
        "group": "Parser",
        "module": "intelmq.bots.parsers.xyz.parser",
        "name": "Xyz",
        "parameters": {}
    },`
I didn't know whether it is a bug or I forgot something so this rather call for help rather than anything else.

**Comment by wagner-certat** [comment]
Is the bot mentioned in the BOTS file? Does the file /usr/(local/)bin/intelmq.bots.parsers.xyz.parser exist?

In the future please use the [intelmq-users mailinglist](https://lists.cert.at/cgi-bin/mailman/listinfo/intelmq-users) for support. Thanks.

**Comment by Narzhan** [comment]
I was missing the definitions in the /user/local/bin/ folder, but it just solved the issue with starting the bot another one appeared (bot is not actually running). Could you please point me towards some more info about this particular thing so I can validate whether I made some mistake in creation of that file (manually crate file and change permissions)

**Comment by wagner-certat** [comment]
See https://lists.cert.at/pipermail/intelmq-users/2017-July/000003.html for further correspondence.
