### ISSUE TITLE
Screenshot expert

### ISSUE THREAD

**Issue by wagner-certat** [certtools/intelmq#1048]
Create screenshots of URLs.

Depends on some infrastructure for saving/serving screenshots, needs to be discussed first. First simple proposal:
* save the file in a defined directory, filename is a generated UUID
* a URL-prefix is defined in the parameters
* screenshot_url is prefix + filename

Candidate for a screenshot module: [python-webkit2png](https://github.com/adamn/python-webkit2png/), not good maintained, thus requires a fork of it to merge all open PRs from there.

**Comment by navtej** [comment]
What do you think of using headless chrome for it? I dont like the dependency on chrome though. However it will be much better solution.

**Comment by wagner-certat** [comment]
We can't avoid a dependency. We can also have multiple supported browsers if that is necessary.

An argument for chrome/chromium is, that it is widespread - and the rendering shouldn't have surprises.

**Comment by aaronkaplan** [comment]
We will need this for 3.0

**Comment by wagner-certat** [comment]
In the last IHAP meeting [lookyloo](https://www.lookyloo.eu/docs/main/index.html) was mentioned as possible screenshotting service, although slow.

**Comment by wagner-certat** [comment]
fixed by #1844
