### ISSUE TITLE
Rename 'source_time' and 'observation_time'

### ISSUE THREAD

**Issue by SYNchroACK** [certtools/intelmq#107]
**Reason:** since we have the following names for keys, doest make sense have 'source_time' because it will be misunderstood.

* 'source_*' names for keys related to source of connection
* 'destination_*' names for keys related to destination of connection

**Suggestion:**
* 'source_time' -> 'timestamp'
* 'observation_time' -> 'system_timestamp'

**Comment by Phantasus** [comment]
I want to add another argument against renaming source_time:

When we rename it, it's not compatible to AbuseHelper (https://bitbucket.org/clarifiednetworks/abusehelper/wiki/Data%20Harmonization%20Ontology)

Someone could then add that compatibilty in every circumstances is a stupid idea as that could lead to complexity (e.g X86, Windows ...) but in our case compatibility is simple and what do we gain from that? 

As @aaronkaplan pointed out we don't get clearity, we get IMHO unclearity. And if we get that, then why do we write this software?

**Comment by SYNchroACK** [comment]
I will close this issue because its a harmonization discussion and we have some issues regarding this topic. Please comment there any harmonization ideas, etc...

**Comment by SYNchroACK** [comment]
Check: https://github.com/certtools/intelmq/issues/185
