### ISSUE TITLE
log level is info at beginning of interactive run

### ISSUE THREAD

**Issue by wagner-certat** [certtools/intelmq#1075]
When running bots interactively, the log level is not debug at the beginning:
```
> intelmqctl run malc0de-parser 
intelmqctl: Starting malc0de-parser...
malc0de-parser: Malc0deParserBot initialized with id malc0de-parser and intelmq 1.1.0.alpha1 and python 3.4.6 (default, Mar 22 2017, 12:26:13) [GCC] as process 8765.
malc0de-parser: Bot is starting.
malc0de-parser: Loading source pipeline and queue 'malc0de-parser-queue'.
malc0de-parser: Connected to source queue.
malc0de-parser: Loading destination pipeline and queues ['deduplicator-expert-queue'].
malc0de-parser: Connected to destination queues.
malc0de-parser: Pipeline ready.
malc0de-parser: Waiting for incoming message.
```

In the debug mode, all parmeters should be logged, which is not the case here. Also, the configured log level *is* debug, so it should be shown in any case.

**Comment by wagner-certat** [comment]
using bisecting I found this bad commit: 31ff5c0d20f05fbec16eba99f1d0583b2827cf34

cc @e3rd

**Comment by e3rd** [comment]
Sorry, could you please explain further? While using `run` command, the initial logging level is set as follows:
`init_log_level = {"console": logging.DEBUG, "message": logging.WARNING, "process": logging.INFO, None: logging.INFO}`

* You mean that we should change `process` and `None` keys to `logging.DEBUG`?
* What do you mean by "Also, the configured log level is debug" – where is that configured please?

**Comment by wagner-certat** [comment]
Okay, found the reason.

Before 31ff5c0 the log level DEBUG has been set for `intelmqctl run`. After that commit, the log level is INFO for `intelmqctl run` and DEBUG for `intelmqctl run botid console`.

The docs are still on the state before 31ff5c0 https://github.com/certtools/intelmq/blob/maintenance/docs/intelmqctl.md#run (DEBUG for run, not INFO). So the docs should be fixed.

Thinking more about it: As `intelmqctl run` is just the interactive version of `intelmqctl start` now, we could actually use the configured log level and not modify it at all in that case.

**Comment by wagner-certat** [comment]
Hm, why should the run-command set a higher log level than the configured one? So I'd only set it to DEBUG for the console subcommand (because it's for debugging) at leave the others at the configured value. We could also add a commandline argument for that.

**Comment by e3rd** [comment]
Quite often, I use `process` subcommand to debug the bot. In the bot source code, I add `import ipdb; ipdb.set_trace()` to get to the console at specified line. (Subcommand `console` gets you to console **before** the bot processes something.)  
Like this, I can easier debug a bot.

...
I agree to add an argument for that. Would you prefer I add a `-v --verbose` flag for settings DEBUG level or to have `-d --debuglevel [INFO|DEBUG|...]` argument?

**Comment by aaronkaplan** [comment]
I agreed with @e3rd here: the expectation of a user (typical unix user) would be:
  * if ``-l --loglevel [INFO|DEBUG|...]`` is given on the command line, then this option overrides the config file
  * otherwise the configured loglevel from the config file is chosen.
