### ISSUE TITLE
MISP Collector question

### ISSUE THREAD

**Issue by 0xffca** [certtools/intelmq#1087]
Hello, 
I am fairly new to IntelMQ, I wanted to import events from my MISP instance but it is not entirely clear to me how to import all events from MISP regardless of the tag.
What should I put in here?

misp_tag_processed:
misp_tag_to_process: 

Thank you!

**Comment by wagner-certat** [comment]
Do you know the docs? https://github.com/certtools/intelmq/blob/develop/docs/Bots.md#misp-generic https://github.com/certtools/intelmq/blob/develop/intelmq/bots/collectors/misp/README.md

Unfortunately there are two places for the docs -.-

Please use the [intelmq-users mailinglist](https://lists.cert.at/cgi-bin/mailman/listinfo/intelmq-users) for support. Thanks.

**Comment by 0xffca** [comment]
Thanks for the answer! Yes I found both docs and I will subscribe to the mailinglist asap!
My question was more regarding downloading all the events regardless of the tag they have, and I think this should be done by adding a private-only tag to all misp events for intelmq to be processed..
Cheers!
