### ISSUE TITLE
Named and addressable destination pipelines

### ISSUE THREAD

**Issue by wagner-certat** [certtools/intelmq#1088]
with multiple destinations / destination groups it would be possible for the filter and sieve expert to push messages to one of the queues based on the message content

**Comment by navtej** [comment]
+1 for this. One use could be an expert which can do complex arithmatic based load balancing, an upgrade to load_balance param.

**Comment by wagner-certat** [comment]
can be used for the filter-expert and the sieve-expert

**Comment by e3rd** [comment]
I've just finished second draft in branch.  
When we finish this [comment](https://github.com/certtools/intelmq/commit/b65a3154bf80aef74cae1524e498aa887089b2a1#r27223975) and make intelmq-manager ready, I may pull merge this into develop branch.

**Comment by wagner-certat** [comment]
> One use could be an expert which can do complex arithmatic based load balancing, an upgrade to load_balance param.

For that I'd rather use better messaging queues such as RabbitMQ. I'm currently working on that to see how they name things.

**Comment by wagner-certat** [comment]
> I may pull merge this into develop branch.

Please open a PR.

**Comment by e3rd** [comment]
I've opened a [PR](https://github.com/certtools/intelmq/pull/1190). When merged, we should still have that issue open at least till:
* [ ] `intelmqctl run ... send` add path parameter.
* [ ] intelmq-manager is able to handle this

**Comment by wagner-certat** [comment]
fixed by #1190

**Comment by e3rd** [comment]
Are you sure to close this ticket? #1190 solved the most important part but I still had two tasks right [above](https://github.com/certtools/intelmq/issues/1088#issuecomment-366021269)

**Comment by wagner-certat** [comment]
Hm, the actual problem is solved, concerning the manager -> issue there: https://github.com/certtools/intelmq-manager/issues/154 and for the ctl tool here: #1210
