### ISSUE TITLE
dead bots reported as alive

### ISSUE THREAD

**Issue by e3rd** [certtools/intelmq#1089]
Something killed some of our bot processes. We don't know what, they just died without leaving a notice in the log. Their PID files stayed at place.
But then, other starting processes got the same ID the old processes had.
Intelmqctl didn't know 31/105 of the bots were not running, yet it showed they are running (because of the other bots with the same ID).
When starting a new process, shouldn't intelmqctl check all the PIDs somehow ...?

I've been thoroughly searching for this issue here but without success. Just tell how to solve this and I'll try to implement it.

**Comment by wagner-certat** [comment]
Do you have commits a8d86662afb6e7b4402d8ce4caffb97b5003205f and 64ea33646f887f8917d48263582e4ac846cc1710? It's part of 1.0.1 and develop. That checks the process name of the process with the given PID and compares it with the value it should be.

I just cherry-picked the second commit (a bug fix) to develop.

**Comment by e3rd** [comment]
It seems great, thank you!
