### ISSUE TITLE
End of support for Python 3.3

### ISSUE THREAD

**Issue by wagner-certat** [certtools/intelmq#1092]
Python 3.3 does not receive security updates beyond September 2017 - i.e. now. Distributions may still provide support for them.

No distribution we are currently supporting with packages does use 3.3, the oldest all use 3.4 already (RHEL 7 / Ubuntu 16.04 / Leap 42.2). So I think we can drop support for it.

Source: https://www.python.org/dev/peps/pep-0398/ https://docs.python.org/devguide/#status-of-python-branches

**Comment by hugovk** [comment]
3.3 is now EOL.
