### ISSUE TITLE
Optionally use faup for URL parsing

### ISSUE THREAD

**Issue by wagner-certat** [certtools/intelmq#1103]
@aaronkaplan [suggested](https://github.com/certtools/intelmq/issues/778#issuecomment-260983670) to use faup for URL parsing instead of python's urllib.

I currently don't see a reason to require and use it, there are no know cases where urllib fails or works wrong (jn intelmq).

IMO faup could be a weak dependency which is used of it exists. but not a hard requirement to keep the number of dependencies low (and thus the number of possible problems...).

**Comment by aaronkaplan** [comment]
I think this one can be closed. I used faup in another project and it's quite slow.
