### ISSUE TITLE
Rules for harmonization keys not enforced and not sufficient

### ISSUE THREAD

**Issue by wagner-certat** [certtools/intelmq#1104]
The current [data harmonization docs say](https://github.com/certtools/intelmq/blob/9fb52b38d6b56a099c1b6de0a0b4d663d386a243/docs/Data-Harmonization.md#rules-for-keys) that any key must match the regular expression `[a-z_.]`. Actually this is not enough, as `extra.` shouldn't be allowed just as `extra..foo`.

Currently both keys are allowed too, as it only checks if they exists in the harmonization configuration and, if the type is a JSONDict anything behind the dot is not checked.

**Comment by wagner-certat** [comment]
The regular expression `^[a-z_](.[a-z_]+)*$` could work:
```python
>>> re.match('^[a-z_](.[a-z_]+)*$', 'extra.foo.asd')
<_sre.SRE_Match object; span=(0, 13), match='extra.foo.asd'>
>>> re.match('^[a-z_](.[a-z_]+)*$', 'extra.foo.')
>>> re.match('^[a-z_](.[a-z_]+)*$', 'extra..')
```

**Comment by wagner-certat** [comment]
Any thoughts @aaronkaplan?

**Comment by aaronkaplan** [comment]
I'd even be willing to relax the RE to  ``^[a-z_](.[a-z_0-9]+)*$``

**Comment by wagner-certat** [comment]
Sure
