### ISSUE TITLE
Improve IP lookup

### ISSUE THREAD

**Issue by SYNchroACK** [certtools/intelmq#111]
python adns library: https://pypi.python.org/pypi/adns-python/1.2.1

**Comment by aaronkaplan** [comment]
why is this closed without any discussion?

**Comment by SYNchroACK** [comment]
The current solution is the better, just need thread support.

**Comment by aaronkaplan** [comment]
I am not sure if I agree.

**Comment by Phantasus** [comment]
To summarize from what I think to understand: This issue was opened because of slow DNS resolving. Then we had the threading experiment, which hasn't taken off and which was done by @SYNchroACK.

@aaronkaplan wasn't sure if we could include that or should have a discussion about that. 

Why am I writing this? Because I think I summarize that for everybody watching this project who wants to add his 2 cents to this issue. 

Can you both agree on my summary?

**Comment by robcza** [comment]
Just encountered a situation where I would like to resolve IPs for collected domains/URLs. Is this the right thread to discuss? There is an expert bot for reverse DNS lookup, should there be one for forward lookup as well?

**Comment by aaronkaplan** [comment]
Yes Rob, I believe this here is a good point to discuss IP address lookup (forward, reverse).

Yes, it is a bottleneck. I have been looking at the adns library (there is even a python lib for that): [adns](http://www.chiark.greenend.org.uk/~ian/adns/) sends out many DNS requests asynchronously and will collect the answers. However, it seems a bit tricky to integrate. 

What do you think?

**Comment by chorsley** [comment]
I've used this Python adns code in the past and it's worked quite well for me: http://www.catonmat.net/blog/asynchronous-dns-resolution/

**Comment by robcza** [comment]
@aaronkaplan tricky part you mean how to actually implement the async part? Do you think it is a smart way to do it in batches? To pop n events from the queue, let adns resolve them all and repeat?

It kinda feels it breaks the concepts of IntelMQ and I like the multithreaded solution @SYNchroACK mentioned. However I don't think that will be ready in the near future, seems quite complex.

**Comment by SYNchroACK** [comment]
@robcza , yap, multi-thread solution was drop. ADNS will not solve the problem since the bottleneck is the pipeline but we can create a bot that using adns and if we use the zmq as pipeline we can take advantage of that bot.

**Comment by aaronkaplan** [comment]
On Aug 23, 2015, at 5:39 PM, Tomás Lima <notifications@github.com> wrote:

> @robcza , yap, multi-thread solution was drop. ADNS will not solve the problem since the bottleneck is the pipeline but we can create a bot that using adns and if we use the zmq as pipeline we can take advantage of that bot.

I do not believe that the bottleneck is the pipeline at all.
I did some tests with redis and achieved between 500k-800k basic operations (LPUSH etc) per second.
That should be enough IMHO.

**Comment by SYNchroACK** [comment]
@aaronkaplan we already had this conversation. The tests that you did are different from the intelmq solution.
Remember, IntelMQ do:
* pop | process message | push | lindex | llen

So... its not a batch operation that you are mentioning...

**Comment by navtej** [comment]
Not directly related to the discussion, just throwing in my 2 bits from the experience. 

I implemented a crude solution using gevents, however redis does not support msg identification and I had to drop gevent solution, after couple of hacks to get it right by hacking lib to add support for msgIDs. 

What worked for me was horizontal scaling with multiple bot instances and load balancing.

An library provided solution would be nice to have. What we need is message ID and acknowledgement/forwarding message from queues by msgID. If we can land such a solution with redis, I believe, gevents could be much better solution than threading. It has been a while, I don't recall exact details, however roughly I remember running up to 500 green threads, on mid sized azure vm, with other bots running as well. I had enabled gevent threads for about 3-4 bots.

**Comment by wagner-certat** [comment]
> I implemented a crude solution using gevents, however redis does not support msg identification and I had to drop gevent solution, after couple of hacks to get it right by hacking lib to add support for msgIDs.

RabbitMQ supports Message IDs: https://www.rabbitmq.com/consumers.html (search for "Message ID"), needs to be set by the publisher (the send component), but can be generated as a UUID.

On the UUID/message topic see also: https://github.com/certtools/intelmq/issues/901
https://github.com/certtools/intelmq/issues/543#issuecomment-233561823
(with a different focus though, as in the case here we need unique IDs - hashes?)

> What worked for me was horizontal scaling with multiple bot instances and load balancing.

Yeah, multiprocessing is definitely something that we need / or: support better. the manual configuration is nothing we can be proud of.

> An library provided solution would be nice to have. What we need is message ID and acknowledgement/forwarding message from queues by msgID. If we can land such a solution with redis, I believe, gevents could be much better solution than threading. It has been a while, I don't recall exact details, however roughly I remember running up to 500 green threads, on mid sized azure vm, with other bots running as well. I had enabled gevent threads for about 3-4 bots.

Such a pre- /batch-fetching mechanism would be useful for the DNS bots for sure. I welcome all efforts :)
