### ISSUE TITLE
data visualization kibana

### ISSUE THREAD

**Issue by novitski** [certtools/intelmq#1115]
Hello ,

How can i do for visualization feeds informations on kibana ? 

There is intergration tutoriel for that  ? 

Thanks

**Comment by aaronkaplan** [comment]
> On 09 Nov 2017, at 16:10, novitski <notifications@github.com> wrote:
> 
> Hello ,
> 
> How can i do for visualization feeds informations on kibana ?
> 
> There is intergration tutoriel for that ?
> 

not yet, but good point, we should make a tutorial for that.
Thx

**Comment by novitski** [comment]
Thanks for you answer.

I understand that there is no tutoriel, but there is any method for integration ? 

Thx

**Comment by navtej** [comment]
Can you elaborate on what visualization you need? Cant you use Elasticsearch output Bot to output to ES and then use Kibana?

**Comment by SYNchroACK** [comment]
@novitski if you have successfully installed kibana and elasticsearch on a machine, then you can follow this approach:

1. Use elasticmapper to define the intelmq fields mapping on your elasticsearch instance: [elasticmapper](https://github.com/certtools/intelmq/tree/develop/contrib/elasticsearch)

```
elasticmapper --harmonization-file=intelmq/intelmq/etc/harmonization.conf --index=intelmq --index-type=events --host=<your ES machine IP> --harmonization-fallback
```

2. Add ElasticSearch Output Bot to your IntelMQ pipeline with the following `runtime.conf`:
```
"elasticsearch-output": {
    "description": "Elasticsearch is the bot responsible to send events to a elasticsearch.",
    "module": "intelmq.bots.outputs.elasticsearch.output",
    "group": "Output",
    "name": "ElasticSearch",
    "enabled": true
    "parameters": {
        "elastic_host": "<your ES machine IP>",
        "elastic_port": 9200,
        "elastic_index": "intelmq",
        "elastic_doctype": "events",
        "http_username": null,
        "http_password": null,
        "flatten_fields": "extra",
        "replacement_char": "_"
    }
},
```

3. Access your Kibana interface and add `events` index to your Kibana settings.
