### ISSUE TITLE
Problem with PostgreSQL

### ISSUE THREAD

**Issue by chappi6** [certtools/intelmq#1116]
Hi, 

I am trying to install PostgreSQL and get it up and running with the Output Bot. 
Well now my problem is that the init script for the db wont work. 
Any ideas whats wrong? 

```
[root@intelMq intelmq]# intelmq_psql_initdb
INFO - File /tmp/initdb.sql exists, generating temporary file.
INFO - Reading /etc/intelmq/harmonization.conf file
Traceback (most recent call last):
  File "/usr/bin/intelmq_psql_initdb", line 9, in <module>
    load_entry_point('intelmq==1.0.2', 'console_scripts', 'intelmq_psql_initdb')()
  File "/usr/lib/python3.4/site-packages/intelmq/bin/intelmq_psql_initdb.py", line 88, in main
    psql = generate()
  File "/usr/lib/python3.4/site-packages/intelmq/bin/intelmq_psql_initdb.py", line 29, in generate
    DATA = json.load(fp)['event']
  File "/usr/lib64/python3.4/json/__init__.py", line 268, in load
    parse_constant=parse_constant, object_pairs_hook=object_pairs_hook, **kw)
  File "/usr/lib64/python3.4/json/__init__.py", line 318, in loads
    return _default_decoder.decode(s)
  File "/usr/lib64/python3.4/json/decoder.py", line 343, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib64/python3.4/json/decoder.py", line 361, in raw_decode
    raise ValueError(errmsg("Expecting value", s, err.value)) from None
ValueError: Expecting value: line 7 column 1 (char 6)
```

EDIT 2017-11-13 11:36+01 by @wagner-certat: markup

**Comment by wagner-certat** [comment]
Your harmonization.conf seems to be invalid JSON. Can you have a look at line 6 and 7 of the file and post it here? I'd like to check if it's a problem at my side.

**Comment by chappi6** [comment]
Ah sorry my fault, I messed something up with copy pasting. 
But now i got a different error: 

INFO - Reading /etc/intelmq/harmonization.conf file
Traceback (most recent call last):
  File "/usr/bin/intelmq_psql_initdb", line 9, in <module>
    load_entry_point('intelmq==1.0.2', 'console_scripts', 'intelmq_psql_initdb')()
  File "/usr/lib/python3.4/site-packages/intelmq/bin/intelmq_psql_initdb.py", line 88, in main
    psql = generate()
  File "/usr/lib/python3.4/site-packages/intelmq/bin/intelmq_psql_initdb.py", line 60, in generate
    raise ValueError('Unknown type %r.' % value['type'])
ValueError: Unknown type 'ASN'. 

and here is the config from  harmonization.conf: 

        "destination.as_name": {
            "description": "The autonomous system name to which the connection headed.",
            "type": "String"
	},
        "destination.asn": {
            "description": "The autonomous system number to which the connection headed.",
            "type": "ASN"
	},
        "destination.fqdn": {
            "description": "A DNS name related to the host from which the connection originated. DNS allows even binary data in DNS, s$
            "regex": "^.*[^\\.]$",
	    "type": "FQDN"
        },


My IntelMQ version is 1.1.0a1
and IntelMQ Manager is 0.3.1

**Comment by wagner-certat** [comment]
> Ah sorry my fault, I messed something up with copy pasting.

Just use the configuration provided in the downloaded software itself, that way you ensure they are compatible. Otherwise you may mix up different versions.

> load_entry_point('intelmq==1.0.2', 'console_scripts', 'intelmq_psql_initdb')()
> ...
> ValueError: Unknown type 'ASN'. 

IntelMQ 1.0.x has no harmonization type ASN, that has been introduced in b46c26b10b8c0114117471b5e5e935b08ca2cb8e (branch develop)

> My IntelMQ version is 1.1.0a1

Apparently not, or you managed to install multiple versions.

**Comment by chappi6** [comment]
Yes i copied the harmonization.conf  directly from git and i was on the dev branch. 
The master version is working. Thx!! 

>   My IntelMQ version is 1.1.0a1

> Apparently  not, or you managed to install multiple versions.


Thats what intemq-manager tells me.

**Comment by wagner-certat** [comment]
Ok, what's the output of:
* `intelmqctl --version`
* `intelmqctl check`
* `python3 -c "import intelmq; print(intelmq.__file__)"`
* `cat /usr/lib/python3.4/site-packages/intelmq-*.egg-info`
* `pip3 list | grep intelmq` (if pip is installed, skip otherwise)
