### ISSUE TITLE
setup.py ignores custom files

### ISSUE THREAD

**Issue by e3rd** [certtools/intelmq#1146]
While installing by `setup.py`, only `.py` files and some others like those mentionned in 

`scripts=[
        'intelmq/bots/experts/tor_nodes/update-tor-nodes',
        'intelmq/bots/experts/maxmind_geoip/update-geoip-data',
        'intelmq/bots/experts/asn_lookup/update-asn-data',
`

are copied to new location. All other files disappear. I.E. in `tests/bots/` folder I am used to have many files meant for testing purposes. Or [shadowserver parser](https://github.com/certtools/intelmq/tree/develop/intelmq/tests/bots/parsers/shadowserver) have plenty of *.csv . 

Is that on purpose, or we can edit `setup.py` to include these files as well, or we have to copy that files manually while deploying?

(This is not a major issue, however I think it's a bug.)

EDIT 2018-01-15 @wagner-certat: fix link syntax

**Comment by wagner-certat** [comment]
> Is that on purpose

No, that's a bug. The sdist should include all files needed for tests (and docs).

**Comment by aaronkaplan** [comment]
agreed. Bug.

**Comment by e3rd** [comment]
I've been investigating this issue and found that putting a line in `MANIFEST.in` will solve it. Now I need to discuss what files should be copied.  
It seems to me every file in `intelmq/` folder should be included. (I've met .json, .sieve, ... files.) **Am I right?** Or should I bother not include *.md files or requirements.txt files?

**Comment by wagner-certat** [comment]
* intelmq/bots/: hold docs (incl example configs) and requirements -> yes
 * intelmq/tests/: for testing we need everything -> yes
 * intelmq/etc/: *.conf configuration is already included manually, could be simplified. feeds.yaml is on the wrong place there IMO, but for now we also need to include it there
 * intelmq/bin: the scipts/files not included explicitly should _not_ be packaged (those only relevant for devs)
 * intelmq/lib: has no other files than included ones.
docs/: should be included actually
 * contrib: puh. I'm not sure. there are very helpful and useful additional resources, so probably yes.
 * debian: i don't know how debian packagers/maintainers need/want it. so for the time being: no

**Comment by e3rd** [comment]
> intelmq/bin: the scipts/files not included explicitly should not be packaged (those only relevant for devs) -> no

What files relevant for devs do you mean? I see no other files than already included *.py files.

**Comment by wagner-certat** [comment]
I mean `intelmq_gen_feeds_docs.py`, `intelmq_gen_harm_docs.py`, `rewrite_config_files.py`, they should actually not be included, but I see they are (because `setuptools.find_packages` picks them up). I think they should be excluded.

**Comment by e3rd** [comment]
* I wasn't able to exclude .py files at any cost; the MANIFEST.in seems to be handling only not-py files
* I wasn't able to include docs and contrib folders, on top of that it doesn't make much sense: Current MANIFEST.in already includes LICENSE, COPYRIGHT, docs and contrib... but **as only `intelmq` folder gets copied to ** `/usr/local/lib/...dist-packages/intelmq`, there is no place these files could be put.

Okay?

**Comment by wagner-certat** [comment]
> I wasn't able to exclude .py files at any cost; the MANIFEST.in seems to be handling only not-py files

k, that needs another solution then (later)

> I wasn't able to include docs and contrib folders,

Ah, I see that's already done. They should of course not be in /usr/, but included in the sdist.

Thanks for looking into it!

**Comment by e3rd** [comment]
I didn't know the concept of `sdist`. When doing sdist, .py files you didn't want **are now excluded** etc. We can close this when you accept the PR :)
