### ISSUE TITLE
file output: does not refresh the file descriptor if deleted

### ISSUE THREAD

**Issue by wagner-certat** [certtools/intelmq#1148]
Scenario:
* file output bot writes to a file.
* User deletes this file (instead of deleting the content)
* bot writes more events there
* user checks if there are events
* file is empty

why? because the bot still has the description to the (deleted) file

-> check if we can detect this from within the bot: https://stackoverflow.com/a/12690767/2851664

**Comment by aaronkaplan** [comment]
This is standard unix-ishness... yes, it's confusing. But we won't aim at fixing standard unix quirkses... 
We can't protect a unix system from it's admin (if someone deletes a file with root perms when the process is still writing to it, then it still has an open file handle).
