### ISSUE TITLE
sieve expert: support paths

### ISSUE THREAD

**Issue by wagner-certat** [certtools/intelmq#1207]
Named destination queues aka "paths" are now supported and can be used by the sieve expert.

cc @antoinet

**Comment by antoinet** [comment]
Where's the best place to get familiar with the concept of named destination queues?

**Comment by wagner-certat** [comment]
Use the `path=` parameter in `self.send_message` and see the docs that have been added: https://github.com/certtools/intelmq/pull/1190/files

**Comment by e3rd** [comment]
Ignorant of this issue, I've just implemented the behaviour at #1217 , including docs & tests. Please comment if that's alright.

**Comment by antoinet** [comment]
Thanks for the contribution! I have one point concerning the selection of the path during the sieve processing:

As implemented, it is only possible to specify the path with the `keep` action, which terminates processing. However, I think there may be cases where we want to specify the path early on and continue processing until reaching either a `keep` or the end of the rules.

Therefore I suggest adding a new action called e.g. `path` that takes the path name as a (mandatory) parameter and stores it until reaching the end of processing, e.g.:
```
if source.fqdn == 'example.com' {
  path 'ignore'
}

// further rules

if source.ip == '1.2.3.4' {
  // terminate processing
  // send event to whichever path was specified above
  keep
}

// reached end of processeing
// send event to whichever path was specified above
```

The parametrized `keep` action can be maintained with it's semantic, it doesn't collide with the suggestion above. Although for the sake of simplicity, I would tend to remove it, even though it  provides a syntactic shortcut for:

```
if source.ip == '1.2.3.4' {
  path 'foobar'
  keep
```

**Comment by e3rd** [comment]
Fully agree, 'll try to implement it on Monday :)

**Comment by e3rd** [comment]
Was merged a week ago, closing.
