### ISSUE TITLE
Gethostbyname enters continuous loop

### ISSUE THREAD

**Issue by charlesgardner221** [certtools/intelmq#1216]
When the gethostbyname-expert attempts to resolve certain URLs and recieves the error:
`  # define EAI_AGAIN        -3    /* Temporary failure in name resolution.  */` 
such as with the URL "himelsatellitecable.com" it is possible that the expert enters a loop whereby this "Temporary failure" does not resolve, and the entire queue stops. This is caused by the same event being resubmitted every 15 seconds.

**Comment by charlesgardner221** [comment]
One solution, although this may be unpopular, is to pass if this error code is encountered. The rationale behind this is that for blocklists etc. we are often encountering domains which cannot be resolved. This 'temporary' error is often actually a terminal error. 

[Line 42](https://github.com/certtools/intelmq/blob/17ebd5aafed19859d4975a2da7df0eb07359434e/intelmq/bots/experts/gethostbyname/expert.py#L42) can therefore be replaced with:

` if exc.args[0] in [-2, -3, -4, -5, -8, -11]:`

**Comment by wagner-certat** [comment]
What have you set as `error_*` in the default/bot configuration?

**Comment by wagner-certat** [comment]
Closing, no response
