### ISSUE TITLE
abuse.ch zeustracker country RSS feed

### ISSUE THREAD

**Issue by chorsley** [certtools/intelmq#1221]
We noticed that there is currently no apparent support in the abusech parser bots for the reports of type https://zeustracker.abuse.ch/monitor.php?countryrss=AU. 

Happy to submit a PR to add it, but wanted to see if there was a specific reason it didn't exist so far, or if there are already any efforts underway.

**Comment by wagner-certat** [comment]
> Happy to submit a PR to add it, but wanted to see if there was a specific reason it didn't exist so far, or if there are already any efforts underway.

I'm not aware of any.

Are they a subset of [Blocklist](the https://zeustracker.abuse.ch/blocklist.php)? Also consider that this feed is (as all the abuse.ch feeds) missing time information.

**Comment by gethvi** [comment]
@wagner-certat This can be closed as Zeus Tracker is discontinued.

**Comment by wagner-certat** [comment]
Thanks, closing here then
