### ISSUE TITLE
error messages during bot development

### ISSUE THREAD

**Issue by michaelb20** [certtools/intelmq#1230]
Hi together.

I'm about to develop my own bots for some services and despair every time a new bot has to be created and an error occurs that just says: `'Incomplete installation: Module ...' not importable.`

Searching all the configs and the BOT-file, it's not easy to find the mistake, if you don't know what to look for

it would be really great if you could be more specific about the error messages.

**Comment by wagner-certat** [comment]
> an error occurs that just says: `'Incomplete installation: Module ...' not importable.`

> it would be really great if you could be more specific about the error messages.

The "..." module can't be imported. E.g. if the module is `intelmq.bots.parsers.example` then this would fail:

```python
import intelmq.bots.parsers.example
```
with an ImportException. The code is not at some place where python can find it.

I can't say more without knowing what you have done exactly.

**Comment by michaelb20** [comment]
It's not about my development problems at all, because after some time they solve themselves during the more detailed code and config review.

However, I wanted to ask you to run more detailed error messages in the next version, which will help in troubleshooting to make development and debugging easier.

In my case the error was in the BOT file and not in the source code by the way.

**Comment by wagner-certat** [comment]
Ok, now I understood.

What we could do is to create an entry in the FAQ about this error message and refer to it in the error message together with a very short summary. The list of possible problems is quite long (I don't know all the possible reasons) as are the solutions.

**Comment by michaelb20** [comment]
I think that it is not problematic regarding the source code developed by a person, because a good development environment can assist in syntactic fault search very well and the logger can be used for intermediate outputs.

FAQs could make it look more complicated than it actually is. In most cases it's about errors in the JSON files, where for e.g. the line, where an error occurs during parsing or where an association between class name and string in the conf file is not possible. You could propagate this information, if the construction allows it.

To be honest, i haven't gone into the actual source code in more detail, but i think that when `utils.load_configuration` is called, there raises an error that could possibly be described further.

**Comment by wagner-certat** [comment]
I am still not sure how I can "fix" this bug. From the programs perspective it is not possible to determine the reason. In your case the error was a typo in the BOTS file, but the program printed the name that was given there, so the user can spot the typo. In other cases the bug is an erroneous installation, in that case I can point the user to the developers guide.
