### ISSUE TITLE
installation

### ISSUE THREAD

**Issue by RadixN** [certtools/intelmq#1233]
After successful installation of intelmq with pip3 install intelmq, got following error on moving
```
[root@localhost  user]# sudo mv `python3 -c "import site; print(site.getsitepackages()[0] + '/opt/intelmq')"` /opt/
```

mv: cannot stat ‘/usr/lib64/python3.4/site-packages/opt/intelmq’: No such file or directory

**Comment by wagner-certat** [comment]
Interesting. Which operating system do you use?

**Comment by wagner-certat** [comment]
no feedback, closing
