### ISSUE TITLE
TLD expert question / proposal

### ISSUE THREAD

**Issue by chorsley** [certtools/intelmq#1236]
For grouping purposes, we'd like to extract and store TLDs from each FQDN we see, as this can be complex to easily determine without using something like https://publicsuffix.org/list/.

* Is this something which exists already? I didn't find one, but happy to write an expert bot if not.
* Would it be appropriate to add "source.tld" and "destination.tld" fields to the harmonisation fields?

**Comment by wagner-certat** [comment]
> Is this something which exists already? I didn't find one, but happy to write an expert bot if not.

yes, see #1224 

> Would it be appropriate to add "source.tld" and "destination.tld" fields to the harmonisation fields?

See #1224. But TLD is not the same as the public suffix. E.g. co.au is a public suffix, but the TLD is au.

And one needs to keep in mind that the public suffix list also contains private suffixes (which my code does ignore).

**Comment by wagner-certat** [comment]
Closing here, as this is probably solved. If not, please reopen.

**Comment by chorsley** [comment]
This is indeed solved with the domain_suffix expert. Thanks!
