### ISSUE TITLE
Elasticsearch-Output initialization fails even though the cluster is up

### ISSUE THREAD

**Issue by michaelb20** [certtools/intelmq#1242]
I connected my IntelMQ environment to Elasticsearch. In another environment im monitoring with the Elastic stack. This has worked perfectly in separate environments, but since the consolidation the bot is missing at every start. I have checked all configurations and ensured connectivity. 

Now I don't know where to continue searching, because I can't explain this error to myself.

Output from `/opt/intelmq/var/log/Elasticsearch-Output`:`

> intelmq@f228099f0416:~/var/log$ cat Elasticsearch-Output.log 
> 2018-05-27 16:54:51,679 - Elasticsearch-Output - INFO - ElasticsearchOutputBot initialized with id Elasticsearch-Output and intelmq 1.1.0.alpha1 and python 3.5.2 (default, Nov 23 2017, 16:37:01) as process 412.
> 2018-05-27 16:54:51,679 - Elasticsearch-Output - DEBUG - Library path: '/usr/local/lib/python3.5/dist-packages/intelmq/lib/bot.py'.
> 2018-05-27 16:54:51,679 - Elasticsearch-Output - DEBUG - Loading defaults configuration from '/opt/intelmq/etc/defaults.conf'.
> 2018-05-27 16:54:51,679 - Elasticsearch-Output - DEBUG - Defaults configuration: parameter 'source_pipeline_db' loaded with value 2.
> 2018-05-27 16:54:51,679 - Elasticsearch-Output - DEBUG - Defaults configuration: parameter 'logging_handler' loaded with value 'file'.
> 2018-05-27 16:54:51,679 - Elasticsearch-Output - DEBUG - Defaults configuration: parameter 'load_balance' loaded with value False.
> 2018-05-27 16:54:51,679 - Elasticsearch-Output - DEBUG - Defaults configuration: parameter 'error_dump_message' loaded with value True.
> 2018-05-27 16:54:51,680 - Elasticsearch-Output - DEBUG - Defaults configuration: parameter 'http_verify_cert' loaded with value True.
> 2018-05-27 16:54:51,680 - Elasticsearch-Output - DEBUG - Defaults configuration: parameter 'error_procedure' loaded with value 'pass'.
> 2018-05-27 16:54:51,680 - Elasticsearch-Output - DEBUG - Defaults configuration: parameter 'error_max_retries' loaded with value 3.
> 2018-05-27 16:54:51,680 - Elasticsearch-Output - DEBUG - Defaults configuration: parameter 'error_log_exception' loaded with value True.
> 2018-05-27 16:54:51,680 - Elasticsearch-Output - DEBUG - Defaults configuration: parameter 'source_pipeline_host' loaded with value '10.34.1.15'.
> 2018-05-27 16:54:51,680 - Elasticsearch-Output - DEBUG - Defaults configuration: parameter 'http_timeout_sec' loaded with value 30.
> 2018-05-27 16:54:51,680 - Elasticsearch-Output - DEBUG - Defaults configuration: parameter 'destination_pipeline_host' loaded with value '10.34.1.15'.
> 2018-05-27 16:54:51,680 - Elasticsearch-Output - DEBUG - Defaults configuration: parameter 'rate_limit' loaded with value 0.
> 2018-05-27 16:54:51,680 - Elasticsearch-Output - DEBUG - Defaults configuration: parameter 'broker' loaded with value 'redis'.
> 2018-05-27 16:54:51,680 - Elasticsearch-Output - DEBUG - Defaults configuration: parameter 'logging_syslog' loaded with value '/dev/log'.
> 2018-05-27 16:54:51,680 - Elasticsearch-Output - DEBUG - Defaults configuration: parameter 'destination_pipeline_port' loaded with value 6379.
> 2018-05-27 16:54:51,680 - Elasticsearch-Output - DEBUG - Defaults configuration: parameter 'log_processed_messages_seconds' loaded with value 900.
> 2018-05-27 16:54:51,680 - Elasticsearch-Output - DEBUG - Defaults configuration: parameter 'error_log_message' loaded with value True.
> 2018-05-27 16:54:51,680 - Elasticsearch-Output - DEBUG - Defaults configuration: parameter 'destination_pipeline_password' loaded with value 'HIDDEN'.
> 2018-05-27 16:54:51,680 - Elasticsearch-Output - DEBUG - Defaults configuration: parameter 'logging_level' loaded with value 'DEBUG'.
> 2018-05-27 16:54:51,680 - Elasticsearch-Output - DEBUG - Defaults configuration: parameter 'http_user_agent' loaded with value 'Mozilla/5.0 (Windows NT 6.1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/41.0.2228.0 Safari/537.36'.
> 2018-05-27 16:54:51,680 - Elasticsearch-Output - DEBUG - Defaults configuration: parameter 'destination_pipeline_db' loaded with value 2.
> 2018-05-27 16:54:51,680 - Elasticsearch-Output - DEBUG - Defaults configuration: parameter 'https_proxy' loaded with value None.
> 2018-05-27 16:54:51,680 - Elasticsearch-Output - DEBUG - Defaults configuration: parameter 'proccess_manager' loaded with value 'intelmq'.
> 2018-05-27 16:54:51,680 - Elasticsearch-Output - DEBUG - Defaults configuration: parameter 'source_pipeline_password' loaded with value 'HIDDEN'.
> 2018-05-27 16:54:51,680 - Elasticsearch-Output - DEBUG - Defaults configuration: parameter 'source_pipeline_port' loaded with value 6379.
> 2018-05-27 16:54:51,681 - Elasticsearch-Output - DEBUG - Defaults configuration: parameter 'error_retry_delay' loaded with value 15.
> 2018-05-27 16:54:51,681 - Elasticsearch-Output - DEBUG - Defaults configuration: parameter 'http_proxy' loaded with value None.
> 2018-05-27 16:54:51,681 - Elasticsearch-Output - DEBUG - Defaults configuration: parameter 'accuracy' loaded with value 100.
> 2018-05-27 16:54:51,681 - Elasticsearch-Output - DEBUG - Defaults configuration: parameter 'http_timeout_max_tries' loaded with value 3.
> 2018-05-27 16:54:51,681 - Elasticsearch-Output - DEBUG - Defaults configuration: parameter 'log_processed_messages_count' loaded with value 500.
> 2018-05-27 16:54:51,681 - Elasticsearch-Output - DEBUG - Defaults configuration: parameter 'logging_path' loaded with value '/opt/intelmq/var/log/'.
> 2018-05-27 16:54:51,681 - Elasticsearch-Output - INFO - Bot is starting.
> 2018-05-27 16:54:51,681 - Elasticsearch-Output - DEBUG - Loading runtime configuration from '/opt/intelmq/etc/runtime.conf'.
> 2018-05-27 16:54:51,682 - Elasticsearch-Output - DEBUG - Runtime configuration: parameter 'replacement_char' loaded with value '_'.
> 2018-05-27 16:54:51,682 - Elasticsearch-Output - DEBUG - Runtime configuration: parameter 'flatten_fields' loaded with value 'extra'.
> 2018-05-27 16:54:51,682 - Elasticsearch-Output - DEBUG - Runtime configuration: parameter 'elastic_port' loaded with value 9200.
> 2018-05-27 16:54:51,682 - Elasticsearch-Output - DEBUG - Runtime configuration: parameter 'http_username' loaded with value None.
> 2018-05-27 16:54:51,682 - Elasticsearch-Output - DEBUG - Runtime configuration: parameter 'elastic_host' loaded with value 'elasticsearch.example.at'.
> 2018-05-27 16:54:51,682 - Elasticsearch-Output - DEBUG - Runtime configuration: parameter 'http_password' loaded with value 'HIDDEN'.
> 2018-05-27 16:54:51,682 - Elasticsearch-Output - DEBUG - Runtime configuration: parameter 'elastic_doctype' loaded with value 'events'.
> 2018-05-27 16:54:51,682 - Elasticsearch-Output - DEBUG - Runtime configuration: parameter 'elastic_index' loaded with value 'intelmq-external-feeds'.
> 2018-05-27 16:54:51,682 - Elasticsearch-Output - DEBUG - Loading pipeline configuration from '/opt/intelmq/etc/pipeline.conf'.
> 2018-05-27 16:54:51,682 - Elasticsearch-Output - DEBUG - Loading Harmonization configuration from '/opt/intelmq/etc/harmonization.conf'.
> 2018-05-27 16:54:51,844 - Elasticsearch-Output - ERROR - Bot initialization failed.
> Traceback (most recent call last):
>   File "/usr/local/lib/python3.5/dist-packages/urllib3/connection.py", line 141, in _new_conn
>     (self.host, self.port), self.timeout, **extra_kw)
>   File "/usr/local/lib/python3.5/dist-packages/urllib3/util/connection.py", line 60, in create_connection
>     for res in socket.getaddrinfo(host, port, family, socket.SOCK_STREAM):
>   File "/usr/lib/python3.5/socket.py", line 732, in getaddrinfo
>     for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
> socket.gaierror: [Errno -2] Name or service not known
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "/usr/local/lib/python3.5/dist-packages/elasticsearch/connection/http_urllib3.py", line 166, in perform_request
>     response = self.pool.urlopen(method, url, body, retries=False, headers=request_headers, **kw)
>   File "/usr/local/lib/python3.5/dist-packages/urllib3/connectionpool.py", line 639, in urlopen
>     _stacktrace=sys.exc_info()[2])
>   File "/usr/local/lib/python3.5/dist-packages/urllib3/util/retry.py", line 333, in increment
>     raise six.reraise(type(error), error, _stacktrace)
>   File "/usr/local/lib/python3.5/dist-packages/urllib3/packages/six.py", line 686, in reraise
>     raise value
>   File "/usr/local/lib/python3.5/dist-packages/urllib3/connectionpool.py", line 601, in urlopen
>     chunked=chunked)
>   File "/usr/local/lib/python3.5/dist-packages/urllib3/connectionpool.py", line 357, in _make_request
>     conn.request(method, url, **httplib_request_kw)
>   File "/usr/lib/python3.5/http/client.py", line 1106, in request
>     self._send_request(method, url, body, headers)
>   File "/usr/lib/python3.5/http/client.py", line 1151, in _send_request
>     self.endheaders(body)
>   File "/usr/lib/python3.5/http/client.py", line 1102, in endheaders
>     self._send_output(message_body)
>   File "/usr/lib/python3.5/http/client.py", line 934, in _send_output
>     self.send(msg)
>   File "/usr/lib/python3.5/http/client.py", line 877, in send
>     self.connect()
>   File "/usr/local/lib/python3.5/dist-packages/urllib3/connection.py", line 166, in connect
>     conn = self._new_conn()
>   File "/usr/local/lib/python3.5/dist-packages/urllib3/connection.py", line 150, in _new_conn
>     self, "Failed to establish a new connection: %s" % e)
> urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x7f18a5b65b70>: Failed to establish a new connection: [Errno -2] Name or service not known
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "/usr/local/lib/python3.5/dist-packages/intelmq/lib/bot.py", line 82, in __init__
>     self.init()
>   File "/usr/local/lib/python3.5/dist-packages/intelmq/bots/outputs/elasticsearch/output.py", line 57, in init
>     if not self.es.indices.exists(self.elastic_index):
>   File "/usr/local/lib/python3.5/dist-packages/elasticsearch/client/utils.py", line 76, in _wrapped
>     return func(*args, params=params, **kwargs)
>   File "/usr/local/lib/python3.5/dist-packages/elasticsearch/client/indices.py", line 213, in exists
>     params=params)
>   File "/usr/local/lib/python3.5/dist-packages/elasticsearch/transport.py", line 314, in perform_request
>     status, headers_response, data = connection.perform_request(method, url, params, body, headers=headers, ignore=ignore, timeout=timeout)
>   File "/usr/local/lib/python3.5/dist-packages/elasticsearch/connection/http_urllib3.py", line 175, in perform_request
>     raise ConnectionError('N/A', str(e), e)
> elasticsearch.exceptions.ConnectionError: ConnectionError(<urllib3.connection.HTTPConnection object at 0x7f18a5b65b70>: Failed to establish a new connection: [Errno -2] Name or service not known) caused by: NewConnectionError(<urllib3.connection.HTTPConnection object at 0x7f18a5b65b70>: Failed to establish a new connection: [Errno -2] Name or service not known)
> 2018-05-27 16:54:51,845 - Elasticsearch-Output - INFO - Bot stopped.
> 

`

**Comment by michaelb20** [comment]
I'm connected with Kibana and i receive current logs from winlogbeat. The service is 100% available.

**Comment by navtej** [comment]
Your IMQ installation is picking `elasticsearch.example.at`  as ES hostname. Is it correct, or obfuscated? Can you please try with IP as well? Thanks.

**Comment by wagner-certat** [comment]
Closing, as it is not reproducible
