### ISSUE TITLE
Get rid of JSON in messages

### ISSUE THREAD

**Issue by wagner-certat** [certtools/intelmq#1252]
Replacing JSON with pickle where applicable (the pipeline) will give a performance boost of about 5x or more estimated for serialization (small objects).

**Comment by wagner-certat** [comment]
@aaronkaplan proposes to use https://google.github.io/flatbuffers/

**Comment by aaronkaplan** [comment]
I think the next version will still stick with JSON even though it might not be as efficient.
Using pickl ties you to a python app processing everything. But you might want to hand over the JSON event to some other process written in another language and maybe that's listening for the event on some Kafka queue.
So... let's stick with JSON for now.

See the new format description in 3.0

**Comment by wagner-certat** [comment]
Then let's close it
