### ISSUE TITLE
unnecessary print command in message.py line 488?

### ISSUE THREAD

**Issue by JanKoDFNCERT** [certtools/intelmq#1281]
Hi,

I came accross a parser bot failure (broken pipe / Errno 32) while calling

```
 event.add('extra', data_dict)
```
It looks like that the broken pipe is caused by a print statement in  intelmq/intelmq/lib/message.py (line 488):

```
   def __contains__(self, item) -> bool:
        if item == 'extra':
            print(self.to_dict(hierarchical=True))                          <-----
            return 'extra' in self.to_dict(hierarchical=True)
        return super(Message, self).__contains__(item)
```
at least, the failure disappeared after deleting this line. Is this print command required or, e.g., a left over from debugging?

**Comment by wagner-certat** [comment]
Hi,

Thanks. Didn't know that the print's can cause broken pipes, but it makes sense as the program may not have a stdout to write to.

I came across this line 4 days ago too. This was already fixed in the maintenance branch, I now also pushed the fix to develop. See 47948709f174659fa3df9ba83461fc455a644d04

**Comment by JanKoDFNCERT** [comment]
thanks for the fast reply and reaction!

Cheers,
	Jan

> Hi,
> 
> Thanks. Didn't know that the print's can cause broken pipes, but it makes sense as the program may not have a stdout to write to.
> 
> I came across this line 4 days ago too. This was already fixed in the maintenance branch, I now also pushed the fix to develop. See 47948709f174659fa3df9ba83461fc455a644d04
> 
> -- 
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/certtools/intelmq/issues/1281#issuecomment-409264196


-- 
Jan Kohlrausch (CSIRT), Phone +49 40 808077-618

DFN-CERT Services GmbH, https://www.dfn-cert.de,  Phone  +49 40 808077-590
Sitz / Register: Hamburg, AG Hamburg, HRB 88805,  Ust-IdNr.:  DE 232129737
Sachsenstraße 5,   20097 Hamburg/Germany, CEO: Dr. Klaus-Peter Kossakowski
