### ISSUE TITLE
event.get("extra") returns None even if event["extra"] would return a dictionary

### ISSUE THREAD

**Issue by bernhard-herzog** [certtools/intelmq#1305]
In IntelMQ 1.1 the way the `extra` field is handled has changed, but for backwards compatibility it's still possible to access it with just the key `"extra"` (#1046). This works fine with the `__getitem__` and `__contains__` methods but does not work with the `get` method. If there are any values in the `extra` field so that  event["extra"] would return a dictionary, `event.get("extra")` will still return `None`.

**Comment by wagner-certat** [comment]
Thanks, fixed
