### ISSUE TITLE
remote logging does not seem to work

### ISSUE THREAD

**Issue by aaronkaplan** [certtools/intelmq#1312]
Tried to follow the instructions and enabled remote syslog logging to

```bash
$ cat defaults.conf
(...)
    "logging_syslog": "['syslog1.somehost.com', 514]",
```

I don't see packets being sent there.

**Comment by wagner-certat** [comment]
Use

```
    "logging_syslog": ["syslog1.somehost.com", 514],
```

(See User Guide section "System Configuration (defaults)")

**Comment by aaronkaplan** [comment]
funny, I did and tried that as well... but did not work.  Must have been too sleepy at night and might have had a typo.

okay, consider this closed then please.
