### ISSUE TITLE
Prebuild package for Ubuntu 16.04 not installable due to dependencies

### ISSUE THREAD

**Issue by swilde** [certtools/intelmq#1319]
Hi,

I just tried to install IntelMQ 1.1.0 from the packages on 
download.opensuse.org/repositories/home:/sebix:/intelmq/xUbuntu_16.04

Unfortunately this fails, because the required version of python3-dateutil is not present in Ubuntu 16.04:
  intelmq : Depends: python3-dateutil (>= 2.5) but 2.4.2-1 is to be installed

Is 2.5 really necessary? (We are running our IntelMQ 1.0 derivate with 2.4 w/o problems)

**Comment by wagner-certat** [comment]
Yes I had problems with 2.4.2, see my commit message of 409544c72ba2a8606b0b05a81bf4abbf2c344c56 (but the message lacks some grammar^^) I think the timestamps in question were those used by intelmq itself, I'll check that.

But I remember that there was a good reason for the change. I however agree with you that minimum required version should not be increased if not necessary.

**Comment by bernhard-herzog** [comment]
> Is 2.5 really necessary? (We are running our IntelMQ 1.0 derivate with 2.4 w/o problems)

Well, at least on the staging system we *do* use 2.5. More precisely, there's a python3-dateutil 2.5.3-2 installed on the staging system. It was apparently installed from our apt server.

**Comment by wagner-certat** [comment]
I enabled the build of python3-dateutil for Ubuntu 16.04, it will be available in the repository soon.

**Comment by wagner-certat** [comment]
> it will be available in the repository soon.

available now
