### ISSUE TITLE
I'm not the maintainer of the upstream packages....  ;-)

### ISSUE THREAD

**Issue by swilde** [certtools/intelmq#1320]
The debian packaging code is derived from my original work.  This likely the reason why I'm still in the Maintainer: field of intelmq/debian/control.

But as I'm not the maintainer of the official upstream packages (not even having commit privileges on the repo) I'm asking you to change the entry to someone actualy responsible for the packaging.  :)

**Comment by wagner-certat** [comment]
fixed in 2fbf8dc4288f3833745b39d5ddf126eaa0e3a54f
