### ISSUE TITLE
High memory usage per each bot

### ISSUE THREAD

**Issue by SYNchroACK** [certtools/intelmq#1326]
Anyone know why each bot use in average 35 MB of memory RAM?

@wagner-certat

**Comment by wagner-certat** [comment]
Using the `memory_profiler` I tried to find out which parts do consume the 50MB virtual memory, but it showed my no useful results yet. The memory usage rises already at it's maximum during startup of python itself even before the import of intelmq's code.

**Comment by wagner-certat** [comment]
AFAIK that is python itself and not related to intelmq

**Comment by wagner-certat** [comment]
Closing at it is unclear what to do
