### ISSUE TITLE
bot collector_http freeze

### ISSUE THREAD

**Issue by kalyparker** [certtools/intelmq#1332]
Hello,
I have an issue on the bot collector_http. Regularly, I have these error message on the log:
Received SIGHUP, initializing again later.
And the bot did not start alone until the next day.
Checking the status of the bot, it said "bot is running", but nothing is downloaded and it does nothing at all.
Do you have already experience this kind of behavior?
Do you have any idea why? 
And how to fix it ? I wish to avoid restarting bot via cron :)
I use the last version of intelmq on ubuntu 18.04. I have actually 41 bots running.
Have a nice day

**Comment by wagner-certat** [comment]
Hi,

Could you please show me a full log example with the relevant lines (probably with URLs removed)?

**Comment by wagner-certat** [comment]
And with the debug log level it is even more interesting (you can set the `log_level` parameter per bot).

**Comment by kalyparker** [comment]
Hi, 
I guess I understand what's happen there!
I setup the bots with time_limit recommendation from the file feeds.yaml and I did not pay attention that for few of them there are 36h idle time.
So nothing wrong here, the bot works as expected :)
Sorry for that, I close the issue.
Have a nice day

**Comment by wagner-certat** [comment]
Lol, ok. But that can be improved by showing the time in a human readable format additionally.
