### ISSUE TITLE
Bot for changing geolocation information

### ISSUE THREAD

**Issue by th-certbund** [certtools/intelmq#1337]
CERT-Bund reports events related to IPs geolocated in Germany to the responsible network owners. Events for IPs geolocated in other countries are reported to the respective national CSIRTs. For geolocating an IP, we use IntelMQ's maxmind_geoip expert.

For notification of network owners, we import all INET(6)NUMS registered with country code 'DE' along with the corresponding abuse-c contact from the RIPE database into our local contact database (https://github.com/Intevation/intelmq/tree/certbund-contact/intelmq/bots/experts/certbund_contact).

Unfortunately, we have to deal with a lot of networks belonging to ISPs in other countries for which Maxmind geolocates individual IPs in DE, for example:

inetnum:        217.163.0.0 - 217.163.255.255
netname:        UK-LVLT-20010404

inetnum:        80.239.128.0 - 80.239.255.255
netname:        SE-TELIAEU-20011129

In many cases it is hard to decide whether Maxmind's results are correct and individual IPs from those networks are actually operated in DE or not. We would prefer reporting events for those IPs to the national CSIRT for the country where the network owner is located.

To solve this, it would be great to have an additional expert that could be added to the workflow after the maxmind_geoip expert which overwrites the geolocation information for the IP in the event based on CIDR matching from a CSV configuration file like this:

"217.163.0.0/16","GB"
"80.239.160.0/22","SE"

**Comment by wagner-certat** [comment]
The sieve expert can handle this and in principle also the modify bot with regular expressions.

**Comment by th-certbund** [comment]
Thanks, I'll try the sieve bot.
Would it be possible to add IP vs. CIDR comparison to the modify bot as well?

**Comment by wagner-certat** [comment]
>  Would it be possible to add IP vs. CIDR comparison to the modify bot as well?

Sure, just needs to be implemented :D

**Comment by th-certbund** [comment]
Implemented using sieve expert, so closing this issue.
