### ISSUE TITLE
TCP output should be usable with non-intelmq TCP collectors (e.g. filebeat)

### ISSUE THREAD

**Issue by Teebor-Choka** [certtools/intelmq#1385]
[Commit](https://github.com/certtools/intelmq/commit/0a38acf096b4934048432360fdfaf041f9fd1eb6) `0a38acf096b4934048432360fdfaf041f9fd1eb6` broke the TCP output bot behavior for certain use-cases.

Until that commit it was possible to construct a pipeline extending beyond *IntelMQ*, that would process the data using a `filebeat` -> `logstash` -> `elasticsearch` pipeline. This is no longer possible, as the aforementioned commit broke communication between the TCP output bot and the filebeat element (specifically by waiting for the `"Ok"` message using `recv`, which does not appear to be sent by `filebeat`).

More information about the issue along with a specific filebeat configuration to replicate this issue was discussed [here](https://github.com/certtools/intelmq/commit/0a38acf096b4934048432360fdfaf041f9fd1eb6#r32477400).

**Comment by wagner-certat** [comment]
cc @e3rd

**Comment by e3rd** [comment]
Sorry for that. We'll have to restore the previous behaviour by adding a parameter, like "wait-for-ok". What should be its default value? True (communication with another IntelMQ collector) or False (before-the-commit compatible)?

**Comment by Teebor-Choka** [comment]
I'd suggest to default into the original (not expecting `OK`) behavior in order to keep backwards compatibility. I assume not everybody reads the minuscule configuration details of each upgraded bot in order to change the settings before an upgrade. However it is reasonable to assume (on the end-user side) that the upgrade should not break the current configuration. What do you think?

**Comment by e3rd** [comment]
Since this still exists just in the `dev` branch, not as a stable master release, the backwards compatibility wouldn't need to be priority. However, it seems to me that "Ok" shouldn't be sent by default because any other application is aware of this little protocol.

I think I should make "Ok" turned down by default both in TCP-output and TCP-collector so that the administrator could turn it on just in the case of a network instability between intelmq instances.

**Comment by Teebor-Choka** [comment]
Agreed.

I meant backward compatibility with the behavior we currently have in the `master` branch and users see when they install from the stable branch and create configuration against that code.
