### ISSUE TITLE
Output BOT AMPQ line update.

### ISSUE THREAD

**Issue by asucrews** [certtools/intelmq#1425]
Hello,

Sorry i am not very good with Git and pull request.  However line 81 and 82 on https://github.com/certtools/intelmq/blob/develop/intelmq/bots/outputs/amqptopic/output.py need to change from

                    self.channel.exchange_declare(exchange=self.exchange, type=self.exchange_type,
                                                  durable=self.durable)

to 

                    self.channel.exchange_declare(exchange=self.exchange, exchange_type=self.exchange_type,
                                                  durable=self.durable)

**Comment by wagner-certat** [comment]
Thanks! I will update the bot
