### ISSUE TITLE
MongoDB authentication: compatibility on different MongoDB and pymongo versions

### ISSUE THREAD

**Issue by kalyparker** [certtools/intelmq#1439]
Hi,

In the new version of intelmq available in the repositories, I faced an issue regarding the bot MongoDB.
```python
        self.pymongo_3 = pymongo.version_tuple >= (3, )
        self.pymongo_35 = pymongo.version_tuple >= (3, 5)`
```
pymongo 3.5.1 is the last version supporting the old way to connect and the new.
You should change by.
```python
        self.pymongo_3 = pymongo.version_tuple >= (3, )
        self.pymongo_35 = pymongo.version_tuple > (3, 5, 1)`
```

**Comment by wagner-certat** [comment]
Thanks for the report, I will adapt the version check.

> In the new version of intelmq available in the repositories

Do you mean pip or deb/rpm?

**Comment by wagner-certat** [comment]
Looking at the source code of pymongo, the handling of username/password as kwargs looks the same. In the changelog, the change is documented for version 3.5

With any version bigger than or equal to 3.5, authentication with kwargs should be possible.

**Comment by kalyparker** [comment]
For the version, sorry, I means deb/rpm.

> With any version bigger than or equal to 3.5, authentication with kwargs should be possible.
The problem is related to the version of the mongodb and not directly to pymongo.
In 3.5.1 this is the last version which support "old" mongodb < 3.4, and unfortunately these mongodb does not support this authentification mode.
I don't know if I'm the only one to notice that.

Anyway, force usage of this authentification mode based on the version of pymongo seems dangerous, maybe a parameter do the trick.

**Comment by wagner-certat** [comment]
> > With any version bigger than or equal to 3.5, authentication with kwargs should be possible.
> 
> The problem is related to the version of the mongodb and not directly to pymongo.
> In 3.5.1 this is the last version which support "old" mongodb < 3.4, and unfortunately these mongodb does not support this authentification mode.
> I don't know if I'm the only one to notice that.
> 
> Anyway, force usage of this authentification mode based on the version of pymongo seems dangerous, maybe a parameter do the trick.

Okay, so we do not only need to check for the pymongo version, but also for the server version with `self.client.server_info()['version']`? So something like (pseudo-code)
```python
if self.pymongo_35 and self.username and self.server_version >= 3.4:
    self.client = (..., username=self.username, password=self.password)
else:
    self.client = (...)
db = self.client...
if self.usernameand (not self.pymongo_35 or self.server_version < 3.4):
    db.authenticate(...)
```

But `Database.authenticate` is deprecated too: https://api.mongodb.com/python/current/api/pymongo/database.html?highlight=authenticate#pymongo.database.Database.authenticate

**Comment by kalyparker** [comment]
yes, could do the job.

**Comment by wagner-certat** [comment]
I applied the proposed fix. I only tested with two different server version, so if something else needs to be adapted, please speak up.
