### ISSUE TITLE
Http collector doesn't add feed.name to reports

### ISSUE THREAD

**Issue by Narzhan** [certtools/intelmq#1445]
As the titles suggests with the current version of intelmq (2.0.1) the Http collector (and maybe others) started to omit the _feed.name_. It is not present in the Report sent to the parser. Following is my configuration and report and event examples:

Debug loaded value:
`abusech-ransomware-tracker-collector: Runtime configuration: parameter 'feed' loaded with value 'abuse-ch-ransomware-tracker'.`

Report
```
{"time.observation": "2019-09-04T07:54:44+00:00", "raw": "", "feed.url": "https://ransomwaretracker.abuse.ch/feeds/csv", "feed.accuracy": 80.0, "__type": "Report"}
```

Example of event created:
```
{"feed.accuracy": 80.0, "feed.url": "https://ransomwaretracker.abuse.ch/feeds/csv", "time.observation": "2019-09-04T07:34:51+00:00", "classification.type": "c2server", "classification.identifier": "CryptoWall", "source.fqdn": "bolizarsospos.com", "source.url": "http://bolizarsospos.com/rb05hez1r044", "status": "online", "raw": "MjAxNi0wMy0xNyAyMzo1Nzo0NixDMixDcnlwdG9XYWxsLGJvbGl6YXJzb3Nwb3MuY29tLGh0dHA6Ly9ib2xpemFyc29zcG9zLmNvbS9yYjA1aGV6MXIwNDQsb25saW5lLCJHb0RhZGR5LmNvbSwgTExDIiwxOTUuMTU3LjE1LjEwMCw4NDI2LEdCDQo=", "__type": "Event"}
```

Runtime configuration of bot:
```
    "abusech-ransomware-tracker-collector": {
        "description": "Ransomware Domain Blocklists",
        "group": "Collector",
        "module": "intelmq.bots.collectors.http.collector_http",
        "name": "Abusech Ransomware Tracker",
        "parameters": {
            "accuracy": 80,
            "error_dump_message": true,
            "error_log_message": true,
            "error_max_retries": 1,
            "error_procedure": "pass",
            "error_retry_delay": 60,
            "feed": "abuse-ch-ransomware-tracker",
            "http_url": "https://ransomwaretracker.abuse.ch/feeds/csv",
            "rate_limit": 129600
        }
    },
```

**Comment by wagner-certat** [comment]
That parameter was deprecated (in favor of `name` - see  #144) in the code (with deprecation warnings in the logs), but apparently is still in the Bots.md documentation. But the configuration upgrade function also takes care of it, so there shouldn't be any problem actually for upgraded installation.

I will re-add the code (was previously removed in 484ee09e41) and postpone the deprecation to 2.1.0.

**Comment by Narzhan** [comment]
So the parameter feed.name is not present in iocs anymore and was replace with name? There is no such filed in the example I've sent and nor is it in any ioc that produces my intelmq. While I was searching in the code in lib/bot in the report creation the feed.name is still being added. I've used the config upgrade tool and the configuration is almost identical. What should I do to add the some equivalent to feed.name to the iocs?

**Comment by wagner-certat** [comment]
The parameter "feed" in collectors was replaced by "name". It results in the `feed.name` field.

> What should I do to add the some equivalent to feed.name to the iocs?

Upgrade to the latest commit or use `name` as parameter instead of `feed`.
