### ISSUE TITLE
documentation diagram

### ISSUE THREAD

**Issue by e3rd** [certtools/intelmq#1457]
Hi,
when installing a new instance on @CSIRTMalta , it helped us a lot to create a diagram that denotes all the important folders, users and their rights. We'd like to push it to the `Installation.md` so that everyone can profit.

(There are multiple typos, like "lb" instead of lib", "intelmqv5" will be "human administrator", "sudders" will be sudoers.)

![image](https://user-images.githubusercontent.com/6942231/65774497-a725b900-e13e-11e9-9397-bf86a5a5a57c.png)

1. Would you prefer to have it in intelmq doc, intelmq-manager doc or elsewhere?
2. Would you allow us to include it as an image or do you know a way to include a diagram into github's markdown?

**Comment by YeomansM** [comment]
Hi Edvard,

We will correct the typos before update.
Suggestions to update this with further details are welcome!

Rgds

**Comment by wagner-certat** [comment]
Interesting, definitively helpful :)

As it only shows the interaction of the Manager with the core IntelMQ, I guess it is well placed in the docs of the Manager.

**Comment by wagner-certat** [comment]
That will be obsolete with certtools/intelmq-manager#80
