### ISSUE TITLE
support creation of DNS response policy zones (RPZ) to block phishing, malware and C&C hosts

### ISSUE THREAD

**Issue by bernhardreiter** [certtools/intelmq#1466]
## Use case 
If a data source indicates phishing, malware and C&C hosts
an operator of a internet service wants to use their DNS servers to
block access to those hosts.

## Design considerations
An output bot of some kind will be needed.

 * By default intelmq does not keep a memory of observed hosts and their status.
 * A https://datatracker.ietf.org/doc/draft-ietf-dnsop-dns-rpz/ file could be used by a DNS server like `bind` to create  IXFR/AXFR towards dns resolvers. The problem here is when to remove an entry again.

Technical ideas to solve this are:

1.   Add a data store to intelmq, e.g. to the bot itself, so a host status can be remembered and a complete file can be written whenever necessary. (One way to add a store is to use redis
 as a database, which offers a TTL for key-value entries. Hint from @aaronkaplan .)
2. Let the output bot only create single entries per event, but with a comment that can be used by a second process that periodically removes the entries from the file or dns resolvers again, based on infos in the comment (like remove on 2019-12-06T05:04:00Z).
3. Put event in a different component that does the job already like
 * https://github.com/Homas/ioc2rpz 
 *  or MISP

For the last option there is already code for a MISP output bot linked from https://github.com/certtools/intelmq/issues/834#issuecomment-457167151
(which would need checking regarding what it does, license and integration in intelmq main repo).

**Comment by bernhardreiter** [comment]
We from Intevation will work on getting a MISP output bot ready and upstream for this purpose.
(Work is contracted by SUNET.)

Seems we start at the code linked from #834

**Comment by wagner-certat** [comment]
So it is planned to use IntelMQ -> MISP -> RPZ?

**Comment by aaronkaplan** [comment]
> On 27.11.2019, at 13:05, Wagner <notifications@github.com> wrote:
> 
> So it is planned to use IntelMQ -> MISP -> RPZ?

In my humble opinion this still does not make much sense to go via MISP for what you are trying to achieve.
a print() of the RPZ zone file is easily done in a pure intelmq output bot (after combining events for a certain duration in some output queue ("aggregator"))

**Comment by bernhardreiter** [comment]
>  it is planned to use IntelMQ -> MISP -> RPZ?

Yes (this is our current understanding what matches the requirement best for our customer).

> In my humble opinion this still does not make much sense to go via MISP 

In my understanding, it makes sense, if there already is a MISP workflow established for creating RPZ files. Then the intelmq output would become other source to this workflow.

Technical it seems that the intelmq output bot can never alone make sure that RPZ entries are being removed when they should. It would at least need a cron trigger to rewrite the files for automatic removal after some time. The aggregating function of an intelmq bot would also make the implementation more complex and add the dependency of a database (e.g. redis, which is just a little requirement, because many intelmq installations use it as message queue, however intelmq at a few places wants to stay indepentent of the message queue implementation.)

**Comment by pettai** [comment]
> On 27.11.2019, at 13:05, Wagner ***@***.***> wrote: So it is planned to use IntelMQ -> MISP -> RPZ?
> In my humble opinion this still does not make much sense to go via MISP for what you are trying to achieve. a print() of the RPZ zone file is easily done in a pure intelmq output bot (after combining events for a certain duration in some output queue ("aggregator"))

While the subject of this issue says DNS RPZ, a MISP-output plugin is useful in other situations too (mostly for the correlation & sharing part which MISPs good at and IntelMQ isn't built for).
Perhaps the subject of this issue should be changed, so it's not misinterpreted as the way forward for generating RPZ-zones for IntelMQ?

**Comment by bernhardreiter** [comment]
CIRCL has added a general MISP-feed output bot meanwhile, see #834 and may even contribute an second one that uses the API, see https://github.com/certtools/intelmq/blob/develop/docs/MISP-Integrations.md

If this can be used to solve the use case stated here for people that already have MISP as part of their infrastructure, it would be one solution. So it somehow belongs to be documented here.

If it turns out the use case documented here needs another solution for non-MISP setups, we could split and use a second issue for this. At this moment I'm unsure if two issues are good, so I'm have a  light inclination to keep the title for now. Otherwise I could add an "in settings for MISP is also used"  to the title.

**Comment by pettai** [comment]
Ok, it seems unnecessary to do duplicate work. We should probably chat with @Rafiot.
Questions that comes to my mind: what is the time plan for contributing the (coming soon) MISP API Output? (if not planned yet, would it be ok for you to do the initial one?)

**Comment by wagner-certat** [comment]
@Rafiot was so kind to contribute the MISP feed output.

> Questions that comes to my mind: what is the time plan for contributing the (coming soon) MISP API Output? (if not planned yet, would it be ok for you to do the initial one?)

There is no timeplan. To avoid expectations in the future I now removed the section from the document.

**Comment by pettai** [comment]
Thanks for the clarification @wagner-certat. Then @bernhardreiter can continue working on the API Output bot, and if @Rafiot has time later, he is welcome review.

**Comment by wagner-certat** [comment]
Solved by the usage of MISP, we have two MISP output bots to push data into it.
