### ISSUE TITLE
MaxMind GeoLite2, now requires registration

### ISSUE THREAD

**Issue by kunforall** [certtools/intelmq#1484]
This morning, I found the update of GeoLite2 database failed.
And then noticed the announcement of the MaxMind GeoLite2 as below.

> Due to upcoming data privacy regulations, we are making significant changes to how you access free GeoLite2 databases starting December 30, 2019. Learn more on our blog.
  https://blog.maxmind.com/2019/12/18/significant-changes-to-accessing-and-using-geolite2-databases/

**Comment by kunforall** [comment]
I used the following workaround for update-geoip-data.

fetch_and_install()
{
  cd "$TMP_DIR"
  curl -s -S -o GeoLite2-City.mmdb.tar.gz "https://download.maxmind.com/app/geoip_download?edition_id=GeoLite2-City&suffix=tar.gz&license_key=XXXYourLicenseKeyXXX"
  tar -mzxf GeoLite2-City.mmdb.tar.gz
  mv -f GeoLite2-City_*/GeoLite2-City.mmdb "$DEST_FILE"
}

**Comment by chorsley** [comment]
Running into this same problem elsewhere, I've started using https://dev.maxmind.com/geoip/geoipupdate/ to manage regular updates of the Geolite2 DB. It's also been updated to handle the new license key requirement.

**Comment by wagner-certat** [comment]
Thanks. I updated the script to require a license key and update the documentation accordingly
I also re-used the proposal of @kunforall, thanks for that!

ae885175229d51938596df91c0f3d1870745fe99
