### ISSUE TITLE
No state file found. Please call 'intelmqctl upgrade-config'.

### ISSUE THREAD

**Issue by bernhardreiter** [certtools/intelmq#1491]
71ca7722ce073bd34d814c29bfc654b0af4776ff (HEAD -> develop)

After installation an `intelmqctl check` misses a "state file"
and recommends running upgrade-config. Following the recommendations leads to 
a strange situation.

```sh
$ intelmqctl check
Reading configuration files.
Checking defaults configuration.
Checking runtime configuration.
Checking runtime and pipeline configuration.
Checking harmonization configuration.
Checking for bots.
No state file found. Please call 'intelmqctl upgrade-config'.
No issues found.

$ intelmqctl upgrade-config
Writing intial state file.
Successfully wrote initial state file. Please re-run this program.

$ intelmqctl upgrade-config
Found no previous version, doing all upgrades.
Upgrading to version 1.0.0.dev7.
Migrate modify bot configuration format: Nothing to do.
[..]
```

It was a fresh installation from git (claming 2.2.0a1)

Expectation: no initial message asking for  a state file.

**Comment by wagner-certat** [comment]
Yes, `intelmqsetup` could cover this.

**Comment by wagner-certat** [comment]
intelmqsetup does it now and the need for calling upgrade-config twice is also gone
