### ISSUE TITLE
New options in Docker 

### ISSUE THREAD

**Issue by einar-lanfranco** [certtools/intelmq#1495]
Hi everyone, we develop one new docker option, the image is in dockerhub: https://hub.docker.com/repository/docker/certunlp/intelmq
Basically we uses your project source code but introducing some changes to the way it works.
We separate the bots from the core,  

* The core source code https://github.com/CERTUNLP/intelmq-docker
* The bots source code https://github.com/CERTUNLP/intelmq-bots

When you start the core you need to configure it  to use some git repository of bots.

We follow this path for 3 reasons:

1- Make our life easier: this way the bots development cycle is simplier
2- Privacy, you can keep your own in a private repository and just tell your intelmq image to use it, just need to configure it in docker-compose.yml
3- We made a pull detect to the repository of a requeriment of mail-*-fetcher bots martinrusev/imbox.  In  https://github.com/martinrusev/imbox/pull/173 be fix an issue of the library when it nedd to handle large filename, we have no answer yet. Then meanwhile we published https://github.com/mateodurante/imbox and add it to requirements.txt of intelmq when we build the docker image waiting for the answer from martinrusev.

We hope it is of your interest and consider adding it to the options you offer. Let us know if we can contribute and how to?

**Comment by wagner-certat** [comment]
> We separate the bots from the core,
> 
>     * The core source code https://github.com/CERTUNLP/intelmq-docker
> 
>     * The bots source code https://github.com/CERTUNLP/intelmq-bots
> 
> 
> When you start the core you need to configure it to use some git repository of bots.

That would be a major architectural change. I agree that this can make life easier in some cases, it also means more maintenance burden (and I currently can't keep up with the current developments & bugs).

> 2- Privacy, you can keep your own in a private repository and just tell your intelmq image to use it, just need to configure it in docker-compose.yml

Please make sure to not violate the AGPL.

> 3- We made a pull detect to the repository of a requeriment of mail-*-fetcher bots martinrusev/imbox. In [martinrusev/imbox#173](https://github.com/martinrusev/imbox/pull/173) be fix an issue of the library when it need to handle large filename, we have no answer yet.

:+1:

**Comment by wagner-certat** [comment]
I think this is resolved by https://github.com/certat/intelmq-docker/pull/3
Please reopen if I understood it wrongly.
