### ISSUE TITLE
Fresh install example config lacks BOTS file (v2.1.2)

### ISSUE THREAD

**Issue by bernhardreiter** [certtools/intelmq#1498]
Symptom:
```sh
intelmqctl check
Reading configuration files.
Coud not load '/opt/intelmq/etc/BOTS': [Errno 2] No such file or directory: '/opt/intelmq/etc/BOTS'.
Fatal errors occurred.
```

This happend after following 2.1.2 version of installation guide and then development guide.
Expectation: `intelmqsetup` also puts the BOTS file in the right place.

**Comment by wagner-certat** [comment]
Fixed by 6f71d7463e9da48afb3edce86d131fad78a089b4
