### ISSUE TITLE
Mail-Attachment-Fetcher-Collector failing to read attachments

### ISSUE THREAD

**Issue by bwogi28** [certtools/intelmq#1503]
Hello 

Was able to successfully set up Mail-Attachment-Fetcher-collector  with an IMAP inbox but it is failing to retrieve and pass the attachments. To be specific i want to parse  them to Shadow server-Parser since they are shadow server logs.
This is what is logged in the Mail-Attachment-Fetcher-Collector.log

Mail-Attachment-Fetcher-Collector - INFO - Email report read.
-- | -- | --

<img width="481" alt="i1" src="https://user-images.githubusercontent.com/5616830/74340855-c785a580-4db7-11ea-8c22-60e89a117788.png">
<img width="482" alt="i2" src="https://user-images.githubusercontent.com/5616830/74340857-c9e7ff80-4db7-11ea-94ac-2f812d620b87.png">

**Comment by wagner-certat** [comment]
So you mean that the attachment is not detected? Could you please run the bot with DEBUG log level and show the logs?
