### ISSUE TITLE
Incompatibility with stomp.py version 6

### ISSUE THREAD

**Issue by wagner-certat** [certtools/intelmq#1504]
Gives this error:
```
    self.conn.start()
AttributeError: 'StompConnection11' object has no attribute 'start'
```

**Comment by wagner-certat** [comment]
fixed by https://github.com/certtools/intelmq/commit/db35d2eaa631e51d4ed75d5a80f0b3187c80cfea

**Comment by guygordon** [comment]
how did you fixed this issue?

**Comment by kamil-certat** [comment]
@guygordon the STOMP support was fixed and upgraded a few times in IntelMQ since the original isue :)
