### ISSUE TITLE
allow bots check() method to run from test without full initialization

### ISSUE THREAD

**Issue by bernhardreiter** [certtools/intelmq#1505]
Allow the check() methods of bots to run in automatic tests.

Right now the check() can happen without all full libraries imported, to check for the existence of parameters, e.g. in https://github.com/certtools/intelmq/blob/ec0e911834a71c2c02c2c25ca0161758cf5b6a29/intelmq/bots/outputs/misp/output_feed.py#L106

It can be good to use the code for automatic tests as well. For this the prepare_bot() method
of https://github.com/certtools/intelmq/blob/ec0e911834a71c2c02c2c25ca0161758cf5b6a29/intelmq/lib/test.py#L187 would need to be split up, so that the init() method of the bot to be tested is not called. At least this would be needed if check() is used like it is in the MISP Output bot above.

**Comment by wagner-certat** [comment]
You mean like this?
85437351

**Comment by bernhardreiter** [comment]
Thanks for suggestion and improvement. Right now I cannot test it, so maybe. ;) It look a bit too simple, when I remember what I had tried, but maybe I did not understand enough when trying to poke around.

**Comment by wagner-certat** [comment]
> It looks a bit too simple,

That's what I thought too :) However, the static check methods are called.

**Comment by wagner-certat** [comment]
Based on what I coded in spring last year, I further added tests on the check's return values.

With the upcoming changes in the configuration handling, the check method will gain more functionalities.
