### ISSUE TITLE
develop branch Changelog announces OutputBot class from 2.1.0, but it is not included

### ISSUE THREAD

**Issue by bernhardreiter** [certtools/intelmq#1508]
It seems the mention of the new class OutputBot in the develop branch for 2.1.0
has to be removed, as it was not included in the release and is not in the "master" branch.

**Comment by wagner-certat** [comment]
I inserted the changelog entry in the wrong section in b587299e22a8bb7079f2281d6589367c024ce41c and b6a46e52c745579b9fbd9f28a3443dda3737935d
