### ISSUE TITLE
gethostbyname expert: Also get host for URLs if FQDN does not exist

### ISSUE THREAD

**Issue by e3rd** [certtools/intelmq#1511]
Usecase: I want every record to have `source.ip`. Some records have `source.fqdn`, some `source.url`.
I could easily use `url2fqdn` and `gethostbyname` experts. However, this would create a superfluous `source.fqdn` record for every `source.url` record.

Way 1: 
This way needs no more implementation, however, it will pollute the botnet with many bots.

`Sieve bot`
  * Does the record have `source.ip` → continue
  * Or does the record have `source.fqdn` → pass to `gethostbyname` and continue
  * Or does the record have `source.url` → pass to `url2fqdn` + `gethostbyname` and continue

Way 2:

Implement `gethostbyname` parameter **`accept_url`**. If True and no `source.fqdn` present, `source.url` would be taken to directly produce `source.ip`.

**Would you allow me to implement way 2?**

**Comment by wagner-certat** [comment]
I see your point.
However I wouldn't call the parameter `accept_url`. Maybe `fallback_to_url` or similar?

Or: What if gethostbyname just uses the URL by default if no FQDN is given?

Also @aaronkaplan

**Comment by e3rd** [comment]
Rather than using URL by default I'd prefer to set `fallback_to_url` to True. That way, we may cover all possible use cases of the people wanting to convert to IP both URL and FQDN or FQDN only.

**Comment by wagner-certat** [comment]
Btw: to get the Host from the URL, the `intelmq.lib.harmonization.URL.to_domain_name` method can be used.

**Comment by gethvi** [comment]
How about adding a function (perhaps `intelmq.lib.utils.extract_fqdn_from_url`) and leaving this up to the parsers? Unlike the `gethostbyname` bot which implements extra logic a functionality, getting `fqdn` from `url` is basically just string manipulation.
