### ISSUE TITLE
intelmqctl --type json check exits with 1 on success

### ISSUE THREAD

**Issue by bernhard-herzog** [certtools/intelmq#1520]
The check command of `intelmqctl` exits with 1 on success when run with
JSON output and 0 on error, which is of course exactly the opposite of
what should happen. With text output, the exit code is fine.

**Comment by wagner-certat** [comment]
Thanks for the report. The exit codes were simply swapped https://github.com/certtools/intelmq/blob/88d0773ddb0016dabf55ea7b21eb3bde22c2114a/intelmq/bin/intelmqctl.py#L1542-L1546
