### ISSUE TITLE
Relative time parsing in Filter Expert Bot

### ISSUE THREAD

**Issue by kbrajneesh** [certtools/intelmq#1523]
For relative filter, if param `not_after: x hours`  (**x < 24**) is given, instead of being parsed as **datetime.timedelta** object by
>             relative = timedelta(minutes=parse_relative(time_attr)) [Line 22]
currently it is being parsed as **datetime.datetime** object by
>             absolute = parser.parse(time_attr) [Line 20]
Leading to error
**TypeError: can't compare offset-naive and offset-aware datetimes**

**Comment by wagner-certat** [comment]
Thanks for reporting!
