### ISSUE TITLE
Bambenek parser broken? (pull request added)

### ISSUE THREAD

**Issue by pettai** [certtools/intelmq#1525]
Some of the Bambenek feeds have moved location and it seems like the parser doesn't handle the feed anymore.

UPDATE: the parser was dependent on correct feed.url, and new URLs has been added for [licensed](https://osint.bambenekconsulting.com/feeds/license.txt) downloads, https://github.com/certtools/intelmq/pull/1526 fixes this

There was some documentation on all possible feeds / data sources here somewhere, that should probably be updated about the Bambenek feed license too

**Comment by pettai** [comment]
wrong file was being parsed, but there is room for future improvements of the parser...

**Comment by pettai** [comment]
This fixes the problem https://github.com/certtools/intelmq/pull/1526

**Comment by wagner-certat** [comment]
Thanks!

So the feed is now private and no more public?

**Comment by pettai** [comment]
Some require a license now, but the DGA feed seems to be left for public use
