### ISSUE TITLE
MISP API output enhancements

### ISSUE THREAD

**Issue by pettai** [certtools/intelmq#1527]
Some enhancements worth considering:

* BUG: Avoid timeouts then doing lookup on configured ("significant_fields") fields that aren't in the intelmq item itself. This caused a long delay (timeout?) to occur, and a false-positive match on the search.
* ENH: Add a option for feed.name as tag (add_feed_name_as_tag)  
* ENH: Support Bulk output (Events grouped by feed.provider / feed.name ?)
   Add option for bulking multiple intelmq items in the queue, into a single misp event
* ENH: if a MISP event attribute is matched, update the event timestamp rather than doing nothing

**Comment by bernhardreiter** [comment]
## bad significant_fields
@pettai can you send me a log on the lookup timeouts?
As https://github.com/certtools/intelmq/blob/develop/intelmq/bots/outputs/misp/output_api.py#L100 should be false if `significant_fields` lists a unexisting attribute, I'm trying to understand what is going on in your case. 

## ENH `add_feed_name_as_tag`
* `add_feed_name_as_tag` should be straightforward to do, if it shall be modeled after the existing `add_feed_provider_as_tag`

## ENH "bulk" output
For IntelMQ the events generally  just run through.

To aggregate them for a special joined output, they need to be collected for a while. For example the mail generation as done by intelmq-mailgen as part of the  IntelMQ-cb-mailgen setups (https://github.com/Intevation/intelmq-mailgen-release) uses a PostgreSQL database
and a cron job to later collect and aggregate all events up to the point of running.

For the MISP output, the "collecting" part can happen in MISP. Once an intelmq events comes in that should be added to an existing MISP event, this event has to be found and the additional information added. @pettai do you have an example how additional intelmq-event should be added to MSIP events?

**Comment by pettai** [comment]
Added an enhancement
* ENH: if a MISP event attribute is matched, update the event timestamp rather than doing nothing

**Comment by pettai** [comment]
> **bad** **significant_fields**

So regarding this, source.reverse_dns doesn't exist in the intelmq event, nor in MISP-instance, hence I suspect the timeout. but I'm surprised by the match-all MISP events outcome.

It wasn't the only one, per default, the example code seems to default to source.fqdn + source.reverse_dns: https://github.com/certtools/intelmq/issues/1483#issuecomment-587409388

I'm not sure about your conclusion though, since you probably have multiple collectors and some of those feeds might be incomplete with regards to all significant fields, but I'm sure you still want the other data. 
But if no significant field is in the intelmq event, then it should be ignored (and logged that it was discarded due to missing mandatory fields)

**Comment by bernhardreiter** [comment]
> bad significant_fields

seems to be more like
## empty significant_fields

Yes, I'll have to find out, why they match so many MISP events in case one significant_fields value is empty. Then we can stop that behaviour.

It is clear that we at least need one significant field value to be present, otherwise there would be an insertion into MISP each time. Maybe there are some use case for this, but I don't directly imagine them.

**Comment by pettai** [comment]
> **ENH "bulk" output**

We can save this one for last. Perhaps making a MISP feed is the better approach...

**Comment by bernhardreiter** [comment]
For information, SUNET via @pettai has contracted us (Intevation) to work on this (except "bulk"). So I'll be working on it.

**Comment by bernhardreiter** [comment]
## empty significant_fields
A test case for the behaviour of pymisp's `search()` has been filed at https://github.com/MISP/PyMISP/issues/577

**Comment by bernhardreiter** [comment]
##  ENH update the event timestamp 
@pettai the event.timestamp seems to be updated by pymisp itself and it is not recorded as part of the event history. An update can be done easily, the bot just set the event.timestamp to `datetime.now()` and calls `misp.updated_event()`.  It then just has the "Last change" entry changed in the MISP gui as far as I can see. Of course the time.observation of the old intelmq event will stay the same.

So in the simplest implementation just the "last change" entry will be newer, without a chance in the gui to see what kind of change was done and by whom. Is this what you want?

**Comment by pettai** [comment]
> ENH update the event timestamp

If the feed.source + <attribute> in the Event is the same, then yes, that should suffice.

**Comment by bernhardreiter** [comment]
## empty significant fields
https://github.com/Intevation/intelmq/commit/005755e1a07285c6a6ae8ccd75509ca3aa250b51 has two more checks now. As a closer inspection of the log showed that no significant field had a value. Again compare to https://github.com/MISP/PyMISP/issues/577

**Comment by bernhardreiter** [comment]
## ENH update the MISP event's timestamp
Done with https://github.com/Intevation/intelmq/commit/9d42f37b9f492e97d71063c69306c857f1c68e1a
(took more work to actually match the MISP attributes)

**Comment by bernhardreiter** [comment]
Code is ready and pull requested.

To test it, grab it from the branch: https://github.com/Intevation/intelmq/tree/dev-output-bot-misp-enh1/intelmq/bots/outputs/misp
 * stop the intelmq bot
 * place output_api.py over the old one (better move the old one away)
 * start the bot

Of course further improvements are possible, as the new checking code
in `_update_misp_event()` could also be moved and adapted to be used in the initial check.
