### ISSUE TITLE
IMQ Manager does not show correct version in frontend

### ISSUE THREAD

**Issue by cgi1** [certtools/intelmq#1529]
Not sure why this is happening:

![grafik](https://user-images.githubusercontent.com/18695252/81658465-1683bb00-9439-11ea-9f68-10be997e582c.png)

![grafik](https://user-images.githubusercontent.com/18695252/81658392-0370eb00-9439-11ea-9872-07978552acfa.png)

**Comment by bernhardreiter** [comment]
Hi @cgi1 shouldn't this be reported to https://github.com/certtools/intelmq-manager instead?

**Comment by sustefil** [comment]
Hi there, we already resolved the issue with @cgi1, can be closed.

**Comment by bernhardreiter** [comment]
@sustefil   what was the solution?

@cgi1, if this is solved, can you close this issue? (I cannot, you as original reporter can.)

**Comment by sustefil** [comment]
@bernhardreiter just a mistake on our side, forgot to copy the files over to /var/www/html
