### ISSUE TITLE
Developers-Guide.md#update group permissions for Manager

### ISSUE THREAD

**Issue by bernhardreiter** [certtools/intelmq#1531]
@sebix 
isn't the 
```sh
chown -R intelmq.intelmq /opt/intelmq
```

in https://github.com/certtools/intelmq/blame/develop/docs/Developers-Guide.md#L147
a problem, if the manager is installed, because the manager would need the group to be `www-data` in the standard setup?

**Comment by wagner-certat** [comment]
Thanks, I'll make it more verbose.
