### ISSUE TITLE
Feed Docu Update

### ISSUE THREAD

**Issue by chappi6** [certtools/intelmq#1537]
Hi, 
I just checked the Feed Urls and found some who are offline. Please update the Feed Documentation.  

Ransomware Tracker
was    Status: on seems to bee offline 
 Status: off
https://ransomwaretracker.abuse.ch/feeds/csv/

`# Ransomware Tracker has been discontinued on Dec 8th, 2019`

Nothink change most of the links they are not availble any more:  
http://www.nothink.org/honeypot_dns_attacks.txt
http://www.nothink.org/blacklist/blacklist_snmp_day.txt
http://www.nothink.org/blacklist/blacklist_ssh_day.txt
http://www.nothink.org/blacklist/blacklist_telnet_day.txt
`
No webpage was found for the web address: http://www.nothink.org/honeypot_dns_attacks.txt`

But there are a bunch of new Links available under http://www.nothink.org/

URLVir
I didnt got any response just a blank page.
http://www.urlvir.com/export-hosts/

br

**Comment by wagner-certat** [comment]
> I just checked the Feed Urls and found some who are offline. Please update the Feed Documentation.
Thanks for checking it!

From time to time I do it too, but the sources are changing quite fast...

> 
> Ransomware Tracker
> was Status: on seems to bee offline
> Status: off
> https://ransomwaretracker.abuse.ch/feeds/csv/
> 
> `# Ransomware Tracker has been discontinued on Dec 8th, 2019`

Thanks, done in 7368848f

> Nothink change most of the links they are not availble any more:
> http://www.nothink.org/honeypot_dns_attacks.txt
> http://www.nothink.org/blacklist/blacklist_snmp_day.txt
> http://www.nothink.org/blacklist/blacklist_ssh_day.txt
> http://www.nothink.org/blacklist/blacklist_telnet_day.txt
> ` No webpage was found for the web address: http://www.nothink.org/honeypot_dns_attacks.txt`
> 
> But there are a bunch of new Links available under http://www.nothink.org/

Is someone able to create configurations for the new feeds, e.g. with the HTML Table parser? That would help me a lot.
https://www.nothink.org/honeypots/honeypot_dns_reflection_attacks.php
https://www.nothink.org/honeypots/honeypot_snmp_attacks.php

There are two feeds with 2019 in the URL:
https://www.nothink.org/honeypots/honeypot_ssh_blacklist_2019.txt
https://www.nothink.org/honeypots/honeypot_telnet_blacklist_2019.txt
I asked the feed provider about the status.

> URLVir
> I didnt got any response just a blank page.
> http://www.urlvir.com/export-hosts/

I asked them about the status, as I am not sure if this is maybe a (temporary) problem on their side.

**Comment by wagner-certat** [comment]
The nothink honeypot feeds have been discontinued for financial reasons. We need to remove them.

**Comment by wagner-certat** [comment]
Nothink removed in 8b8c1190

**Comment by chappi6** [comment]
Ah to bad.... 
Are you responsive on your cert address?

**Comment by wagner-certat** [comment]
> Are you responsive on your cert address?

Best effort ;)

**Comment by wagner-certat** [comment]
> > URLVir
> > I didnt got any response just a blank page.
> > http://www.urlvir.com/export-hosts/
> 
> I asked them about the status, as I am not sure if this is maybe a (temporary) problem on their side.

Got a response now: data feed is dicontinued
