### ISSUE TITLE
Deduplicator: Problem with hash function with multiple filter_keys values

### ISSUE THREAD

**Issue by G0meisa** [certtools/intelmq#1539]
Hi,
Deduplicator expert uses a hash function, with list of blacklist or whitelist fields.
The hash function doesn't work properly when more than one fields is set for the filter_keys.
In test_message.py I've tested "test_event_hash_method_blacklist" function, If you add another field to filter_keys the hash won't be the same when they should.

**Comment by wagner-certat** [comment]
Could you please clarify your observation? This example test passes for me:
```python
    def test_event_hash_issue_1539(self):
        event = self.new_event()
        event = self.add_event_examples(event)
        self.assertEqual(event.hash(filter_type="blacklist",
                                    filter_keys={"source.ip"}),
                         event.hash(filter_type="blacklist",
                                    filter_keys={"source.fqdn"}))
```

**Comment by G0meisa** [comment]
I've changed the feed.name and added it to whitelist  but all the test passed.
`    def test_event_hash_method_whitelist(self):
        """ Test Event hash(blacklist) """
        event = self.new_event()

        event1 = self.add_event_examples(event)
        event2 = event1.deep_copy()

        event2.add('feed.name', 'Some Other Feed', overwrite=True)

        self.assertNotEqual(event1.hash(), event2.hash())

        self.assertEqual(event1.hash(filter_type="whitelist",
                                     filter_keys={"feed.name,raw"}),  
                         event2.hash(filter_type="whitelist",
                                     filter_keys={"feed.name, raw"}))`

**Comment by wagner-certat** [comment]
It took me a while to understand where the bug comes from, but I've now found it: That's a bug in the testcases

Wrong:
```python
filter_keys={"feed.name,raw"}),
```
Correct:
```python
filter_keys={"feed.name", "raw"}),
```
