### ISSUE TITLE
Stacking up multiple incoming messages and forwarding only one

### ISSUE THREAD

**Issue by RosinTheBeau** [certtools/intelmq#1541]
Hi, I was wondering if it is possible for an IntelMQ bot to collect incoming messages (in a buffer for example) and every 2 seconds to forward only one message that will regroup the payloads of all the incoming messages received during those 2 seconds.

I have already created custom bots, so I am comfortable with modifying their source code, in case my problem doesn't have an existent solution. I just need to know how to do so. 

Thanks a lot!

**Comment by wagner-certat** [comment]
Hi,

> Hi, I was wondering if it is possible for an IntelMQ bot to collect incoming messages (in a buffer for example) and every 2 seconds to forward only one message that will regroup the payloads of all the incoming messages received during those 2 seconds.

Not currently. How should that regrouping work?

> I have already created custom bots, so I am comfortable with modifying their source code, in case my problem doesn't have an existent solution. I just need to know how to do so.

Great to hear - we always welcome contributions :)

similar issues/questions: #751 #1509 

cc @aaronkaplan

**Comment by aaronkaplan** [comment]
I'll take that as architecture wish list item for IntelMQ 3.0 . Thanks!

**Comment by aaronkaplan** [comment]
It is in the architecture document. This one is not so easy.

**Comment by wagner-certat** [comment]
reminder @aaronkaplan you assigned this to you

btw, we have an aggregate expert #1959 it might solve this issue

**Comment by wagner-certat** [comment]
Please check if the aggregate expert solves your problem: https://intelmq.readthedocs.io/en/latest/user/bots.html#aggregate
Otherwise please reopen the issue.
