### ISSUE TITLE
Core - Hashing - SHA1 is deprecated

### ISSUE THREAD

**Issue by aaronkaplan** [certtools/intelmq#155]
This is a minor thing for now, however, in the long run we should switch to SHA2 since SHA1 has problems when it comes to possible collisions.

From file:
lib/utils.py:

def hashgen(data, func=hashlib.sha1):

--> switch to SHA2

**Comment by azet** [comment]
btw. if you want to use a good crypto api, there's now a new python crypto authority (hashlib kinda sucks):  http://cryptography.io/ (compatible with python2 and python3

**Comment by SYNchroACK** [comment]
implemented on [lib/message.py](https://github.com/certtools/intelmq/blob/master/intelmq/lib/message.py#L314)
