### ISSUE TITLE
HPHosts feed doesn't seem to exist anymore

### ISSUE THREAD

**Issue by gethvi** [certtools/intelmq#1559]
The URL for the feed: https://hosts-file.net/download/hosts.txt

Returns 404.

The root URL https://hosts-file.net/ redirects to https://www.malwarebytes.com/browserguard.

**Comment by wagner-certat** [comment]
Thanks, I'll do the cleanup work.

**Comment by wagner-certat** [comment]
fixed in fcf8395418df385569ead49aec7aa14f9802dc80
