### ISSUE TITLE
Bash completion scripts search in wrong directory in packages

### ISSUE THREAD

**Issue by wagner-certat** [certtools/intelmq#1561]
For LSB-path installations, the bash completion-scripts use /opt/intelmq/etc and /opt/intelmq/var/log instead /etc/intelmq und /var/log/intelmq

Idea: Instead of using the fixed path, use same logic as in `__init__.py` and check if the directories exist. If this is ambiguous, use `intelmqctl debug` to get the path (but that needs more time)

**Comment by wagner-certat** [comment]
> (but that needs more time)

I meant execution time

**Comment by aaronkaplan** [comment]
Or just use /etc/default/intelmq ... and define some very common , basic configs there (such as where intelmq resides)
