### ISSUE TITLE
Output - PostgreSQL - Handling insertion errors

### ISSUE THREAD

**Issue by aaronkaplan** [certtools/intelmq#157]
If the data arriving at the postgresql bot can not be inserted into the postgresql DB, it should not stop processing but rather log an error an continue.

**Comment by SYNchroACK** [comment]
Fixed.
* in the v1.0-beta branch, values trully respect the harmonization since the datatype need to be defined.
* in the v1.0-beta branch, each bot can configure the following parameters like you need:
```
    "error_procedure": "pass",
    "error_log_message": true,
    "error_log_exception": true,
    "error_dump_message": true,
```
