### ISSUE TITLE
Abuse.ch URLhaus feed parsing error

### ISSUE THREAD

**Issue by gethvi** [certtools/intelmq#1571]
Feeds documentation suggests using generic CSV parser for this feed. However the mapping for columns brings error for lines, where there is no FQDN. Example:

```
"2020-04-03 13:11:03","http://ucto-id.cz/binr.image","offline","malware_download","ucto-id.cz","87.236.194.255","35592","CZ"
"2020-04-04 13:17:12","http://80.211.217.221/hakka/helios.x86","offline","malware_download","80.211.217.221","80.211.217.221","24806","CZ"
```

The first line is parsed fine, because the fifth column contains valid FQDN. However the second line throws InvalidValue exception, because `80.211.217.221` is obviously not valid FQDN.

Secondly, `type_translation` is ignored because the `malware_download` string is assigned to key `extra.urlhaus.threat_type`.

Also `delimeter` parameter is missing.

Fixes incoming.

**Comment by wagner-certat** [comment]
Thanks for reporting and fixing this documentation bug!

> Also `delimeter` parameter is missing.

The default `,` is fine here, [but explicit is better than implicit](https://www.python.org/dev/peps/pep-0020/).
