### ISSUE TITLE
Generic csv parser multiple regex

### ISSUE THREAD

**Issue by G0meisa** [certtools/intelmq#1579]
Hello,

In generic csv parser if you want to use regex for multiple fields like this:
`{"time.source":"(?<=\=).*","source.ip":"(?<=\=).*"`
you will get this error:
` File "/opt/dev_intelmq/intelmq/bots/parsers/generic/parser_csv.py", line 106, in parse_line
    regex = self.column_regex_search.get(key, None)
AttributeError: 'str' object has no attribute 'get'`

I suggest adding ` self.column_regex_search=ast.literal_eval(self.column_regex_search)` 
after getting the column_regex_search parameter in init function.

**Comment by wagner-certat** [comment]
`literal_eval`? No. `json.loads` is sufficient.

Did you forget the closing `}` just here in the issue?

Did you use the IntelMQ Manger? I assume that's an issue of parameter type (value is saved as string, not as dict), see certtools/intelmq-manager#81, but I thought we already fixed that.

**Comment by G0meisa** [comment]
Mising `}` is just a typo in here.

Yes I'm using IntelMQ Manager version 2.1.1

**Comment by wagner-certat** [comment]
IMHO that's a bug in the Manager, as it saves a dictionary as string, not as dict object itself.

@e3rd I image that did work in the past if I remember correctly. But certtools/intelmq-manager#174 only affected the configuration parameter loading, not the writing (as that was - IIRC - anyway the default behavior). Do you remember something on that topic? It's already 1.5 years ago and I am not sure if that worked at that time.

**Comment by e3rd** [comment]
(sorry, I'm out, get back to this around next Wed)

**Comment by e3rd** [comment]
I've found a place where we are using dict, in `collector_http` https://github.com/certtools/intelmq/blob/950b5ab8c5c06d2337166c1093c52a84c29993c8/intelmq/bots/collectors/http/collector_http.py#L54 We receive a dict in the variable `formatting`, it works correctly. When I try to re-save it in the manager, it even looks as a dict in the runtime.conf: `"http_url_formatting": {
                "days": -1
            },`. Could you please paste here the concerning part of `runtime.conf`, as generated by the Manager, so I can clearly see whether the Manager saves it as a dict or as a str?



IntelMQ 2.2.0
IntelMQ Manager 2.2.0

**Comment by wagner-certat** [comment]
You are right, the feature itself works. With that information I now found out, why it fails in this case. It's escaping.

If you enter this value in IntelMQ Manager, it is saved as string:
```
{"time.source":"(?<=\=).*","source.ip":"(?<=\=).*"}
```
And this is saved as dictionary:
```
{"time.source":"(?<=\\=).*","source.ip":"(?<=\\=).*"}
```
Mind the escaped backslashes.

The first is not a proper object (or whatever it is called in JavaScript) as the escaping is wrong.

Edvard, do you think we can we do something about that? Except for mentioning it in the docs.

**Comment by e3rd** [comment]
I've tested a solution PR'ed above that might do. It doubles all backslashes in the bot dict-like parameters which is what we want here. 

However, this solution would break up things – we could no more insert a new-line character.

My skilled opinion **is to document** you have to properly put double-backslashes into the regexes. 

Consider this:
```python
r"\*" == "\\*" == "\*"  # True
r"\n" == "\\n" != "\n"  # True
```
I guess software can easily guess whether your backslash needs to be doubled or not.

**Comment by wagner-certat** [comment]
Thanks for you efforts @e3rd I see your point and I thus added this to the docs of the Generic CSV Parser.
