### ISSUE TITLE
Inconsistent use of shebang

### ISSUE THREAD

**Issue by mlmarkovic** [certtools/intelmq#1582]
Most .py files use `#!/usr/bin/python3` as shebang, but few others use `#!/usr/bin/env python3`.

Files which use `#!/usr/bin/env python3`:
```
./contrib/eventdb/common.py
./intelmq/bin/intelmq_generate_misp_objects_templates.py
./intelmq/tests/bots/parsers/github_feed/test_parser.py
```
These files should use `#!/usr/bin/python3` for the sake of consistency.

**Comment by wagner-certat** [comment]
For the tools which cannot be run standalone, the shebang can be removed at all. That affects for example intelmqctl, intelmqdump and others. For script which are needed for development, like `intelmq_gen_docs` and `intelmq_generate_misp_objects_templates`, the shebang is necessary, but `intelmq/bin/` might be the wrong place for them anyway.

I'm ok with having env-shebangs in the repo (but if, then consistently), for the deb/rpm packages we remove then anyway automatically.

Comments appreciated.
