### ISSUE TITLE
Cymru Expert: Wrong Cache-Key Calculation

### ISSUE THREAD

**Issue by daniwb** [certtools/intelmq#1592]
The Cymru Expert creates a Key from an IP-Address in the following manner:
IP to Int 
Int to bin
f.e.:
8.39.215.10 => 136828682 => '0b**100000100111110101110000**1010'

When the first octet is smaller than 128 (ipv4), the resulting binary is < 32 Chars.
For the Key Calculation in the Cache you strip the IP address to 24 Chards (in ipv4), this leads to wrong information in the cache.

The upper IP leads to a key: 100110010110110101111100

When you check the same algorithm for 130.125.112.0 you will end up with the same key.
[130.125.112.0 => 2189258752 => '0b**100000100111110101110000**00000000']

This will lead to wrong information when the Cache is hit.

Suggestion:
(Line 55, intelmq/bots/experts/cymru_whois/expert.py)
            cache_key = bin(ip_integer)[2: minimum + 2]

            ip_bin = bin(ip_integer)[2:]
            if(ip_version == '4' and len(ip_bin) < 32) # check if lenght is smaller than 32, so shorten minimum
                minimum = minimum - (32 - len(ip_bin))
            cache_key = ip_bin[0:minimum]

But maybe you have a better Idea.

This will lead, that the Key is shorter than 24 Characters if the first octet of the ip is smaller than 128.

**Comment by wagner-certat** [comment]
Thanks @daniwb for finding this nasty bug! Have you been hit by it?

That code is pretty old and was first introduced in 0942056d1. @SYNchroACK @aaronkaplan do you know any background on the logic used here?

**Comment by daniwb** [comment]
Thanks for the quick reply @wagner-certat 
Yes we were hit by the bug, we heard about problematic routing since more than a year, but we didn't had the time to check in detail because of our complex configuration. Finally we have found it.

**Comment by wagner-certat** [comment]
I don't see a reason why the computation of the cache key is so complex, do you see any? I think we can just use something easier and more readable like `ipv[46]_[address]`, e.g.  `ipv4_127.0.0.1`.

I'd also remove the backwards compatibility, basically invalidating the existing cache, as we know it is bogus.

**Comment by wagner-certat** [comment]
I proposed a fix in #1606
