### ISSUE TITLE
the upgrade procedure overwrites /etc/intelmq/* configs. 

### ISSUE THREAD

**Issue by aaronkaplan** [certtools/intelmq#161]
```pip install --upgrade git+https://$username@github.com/certtools/intelmq.git ```  overwrites the /etc/intelmq/* configs. 
That can be unexpected behaviour (even if documented) for users. 
We should improve the user experience here.

**Comment by SYNchroACK** [comment]
Fixed.

0913cbb92f6efa3fa30b0868f521466dcc4347b7
f3d50d973aeac58c410a0f44fa4d87ad3df8d5ff
