### ISSUE TITLE
if /etc/intelmq is not writeable (permissions) then intelmq-manager does not show it to the user

### ISSUE THREAD

**Issue by aaronkaplan** [certtools/intelmq#162]
If the unix ownership of /etc/intelmq/* is not set to intelmq:intelmq (with proper perms 0644), then intelmq-manager will say "yes, I 'll save your config" when the user presses "save" . However, it has not feedback if the save operation succeeded. In the case of wrong ownership/perms, it did not succeed.

Need to fix the user experience here.

**Comment by SYNchroACK** [comment]
Moved to intelmq-manager issues section
