### ISSUE TITLE
Document missing commandline switches of intelmqctl run

### ISSUE THREAD

**Issue by schacht-certat** [certtools/intelmq#1625]
in the `--help` output of `intelmqctl` the switches `-p` and `-m` are missing

**Comment by wagner-certat** [comment]
They are defined in the help pages of the respective subcommand help pages, e.g. `intelmqctl upgrade-config -h`

**Comment by schacht-certat** [comment]
Ah, sorry, I was both wrong and not specific enough: I was referring to this example from the tutorial `intelmqctl run MaxMind-GeoIP-Expert process -m '{"source.ip": "131.130.254.77"}' -d -s`. I was not able to find an explanation about `-d`, `-s` and `-m` but I've now tried `intelmqctl run MaxMind-GeoIP-Expert process -h` which gives and explanation
