### ISSUE TITLE
Collector - URL - Add user-agent

### ISSUE THREAD

**Issue by aaronkaplan** [certtools/intelmq#165]
Some feeds seem to block the default urllib2 user-agent:

Example:

```
curl -A "Python-urllib/2.6" http://malc0de.com/rss/
```

--> blocked

```
curl -A "mozilla" http://malc0de.com/rss/
```

--> works!

So, it might be a good thing to add a user-agent parameter to the url fetcher bot.
(credits for discovering this go to @chorsley )

**Comment by SYNchroACK** [comment]
I suggest:
1. Create (if is not already created) the malc0de bots (IPs feed and Domains feed)
2. Verify that error persist
3. Add user-agent parameter to IntelMQ

**Comment by aaronkaplan** [comment]
Agreed makes sense

---
Mobile

**Comment by robcza** [comment]
Could this be done like this? user-agent defaults to Chrome, worked good for me. It is configurable per collector if needed.
https://github.com/robcza/intelmq/commit/6351643c0d365a57b87112b6a156f9d38ed02a8b

**Comment by SYNchroACK** [comment]
Looks great @robcza ! For me is completely ok. ;)

**Comment by mauroasilva** [comment]
I would suggest that instead of:

`if user_agent == None:`
`    user_agent = "Mozilla/5.0 (Windows NT 6.1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/41.0.2228.0 Safari/537.36"`

You can put it into the definition of the function like this:

`def fetch_url(url, timeout=60.0, chunk_size=16384, http_proxy = None, https_proxy = None, user_agent = "Mozilla/5.0 (Windows NT 6.1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/41.0.2228.0 Safari/537.36"):`

**Comment by robcza** [comment]
Thanks @mauroasilva, you are right. My construct is kinda confusing and it is a result several different approaches I've tried.

**Comment by mauroasilva** [comment]
Hmm... I see... you are right. From that perspective I think your solution might be the best because it is better to have greater complexity on the lib than on the bots. Thanks for the contribution ;)

**Comment by SYNchroACK** [comment]
Thank you @robcza . Great work!

**Comment by robcza** [comment]
Ok guys, I've destroyed everything, let's fix it (collectors are not working with my adjustments without user_agent defined in system.conf). My proposals are:
1) Define default user_agent in system.conf, for example the chrome one, add the user_agent header only if "if user_agent != None:"
2) Leave everything as it is and just define "user_agent" = null in the system.conf

Let me please know, what do you prefer, I'll fix. Terribly sorry for introducing such a mess.

**Comment by mauroasilva** [comment]
To be honest I don't like having the User Agent in the system.conf, for every bot that doesn't need it, the existence of this feature should be transparent.

**Comment by mauroasilva** [comment]
Let me make a suggestion, not sure if everyone will agree with it... what if in the collector we put:

```python
user_agent = self.parameters.user_agent if hasattr('user_agent', self.parameters) else None
```

Instead of the current:

```python
user_agent = self.parameters.user_agent
```

**Comment by robcza** [comment]
thank you @mauroasilva, just switched the parameters for hasattr, otherwise I've included your code as proposed
https://github.com/certtools/intelmq/pull/269

**Comment by SYNchroACK** [comment]
Check the comment here: https://github.com/certtools/intelmq/pull/269
