### ISSUE TITLE
Core - Startup checks

### ISSUE THREAD

**Issue by SYNchroACK** [certtools/intelmq#169]
Add some checks in intelmqctl to check:
- bot id is valid
- queues name are valid
- queues are already in use
- intelmqctl 'alreay message'

**Comment by Phantasus** [comment]
@SYNchroACK What do you think if, whoever does this issue, also fixes the bug of displaying "already started",
when a bot is freshly started? Atleast this is in the master branch, don't know if you fixed that already in
your beta branch.

**Comment by CNCS-PT** [comment]
accept

**Comment by SYNchroACK** [comment]
@Phantasus , accepted

**Comment by sebix** [comment]
> * bot id is valid

fixed by 3a25cdbd68608d59dff233563bed9b4ff58a7037
> * queues name are valid

There's no functionality to give queue names.
> * queues are already in use

What is the difference between empty queues and queues not in use?
> * intelmqctl 'alreay message'

fixed by 9cd3205759f17182371919cf9a591e35eabc3f16

**Comment by SYNchroACK** [comment]
>> * bot id is valid

>fixed by 3a25cdbd68608d59dff233563bed9b4ff58a7037 (in main repo)

awesome!

>> * queues name are valid

>There's no functionality to give queue names.

The idea is to add that functionality and then check the queue names.

>> * queues are already in use

>What is the difference between empty queues and queues not in use?

Didnt understand the question.

>> * intelmqctl 'alreay message'

>fixed by 9cd3205759f17182371919cf9a591e35eabc3f16 (currently only in my fork)

awesome!

**Comment by sebix** [comment]
> > > * queues name are valid

> > There's no functionality to give queue names.

> The idea is to add that functionality and then check the queue names.

Which functionality do you mean in particular? I implemented the `--clear` function, which needs the queue name, the check is implemented. Do you mean that? 

> > > * queues are already in use

> > What is the difference between empty queues and queues not in use?

> Didnt understand the question.

Ok, what do you mean with *queues are already in use* in intelmqctl-context?

**Comment by SYNchroACK** [comment]
Well, to be honest i dont remember precisely what I mean but the generic idea is to add the possibility to change through intelmq-manager or manually the queues names in configuration but to be sure, we need to check the name of queues are valid.

Regarding the 'queues not in use' i dont remember as well... forget it...may be in future I will remember :P

**Comment by sebix** [comment]
> to add the possibility to change through intelmq-manager or manually the queues names in configuration but to be sure, we need to check the name of queues are valid.

Currently the intelmq-manager directly accesses/writes the files and intelmqctl has no functionality at all writing any kind of configuration.
So you want a feature to renames queues in configuration?

**Comment by SYNchroACK** [comment]
yes @sebix  ;)

**Comment by sebix** [comment]
I don't see a good reason to implement a functionality renaming queue-names. Moving to Future.

**Comment by wagner-certat** [comment]
Unassigning this from me now, because I don't see a good reason to do this.
