### ISSUE TITLE
Shadowserver Parser: missing mapping for sinkhole_dns parser

### ISSUE THREAD

**Issue by wagner-certat** [certtools/intelmq#1716]
We are missing a mapping for this feed: https://www.shadowserver.org/what-we-do/network-reporting/sinkhole-dns-report/

**Comment by schacht-certat** [comment]
> This report lists DNS queries seen from recursive DNS servers for sinkholed domains. Please note that the IP listed are not the 
> same as the actual source IP of the client that is making the query and hence are likely not infected hosts. This report therefore
> is to be used primarily to support investigations into a threat, and **not as a source of direct identification of infected  hosts**.

not sure how useful that information is in IntelMQ

**Comment by wagner-certat** [comment]
> not sure how useful that information is in IntelMQ

Maybe not for every user, but surely for some of them.
