### ISSUE TITLE
Send multiple events as one file with the same source.asn to one email address

### ISSUE THREAD

**Issue by Higgsx** [certtools/intelmq#1719]
This is a question :)

I have one feed, lets say it is shadowserver. I receive events freely and writing to a file. everything works just fine.

I have events like:
```
{"source.asn": 11111, "source.ip": "212.2.2.2"}
{"source.asn": 11111, "source.ip": "212.2.2.3"}
{"source.asn": 22222, "source.ip": "212.2.2.4"}
{"source.asn": 22222, "source.ip": "212.2.2.5"}
{"source.asn": 33333, "source.ip": "212.2.2.6"}
```

I want events which have source.asn == 11111 to be combined into one email attachment and send to abc@abc.com
I want events which have source.asn == 22222 to be combined into one email attachment and send to bbb@bbb.com

I tried to explain what I want as clearly as possible :)

I can send emails freely but issue is that email recipient is receiving 5 emails and each attachment has only one event.
what I want is one attachment which contains multiple events.

Smtp-output sends only one event per email.
![2021-01-22 16_01_16-Mailtrap - Safe Email Testing](https://user-images.githubusercontent.com/11138119/105488731-85edc200-5ccb-11eb-88bb-e60a4c5d7782.png)

Here, asn: 20771 should have only one email and not two.

I read documentation, also tried multiple bots but can't get result what I want. Maybe I missed something...

**Comment by wagner-certat** [comment]
Hi and sorry for the late response,

Sending data grouped is not easy as it sounds unfortunately. You need some database to queue the events (SQL or "NoSQL") and some rules on which you decide on the grouping, including network ranges/ASNs, abuse contacts, time spans etc. There is no solution that fits all different needs and therefore this component is *often* implemented per user.

In your case, if you want to send via SMTP, have a look at the [mailgen program](https://github.com/Intevation/intelmq-mailgen) which sends notifications via SMTP, with some OTRS integration. I don't know however if OTRS is strictly necessary to operate mailgen or if it can be disabled. (mentioned and linked in the [ecosystem document](https://intelmq.readthedocs.io/en/latest/user/ecosystem.html))

If you are interested in an aggregation component in IntelMQ, or something else, we could also aim for a small hackathon to evaluate ideas and possible paths forward.

cc @bernhardreiter

**Comment by Higgsx** [comment]
Thanks for reply. I solved the problem. I wrote my own scripts and they sort my data into groups by asn as I wanted.

**Comment by bernhardreiter** [comment]
@wagner-certat Yes, it is possible to run https://github.com/Intevation/intelmq-mailgen without OTRS. (I wonder where the OTRS mention comes from in the ecosystem document.)
