### ISSUE TITLE
Shadowserver Collector: (Optionally?) Only collect reports which we can parse

### ISSUE THREAD

**Issue by ghost** [certtools/intelmq#1727]
The Shadowserver collector can fetch all reports, including reports where the parser does not have a mapping for. If the collector is configured to fetch all reports, the parser will fail.

I see two options:
 1. The collector does not fetch unparseable reports.
    - Optional: Add a parameter to download all reports, irrespective of parseability
 2. The collector fetches all reports by default and add an optional parameter to skip unparseable reports.

If the collector is configured to fetch a list of reports, IMO the report should also be fetched if there is no mapping, as it is explicitly requested.

I'm in favor of option 1

**Comment by waldbauer-certat** [comment]
IMHO I would also prefer option 1. 

>     * Optional: Add a parameter to download all reports, irrespective of parseability
> If the collector is configured to fetch a list of reports, IMO the report should also be fetched if there is no mapping, as it is explicitly requested.

Is it important to have such feature? Is it used if reports are parseable later on?

**Comment by wagner-certat** [comment]
> Is it important to have such feature? Is it used if reports are parseable later on?

I think *not having* the possibility to download the reports the user explicitly wants to download is an anti-feature :)

And yes, for archiving and similar purpose it can be useful.

**Comment by sebix** [comment]
cc @elsif2

**Comment by elsif2** [comment]
Once https://github.com/certtools/intelmq/pull/2143
 is merged, all supported Shadowserver report types will have a parser.  New parsers will be added as new types are announced.

**Comment by elsif2** [comment]
All existing Shadowserver report types are supported in the develop branch. 

Support for new reports will be added as they are deployed to consumers.
