### ISSUE TITLE
Shadowserver parser: missing mapping for Vulnerable HTTP Report

### ISSUE THREAD

**Issue by wagner-certat** [certtools/intelmq#1733]
https://www.shadowserver.org/what-we-do/network-reporting/vulnerable-http-report/

**Comment by waldbauer-certat** [comment]
Its already implemented https://github.com/certtools/intelmq/commit/092a37a8e1ab06882528b3804a8d988bfec37cf5

**Comment by wagner-certat** [comment]
As I said in #1736 , The Vulnerable HTTP and Accessible HTTP feeds are different
