### ISSUE TITLE
regression: intelmq-manager does not properly write to new /opt/intelmq/etc/* files

### ISSUE THREAD

**Issue by aaronkaplan** [certtools/intelmq#174]
How to repeat:

try editing something in intelmq-manager (-> Configuration), press "Save".
The file ```/opt/intelmq/etc/pipeline.conf ``` will get written to properly, however, ```runtime.conf``` and ```startup.conf``` will not be written to (even though the permissions are the same)!

This will prevent the whole system from (re-)starting properly as intended.

**Comment by aaronkaplan** [comment]
I am not sure yet, where the problem resides: in intelmqctl or intelmq-manager.

**Comment by SYNchroACK** [comment]
@aaronkaplan which browser did you use?

**Comment by aaronkaplan** [comment]
On Apr 30, 2015, at 7:18 PM, Tomás Lima <notifications@github.com> wrote:

> @aaronkaplan which browser did you use?
> 

Chrome on OS X

**Comment by ufoczek** [comment]
That's correct. I will upload update soon.

**Comment by aaronkaplan** [comment]
any news on this?

**Comment by SYNchroACK** [comment]
@ufoczek , do you have the fix?

**Comment by SYNchroACK** [comment]
@ufoczek news? 
the problem persist?

**Comment by SYNchroACK** [comment]
this issue is already solved with new documentation and checks.
