### ISSUE TITLE
setup.py breaks with python3

### ISSUE THREAD

**Issue by Phantasus** [certtools/intelmq#175]
Installation of intelmq breaks with python version 3.

it works with python2.7 but not python3, as
python3 has print as a function and not a command.

Error:
  File "setup.py", line 8
    print "IntelMQ seems to be already installed due the existence of /opt/intelmq directory. If you continue the directory will be overwritten."
                                                                                                                                                ^
SyntaxError: Missing parentheses in call to 'print'

Fix would be to change it or to change installation guide

**Comment by aaronkaplan** [comment]
Pull requests are more than welcome :)

**Comment by Phantasus** [comment]
Working on it :)

**Comment by Phantasus** [comment]
Ok, I'm a bit embarassed but I would have a "work in progress suggestion": 
https://github.com/Phantasus/intelmq/tree/python3

I'm interested into your opinion. Does it behave as excpected?
What should I fix? I could incoporate those then and open a pull request.
