### ISSUE TITLE
Installation process - Python2 vs Python3

### ISSUE THREAD

**Issue by Phantasus** [certtools/intelmq#176]
Intelmq is optimized for python2 but as some users as I do have a multi 
python env installed it would be a good idea to be able to select or to
write code so that it can run on both python2 and python3.

A fix for that is to run intelmqctl or other scripts directly with your current 
python2 interpreter. like 
````
python2.7 bin/intelmqctl -h
```

**Comment by Phantasus** [comment]
I have a better more practical idea: change all those shebang lines to python2. I converted in my initial stupidity all code to python3, which is actually ok, as we actually want to support that (python3 is cleaner => cleaner is less WTF => less WTF helps in acquiring people to help in project => more people mean more support and more usage => more usage means more work => more work means that each person has a job => a job means money => a job which gets money means that each person gets his fullfillment while being paid for that).

**Comment by SYNchroACK** [comment]
@sebix do you know whats the current status regarding this python versions compatibility?

**Comment by sebix** [comment]
Only incompatibilities I know of currently are the csv issues. The setup process runs on both, so this issue can be closed.
