### ISSUE TITLE
Malware Domain List feed broken

### ISSUE THREAD

**Issue by wagner-certat** [certtools/intelmq#1762]
As reported on the mailing list, the feed Malware Domain List is broken, it returns an empty page.
https://lists.cert.at/pipermail/intelmq-users/2021-February/000202.html ff.

It is not clear if this is a temporary issue or permanent.

If it's temporary, the parser should be able to handle that, otherwise we can remove it.

**Comment by wagner-certat** [comment]
The responses via mail were clear: the feed is already inactive for a while and therefore we can safely remove the parser.

- [ ] remove parser
- [ ] remove feed documentation
- [ ] add upgrade routine checking for existence of the parser
- [ ] add upgrade routine checking for existence of http collector pointing to the URL
- [ ] Update the shipped runtime/pipeline configuration by removing and optionally replacing the feed

**Comment by schacht-certat** [comment]
This was fixed in f6063299fe98a302478f879be0df49bfe2eda0f4
