### ISSUE TITLE
Shadowserver Parser: Drone feed has (also?) application protocol in `type` field (mapped to transport protocol)

### ISSUE THREAD

**Issue by ghost** [certtools/intelmq#1763]
I see regular log message like this:
> Could not add key 'type' in feed 'Drone', adding it to extras.

We are currently mapping `type` to `protocol.transport` and `application` to `protocol.application`. Looks like we need more tweaks (or ask Shadowserver)

**Comment by sebix** [comment]
@elsif2 can you check if this issue is still present?

**Comment by elsif2** [comment]
The 'drone' report type is no longer supported.  This issue can be closed.
