### ISSUE TITLE
Incorrect parsing of Team Cymru message

### ISSUE THREAD

**Issue by aleksejsv** [certtools/intelmq#1794]
Some lines we receive from Team Cymru are:
```
bruteforce|x.x.x.x|41390|2021-03-09 00:11:21|destination_port_numbers: 22;port: 16794;protocol: 6;|RN-DATA-, LV
```
The result is `"classification.identifier": "destination_port_numbers: 22"` which is not an identifier. Report type is new as it contains `#generated on 20210310`

**Comment by wagner-certat** [comment]
Thanks for the report, I haven't seen such a message yet. I'm working on a fix and provide a PR soon, then available for you as review (and temporary fix, if you'd like), afterwards in the bugfix release 2.3.1
