### ISSUE TITLE
Unable to locate package intelmq-api

### ISSUE THREAD

**Issue by 9e4xd** [certtools/intelmq#1804]
Hello,
I can not install package intelmq-api on Ubuntu 20.04 via apt. intelmq and intelmq-manager worked. Maybe C has not been released yet?

```
$ sudo apt install intelmq-api
Reading package lists... Done
Building dependency tree       
Reading state information... Done
E: Unable to locate package intelmq-api
```

**Comment by wagner-certat** [comment]
That's strange, the package disappeared from the repos. Thanks for letting us know.

I now triggered a rebuild, let's see if that is sufficient.

**Comment by wagner-certat** [comment]
Can you please check again?

**Comment by 9e4xd** [comment]
Now it works, thanks for the quick help!

**Comment by wagner-certat** [comment]
Sorry, that was a configuration error.

Thank you for reporting the issue!
