### ISSUE TITLE
Missing Code of Conduct

### ISSUE THREAD

**Issue by BobinMathew** [certtools/intelmq#1817]
I see that your repo is missing its Code of Conduct. Adding a Code of Conduct improves your community profile.
Can I propose a Code of Conduct?

**Comment by wagner-certat** [comment]
What do we need a CoC for?

**Comment by BobinMathew** [comment]
> What do we need a CoC for?

Codes of conduct help protect not just your participants, but yourself. If you maintain a project, you may find that unproductive attitudes from other participants can make you feel drained or unhappy about your work over time.

A code of conduct empowers you to facilitate healthy, constructive community behavior. Being proactive reduces the likelihood that you, or others, will become fatigued with your project, and helps you take action when someone does something you don’t agree with.

**Comment by wagner-certat** [comment]
Thanks for your offer, but apparently the idea did not gain traction or attention among the community. Closing here.
