### ISSUE TITLE
Shadowserver Reports API BOT Not Download My Reports

### ISSUE THREAD

**Issue by MarcosxDeveloper** [certtools/intelmq#1823]
Hello! I Use `Shadowserver Reports API BOT` in my flow, but it doesn't download my account report types.

country: 
`DO`
types:
`blocklist,botnet_drone,cisco_smart_install,darknet,ddos_amplification,drone_brute_force,hp_http_scan,microsoft_sinkhole,scan_adb,scan_afp,scan_ard,scan_chargen,scan_coap,scan_dns,scan_elasticsearch,scan_ftp,scan_http_vulnerable,scan_ipmi,scan_ipp,scan_isakmp,scan_ldap,scan_ldap_tcp,scan_mdns,scan_memcached,scan_mongodb,scan_mqtt,scan_mssql,scan_nat_pmp,scan_netbios,scan_ntp,scan_ntpmonitor,scan_portmapper,scan_qotd,scan_radmin,scan_rdp,scan_rdpeudp,scan_redis,scan_rsync,scan_smb,scan_snmp,scan_ssdp,scan_ssl_freak,scan_ssl_poodle,scan_telnet,scan_tftp,scan_ubiquiti,scan_vnc,sinkhole6_http,sinkhole_http_drone`

**Comment by wagner-certat** [comment]
What is the log output of the bot?

**Comment by MarcosxDeveloper** [comment]
Starting Shadowserver-Reports-API-Collector...
Shadowserver-Reports-API-Collector: ShadowServerAPICollectorBot initialized with id Shadowserver-Reports-API-Collector and intelmq 2.3.0 and python 3.6.9 (default, Jan 26 2021, 15:33:00) as process 31057.
Shadowserver-Reports-API-Collector: Bot is starting.
Shadowserver-Reports-API-Collector: Bot initialization completed.
Shadowserver-Reports-API-Collector: Idling for 86400.0s (1d) now.

**Comment by wagner-certat** [comment]
So no errors are happening. To get more insight, we'll need to see the debug logging output - just make sure to not post your API key and secret publicly :)
The debug logs will show us what reports the bot can see and if they are downloaded or why not.

**Comment by MarcosxDeveloper** [comment]
sorry! error copy, here you have the bot errors.

**Comment by wagner-certat** [comment]
Well, for `Read timed out.` there's not much we can do. I have seen this kind of errors myself as well - but only after some successful downloads. I suspect that Shadowserver does some kind of rate-limiting. We could ask our Shadowserver contacts about this. Did you have *any* successful download before the error?

**Comment by MarcosxDeveloper** [comment]
Yes! it seems that it only manages to download the first report and then the timed out error appears.

**Comment by wagner-certat** [comment]
I asked Shadowserver if they can give us any advice on this behaviour.

Meanwhile, we can investigate this error:

> sorry! When I specify the type of report, it seems that there are no errors but it does not download them either.

I don't yet understand why you don't get any results when specifying the reports directly. Did the debug logging show anything?

**Comment by MarcosxDeveloper** [comment]
Hello @wagner-certat,

It seems that the problem of the bot that does not show error and does not download reports occurs when putting the wrong type of report. 

when adding a correct type of report the bot throws the time out error that I mentioned above.

**Comment by wagner-certat** [comment]
> It seems that the problem of the bot that does not show error and does not download reports occurs when putting the wrong type of report.

Which of the listed report types was invalid? Using the list you posted above I'm able to download various reports (96 reports to be precise).

Determining if the given report types are valid is not easy as far as I know because the report list provided by the API depends on the _subscriptions_. For validating the types against our internal list in the parser, see the discussion in #1727

**Comment by wagner-certat** [comment]
fixed in - or at least made better - in 8ea92909a688012afc22bc0dff6bf5b648ab3d82 by @mariuskarotkis
