### ISSUE TITLE
redis pipeline: brpoplpush is deprecated

### ISSUE THREAD

**Issue by ghost** [certtools/intelmq#1827]
[BRPOPLPUSH](https://redis.io/commands/brpoplpush) is deprecated in favour of [BLMOVE](https://redis.io/commands/blmove).

The command is used here:
https://github.com/certtools/intelmq/blob/979af96050175ec52f15f31a5041aab8112c7df3/intelmq/lib/pipeline.py#L271-L272
and mocked here:
https://github.com/certtools/intelmq/blob/188609bccc11338b995a9e5fde4418059febfeea/intelmq/lib/bot_debugger.py#L120

**Comment by aaronkaplan** [comment]
you could also take a look at redis streams

**Comment by ghost** [comment]
Do redis streams already support atomic push+pop operations? If not, we can add them as optional broker, if consistency is not important, but not as replacement for the redis-list based approach.

**Comment by aaronkaplan** [comment]
> On 10.09.2021, at 15:56, Wagner ***@***.***> wrote:
> 
> 
> Do redis streams already support atomic push+pop operations?

yes AFAIK

> If not, we can add them as optional broker, if consistency is not important, but not as replacement for the redis-list based approach.
> 
Take a look and read the docs, it's pretty amazing what it can do.

**Comment by waldbauer-certat** [comment]
I tried fixing that issue, but I've seen that redis-py had some bugs <= 4.1.2 with blmove, its fixed in the latest release https://github.com/redis/redis-py/issues/1776. https://github.com/redis/redis-py/releases/tag/v4.1.2

Btw. I like their release design :D looks sooo pretty
