### ISSUE TITLE
Various missing Shadowserver report types

### ISSUE THREAD

**Issue by ghost** [certtools/intelmq#1829]
These reports are currently [not supported by the Shadowserver parser](https://intelmq.readthedocs.io/en/maintenance/user/bots.html#shadowserver-supported-reports) as of IntelMQ 2.3.0:

 - [ ] Accessible QUIC Report
 - [ ] Accessible SSH Report
 - [ ] Accessible SSL Report
 - [ ] Click-Fraud Report
 - [ ] DDoS Report
 - [ ] Honeypot URL Report
 - [ ] Open Proxy Report
 - [ ] Sandbox Connection Report
 - [ ] Sandbox IRC Report
 - [ ] Sandbox SMTP Report
 - [ ] Scan Report
 - [ ] Sinkhole DNS report
 - [ ] Synful Scan Report

All of them are optional reports which are not automatically sent, but only available if explicitly subscribed to them.

**Comment by sebix** [comment]
@elsif2

**Comment by elsif2** [comment]
All supported report types will be added with https://github.com/certtools/intelmq/pull/2143.

**Comment by elsif2** [comment]
All Shadowserver reports are now supported in the current develop branch and will be included in the 3.1.0 release.
