### ISSUE TITLE
ParserBot: erroneous raw line recovery in error handling

### ISSUE THREAD

**Issue by ghost** [certtools/intelmq#1850]
This logic here:

https://github.com/certtools/intelmq/blob/7ba8b625a0189b7b2cbf86eb8d1825eeb4aac729/intelmq/lib/bot.py#L1005-L1031

does not work with all recover_line_* methods. Some methods use the parameter `line`, others use `self.current_line`. The overall logic is fine, but there is a major bug:

process collects all fails (`self.__failed` is appended with `line`) in the first loop (`for line in self.parse(report)`)
In the second loop (`for exc, line in self.__failed`), `recover_line` is called with `line`.
If `recover_line` accesses `self.current_line`, the data is wrong, as `self.current_line` is then the last line of the report, not the actual one.

Unfortunately, simply fixing some `recover_line_*` functions is not enough, the process in `self.process` needs to be thought through and eventually adapted as well.

- `self.current_line` should be deleted after the parsing end to prohibit this error in the future.
- `self.recover_line` behaviour should be harmonized, making it applicable for use in `self.parse_line` and in `self.process`
- `self.process` should be investigated

In the future we also need better tests, but that's a bigger task and I'm afraid we can't stem that on a short term. And unfortunately the issue is important, as it leads to bogus (wrong/duplicated) data in the dumps and therefore loss of data.

**Comment by sebix** [comment]
fixed by #2192
