### ISSUE TITLE
Core - Simplify bot utilities

### ISSUE THREAD

**Issue by Phantasus** [certtools/intelmq#188]
Hi,

utility functions need more extra arguments than is necessary, for example:

utils.generate_source_time(event, "source_time")
utils.generate_observation_time(event, "observation_time")

Why do we overspecify source_time and observation_time in an utility function which already
has those names in them? How about just:

utils.generate_source_time(event)
utils.generate_observation_time(event)

As we have already a those two fields as obligatory specification, so why introduce "configurability" where it doesn't make any sense?

**Comment by SYNchroACK** [comment]
Already solved in intelmq-beta. 

Example: https://github.com/certtools/intelmq-beta/blob/master/intelmq/bots/parsers/alienvault/parser.py#L67
