### ISSUE TITLE
Doc - Improve DataHarmonization.md

### ISSUE THREAD

**Issue by Phantasus** [certtools/intelmq#189]
Hi,

DataHarmonization.md reads clumsy and not that well formulated. As this is a very important
document it must be clear to understand. After reading it I still felt not to get "it".

I will add the relevant sections, which in my opinion need better explanation.

**Comment by SYNchroACK** [comment]
@Phantasus agree with you! Send the proposal, it will be really helpful for community.

**Comment by sebix** [comment]
Duplicate of #185
