### ISSUE TITLE
Doc - Add configuration document and harmonize config files

### ISSUE THREAD

**Issue by Phantasus** [certtools/intelmq#190]
Hi,

when I read into IntelMQ I had difficulties to actually find out what should be written to 
each config file (startup.conf, runtime.conf, BOTS, pipeline.conf, system.conf). 

When *only* reading the DevGuide it seems like that the BOTS file is just for documentation
purpose there, but it is actually used for the IntelMQ Manager and so it should be explained,
that it is needed for that.

Also the convention of the BOTS file is a different one as for the other configuration files.

Besides that how do we intend to have in this JSON style configuration files something like
comments?

**Comment by SYNchroACK** [comment]
@Phantasus make proposals.

```
when I read into IntelMQ I had difficulties to actually find out what should be written to 
each config file (startup.conf, runtime.conf, BOTS, pipeline.conf, system.conf).
```
A: may be a Config.md document where for each bot and for each config we can have a section where we describe the parameters, etc...


```
When only reading the DevGuide it seems like that the BOTS file is just for documentation
purpose there, but it is actually used for the IntelMQ Manager and so it should be explained,
that it is needed for that.
```
A: maye be we can rename the file to TEMPLATES


```
Also the convention of the BOTS file is a different one as for the other configuration files.
```
A: propose a new approach, i agree with you, its something to improve ;)


```
Besides that how do we intend to have in this JSON style configuration files something like
comments?
```
A: dont know... :(

**Comment by Phantasus** [comment]
@SYNchroACK, I know I know it sucks when I just "point out stuff". But I'm working on a proposal(tm).
I open issues for IntelMQ so that they are recorded. And I just can make a solution which hopefully closes then the issue. 

It's just more practical.

**Comment by SYNchroACK** [comment]
ok @Phantasus . Really cool to have you on board with these kind of good procedures. Thank you for your help.

**Comment by Th4nat0s** [comment]
@SYNchroACK could you tell me which README.md template I could follow to document a bot ?

This one seem too light  https://github.com/certtools/intelmq/blob/master/intelmq/bots/experts/asnlookup/README.md 

I miss the explanation of what the bot do ?  Isn't it ?

**Comment by SYNchroACK** [comment]
@Th4nat0s you're completly right. Since Im dealing with a lot of code issues to release the new version, I would like to receive a proposal from you, do what you think make sense and I will give for sure feedback to improve it and in the end we will have a good template. Lets try to do it together.

First approach could be merge the ideas between the codes that has the README.md file and get the common topics and generate a basic template. :)

Again, thank you for your feedback in all project, its been really interesting your evaluation.
