### ISSUE TITLE
intelmqctl run subcommands should be subparagraphs of intelmqctl run paragrap

### ISSUE THREAD

**Issue by schacht-certat** [certtools/intelmq#1936]
In the documentation of the `intelmqctl` command the `intelmqctl run conole`, `intelmqctl run messsage` and `intelmqctl run process` are at the same level as `intelmqctl run` - they should probably be on level below, as they are subcommands

**Comment by wagner-certat** [comment]
You mean https://intelmq.readthedocs.io/en/latest/user/intelmqctl.html#run?

**Comment by schacht-certat** [comment]
> You mean https://intelmq.readthedocs.io/en/latest/user/intelmqctl.html#run?

exactly
