### ISSUE TITLE
harmonization field names does not contain the harmonziation field name table

### ISSUE THREAD

**Issue by schacht-certat** [certtools/intelmq#1937]
On https://intelmq.readthedocs.io/en/latest/dev/harmonization-fields.html there should be a table of harmonization fields like on https://intelmq.readthedocs.io/en/maintenance/dev/harmonization-fields.html - this table seems to have disappeared in the `develop` branch of the documentation.

**Comment by wagner-certat** [comment]
I wonder where that comes from, the autogen.py does not differ between the two branches. Maybe there is a content-related error during the sphinx-build which causes the table to be ignored?
