### ISSUE TITLE
Changes to Shadowserver feeds on 1 June 2021

### ISSUE THREAD

**Issue by chorsley** [certtools/intelmq#1964]
I've been trying to ascertain if any necessary Shadowserver feed bot parser updates to handle the [changes to feeds announced by Shadowserver](https://www.shadowserver.org/news/changes-in-sinkhole-and-honeypot-report-types-and-formats/) are already ongoing for IntelMQ at this point.

I found the mention of this change at https://github.com/certtools/intelmq/blob/develop/NEWS.md#shadowserver, but couldn't immediately see updates that would handle those changes in the develop branch at https://github.com/certtools/intelmq/blob/develop/intelmq/bots/parsers/shadowserver/parser.py.

Given Shadowserver will cut over their formats on 1 June 2021, is there already some work underway on this? Happy to pitch in / test with anyone already working on it.

**Comment by wagner-certat** [comment]
> I've been trying to ascertain if any necessary Shadowserver feed bot parser updates to handle the [changes to feeds announced by Shadowserver](https://www.shadowserver.org/news/changes-in-sinkhole-and-honeypot-report-types-and-formats/) are already ongoing for IntelMQ at this point.

The same question has been raised on the ML at the beginning of May and we welcomed contributions from other parties, but sadly yet no-one cared to do that yet :/ We (CERT.at) only had time to add the mappings of the feeds which we need in particular, see below.

> I found the mention of this change at https://github.com/certtools/intelmq/blob/develop/NEWS.md#shadowserver, but couldn't immediately see updates that would handle those changes in the develop branch at https://github.com/certtools/intelmq/blob/develop/intelmq/bots/parsers/shadowserver/parser.py.

The mappings are in `intelmq/bots/parsers/shadowserver/_config.py`. (see also https://intelmq.readthedocs.io/en/latest/user/bots.html#shadowserver last paragraph)

> Given Shadowserver will cut over their formats on 1 June 2021, is there already some work underway on this? Happy to pitch in / test with anyone already working on it.

Yes, see the changelog and NEWS file for the newly added feeds. Some feeds are still missing, Pull Requests (against the maintenance branch if the PR is coming in before the next release, otherwise develop is ok as well) are welcome as always.
I'll do a bugfix release containing the fixes in the next days, before the 1st June.

**Comment by schacht-certat** [comment]
Some of those were implemented in 32bdb73d3b56490a0d8f192f05b2a1cd940f67b8, b7bfd66972c15f7d79576275ec2a5410e248bbb3, d33de328bd0d396b9c56281e1308523cf5dffb67 and c2d19d302f18ce2b0ae9828fe883ba98506fb30b and merged into the `maintenance` branch. I'm not sure if we will have enough timecycles in the next week to do the rest.
Testing would be highly appreciated, I think it should be enough to replace the `config.py` of the shadowserver parser bot.

**Comment by chorsley** [comment]
Many thanks all - will examine what's been done so far and add any further comments / tests / fixes.

**Comment by wagner-certat** [comment]
Solved by various PRs

**Comment by chorsley** [comment]
Looking at some more new feeds, there were two more feed changes made on June 8 which replace the existing Microsoft Sinkhole report:

> 2021-06-08 UPDATE:
> 
> LEGACY: Microsoft Sinkhole Report has been replaced by two reports: Microsoft Sinkhole Events Report and Microsoft Sinkhole HTTP Events Report.

https://www.shadowserver.org/what-we-do/network-reporting/microsoft-sinkhole-events-report/
https://www.shadowserver.org/what-we-do/network-reporting/microsoft-sinkhole-http-events-report/

Looking at the report and the mapping at https://github.com/certtools/intelmq/blob/develop/intelmq/bots/parsers/shadowserver/_config.py#L2856, the formats seem to match the other sinkhole report fields, so we could possibly just add new mappings for these reports like:

```
    ('Microsoft-Sinkhole-Events', 'event4_sinkhole', event46_sinkhole),
    ('Microsoft-Sinkhole-Events-HTTP IPv4', 'event4_microsoft_sinkhole_http', event46_sinkhole_http),
```

If anyone else is also looking at this, would be interested in your thoughts on this approach.
