### ISSUE TITLE
Shadowserver Parser can't differentiate between "Accessible HTTP" and "Vulnerable HTTP"

### ISSUE THREAD

**Issue by wagner-certat** [certtools/intelmq#1984]
See https://github.com/certtools/intelmq/pull/1971#issue-654792490 and https://github.com/certtools/intelmq/pull/1971#discussion_r647551806

The two feeds [Accessible HTTP Report](https://www.shadowserver.org/what-we-do/network-reporting/accessible-http-report/) and [Vulnerable HTTP Report](https://www.shadowserver.org/what-we-do/network-reporting/vulnerable-http-report/) use the same file name `scan_http`. Our feed detection is solely based on the file name and detects now `Vulnerable-HTTP`. Fortunately, the columns are identical, but this still causes a wrong feed name to be added to the data, of the file is actually from the `Accessible-HTTP` feed. Shadowserver's docs say, that the `tag` column is always `http` for the Accessible HTTP feed, so the data is still differentiable maybe?

**Comment by monoidic** [comment]
Slight correction:
>Our feed detection is solely based on the file name

You can match by feed name as well, and if this is done, then they are differentiated. This is only a problem if the feeds are matched by filename.
