### ISSUE TITLE
README.md should have some text. Not only a link to the Wiki

### ISSUE THREAD

**Issue by aaronkaplan** [certtools/intelmq#199]
master branch (as well as beta branch): 
It would be better to have a short description of the project, what it does and how it can help people on the main README.md file (as it was before!) Not only a link to the wiki.
Why? Because README.md is the de-facto landing page of the project.

**Comment by SYNchroACK** [comment]
fixed 193d49193c8ed2572e2b82634a4beeb4026f42b3
