### ISSUE TITLE
ruamel.yaml loader and dumper: human readability / support for comments

### ISSUE THREAD

**Issue by ghost** [certtools/intelmq#2003]
277f72d019eab234501a3e91176186e673b880ba fixed the issue that comments where not preserved.
However when the runtime configuration is loaded with the default loader, as it was with the comment, and then dumped afterwards, the resulting file is formatted uglily:
```
{file-input: {bod_id: file-input, description: Reads file /assets/*.txt, group: Collectors,
name: File Input, enabled: true, module: intelmq.bots.collectors.file.collector_file,
run_mode: scheduled, parameters: {path: /assets, postfix: .txt, delete_file: false,...
```
Therefore I reverted the commit with 9a6946120c16505c1440081e850196415bb23ade, which brings back a human readable and better structured format for the `runtime.yaml`. But OTOH it breaks comments again. We need a solution to preserve both, comments and readability.

**Comment by wagner-certat** [comment]
Maybe we use the dump-method wrongly?

**Comment by sebix** [comment]
Comments are still not preserved, even though we use `YAML(typ='unsafe', pure=True)`
