### ISSUE TITLE
apt install intelmq on Ubuntu 20.04 fails

### ISSUE THREAD

**Issue by RobKuiters** [certtools/intelmq#2015]
I tried to install IntelMQ on Ubuntu 20.04 but it requires libjs-sphinxdoc (>= 2.4.3-5~) where libjs-sphinxdoc_1.8.5-7 is the only supported version on Ubuntu 20.04.

```Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 intelmq : Depends: libjs-sphinxdoc (>= 2.4.3-5~) but 1.8.5-7ubuntu3 is to be installed
E: Unable to correct problems, you have held broken packages.

**Comment by wagner-certat** [comment]
Did you probably add the repo for Ubuntu 20.10 instead of Ubuntu 20.04?

**Comment by RobKuiters** [comment]
Yes, how stupid of me. Shouldn't be installing stuff with not enough sleep and no coffee. Thanks wagner-certat!

**Comment by wagner-certat** [comment]
If only all issues could be resolved as easily ... :)
