### ISSUE TITLE
Bot database update scripts: Be quiet by default in cron scripts

### ISSUE THREAD

**Issue by wagner-certat** [certtools/intelmq#2016]
Currently, the bot database update scripts print this on every call if nothing is done:

```
Database update skipped. No bots of type intelmq.bots.experts.asn_lookup.expert present in runtime.conf.
```

I think a good default would be to be quiet by default on the cron runs, e.g. by setting a `--quiet` flag. If the user wants to have verbose information, it can always be turned on.

Or: honour the logging level as defined for the bot. With the configuration overhaul, this should now be easier to do on the code-side.

**Comment by ghost** [comment]
in the domain suffix expert, one line was missing (the `Database update skipped...`).
