### ISSUE TITLE
Should list bots output yaml?

### ISSUE THREAD

**Issue by schacht-certat** [certtools/intelmq#2025]
The documentation says:
```
You can use the output of ``intelmqctl --type json list bots`` to write the ``runtime.conf``
```

One the one hand `intelmqctl --type json list bots` is not indented, thus not really usable for humans. On the other hand we are now using yaml. Should `list bots` get a `--yaml` switch?

**Comment by wagner-certat** [comment]
> The documentation says:
> 
> ```
> You can use the output of ``intelmqctl --type json list bots`` to write the ``runtime.conf``
> ```

That was actually only true partially, as the user still needed to extract the relevant parts from the huge JSON-structure. And I see no real purpose in doing so unless we have a good and complete workflow which actually helps user in configuring bots using cli-tools only (that would also require to show get individual bot-configuration templates, not *all* available ones in a row etc.)

So, I propose to remove that line.
