### ISSUE TITLE
docs/ files dissapeared

### ISSUE THREAD

**Issue by aaronkaplan** [certtools/intelmq#205]
Hi,

It's non intuitive to extra check out the github wiki repo for the project and then get the INSTALL file from there (or any other documentation file). Hence, I believe the markdown docs should be moved back to the docs/ folder because this is what you will see when you check out the project.
We can link these documents from the wiki page with some additional comments. OK?

Will send a PR for this.

**Comment by SYNchroACK** [comment]
```
We can link these documents from the wiki page with some additional comments. OK?
```

No. If it goes to docs folder we remove from wiki. We cant maintain both

**Comment by aaronkaplan** [comment]
On Jun 3, 2015, at 11:22 AM, Tomás Lima <notifications@github.com> wrote:

> We can link these documents from the wiki page with some additional comments. OK?
> 
> No. If it goes to docs folder we remove from wiki. We cant maintain both
> 

Well, the Wiki can be just pointers to how to read the docs/* files, no?

**Comment by SYNchroACK** [comment]
For me doest make sense to have both since you said is non intuitive. Less problems.

**Comment by aaronkaplan** [comment]
On Jun 3, 2015, at 12:04 PM, Tomás Lima <notifications@github.com> wrote:

> For me doest make sense to have both since you said is non intuitive. Less problems.
> 

Okay, well then I vote for keeping the docs/* files as they are.
Because you can see them when you check out the repo.

**Comment by SYNchroACK** [comment]
I disagree but its not a core topic. Its ok for me.

**Comment by aaronkaplan** [comment]
okay, we moved it back. closing this now.
