### ISSUE TITLE
MalwareDomainList Feed - add new feeds

### ISSUE THREAD

**Issue by aaronkaplan** [certtools/intelmq#208]
Hi, Just as a reminder in order to not forget: there seems to be way more data than we currently process in the malwaredomainslist collector. See : http://www.malwaredomainlist.com/forums/index.php?topic=3270.0 for a list of available data.

Not high prio... just noticing it and writing it down in order to not forget later.

**Comment by SYNchroACK** [comment]
Moved to https://github.com/certtools/intelmq/issues/93
