### ISSUE TITLE
v300_pipeline_file_removal fails

### ISSUE THREAD

**Issue by schacht-certat** [certtools/intelmq#2082]
Not sure why this wasn't caught by the vagrant tests - this happens when running `intelmqctl upgrade-config -u v300_pipeline_file_removal -f` with the `runtime.conf` and `pipeline.conf` from the ansible assets directory.
```
Upgrade 'v300_pipeline_file_removal' failed, please report this bug with the shown traceback.
Traceback (most recent call last):
  File "/home/birger/data/vcs/intelmq/intelmq/bin/intelmqctl.py", line 1048, in upgrade_conf
    retval, runtime_new, harmonization_new = getattr(
  File "/home/birger/data/vcs/intelmq/intelmq/lib/upgrades.py", line 678, in v300_pipeline_file_removal
    if bot_id == 'global':
NameError: name 'bot_id' is not defined
```

**Comment by wagner-certat** [comment]
I introduced the bug here: https://github.com/certtools/intelmq/commit/1fd640ecc98f7582436ae6a04cb250a4e18a740f#diff-7281e311c8af2ac97f67f28bec743b3f7b6dcc365f6aaa959ae27d5656b1895cR677 - so it only applies to the develop branch
