### ISSUE TITLE
ASN Lookup expert database update fails after the 28th of each month

### ISSUE THREAD

**Issue by wagner-certat** [certtools/intelmq#2088]
```
intelmq@localhost:~$ intelmq.bots.experts.asn_lookup.expert --update-database
Searching for the latest database update...
Database update failed. Couldn't find the latest database update.
```

haven't yet investigated the reasons

**Comment by wagner-certat** [comment]
As @schacht-certat found out, the issue was that the server had an empty directory named "2021.09" yesterday. Today it works fine again. Should be handled though.

**Comment by ghost** [comment]
That fails at the end of every month. The monthly directories in http://archive.routeviews.org/route-views4/bgpdata/ are always created on the 28th of the previous month and thus our code fails on every 29th, 30th and 31st of each month.
