### ISSUE TITLE
beta-branch - feature request

### ISSUE THREAD

**Issue by aaronkaplan** [certtools/intelmq#209]
Hi,
## Problem description

Since the format of events / messages changed in the beta branch, we have a slight problem when comparing the events.txt output between the "old" master branch and the beta branch.

While in the master branch an event in events.txt looks like this:

```
{
  "feed": "malwaredomainslist",
  "source_cymru_cc": "US",
  "taxonomy": "Malicious Code",
  "source_registry": "arin",
  "malware": "trojan",
  "reported_source_ip": "216.158.67.76",
  "feed_url": "http://www.malwaredomainlist.com/updatescsv.php",
  "source_city": "Los Angeles",
  "source_allocated": "2013-04-10",
  "source_reverse_dns": "server.hostgoodies.com.",
  "source_bgp_prefix": "216.158.64.0/19",
  "type": "malware",
  "source_latitude": "34.053",
  "source_cc": "US",
  "source_url": "http://brownblogs.org/Document-4.zip",
  "source_time": "2015-04-28T14:15:00+00:00",
  "source_longitude": "-118.2642",
  "observation_time": "2015-06-03T12:53:50",
  "source_ip": "216.158.67.76",
  "source_abuse_contact": "abuse@webnx.com",
  "reported_source_asn": "18450",
  "source_domain_name": "brownblogs.org",
  "reported_source_url": "brownblogs.org/Document-4.zip",
  "source_as_name": "WEBNX - WebNX, Inc.,US",
  "source_asn": "18450"
}
```

in the new beta branch in events.txt the same data looks like this:

```
{
  "feed": {
    "url": "http://www.malwaredomainlist.com/updatescsv.php",
    "name": "malwaredomainslist"
  },
  "malware": {
    "name": "trojan"
  },
  "classification": {
    "type": "malware"
  },
  "raw": "MjAxNS8wNC8yOF8xNDoxNSxicm93bmJsb2dzLm9yZy9Eb2N1bWVudC00LnppcCwyMTYuMTU4LjY3Ljc2LHNlcnZlci5ob3N0Z29vZGllcy5jb20uLHRyb2phbixicm93biBicmVlenkgLyBoYWxsbXJrQHlhaG9vLmNvbSwxODQ1MA==",
  "source": {
    "url": "http://brownblogs.org/Document-4.zip",
    "ip": "216.158.67.76",
    "reverse_domain_name": "server.hostgoodies.com.",
    "asn": "18450"
  },
  "time": {
    "source": "2015-04-28T14:15:00+00:00",
    "observation": "2015-06-03T12:16:23+00:00"
  }
}
```
## So how can we compare this?

Suggestion: 
1. we sort all keys in each JSON object
2. we then output it into events.txt
3. we have a mapping between the two by using small, simple JSON scripts such as [jq](https://stedolan.github.io/jq/)
4. we establish a test pipeline where well defined input gets fed to a well defined intelmq setup in both branches. It then should produce the same output (after filtering through the JSON scripts).

**Comment by SYNchroACK** [comment]
sugestion:
had a temporary feature to beta-branch which will convert the output in the old one to compare directly.

**Comment by SYNchroACK** [comment]
@aaronkaplan any news about this issue?

**Comment by SYNchroACK** [comment]
this issue is deprecated right?

**Comment by sebix** [comment]
Please reopen if still relevant.

**Comment by aaronkaplan** [comment]
I believe the mapping needs to be done anyway. Especially for XMPP AH <-> intelmq

**Comment by dmth** [comment]
I propose to create a new Issue for the AH <-> IntelMQ mapping.
