### ISSUE TITLE
Passwords in plain text in the log files

### ISSUE THREAD

**Issue by aaronkaplan** [certtools/intelmq#210]
## problem description

When adding passwords to the bots configurations (runtime.conf), these get parsed as parameters and printed again in the log files in plain text.
That's not particularly pretty. Especially if you want the log files to be world readable.

I know this is not a serious issue right now, but I'd rather document it before we forget.

Example:
self.parameters.azure_account_key

--> search for this in the log files. You will find the full key there.

**Comment by SYNchroACK** [comment]
Change in system.log the log_level to INFO. Debug is debug. hehehe

**Comment by SYNchroACK** [comment]
feedback?

**Comment by SYNchroACK** [comment]
@aaronkaplan , Can I close it?

**Comment by Phantasus** [comment]
@SYNchroACK sure would be a solution. Don't know if that would be the best solution (= my 2 cents).

**Comment by CNCS-PT** [comment]
Suggestion?

**Comment by SYNchroACK** [comment]
@Phantasus , suggestions?

**Comment by aaronkaplan** [comment]
On Jun 19, 2015, at 11:46 AM, National Cyber Security Center - Portugal <notifications@github.com> wrote:

> Suggestion?

sorry guys I can only answer all these github issues after my travels. Sorry for the delay.
200% busy here.
>

**Comment by Phantasus** [comment]
@SYNchroACK no suggestions, I'm just unsure. You could also masquerade those outputs with "PROTECTED" in the logfile, but would make that sense? One ex-colleague did that once, wasn't IMHO an improvement.

**Comment by SYNchroACK** [comment]
I think is not necessary...debug is debug... in production system its not usual to use debug mode...

**Comment by Phantasus** [comment]
@SYNchroACK ehmmm.... no... I have seen production systems which use debug mode, as admins don't get enough information for troubleshooting out of the normal loglevels. It depends on the software if they do that or not. Also I doubt, that IntelMQ will be better configured than any other software package out there, we ship at the moment with a default loglevel of DEBUG in conf/system.conf. 

So, the quickfix for this issue would be to just set the loglevel in conf/system.conf to INFO.

**Comment by Phantasus** [comment]
And here we have a PR for this issue. You can add it or whatever you wish with it.

**Comment by Phantasus** [comment]
Can we now close the issue?
