### ISSUE TITLE
GitHub Code Scanning result for Twitter collector, leads to check fail

### ISSUE THREAD

**Issue by sebix** [certtools/intelmq#2123]
Pull Requests are marked with failing tests as there is still a CodeQL result for the Twitter collector:

![image](https://user-images.githubusercontent.com/199050/142379580-9bfa5de1-e533-4843-bb87-756ff258e0b1.png)
This line
https://github.com/certtools/intelmq/blob/d8ff6514c0b754b82665f60f5f3e83cbc22b3fa6/intelmq/bots/collectors/twitter/collector_twitter.py#L83-L83
should be refactored to parse the URL and compare the hostname only. It's a minor issue and not security-relevant IMO, but needs to be fixed nevertheless.

**Comment by waldbauer-certat** [comment]
Has been fixed within PR #1754
