### ISSUE TITLE
race condition in filecollector line 75

### ISSUE THREAD

**Issue by aaronkaplan** [certtools/intelmq#2128]
https://github.com/certtools/intelmq/blob/74c5a6435c1c629ace1ae66f67636207e87fc6a1/intelmq/bots/collectors/file/collector_file.py#L75

Has a race condition. Two bots may open the same file twice , this would then result in duplicated reports . Bug.

**Comment by sebix** [comment]
possible duplicate of #1631

**Comment by sebix** [comment]
Duplicate of #1631
