### ISSUE TITLE
Log4j - Collector & Parser

### ISSUE THREAD

**Issue by YeomansM** [certtools/intelmq#2131]
Dear All,

May i ask whether you were thinking to add Log4j for shadowserver feeds within its collector api and parser?

Perhaps we can be of assistance?

Regards
Matthew

**Comment by sebix** [comment]
The Shadowserver Reports API collector is able to fetch all feeds, just the parser is missing the mapping.

Here's some public information: https://www.shadowserver.org/what-we-do/network-reporting/vulnerable-log4j-servers-special-report/
Looks easy to do (if the documentation does not deviate from the actually used format)

**Comment by YeomansM** [comment]
That is a good point, all what is missing is the parser.

Unless other people already volunteered,  I would love to give it a try.

Thanks 
Matthew

**Comment by sebix** [comment]
> Unless other people already volunteered, I would love to give it a try.

I haven't noticed any attempt yet, so feel free. If you need any help, ping me.

**Comment by sebix** [comment]
@elsif2 I think you PR closes this issue

**Comment by elsif2** [comment]
Yes, that is correct.

**Comment by sebix** [comment]
Fixed by #2227
