### ISSUE TITLE
Bot command line parameters for manual interaction

### ISSUE THREAD

**Issue by ghost** [certtools/intelmq#214]
I propose to add to the bot class some command line handling
with the following characteristics:
1. Add a --debug flag which starts a bot in a debug mode, which:
   a. loads pdb (python debugger)
   b. sets breakpoint for process method for bot
   c. waits there for user input (pdb actually does that)
2. Add a --help directive to display a help message, which is generated by reading BOTS file.
3. Add the ability to give the bot parameters from the command line, maybe by prefixing each parameter in the BOTS file with '--', so for example a theoretical parameter "account_name" we would have "bot --account_name=foobar"

What do you think? I obviously like that idea ...

**Comment by aaronkaplan** [comment]
My 2 cents: right now, I would not like to focus on this. Before that I want to see better unit tests for all bots. As mentioned, that's my 2 cents.
I like suggestion 3. However, again ... feature creep , later.. let's focus on the core issues first.

**Comment by SYNchroACK** [comment]
The idea is interesting but as @aaronkaplan said, is not a priority.

**Comment by SYNchroACK** [comment]
similar features were already implemented with intelmqctl and a lot of new information was documented.

**Comment by wagner-certat** [comment]
As far as I see, the feature request has been postponed, not rejected, right?

**Comment by wagner-certat** [comment]
The first issue is resolved, we have a debugger. See #975

**Comment by wagner-certat** [comment]
The third issues is also in #698

**Comment by wagner-certat** [comment]
And the second needs/is solved by #632 #757.
Closing here, as we have separate issues for all ideas too.
