### ISSUE TITLE
Problem running Twitter Bot

### ISSUE THREAD

**Issue by oencarnacion** [certtools/intelmq#2140]
Complete all the steps mentioned in the documentation of the bot configuration.

**Logs:**  

```python
File "/usr/bin/intelmqctl", line 11, in <module>
    load_entry_point('intelmq==3.0.2', 'console_scripts', 'intelmqctl')()
  File "/usr/lib/python3/dist-packages/intelmq/bin/intelmqctl.py", line 1909, in main
    return x.run()
  File "/usr/lib/python3/dist-packages/intelmq/bin/intelmqctl.py", line 1048, in run
    retval, results = args.func(**args_dict)
  File "/usr/lib/python3/dist-packages/intelmq/bin/intelmqctl.py", line 1413, in read_bot_log
    for line in utils.reverse_readline(bot_log_path):
  File "/usr/lib/python3/dist-packages/intelmq/lib/utils.py", line 425, in reverse_readline
    next_char = qfile.read(1)
  File "/usr/lib/python3.8/codecs.py", line 322, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x99 in position 0: invalid start byte
```

**Comment by sebix** [comment]
It looks like you are calling `intelmqctl log <some instance of a twitter collector>`? And that fails because something is not logged in valid UTF-8. So there are two errors, one that `intelmqctl log` doesn't handle bogus encodings safely and the other being the actual bug in the bot, which also cause the error message in the log.
To fix any of them, an example log entry is helpful/needed.
And as always: PRs to fix that are welcome (or some funding...).

**Comment by oencarnacion** [comment]
**I am confused with your answer. In the bot I have manually completed the following fields:**

- access_token_key
- access_token_secret
- consumer_key
- consumer_key
- supplier
- target_timelines

**Comment by sebix** [comment]
How did you get the stacktrace posted above?

**Comment by oencarnacion** [comment]
@sebix just run the bot and then go check the logs

**Comment by sebix** [comment]
I see two issues here. The bot itself is inoperable with the normal API keys. Elevated access is required. Upstream issue at the twitter API: https://github.com/bear/python-twitter/issues/699
```
twitter-hashtag-intelmq: Bot has found a problem.
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/intelmq/lib/bot.py", line 310, in start
    self.process()
  File "/usr/lib/python3/dist-packages/intelmq/bots/collectors/twitter/collector_twitter.py", line 101, in process
    statuses = self.api.GetUserTimeline(
  File "/usr/lib/python3/dist-packages/twitter/api.py", line 799, in GetUserTimeline
    data = self._ParseAndCheckTwitter(resp.content.decode('utf-8'))
  File "/usr/lib/python3/dist-packages/twitter/api.py", line 4894, in _ParseAndCheckTwitter
    self._CheckForTwitterError(data)
  File "/usr/lib/python3/dist-packages/twitter/api.py", line 4914, in _CheckForTwitterError
    raise TwitterError(data['errors'])
twitter.error.TwitterError: [{'message': 'You currently have Essential access which includes access to Twitter API v2 endpoints only. If you need access to this endpoint, you’ll need to apply for Elevated access via the Developer Portal. You can learn more here: https://developer.twitter.com/en/docs/twitter-api/getting-started/about-twitter-api#v2-access-leve', 'code': 453}]
```
The other problem is the inability of `intelmqctl` to read the bot's log

**Comment by sebix** [comment]
cc the author/maintainer of the collector @hugeox

**Comment by oencarnacion** [comment]
@sebix I will be reviewing the API privileges provided by twitter

**Comment by sebix** [comment]
I'm experimenting with [tweepy](https://pypi.org/project/tweepy) which looks like a usable replacement, it supports the v2 better than [twitter](https://pypi.org/project/twitter/) and [python-twitter](https://pypi.org/project/python-twitter)

**Comment by oencarnacion** [comment]
the solution to the problem was to request a higher access to the API
