### ISSUE TITLE
Autoshun feed changed/dead

### ISSUE THREAD

**Issue by gethvi** [certtools/intelmq#2162]
Autoshun (by RiskAnalytics) seems to have changed. Autoshun Collector fails because the feed URL returns 404.

From their website:

_We have merged AutoShun and Malware Domains, and have integrated those technologies into ShadowNet.  Through ShadowNet we are able to identify the latest threat intel gathered from around the globe, share learnings and best practices from our network of clients and partners and continually build those learnings into our products, resulting in the best, most powerful threat intel for your organization._

_Currently, both AutoShun and Malware Domains are shut off.  Subscribers will need to register below to continue receiving intel from those sources._
_We will continue to make a free, non-commercial version of our threat intel, ShadowNet, while the enhanced full-threat intel feed will be licensed to our commercial partners._

**Comment by sebix** [comment]
Thanks.

Aside from removing the code, we also need an upgrade function which warns the users about the removal. There are already some of these functions in lib/upgrades
