### ISSUE TITLE
Kafka Collector: possible bug

### ISSUE THREAD

**Issue by gethvi** [certtools/intelmq#2168]
While searching the source code for something else, I noticed Kafka Collector uses `self._Bot__bot_id` which was deprecated I believe.

https://github.com/certtools/intelmq/blob/651d0733f719579e96ec4b063a260023ebeadc50/intelmq/bots/collectors/kafka/collector.py#L41

Sorry if this is a bogus issue, I currently don't have time to investigate deeper (but I don't want to overlook it either).

**Comment by sebix** [comment]
My knowledge of Kafka is limited, but if that `group_id` is some required internal identifier for the consumer, it doesn't look wrong. What I don't know is if each thread needs its own identifier, then `self._Bot__bot_id_full` would be correct.

**Comment by gethvi** [comment]
I ment that `self._Bot__bot_id` attribute is not assigned anywhere to my knowledge.

https://github.com/certtools/intelmq/search?q=_Bot__bot_id

I belive this code would fail on `AttributeError: 'KafkaCollectorBot' object has no attribute '_Bot__bot_id'`.

I only know of these (note the lowercase names) being assigned:
https://github.com/certtools/intelmq/blob/d686fff5f1b8cd2d646bab9f8a8016f130af73a1/intelmq/lib/bot.py#L151

Likewise my knowledge of Kafka Collector is limited, just found this by accident.

**Comment by sebix** [comment]
`__bot_id` is a private variable of the `Bot` class (starts with `__`). In derived classes these private variables are accessible as `_$orginatingclass__$variablename`. See https://docs.python.org/3/tutorial/classes.html#tut-private

**Comment by gethvi** [comment]
I didn't know this. Now it makes sense to me. Sorry about the bogus issue and for wasting your time. Thank you very much for the explanation, you helped me learn something new!

**Comment by sebix** [comment]
You're welcome :)Message ID:
***@***.***>
