### ISSUE TITLE
Docker workflow fails because of missing valid authentication details

### ISSUE THREAD

**Issue by sebix** [certtools/intelmq#2183]
Additionally and independent of #2157 the docker action also fails in certtools itself now: https://github.com/certtools/intelmq/actions/runs/2369229111

```
Run docker/login-action@v1
  with:
    username: ***
    password: ***
    ecr: auto
    logout: true
  env:
    pythonLocation: /opt/hostedtoolcache/Python/3.6.15/x64
    LD_LIBRARY_PATH: /opt/hostedtoolcache/Python/3.6.15/x64/lib
Logging into Docker Hub...
Error: Error response from daemon: Get "https://registry-1.docker.io/v2/": unauthorized: incorrect username or password
```

This is a result of the deletion of my cert.at-account at dockerhub (https://hub.docker.com/r/certat/) as we used these credentials in GitHub.

@waldbauer-certat Please create new tokens and pass them on to @aaronkaplan for saving them in GitHub.

**Comment by waldbauer-certat** [comment]
Fixed, thanks @aaronkaplan

**Comment by aaronkaplan** [comment]
welcome
