### ISSUE TITLE
How to login to the IntelMQ manager?

### ISSUE THREAD

**Issue by NaSangWon** [certtools/intelmq#2196]
What is username and password for login?

I'm using ubuntu.

**Comment by waldbauer-certat** [comment]
Hey @NaSangWon,

you have to create a user first to be able to login, see [docs](https://intelmq.readthedocs.io/en/maintenance/user/intelmq-api.html#adding-a-user)

After you've added an account, you're able to login using the button in the upper right :)

Regards,

**Comment by NaSangWon** [comment]
I see, 

but I'm getting error with intelmq api, when I run
`hug -m intelmq_api.serve`
It return
sqlite3.OperationalError: unable to open database file

I think my api config is wrong.
on docs, it says

>On Debian based systems, the default path for the session_store is /var/lib/dbconfig-common/sqlite3/intelmq-api/intelmqapi

which I don't have, any thoughts on this? thanks.

**Comment by waldbauer-certat** [comment]
Hey @NaSangWon :)

According to the docs
> [sqlite3.OperationalError: attempt to write a readonly database](https://intelmq.readthedocs.io/en/maintenance/user/intelmq-api.html#id14)
 SQLite does not only need write access to the database itself, but also the folder the database file is located in. Please check that the webserver has write permissions to the folder the session file is located in.

Have you used pip or rpm/deb packages to install the intelmq-api?

**Comment by NaSangWon** [comment]
rpm/deb packages. on ubuntu vm machine.

Maybe I didn't set redis work properly?

**Comment by waldbauer-certat** [comment]
@NaSangWon 

Are you able to share your `api-config.json` file?

Open your `api-config.json` and do `ls -al <session_store>` (replace <session_store> with the path from `api-config.json`)

It looks like your webserver is not able to write to the folder where the session file is located in ( permission errors )

Redis is not used in this process, as the intelmq-manager does intelmq-api calls, which leads to `intelmqctl` calls. IntelMQ itself uses redis to ship information from A to B.

**Comment by sebix** [comment]
> rpm/deb packages. on ubuntu vm machine.

Which Ubuntu version?

At the installation you have been asked to enter a username and password for the API/Manager. 

> `hug -m intelmq_api.serve`
> It return
> sqlite3.OperationalError: unable to open database file

There's no need to start the interfaces by hand. You installed with deb/rpm packages and apache was already configured for you automatically. Go to http://localhost/intelmq-manager/ and login with the credentials that you entered during the installation.

**Comment by NaSangWon** [comment]
@waldbauer-certat 

Here's my `api-config.json` file. on `/etc/intelmq/api-config.json`

> {
        "intelmq_ctl_cmd": ["sudo", "-u", "intelmq", "intelmqctl"],
        "allowed_path": "/opt/intelmq/var/lib/bots/",
        "session_store": "/var/lib/dbconfig-common/sqlite3/intelmq-api/intelmqapi",
        "session_duration": 86400,
        "allow_origins": ["*"]
}

Again, default "session_store" path is don't exist in my VM.

Not sure how to do `ls -al <session_store>`
But here's `ls -al /etc/intelmq`

> root@ubuntu:~# ls -al /etc/intelmq
total 76
drwxrwxr-x   3 intelmq intelmq  4096 Jun 29 18:07 .
drwxr-xr-x 133 root    root    12288 Jun 28 19:34 ..
-rw-rw-r--   1 intelmq intelmq   506 Sep  2  2021 api-apache.conf
-rw-rw-r--   1 intelmq intelmq   241 Sep  2  2021 api-config.json
-rw-rw-r--   1 intelmq intelmq   264 Sep  2  2021 api-sudoers.conf
-rw-rw-r--   1 intelmq intelmq 21097 Sep  9  2021 harmonization.conf
drwxrwxr-x   2 intelmq intelmq  4096 Jun 24 04:23 manager
-rw-r--r--   1 root    root      385 Sep  2  2021 manager-apache.conf
-rw-rw-r--   1 intelmq intelmq  6324 Jun 24 04:16 runtime.yaml
-rw-rw-r--   1 intelmq intelmq  6313 Jun 24 04:16 runtime.yaml.bak

**Comment by NaSangWon** [comment]
@sebix 

> Which Ubuntu version?

20.04.4 LTS

> At the installation you have been asked to enter a username and password for the API/Manager.

On installing intelmq-api, yes. I have entered username and password.
But somehow I can't login intelMQ manager with that.

**Comment by sebix** [comment]
Can you please run
```
sudo apt-get install --reinstall intelmq-api
```
and show the output (excluding your password of course). That command should (re-)create the file `/var/lib/dbconfig-common/sqlite3/intelmq-api/intelmqapi`, so maybe it shows us an error message.

**Comment by NaSangWon** [comment]
root@ubuntu:~# sudo apt-get --reinstall intelmq-api
E: Command line option --reinstall is not understood in combination with the other options

Did you mean `sudo apt-get install --reinstall intelmq-api`?

**Comment by sebix** [comment]
Yeah, whatever apt's parameters work :)

**Comment by NaSangWon** [comment]
I did `sudo apt-get install --reinstall intelmq-api` multiple times and this is what I finally get.

Reading package lists... Done
Building dependency tree       
Reading state information... Done
0 upgraded, 0 newly installed, 1 reinstalled, 0 to remove and 67 not upgraded.
1 not fully installed or removed.
After this operation, 0 B of additional disk space will be used.
E: Internal Error, No file name for intelmq-api:amd64

**Comment by sebix** [comment]
`1 not fully installed or removed.` and `Internal Error` doesn't look that good.
Please show `sudo dpkg -l | grep ^..R`
You also try `apt-get install -f` and `sudo dpkg --configure -a` to fix apt/dpkg problems on your machine.

**Comment by NaSangWon** [comment]
`sudo dpkg -l | grep ^..R` show nothing.

both `apt-get install -f` and `sudo dpkg --configure -a` return same error.

dbconfig-common: writing config to /etc/dbconfig-common/intelmq-api.conf
Loading config from /etc/intelmq/api-config.json
Traceback (most recent call last):
  File "/usr/bin/intelmq-api-adduser", line 27, in <module>
    session_store = intelmq_api.session.SessionStore(str(api_config.session_store), api_config.session_duration)
  File "/usr/lib/python3/dist-packages/intelmq_api/session.py", line 86, in __init__
    self.init_sqlite_db()
  File "/usr/lib/python3/dist-packages/intelmq_api/session.py", line 100, in init_sqlite_db
    with self.connect() as con:
  File "/usr/lib/python3/dist-packages/intelmq_api/session.py", line 91, in connect
    return sqlite3.connect(self.dbname, check_same_thread=False,
sqlite3.OperationalError: unable to open database file

**Comment by sebix** [comment]
I have no idea in what state dpkg is in your system. Normally the package creates the database in dpkg's `postinst` step and asks you for the credentials after that. For whatever reason the database can't be created?
*Maybe* the directory permissions got messed up? `ls -la /var/lib/dbconfig-common/sqlite3/intelmq-api/`

You could also try to purge the package before re-installing it.

**Comment by NaSangWon** [comment]
I updated dpkg, purged and reinstalled intelmq-api.

I logged in! thank you so much @sebix. 

Problem solved.

**Comment by sebix** [comment]
Phew, finally :) Sorry for the troubles, but I unfortunately I don't know what caused that situation.
