### ISSUE TITLE
Shadowserver NTP Version Report parsing issue

### ISSUE THREAD

**Issue by ClevenL** [certtools/intelmq#2228]
It seems like last week there was a change in Shadowserver NTP Version Report's `jitter` field type. 
The clock jitter was previously represented by a float e.g. `0.976`, the change included `sys_` - becoming `sys_0.976`. The parser errors could be resolved by modifying the parser `config.py` file:
In `ntp_version` object
```python
('extra.', 'jitter', convert_float),
```
-->
```python
('extra.', 'jitter', validate_to_none),
```
But this solution could create problems down the pipeline when a type is considered. For instance if outputting to ElasticSearch and it still expects a float type instead of a string.

**Comment by ClevenL** [comment]
Another solution if value type preservation is preferred:
Include an additional definition that extracts `sys_`:
```python
def convert_jitter_float(value: str) -> Optional[float]:
    """ 
    Returns an float or None for empty strings. 
    Used to preserve float value type for jitter
    field in ntp_version reports.
    """
    if re.match(r'^sys_', value):
        return float(value[4:]) if value else None

    return float(value) if value else None
```
and use it:
```python
('extra.', 'jitter', convert_jitter_float),
```

**Comment by sebix** [comment]
I don't know the intent of Shadowserver changing the type/content here, but removing the prefix `sys_` looks cleaner to me. Except if there will be other prefixes in the future.
@elsif2 do you know more on this?

**Comment by elsif2** [comment]
The `sys_` prefix was added inadvertently by an upstream update to our scanning tool.  The prefix will not appear going forward from 2022-08-02.
