### ISSUE TITLE
Shadowserver database upgrade statements are erroneous

### ISSUE THREAD

**Issue by sebix** [certtools/intelmq#2245]
For example the first entry:
```
UPDATE events
   SET "classification.identifier" = 'open-adb'
   WHERE "classification.identifier" = 'accessible-adb';
```
The identifier for this feed was previously `accessible-adb` and is still `accessible-adb`. Why should the values in the database be changed to `open-adb` now?

Same with other entries.

@elsif2

**Comment by elsif2** [comment]
The database updates were included in the original merge request and should have been reversed when I reworked the schema to maintain the original names.  I can remove these in the shadowserver-20220909 branch I have open for a few other updates.

**Comment by sebix** [comment]
ok. That would have prevented some work regarding backwards-compatibility on my side.

Yes, please remove these wrong statements and replace them with a note, that if users already executed them, they need to revert.

**Comment by elsif2** [comment]
Included in https://github.com/certtools/intelmq/commit/8880e0955c2c93b5b3ab9bef03f87e895cdbf267

**Comment by elsif2** [comment]
Fix included in https://github.com/certtools/intelmq/pull/2246

**Comment by sebix** [comment]
I think this is fixed
