### ISSUE TITLE
Problem using RT-Output bot

### ISSUE THREAD

**Issue by ndnikolaev** [certtools/intelmq#2249]
I have intelMQ - 3.0.2 installed on Ubuntu 20.04.
I am trying to auto create ticket from intelMQ to RT but I get error in /var/logs/intelmq/RT-Output-2.dump

 "source_queue": "RT-Output-2-queue",
        "traceback": [
            "Traceback (most recent call last):\n",
            "  File \"/usr/lib/python3/dist-packages/intelmq/lib/bot.py\", line 310, in start\n    self.process()\n",
            "  File \"/usr/lib/python3/dist-packages/intelmq/bots/outputs/rt/output.py\", line 71, in process\n    RT = rt.Rt(self.uri, verify_cert=self.verify_cert)\n",
            "AttributeError: module 'rt' has no attribute 'Rt'\n"

**Comment by sebix** [comment]
How did you install the rt library?

https://pypi.org/project/rt/

**Comment by ndnikolaev** [comment]
I install it with "pip install rt"

**Comment by sebix** [comment]
Is your `pip` Python 3?

**Comment by ndnikolaev** [comment]
It is Python3

pip show rt
Name: rt
Version: 3.0.3
Summary: Python interface to Request Tracker API
Home-page: None
Author: None
Author-email: Georges Toth <georges.toth@govcert.etat.lu>
License: GNU General Public License v3 (GPLv3)
Location: /usr/local/lib/python3.8/dist-packages
Requires: requests-toolbelt, requests

Base on documentation that @sebix provided I changed /intelmq/bots/outputs/rt/output.py to use rest1 api and now error displeased 
Now I can  connect to RTIR instance.
I need some time and testing to check if this solve my problem.

**Comment by ndnikolaev** [comment]
adding .rest1 on line 25 (import rt.rest1) and line 71 ( RT = rt.rest1.Rt(self.uri, verify_cert=self.verify_cert)) in file outputs/rt/output.py" do the trick.

Thanks
