### ISSUE TITLE
How to rotate event file?

### ISSUE THREAD

**Issue by qasidali861** [certtools/intelmq#2250]
How can I configure the event file rotating policy.

**Comment by sebix** [comment]
In `/etc/logrotate.d/intelmq`

**Comment by qasidali861** [comment]
Thanks Sebix for this 
I unable to find the intelmq file in logrotate.d
I need to create new one, if need to create new one so what will be the format of that file.

Thanks

**Comment by sebix** [comment]
> I unable to find the intelmq file in logrotate.d

How did you install IntelMQ?
> I need to create new one, if need to create new one so what will be the format of that file.

This is the expected content: https://github.com/certtools/intelmq/blob/develop/contrib/logrotate/intelmq

**Comment by qasidali861** [comment]
Thankx Sebix

**Comment by qasidali861** [comment]
Hi Sebix

I have tried but I am getting error 

```
error: intelmq:1 glob failed for /opt/intelmq/var/lib/bots/file-output/*.txt: No such file or directory

/opt/intelmq/var/lib/bots/file-output/*.txt {
    su intelmq intelmq
    daily
    maxsize 10M
    rotate 60
    notifempty
    compress
    delaycompress
    create 644 intelmq intelmq
    sharedscripts
    postrotate
        sudo -u intelmq /usr/local/bin/intelmqctl --quiet reload file-output
    endscript
}
```


intelmq file is above in logrotate.d

When I check opt/intelmq

There is no such directory which exist.....

Also tried giving my local directory location but got the same error.
