### ISSUE TITLE
Development Guide updates for working with local user and all dependency services

### ISSUE THREAD

**Issue by kamil-certat** [certtools/intelmq#2257]
Currently, the development guide suggested working with globally installed `intelmq`. For lowering potential conflicts with the local machine, easier development and integrations with IDE, I'd propose a guide to develop using a virtual environment and local non-root user.

In addition, there are some missing information about commonly used local services and test packages. I'd like to propose guide updates and eventually some additional automaton (e.g. docker-compose with development services) to make the start easier and quicker.

**Comment by sebix** [comment]
> I'd propose a guide to develop using a virtual environment and local non-root user.

intelmq doesn't run as root, so the second part is already fulfilled. To run IntelMQ in venvs, you can try setting INTELMQ_ROOT env variable to use different paths (not / or /opt/intelmq). But it could be the case that you need to change some code too.

**Comment by kamil-certat** [comment]
> intelmq doesn't run as root, so the second part is already fulfilled

Yes, yes. I want to switch from using a dedicated user to a local user (both non-root), for the development purposes.

So far, it looks working. I'd like to leave the configuration files where they are for now, but I agree, the best would be to make it configurable if it's possible. Will try with the env and see how it works.

**Comment by sebix** [comment]
using a user which is not `intelmq` should work as well. IntelMQ just rejects running as root:
https://github.com/certtools/intelmq/blob/122e3a386581688593878014cba457dd1c1e5599/intelmq/lib/utils.py#L682-L691
