### ISSUE TITLE
Python 3.6 full test fails to build due to pymssql wheel lack

### ISSUE THREAD

**Issue by kamil-certat** [certtools/intelmq#2262]
Yesterday, pymssql has uploaded a new version that lacks of wheel for Python 3.6. It stopped our tests to build on this platform.

They did not officially announce the drop of support for Python 3.6, so I've asked in the issue https://github.com/pymssql/pymssql/issues/787 if it was the plan. If no, we should wait for new wheel; if yes, then we should decide to pin the version or support building the package in the CI.

**Comment by sebix** [comment]
> or support building the package in the CI.

If you have the resources (time) to do so, feel free. But it's also OK to just drop support for it, if upstream does not provide it.

Quickest solution is something like
```
pymssql<$VERSION; python_version < '3.7'
pymssql; python_version >= '3.7'
```
in the requirements file

**Comment by kamil-certat** [comment]
Sure, will do it if pymssql answers that they intended to drop 3.6 :)

**Comment by sebix** [comment]
I didn't remember [3.6 is already EOL](https://devguide.python.org/versions/), as pymyssql upstream pointed out. I'm absolutely OK dropping the support for it in IntelMQ. Needs communication to the community via the lists, some doc updates and some smaller cleanups in the code.

**Comment by kamil-certat** [comment]
Okay, but I think it's another issue - could you please create it? 

I've noticed that the DEB packages still refers to compat level 9 and Python 3.5. Do we have a clear policy about supported Python/Debian/etc. versions?

**Comment by sebix** [comment]
> I've noticed that the DEB packages still refers to compat level 9 and Python 3.5.

PRs welcome.

> Do we have a clear policy about supported Python/Debian/etc. versions?

The reality is simple: If someone supports it, it's supported.
My guideline was: Is the Python/OS version EOL? Then drop it. Is it old and requires special attention/workarounds: Ask on the ML if someone else wants to maintain it, otherwise drop it. Do I need to support it (funded projects, partners, internal reasons): Support it. Everything else: Support it, if it works.
YMMV
