### ISSUE TITLE
Drop support for Python 3.6

### ISSUE THREAD

**Issue by kamil-certat** [certtools/intelmq#2272]
Python 3.6 is already EOL. We can drop support and update docs, requirements files and package definitions.

Before that, the question should be sent to the mailing list to be sure that no one needs/wants to maintain it.

Follow of #2262

**Comment by kamil-certat** [comment]
The email was sent.

For clean up:
the `harmonization.py` contains some compatibility code for Python lower than 3.6

**Comment by kamil-certat** [comment]
New reason for dropping: Github Action doesn't have Python 3.6 for the Ubuntu 22.04, which now is the `ubuntu-latest`. This means, our CI is at the moment blocked.

**Comment by aaronkaplan** [comment]
> The email was sent.
> 
> For clean up: the `harmonization.py` contains some compatibility code for Python lower than 3.6

I did not look into that yet.

**Comment by aaronkaplan** [comment]
keeping open , so far only did the unit test python 3.6 CI removal. See https://github.com/certtools/intelmq/pull/2281/
Still need to look at the code

**Comment by sebix** [comment]
3.6 is still mentioned in the setup.py
