### ISSUE TITLE
IntelMQ 3.0.2 not installable from pip

### ISSUE THREAD

**Issue by laciKE** [certtools/intelmq#2273]
[Pip website](https://pypi.org/project/intelmq/3.0.2/) states that the current version of IntelMQ is 3.0.2 and also that we could install it with command: `pip install intelmq==3.0.2`, which results into the error:

```
ERROR: Could not find a version that satisfies the requirement intelmq==3.2.0 (from versions: 1.0.0.dev3, 1.0.0.dev4, 1.0.0.dev5, 1.0.0.dev6, 1.0.0.dev7, 1.0.0.dev8, 1.0.0rc1, 1.0.0, 1.0.1rc1, 1.0.1, 1.0.2, 1.0.3, 1.0.4, 1.0.5, 1.0.6a1, 1.1.0rc1, 1.1.0rc2, 1.1.0, 1.1.1, 1.1.2, 2.0.0b1, 2.0.0, 2.0.1, 2.0.2, 2.1.0, 2.1.1, 2.1.2, 2.1.3, 2.2.0rc1, 2.2.0, 2.2.1, 2.2.2, 2.2.3, 2.3.0rc1, 2.3.0, 2.3.1, 2.3.2, 2.3.3, 3.0.0b1, 3.0.0rc1, 3.0.0, 3.0.1, 3.0.2.post1, 3.1.0rc1.post1)
ERROR: No matching distribution found for intelmq==3.2.0
```

In pip, the version is stated as 3.0.2.post1, which is also not installable, because there is an inconsistency in filename and metadata:
```
$ pip install intelmq==3.0.2.post1
Requested intelmq==3.0.2.post1  ... has inconsistent version: filename has '3.0.2.post1', but metadata has '3.0.2'
```

This means that command `pip install intelmq` installs the older version 3.0.1 with known bugs.

**Comment by kamil-certat** [comment]
@sebix Would you have a time to look at this?

**Comment by sebix** [comment]
*sigh* pip/pypi is complicated.

However: How could we resolve the situation? Only by releasing a new version?

@laciKE Does `pip install intelmq==3.1.0rc1.post1` work?

**Comment by kamil-certat** [comment]
> However: How could we resolve the situation? Only by releasing a new version?

Yea, I think so. The 3.0.3 with the corresponding correct version in the package.

**Comment by sebix** [comment]
Or a post2 with consistent versions^^

**Comment by laciKE** [comment]
@sebix yes, `pip3 install intelmq==3.1.0rc1.post1` works, I have used it as a temporary workaround together with intelmq-api==3.1.0 and intelmq-manager==3.1.0rc1

**Comment by sebix** [comment]
As 3.1.0 is around the corner anyway I suggest to skip fixing the issue with the 3.0.2 tarball

**Comment by laciKE** [comment]
Sounds reasonable, at least from my point of view.
Currently for IntelMQ installation from pip there is a workaround with 3.1.0rc1. And 3.1.0 will be soon the default version when someone do `pip install intelmq`
