### ISSUE TITLE
Universal collector and expert based on odo

### ISSUE THREAD

**Issue by Brandl** [certtools/intelmq#228]
Hello,

there is a brilliant python project called [odo](https://github.com/ContinuumIO/odo), basically the idea is to leverage a network of python data migration methods to get data from any shape into another.
It is also quite efficient and fault tolerant, because it uses shortest path from format A to B and takes a different path if one fails.

Basis Syntax:

    >>> from odo import odo 
    >>> odo(source, target)  # load source into target

Examples:

    >>> odo('myfile.*.csv', 'postgresql://hostname::tablename')  # Load CSVs to Postgres
    >>> odo('postgresql://hostname::tablename', 'myfile.json')

It tries to understand the input data, but it's also possible to override this behaviour by explicitly telling it what kind of data it is looking at:

    >>> odo('accounts.csv', pd.DataFrame,
    ...      dshape='var * {name: string, balance: float64}')
    
Supported formats:

- python objects
- pandas dataframes
- .csv
- .json
- .txt/log
- .csv.gz/json.gz
- .hdf5
- .hdf5::/datapath
- .bcolz
- .xls(x)
- .sas7bdat
- sqlite:////absolute/path/to/myfile.db::tablename
- sqlite:////absolute/path/to/myfile.db (specify a particular table)
- postgresql://username:password@hostname:port
- impala://hostname (uses impyla)
- anything supported by SQLAlchemy
- mongodb://username:password@hostname:port/database_name::collection_name

(based on the odo documentation)

I know there are already experts, which cover mongodb and postgresql export, yet having a universal import and export would still be beneficial I think.

As discussed with @aaronkaplan yesterday, I will try to create a bot to demonstrate this.

**Comment by aaronkaplan** [comment]
Coool!

Thanks for this!

**Comment by Th4nat0s** [comment]
Sounds nice since the mongodb is still broken .)

**Comment by SYNchroACK** [comment]
@Th4nat0s mongodb output bot? Try again please

**Comment by Th4nat0s** [comment]
Did you fix https://github.com/certtools/intelmq/issues/212 ?

**Comment by SYNchroACK** [comment]
https://github.com/certtools/intelmq/commit/8f94772c159aabe9cf1574e0ba90e7c0ec3579ad

I think so

**Comment by sebix** [comment]
Is this fixed now?

**Comment by SYNchroACK** [comment]
yes
