### ISSUE TITLE
SQLBot throws a AttributeError on reconnect

### ISSUE THREAD

**Issue by DigitalTrustCenter** [certtools/intelmq#2299]
This issue is only applicable for the 3.0.2 stable version, it is already fixed in develop.

The SQLBot uses the ‘engine’ variable for both the type of the sql engine (type string: sqlite/postgresql), and for the database engine object itself (type psycopg2 or sqlite3). 

In our tests this happens:
engine is set to “postgresql” (from the bot config)
_connect is called, which sets engine to psycopg2
Later the database disconnects, due to a timeout.
execute, catches the exception, which calls init.
Init tries to call lower() on engine. It expects engine to be a string, but is now the psycopg2 module.
An AttributeError is thrown, causing the message to drop (moved to the dump file). 

We have a fix in our fork https://github.com/DigitalTrustCenter/intelmq/tree/sqlbot-reconnect-issue
Since this is already fixed in develop (as SQLBot is replaced with SQLMixin), should we make a PR for the maintenance branch?

**Comment by sebix** [comment]
I'm currently coordinating to get the 3.1.0 release out. Well, I said that already half a year ago, but we are getting closer.

In the previous years, we (when I was working at CERT.at) maintained two branches, a stable one for patch releases (branch `maintenance`) and one for the development of the following feature/major release (branch `develop`). With the massive reduction in development time and maintenance contributions to IntelMQ, it is unfortunately impossible to keep this two-track development.

**Comment by sebix** [comment]
This bug is fixed in version 3.1.0, to be released today
