### ISSUE TITLE
Pip hangs, because of input() in setup.py

### ISSUE THREAD

**Issue by Brandl** [certtools/intelmq#230]
Hey,

I'm currently trying to automate the creation of a Vagrant-development-box 
(https://github.com/Brandl/intelmq-vagrant).

Unfortunately, I had some issues with pip freezing, when trying to install intelmq from source.
The problem seems to be the raw_input(), which requires user interaction:
https://github.com/certtools/intelmq/blob/master/setup.py#L9

**Comment by SYNchroACK** [comment]
Hi @Brandl 
Did you already check https://github.com/certtools/intelmq/tree/v1.0-beta/scrips/vagrant ?

Thank you,
Best regards

**Comment by Brandl** [comment]
Well, I started working on it independently, before @aaronkaplan told me that there are major changes happening on the beta-branch and of course noticed that someone already played with vagrant. 

The major difference is, that mine is built upon an ansible playbook:
https://github.com/ezeteze/intelmq-elk 
Which I think is more robust and easier to maintain. Also a major difference is, that mine also sets up and configures elasticsearch and kibana, which is definitely a use-case where ansible shines. 

If you wish, I could refactor and merge my version into the beta-branch, or should we keep both solutions?

**Comment by SYNchroACK** [comment]
I prefer this one 'I could refactor and merge my version into the beta-branch'. Thank you @Brandl

**Comment by pedrosa-t** [comment]
I was stating the ELK installation with kibana 4 continuing the bootstrap script. But as @Brandl as it done in a ansible cookbook maybe we could change the provision of vagrant to ansible. What do you think? 
Should provision be made in shell script or in an ansible cookbook? 
Should we provide both options or even choose a different CMF ?

**Comment by SYNchroACK** [comment]
To be honest, Im not familiar with any solution. I would support any solution that you and @Brandl can arrange together. Please, use this issue to discuss and decide ;) Thank you both of you

**Comment by Brandl** [comment]
I made a separate issue(#231), because I still need a solution for my problem with pip freezing, because there is raw_input() within the setup.py script:
https://github.com/certtools/intelmq/blob/master/setup.py#L9

**Comment by sebix** [comment]
This is what the installation routine of zmq does:

>    I will now try to build libzmq as a Python extension
>    unless you interrupt me (^C) in the next 10 seconds...

May this be an option for us?

**Comment by sebix** [comment]
Fixed by #448
