### ISSUE TITLE
ctl tests require an installed IntelMQ instance

### ISSUE THREAD

**Issue by wagner-intevation** [certtools/intelmq#2300]
@kamil-certat `test_check_pass_with_default_runtime` and `test_check_passed_with_default_harmonization_and_empty_runtime` assume a local installation of IntelMQ, including a state file and the bot executables in $PATH. Is that intentional?

**Comment by kamil-certat** [comment]
Not entirely, but I need to verify the behavior, and ensure I've tested it properly.

The assumption was that we have the working and importable IntelMQ package, installed with setup.py or similar (= normal pre-step for unittests). This should be enough to install all entry points (and all bots, all in entry points as per `setup.py`). The state file is, however, missed by me, but please note: the missing state file shouldn't break tests - it doesn't change the return value.

**Comment by wagner-intevation** [comment]
Working on a fix/workaround
