### ISSUE TITLE
Readme file contains broken link

### ISSUE THREAD

**Issue by Turecky** [certtools/intelmq#2306]
In section `IntelMQ Manager and more tools` is url to 
`Ecosystem chapter in the documentation` -> `https://intelmq.readthedocs.io/en/latest/user/ecosystem.html`

URL returns 404.

**Comment by sebix** [comment]
Thanks.

We renamed this section to `universe`.

**Comment by aaronkaplan** [comment]
Is there any specific reason to rename it to universe? Ecosystem (language-wise) seems more meaningful for my sense of english. "universe" is a bit ... too broad maybe ?  Just wondering.
Don't get me wrong, it will be understandable . And I also merged the changes. However on second thought, I was merely wondering why we took that big term. Sounds like cosmos. Or ... "multiverse" ;-)

**Comment by sebix** [comment]
The idea to rename the page was originally from @b1rger. "Ecosystem" is a closed environment, while "universe" sounds more _open_. Not only the source of all tools is _open_, but also the APIs' and tools' purpose is connecting to other (external) tools.

**Comment by aaronkaplan** [comment]
okay, I see the intention. But - planet earth is an ecosystem as well. I would rather call that a big one ;-)
Anyways, we can discuss in person. No need to increase the noise here hehe. Anyways, I was merely wondering what the reasoning was. But yeah, I got your point.
