### ISSUE TITLE
Provisioning solution for IntelMQ

### ISSUE THREAD

**Issue by Brandl** [certtools/intelmq#231]
Hello,

basically, vagrant is not a provisioning framework, but a very handy too to automate the creation of virtual machines with support for different hypervisors. It comes with a simple config file called Vagrantfile and allows to execute bash scripts or full fledged provisioning after VM creation.

There is some prior art done by @pedrosa-t to setup intelmq with a simple, yet easy to understand bash script, see:
https://github.com/certtools/intelmq/tree/v1.0-beta/scripts/vagrant

In the meanwhile, I took a different approach, by using the existing ansible playbooks by @ezeteze to build a vagrant box, which also sets up a elastic search and kibana stack:
https://github.com/Brandl/intelmq-vagrant

So questions to discuss are:
1. How do we combine our efforts on this?
2. Which framework should be used for making intelmq provisioning scripts?
3. Should this be part of the intelmq core or a sub-project?

For previsions thoughts on this see: #230

**Comment by pedrosa-t** [comment]
Hi,
My idea was to automate the testing of the project on a virtual machine. So I used vagrant to execute a simple bash script that could deploy the beta branch of the project.

Follow my contribute to the discussion  :

1 - If the idea is only testing on a VM, maybe it will be overkill to use a CMF. If we want to enable users to automate the deploy intelmq services on their systems, we should evolve to the use of a CMF and use it also for the testing.

2 - In this project I don’t see requirements that point me to choose a special CMF. Therefore, considering the work already done by @Brandl we can use ansible.

3 - I’m seeing 2 scenarios: 
First one,: Everything on the core part: creating  a directory “ansible"  inside scripts, to store the playbook for all the deploy:
	\scripts
		\vagrant
			Vagrantfile
		\ansible
			…
	And the vagrant will point to the ansible. With this approach, users can go to the vagrant directory and execute “vagrant up” to test the ansible  deploy of the project on a VM. Or they can go to ansible directory and execute the ansible playbook to a specific server. If someone what to develop provisioning scripts using different CMFs other directories per CMF can be created.

The second approach  is to create a repository for have the ansible playbook. That can be considered a git submodule on the ansible directory That would enable to deploy the intelmq on their servers using ansible just by cloning the repository of the ansible playbook. For testing proposes using the vagrant, users need clone the intelmq repo and the submodule (ansible intemq cookbook) to execute vagrant and use the cookbook on the VM. I think that clone can be made with --recursive option to clone the repository and the submodule repository at once. This will enable also to create diverse repositories for different CMFs is someone wants to.

What do you think ?

**Comment by SYNchroACK** [comment]
@Brandl and @pedrosa-t any news about this issue?

**Comment by aaronkaplan** [comment]
On Jun 16, 2015, at 7:14 PM, Tiago Pedrosa <notifications@github.com> wrote:

> Hi,
> My idea was to automate the testing of the project on a virtual machine. So I used vagrant to execute a simple bash script that could deploy the beta branch of the project.
> 

I believe, the testing is now implemented via Travis-CI.
Is that sufficient for you Tiago?

**Comment by pedrosa-t** [comment]
> On 18/09/2015, at 20:57, AaronK <notifications@github.com> wrote:
> 
> 
> On Jun 16, 2015, at 7:14 PM, Tiago Pedrosa <notifications@github.com> wrote:
> 
> > Hi,
> > My idea was to automate the testing of the project on a virtual machine. So I used vagrant to execute a simple bash script that could deploy the beta branch of the project.
> > 
> 
> I believe, the testing is now implemented via Travis-CI.
> Is that sufficient for you Tiago?
Yes.

**Comment by zurgutt** [comment]
Having installers in separate repository serves no good purpose at all, lets have them in main repo.
