### ISSUE TITLE
Undocumented native packages for CentOS 8 don't work on CentOS 9

### ISSUE THREAD

**Issue by kamil-certat** [certtools/intelmq#2325]
```
yum install intelmq
Extra Packages for Enterprise Linux 9 - x86_64                                                                                                                                                            11 MB/s |  14 MB     00:01    
Extra Packages for Enterprise Linux 9 - Next - x86_64                                                                                                                                                    1.8 MB/s | 1.2 MB     00:00    
Last metadata expiration check: 0:00:02 ago on Thu 16 Feb 2023 03:36:35 PM CET.
Error: 
 Problem: package intelmq-3.0.2-1.8.noarch requires python3-intelmq = 3.0.2, but none of the providers can be installed
  - conflicting requests
  - nothing provides python(abi) = 3.8 needed by python3-intelmq-3.0.2-1.8.noarch
  - nothing provides python3.8dist(psutil) >= 1.2.1 needed by python3-intelmq-3.0.2-1.8.noarch
  - nothing provides python3.8dist(pytz) >= 2012c needed by python3-intelmq-3.0.2-1.8.noarch
  - nothing provides python3.8dist(requests) >= 2.2.0 needed by python3-intelmq-3.0.2-1.8.noarch
  - nothing provides /usr/bin/python3.8 needed by python3-intelmq-3.0.2-1.8.noarch
  - nothing provides python38-setuptools needed by python3-intelmq-3.0.2-1.8.noarch
  - nothing provides python38-requests needed by python3-intelmq-3.0.2-1.8.noarch
  - nothing provides python38-psutil needed by python3-intelmq-3.0.2-1.8.noarch
  - nothing provides python38-pytz needed by python3-intelmq-3.0.2-1.8.noarch
```

**Comment by sebix** [comment]
What's the source for the intelmq package on CentOS 9?

**Comment by kamil-certat** [comment]
Sorry for missed information, I forgot to add a comment. I used the repo for CentOS 8, so basically some issues were expected. However, the CentOS 9 is the current version, so we rather should build packages against it. Currently, we don't have any package for it.

**Comment by sebix** [comment]
> I used the repo for CentOS 8, so basically some issues were expected.

You answer your own bug report.

I will remove the CentOS 8 repos too to not trigger bug reports like these. CentOS 8 packages are broken too and never worked for CentOS 8. I previously already removed CentOS completely from https://intelmq.readthedocs.io/en/latest/user/installation.html#native-deb-rpm-packages

**Comment by kamil-certat** [comment]
Hmm, last time I was looking on the doc it was still there. So, we don't support CentOS packages anymore?

**Comment by sebix** [comment]
> So, we don't support CentOS packages anymore?

They only worked OKish for CentOS 7. The newer versions required different approaches (remember "CentOS Stream"?) and there was not enough interest in the community.

**Comment by kamil-certat** [comment]
Okay, thanks for clarify! I was probably looking on some old doc version (maybe local PR build instead of the one online?) where CentOS 8 was still listed.
