### ISSUE TITLE
v1.0-beta branch collecters are not starting

### ISSUE THREAD

**Issue by pedrosa-t** [certtools/intelmq#233]
After a clean install using the vagrant scripts the collectors are not starting.

intelmq@vagrant-ubuntu-trusty-64:~$ ./bin/intelmqctl --botnet status
arbor-collector is stopped.
arbor-parser is stopped.
file-output is stopped.
malware-domain-list-collector is stopped.
malware-domain-list-parser is stopped.
intelmq@vagrant-ubuntu-trusty-64:~$ ./bin/intelmqctl --botnet start
Starting Botnet...
Starting arbor-collector...
arbor-collector is already running.
Starting arbor-parser...
arbor-parser is already running.
Starting file-output...
file-output is already running.
Starting malware-domain-list-collector...
malware-domain-list-collector is already running.
Starting malware-domain-list-parser...
malware-domain-list-parser is already running.
Botnet is already running.
intelmq@vagrant-ubuntu-trusty-64:~$ ./bin/intelmqctl --botnet status
arbor-collector is stopped.
arbor-parser is already running.
file-output is already running.
malware-domain-list-collector is stopped.
malware-domain-list-parser is already running.

If I try to run:

intelmq@vagrant-ubuntu-trusty-64:~$ python -m  intelmq.bots.collectors.http.collector_http arbor-collector
Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "build/bdist.linux-x86_64/egg/intelmq/bots/collectors/http/collector_http.py", line 2, in <module>
ImportError: No module named url.lib

**Comment by CNCS-PT** [comment]
@pedrosa-t Thank you.
Its fixed in v1.0 branch and also in v1.0-beta branch.

Please, use the v1.0 branch now... it will be merged in few days with master.

**Comment by aaronkaplan** [comment]
On Jun 17, 2015, at 5:19 PM, National CyberSecurity Center <notifications@github.com> wrote:

> @pedrosa-t Thank you.
> Its fixed in v1.0 branch and also in v1.0-beta branch.
> 
> Please, use the v1.0 branch now... it will be merged in few days with master.
> 

I do not believe that merging with the master branch *without tests* from multiple partners in the project is a good idea. It might ruin stability.

My 2 cents,
a.

**Comment by CNCS-PT** [comment]
Well, who wants to do the test?

**Comment by pedrosa-t** [comment]
I've just clone the v1.0-final branch changed the bootscript.sh on vagrant to use this branch.
After the creation of the clean vm and deploy of intelmq, I've the following error.


vagrant@vagrant-ubuntu-trusty-64:~$ sudo su - intelmq
intelmq@vagrant-ubuntu-trusty-64:~$ ./bin/intelmqctl --botnet start
/usr/lib/python2.7/dist-packages/pkg_resources.py:1031: UserWarning: /opt/intelmq/.python-eggs is writable by group/others and vulnerable to attack when used with get_resource_filename. Consider a more secure location (set with .set_extraction_path or the PYTHON_EGG_CACHE environment variable).
  warnings.warn(msg, UserWarning)
Traceback (most recent call last):
  File "./bin/intelmqctl", line 13, in <module>
    from intelmq.lib.pipeline import PipelineFactory, Redis
ImportError: No module named intelmq.lib.pipeline

**Comment by aaronkaplan** [comment]
On Jun 17, 2015, at 6:34 PM, National CyberSecurity Center <notifications@github.com> wrote:

> Well, who wants to do the test?
> 

As discussed, I will do integration tests and compare against the output of the old format after my travels.
