### ISSUE TITLE
Error Installing IntelMQ Manager with PYPI

### ISSUE THREAD

**Issue by Qazxcvbd** [certtools/intelmq#2334]
I tried to install IntelMQ Manager 3.0.0 with PYPI on Ubuntu 18.04, but it failed.
I followed the intelmq.readthedoc intelmq-manager's instruction, but one of instructions that I can't really understand.
this one -> intelmq-manager-build --output-dir your/preferred/output/directory/.
According to the above operating instruction, what command should I write in the Ubuntu ?

**Comment by sebix** [comment]
Does the manager work without calling this command? Are files in `/usr/share/intelmq_manager/html`?

Ubuntu 18.04 is not supported by IntelMQ

**Comment by Qazxcvbd** [comment]
Yes, there are files in /usr/share/intelmq_manager/html.
I upgraded my Ubuntu to 20.04 version yesterday and installed intelmq, intelmq-manager and intelmq-api with PYPI.
After that,  I've created an account with the cmd "intelmq-api-adduser", but the intelmq-manager still didn't work and coudn't let me log in.

On about.html : pop-up with Error getting version and Error getting debugging information. Do you have IntelMQ >= 2.2.0?
On configs.html : 
1. Get an error error, Forbidden when trying to obtain config file properly
    http://mylocalhost/intelmq/v1/api/positions
2. Get an error error, Forbidden when trying to obtain config file properly
    http://mylocalhost/intelmq/v1/api/runtime
3. Get an error error, Forbidden when trying to obtain config file properly
    http://mylocalhost/intelmq/v1/api/bots

If it can help, the result of "intelmqctl debug --get-paths"
Paths:
HARMONIZATION_CONF_FILE: '/opt/intelmq/etc/harmonization.conf'
RUNTIME_CONF_FILE: '/opt/intelmq/etc/runtime.yaml'
VAR_RUN_PATH: '/opt/intelmq/var/run/'
STATE_FILE_PATH: '/opt/intelmq/var/lib/state.json'
DEFAULT_LOGGING_PATH: '/opt/intelmq/var/log/'
__file__: '/usr/local/lib/python3.8/dist-packages/intelmq/bin/intelmqctl.py'
CONFIG_DIR: '/opt/intelmq/etc/'
ROOT_DIR: '/opt/intelmq/'

**Comment by Qazxcvbd** [comment]
In addition, I want to make sure that if I want to browse the webinterface, is the URL **http://localhost/intelmq-manager** I entered correct?

**Comment by sebix** [comment]
> Yes, there are files in /usr/share/intelmq_manager/html. I upgraded my Ubuntu to 20.04 version yesterday and installed intelmq, intelmq-manager and intelmq-api with PYPI. After that, I've created an account with the cmd "intelmq-api-adduser", but the intelmq-manager still didn't work and coudn't let me log in.
> 
> On about.html : pop-up with Error getting version and Error getting debugging information. Do you have IntelMQ >= 2.2.0?

That means either not being logged in or the API does not work. Both is the case here.

> If it can help, the result of "intelmqctl debug --get-paths" Paths: HARMONIZATION_CONF_FILE: '/opt/intelmq/etc/harmonization.conf' RUNTIME_CONF_FILE: '/opt/intelmq/etc/runtime.yaml' VAR_RUN_PATH: '/opt/intelmq/var/run/' STATE_FILE_PATH: '/opt/intelmq/var/lib/state.json' DEFAULT_LOGGING_PATH: '/opt/intelmq/var/log/' **file**: '/usr/local/lib/python3.8/dist-packages/intelmq/bin/intelmqctl.py' CONFIG_DIR: '/opt/intelmq/etc/' ROOT_DIR: '/opt/intelmq/'

That looks OK.

Did you call `intelmqsetup` after the upgrade? It should output `Running setup for intelmq-api` and `Running webserver setup for intelmq-api`.



> In addition, I want to make sure that if I want to browse the webinterface, is the URL **http://localhost/intelmq-manager** I entered correct?

Yes. And if the manager (frontend) works for you, even more so.

**Comment by Qazxcvbd** [comment]
> That means either not being logged in or the API does not work. Both is the case here.

When I try to log in, the system shows a notification that Login failed with unknown reason. Please report this bug.
Are those cases both about permission setting?  I already tried to give it permissions in various ways with chown and chmod but the problem persists.

> Did you call intelmqsetup after the upgrade? It should output Running setup for intelmq-api and Running webserver setup for intelmq-api.

Yes! I called intelmqsetup after the upgrade, and it output Running setup for intelmq-api and Running webserver setup for intelmq-api. However, it appears another error : 

`Migrates feeds' configuration for changed/fixed parameter: Upgrade failed: A discontinued feed "Malc0de" has been found as bot malc0de-parser. Remove affected bots yourself. Some migration did not succeed or manual intervention is needed. Look at the output above. Afterwards, re-run this program.`

About this error, I don't know what the correct path is for bot malc0de-parser, so I coudn't remove it.

**Comment by sebix** [comment]
> > That means either not being logged in or the API does not work. Both is the case here.
> 
> When I try to log in, the system shows a notification that Login failed with unknown reason. Please report this bug. Are those cases both about permission setting? I already tried to give it permissions in various ways with chown and chmod but the problem persists.

I don't know the reason yet. Doing permission changes on spec can lessen your system security.

> > Did you call intelmqsetup after the upgrade? It should output Running setup for intelmq-api and Running webserver setup for intelmq-api.
> 
> Yes! I called intelmqsetup after the upgrade, and it output Running setup for intelmq-api and Running webserver setup for intelmq-api.

Okay, that's good. It means the apache configuration for the API is in place. Please check the error log of Apache now.

> However, it appears another error :
> 
> `Migrates feeds' configuration for changed/fixed parameter: Upgrade failed: A discontinued feed "Malc0de" has been found as bot malc0de-parser. Remove affected bots yourself. Some migration did not succeed or manual intervention is needed. Look at the output above. Afterwards, re-run this program.`
> 
> About this error, I don't know what the correct path is for bot malc0de-parser, so I coudn't remove it.

That error is not relevant for this problem.
The configuration of IntelMQ's bots is in `/etc/intelmq/runtime.yaml` or you wait until the Manager/API work.

**Comment by Qazxcvbd** [comment]
Below is the error log of Apache:

```
"GET /intelmq/v1/api/queues-and-status HTTP/1.1" 403 491 "http://mylocalhost/intelmq-manager/configs.html"
"GET /intelmq-manager/configs.html HTTP/1.1" 200 3543 "http://mylocalhost/intelmq-manager/about.html"
"GET /intelmq-manager/js/var.js HTTP/1.1" 404 488 "http://mylocalhost/intelmq-manager/configs.html"
"http://mylocalhost/intelmq-manager/configs.html"
"GET /intelmq/v1/api/runtime HTTP/1.1" 403 491 "http://mylocalhost/intelmq-manager/configs.html"
"GET /intelmq/v1/api/positions HTTP/1.1" 403 491 "http://mylocalhost/intelmq-manager/configs.html"
```

> That error is not relevant for this problem.
The configuration of IntelMQ's bots is in /etc/intelmq/runtime.yaml or you wait until the Manager/API work.

Thanks ! I'll wait until the Manager/API work.

>

**Comment by sebix** [comment]
> Below is the error log of Apache:

This is the access.log, not the error.log

**Comment by Qazxcvbd** [comment]
Sorry, it's my fault.
Below is error log:
`client denied by server configuration: /usr/lib/python3/dist-packages/intelmq_api, referer: http://mylocalhost/intelmq-manager/configs.html`

**Comment by sebix** [comment]
I think the culprit is, that Ubuntu's python/pip installed into `/usr/local/lib/python3.8/dist-packages/intelmq_api` where as the Apache configuration for the API expectes `/usr/lib/python3/dist-packages/intelmq_api`.

Can you check `/etc/apache2/conf-available/api-apache.conf` (or elsewhere in `/etc/apache2`) and fix the path there?

**Comment by Qazxcvbd** [comment]
I fixed the path in api-apache.conf
`WSGIScriptAlias /intelmq /usr/lib/python3/dist-packages/intelmq_api/intelmq-api.wsgi`     to
`WSGIScriptAlias /intelmq /usr/local/lib/python3.8/dist-packages/intelmq_api/intelmq-api.wsgi` 
and
`<Directory  /usr/lib/python3/dist-packages/intelmq_api/>` to
`<Directory /usr/local/lib/python3.8/dist-packages/intelmq_api/>`

But when I checked for Apache error.log, it still has the same error : 
`client denied by server configuration: /usr/lib/python3/dist-packages/intelmq_api, referer: http://mylocalhost/intelmq-manager/configs.html`

**Comment by sebix** [comment]
Something in the apache config still links to `/usr/lib/python3/dist-packages/intelmq_api`

**Comment by Qazxcvbd** [comment]
I coudn't find other config that need to fix the path in apache.
Is there another config you think is possible?

**Comment by Qazxcvbd** [comment]
I checked `/etc/intelmq/api-apache.conf` as well as fixed the path, and it works successfully !
Although I can log in successfully, it still pop up some errors.

On about.html : 
`pop-up with Error getting version` and `Error getting debugging information. Do you have IntelMQ >= 2.2.0?`
On configs.html :
Error loading bot queues information: sudo: /etc/sudoers.d/01_intelmq-api is owned by uid 33, should be 0
`sudo -u www-data sudo -u intelmq intelmqctl --type json list queues-and-status`
Saved positions are not valid or not complete. The configuration has possibly been modified outside of the IntelMQ-Manager.
Get an error error, Internal Server Error when trying to obtain config file properly
`http://mylocalhost/intelmq/v1/api/positions`
Get an error error, Internal Server Error when trying to obtain config file properly
`http://mylocalhost/intelmq/v1/api/bots`

apache error log:
[wsgi:error] [pid 51594] [client 10.3.93.209:62943] Loading config from /etc/intelmq/api-config.json, referer: http://mylocalhost/intelmq-manager/about.html
[wsgi:error] [pid 51596] [client 10.3.93.209:62949] Loading config from /etc/intelmq/api-config.json, referer: http://mylocalhost/intelmq-manager/configs.html

**Comment by sebix** [comment]
> I checked `/etc/intelmq/api-apache.conf` as well as fixed the path, and it works successfully !

OK, great that the login works now. That means the python backend does run and can access the user database.
But it seems it can't call `intelmq` correctly.

> On configs.html : Error loading bot queues information: sudo: /etc/sudoers.d/01_intelmq-api is owned by uid 33, should be 0

Can you please check this file? Also check if the path of intelmqctl in the sudoers file is correct.
Maybe you also need to set `intelmq_ctl_cmd`, see: https://intelmq.readthedocs.io/en/develop/user/intelmq-api.html#configuring-intelmq-api

**Comment by Qazxcvbd** [comment]
> On configs.html : Error loading bot queues information: sudo: /etc/sudoers.d/01_intelmq-api is owned by uid 33, should be 0

This error has been resolved !
I ran `chown root:root /etc/sudoers.d/01_intelmq-api` and  `chmod 440 /etc/sudoers.d/01_intelmq-api`

Now, there is only one problem popup on configs.html :
```
Get an error error, Internal Server Error when trying to obtain config file properly
http://mylocalhost/intelmq/v1/api/positions
```

**Comment by sebix** [comment]
> This error has been resolved ! I ran `chown root:root /etc/sudoers.d/01_intelmq-api` and `chmod 440 /etc/sudoers.d/01_intelmq-api`

Great!

> Now, there is only one problem popup on configs.html :
> 
> ```
> Get an error error, Internal Server Error when trying to obtain config file properly
> http://mylocalhost/intelmq/v1/api/positions
> ```

After saving the configuration for the first time, the positions will be saved too and the error should go away.

**Comment by Qazxcvbd** [comment]
The error was went away!!
After I saved the configuration, it popup permission denied to access runtime.yaml. Then I ran `chown www-data:www-data /opt/intelmq/etc/runtime.yaml`, my intelmq work successfully without any error.
Thank for your help !!

**Comment by sebix** [comment]
Great!

Installations with PyPI are a bit tricky as they require some manual work, but it works :)

**Comment by Qazxcvbd** [comment]
For some reason I reinstalled intelmq and upgraded Ubuntu to version 22.04.
It still popup some errors : ((
When I try to log in, the system shows a notification that Login failed with unknown reason. Please report this bug.
On about.html : pop-up with Error getting version and Error getting debugging information. Do you have IntelMQ >= 2.2.0?

Apache error.log:
```
[Mon Mar 20 16:09:06.079770 2023] [mpm_prefork:notice] [pid 717859] AH00163: Apache/2.4.52 (Ubuntu) configured -- resuming normal operations
[Mon Mar 20 16:09:06.079888 2023] [core:notice] [pid 717859] AH00094: Command line: '/usr/sbin/apache2'
```

My apache status is active(running),  and I has already ran intelmqsetup.

**Comment by sebix** [comment]
> When I try to log in, the system shows a notification that Login failed with unknown reason. Please report this bug.

Can you open the Manager in the browser, open the developer tools, go to the network tab, (try to) login and check what the response of the `http://localhost/intelmq/v1/api/login` request? Maybe it reveals something by itself.

**Comment by Qazxcvbd** [comment]
[
![image](https://user-images.githubusercontent.com/127489935/226551198-a643efdf-100d-449d-a861-7c0c031ecf51.png)
](url)

It's my status of open the manager in the browser.
Besides, there is no var.js in /usr/share/intelmq-manager/html/js/, only dynvar.js. I'm a bit confused about one of this error.

**Comment by sebix** [comment]
> [ ![image](https://user-images.githubusercontent.com/127489935/226551198-a643efdf-100d-449d-a861-7c0c031ecf51.png) ](url)
> 
> It's my status of open the manager in the browser.

OK, it shows that the requests to the API end in an error 404. Can you check the apache config for intelmq-api?

> Besides, there is no var.js in /usr/share/intelmq-manager/html/js/, only dynvar.js. I'm a bit confused about one of this error.

`var.js` is an optional file. This is not an error.

**Comment by Qazxcvbd** [comment]
I finally decided to run on Ubuntu 20.04, so the path still /usr/local/lib/python3.8/dist-packages/intelmq_api

Below is the screenshot of api-apache.conf:
[
![image](https://user-images.githubusercontent.com/127489935/226565745-a76d872b-153c-49f0-b17d-7e2e1c36f238.png)
](url)

**Comment by sebix** [comment]
mod_wsgi is installed? the wsgi script exists in that place?

EDIT: The shown configuration is in conf-enabled (not only in conf-available?)

**Comment by Qazxcvbd** [comment]
Yes, there is wsgi script in that place.
The shown configuration is only in conf-available.

**Comment by Qazxcvbd** [comment]
I checked the file in /etc/sudoers.d/01_intelmq-api:
And the content is :
```
# SPDX-FileCopyrightText: 2020 Birger Schacht
#
# SPDX-License-Identifier: CC0-1.0
#
# intelmq-api sudoers file, allowing the intelmq-api which usually
# is run by a webserver, to run intelmqctl as user intelmq
www-data ALL=(intelmq) NOPASSWD: /usr/bin/intelmqctl
```

Then I found that there is no intelmqctl file in /usr/bin.

**Comment by Qazxcvbd** [comment]
I verified `which intelmqctl` and the result shows /usr/local/bin/intelmqctl.
I fixed the path in /etc/sudoers.d/01_intelmq-api:
And the content is :
```
# SPDX-FileCopyrightText: 2020 Birger Schacht
#
# SPDX-License-Identifier: CC0-1.0
#
# intelmq-api sudoers file, allowing the intelmq-api which usually
# is run by a webserver, to run intelmqctl as user intelmq
www-data ALL=(intelmq) NOPASSWD: /usr/local/bin/intelmqctl
```

My intelmq-api still doesn't work : (

**Comment by Qazxcvbd** [comment]
I uninstalled intelmq, intelmq-api and intelmq-manager. Then installed them with native packages.
It works successfully !!
Thanks for your help : )

**Comment by sebix** [comment]
> The shown configuration is only in conf-available.

Then it can't work, you can run `a2enconf api-apache` to enable it.

> I uninstalled intelmq, intelmq-api and intelmq-manager. Then installed them with native packages. It works successfully !!

Great to hear the packages are possible for your setup and that they work. They require much less effort for the sysadmin.

**Comment by Qazxcvbd** [comment]
I already ran a2enconf api-apache, but it coudn't work : (
Installations with PyPI is really complicated, I'm glad that my intelmq finally worked by using native packages.
Thanks !

**Comment by sebix** [comment]
yeah, native packages are definitely recommended for all non-development setups.
