### ISSUE TITLE
intelmqsetup changes the root directory ownership

### ISSUE THREAD

**Issue by kamil-certat** [certtools/intelmq#2354]
`intelmqsetup` tries to fix ownership of related directories:

https://github.com/certtools/intelmq/blob/7674949656748164aede86e7dfc3aa39372add44/intelmq/bin/intelmqsetup.py#L172-L176

However, the `ROOT_DIR` can be set to `/`:

https://github.com/certtools/intelmq/blob/7674949656748164aede86e7dfc3aa39372add44/intelmq/__init__.py#L18-L20

This causes `intelmqsetup` to take over the ownership of the root directory, what could open some security risk as well as break some system actions (e.g. `systemd-tmpfiles`)

**Comment by sebix** [comment]
It should be noted that `path == "lsb"` is only true if the user explicitly sets `INTELMQ_PATHS_NO_OPT`, and only in installations from git/PyPI. Installations from packages are not affected, the affected code is not present there.
