### ISSUE TITLE
source.fqdn -> Domain

### ISSUE THREAD

**Issue by SYNchroACK** [certtools/intelmq#241]

**Comment by robcza** [comment]
Does this mean the you are going to change "source.fqdn" to "source.domain"?
ping @kozeltom @karm

**Comment by SYNchroACK** [comment]
no... it means that i will change the name of the class in harmonization.py from 'Domain' to 'FQDN'

**Comment by SYNchroACK** [comment]
Fixed e7bbcd6c8c8996167309af57217a81ae35604900
