### ISSUE TITLE
Unable to install intelmq on Ubuntu 20.04

### ISSUE THREAD

**Issue by Paul-Dutot** [certtools/intelmq#2418]
I am trying to install intelmq on Ubuntu 20.04 following the instructions from [here](https://software.opensuse.org/download.html?project=home%3Asebix%3Aintelmq%3Aunstable&package=intelmq)

It is not possible to install due to a dependancy requirement of python3-dnspython >= 2.0.0.

I have even tried compiling the python package manually

## Steps to reproduce ##
Fresh install of ubuntu fully updated followed by below
```
cert@intelmqtest:~/dnspython-2.4.2$ history
    1  sudo ap[t-get update
    2  sudo apt-get update
    3  sudo apt-get upgrade
    4  echo 'deb http://download.opensuse.org/repositories/home:/sebix:/intelmq:/unstable/xUbuntu_20.04/ /' | sudo tee /etc/apt/sources.list.d/home:sebix:intelmq:unstable.list
    5  curl -fsSL https://download.opensuse.org/repositories/home:sebix:intelmq:unstable/xUbuntu_20.04/Release.key | gpg --dearmor | sudo tee /etc/apt/trusted.gpg.d/home_sebix_intelmq_unstable.gpg > /dev/null
    6  sudo apt update
    7  sudo apt install intelmq intelmq-api
    8  wget https://github.com/rthalley/dnspython/archive/refs/tags/v2.4.2.tar.gz
    9  ls -al
   10  tar xvf v2.4.2.tar.gz
   11  sudo apt-get install python3-dev
   12  sudo apt-get install build-essential
   13  ls -al
   14  cd dnspython-2.4.2/
   15  ls -al
   16  pip3 install --upgrade pip build
   17  sudo apt install python3-pip
   18  pip install --upgrade pip build
   19  python -m build
   20  python3 -m build
   21  sudo apt install python3.8-venv
   22  python3 -m build
   23  pip install dist/*.whl
   24  sudo apt-get update
   25  sudo apt-get install intelmq

```
 
![image](https://github.com/certtools/intelmq/assets/119335775/56ca0a0c-5242-4f96-950a-8e6346a9d669)

Therefore I do not think it is possible to install on Ubuntu 20.04 given [Ubuntu package version](https://packages.ubuntu.com/focal/python3-dnspython)

Any help appreciated.

**Comment by kamil-certat** [comment]
Hey, let's try using the stable repository: https://download.opensuse.org/repositories/home:/sebix:/intelmq/xUbuntu_20.04/ As you can see, it has also the DEB package for dnspython. You have decided to use the unstable repository, which does not have it included. 

If you wish to use/test the newest IntelMQ regardless of the stable releases, I'd recommend installing in a virtualenv with pip.

**Comment by Paul-Dutot** [comment]
Thankyou for helping find my mistake. BTW the unstable appears first in a search for intelmq

**Comment by sebix** [comment]
> Thankyou for helping find my mistake. BTW the unstable appears first in a search for intelmq

Although I don't think we have an influence on search result order: Which search (engine, keywords)?
