### ISSUE TITLE
Missing docs for SMTP batch output (lost in conversion)

### ISSUE THREAD

**Issue by sebix** [certtools/intelmq#2438]
The old docs had documentation for the SMTP batch output (introduced by #2253)
https://intelmq.readthedocs.io/en/latest/user/bots.html#intelmq-bots-outputs-smtp-batch-output
but the new docs at https://docs.intelmq.org/develop/user/bots/ don't contain this section.

ping @gethvi

**Comment by gethvi** [comment]
Thanks for noticing, my bad. I don't know how I missed it. Fix incoming.
