### ISSUE TITLE
Clear a queue

### ISSUE THREAD

**Issue by Brandl** [certtools/intelmq#244]
Hello,

maybe I'm have overlooked something, but I've not found a convenient way, to clear a queue.

Possible usecases:
- unintentionally fetch garbage, which then keeps stuck somewhere in the pipe
- debugging, when the original collector format or the parser changes and old data is still in the queue
- aborting processing, when it would clearly take too long

Therefore I would suggest to have a clear command in intelmqctl and a "clear queue" button in the "monitor"-tab of the Manager.

**Comment by sebix** [comment]
2a6fea48ee0f8587d158cf2e72fc6f5e4da46c3c implements the functionality for `intelmqctl` with `--clear queue`.

**Comment by SYNchroACK** [comment]
@sebix looks really awsome. Create a pull req and I will accept it!

**Comment by sebix** [comment]
Can be closed when PR is merged, which implements the intelmqctl part. For the part in intelmq-manager, I created an issue there: certtools/intelmq-manager#54

**Comment by sebix** [comment]
This can be closed now.

**Comment by SYNchroACK** [comment]
@sebix thanks
