### ISSUE TITLE
Shadowserver parser docs missing part on feedname

### ISSUE THREAD

**Issue by gethvi** [certtools/intelmq#2455]
Shadowserver parser docs says:

> A list of possible values of the feedname parameter can be found in the table below in the column "Report Type".

This is no longer true. I understand that the feedname mapping is now gathered from the schema, but still the user doesn't know what feedname he should use for configuration.

If we want to keep the possibility for "fixed report type" we should provide the user with easily accessible values he can use for `feedname` parameter.

**Comment by sebix** [comment]
@elsif2

**Comment by elsif2** [comment]
The `feed_name` for each report type is included in the schema:

```
   "population_msmq" : {
      "constant_fields" : {
         "classification.identifier" : "accessible-msmq",
         "classification.taxonomy" : "vulnerable",
         "classification.type" : "potentially-unwanted-accessible",
         "protocol.application" : "msmq"
      },
      "feed_name" : "Accessible-MSMQ",
      "file_name" : "population_msmq",
```
