### ISSUE TITLE
Look for 'FIXME'

### ISSUE THREAD

**Issue by SYNchroACK** [certtools/intelmq#246]

**Comment by sebix** [comment]
egrep -i 'todo|fixme|implemented' * -R

**Comment by SYNchroACK** [comment]
@sebix the idea is to fix the code where we found [FIXME]

**Comment by sebix** [comment]
I know. Just extended the list of keywords.

**Comment by bernhardreiter** [comment]
Checking size of the problem:
commit 6399e3a9ad44398f0928defd8ceb3fea10a735b3
Date:   Tue Oct 11 14:30:29 2016 +0200
egrep -i -R 'todo|fixme|implemented' *  | wc -l
115

**Comment by sebix** [comment]
On 10/12/2016 01:37 PM, Bernhard E. Reiter wrote:
>
> Checking size of the problem:
> commit 6399e3a
> <https://github.com/certtools/intelmq/commit/6399e3a9ad44398f0928defd8ceb3fea10a735b3>
> Date: Tue Oct 11 14:30:29 2016 +0200
> egrep -i -R 'todo|fixme|implemented' * | wc -l
> 115
>
Many of these can be postponed to later releases. Needs to be decided
per case.

**Comment by bernhardreiter** [comment]
What is the decision criteria? (I wonder if I or others could help to decide this, otherwise we are looking at 115 time the decision time plus 115 times the time to come up with a fix.)

**Comment by sebix** [comment]
closing this as it is not useful. if there's a todo which needs to be discussed or is important, open separate issues
