### ISSUE TITLE
Generic stop method

### ISSUE THREAD

**Issue by SYNchroACK** [certtools/intelmq#248]
* stop method should be generic to fit the kill method from @helderfernandes1279

**Comment by sebix** [comment]
Currently the `stop()` method kills the bot with `exit(-1)`. I would like to split the functionality into `stop` and `terminate`. While `stop` does not exit the bot, `terminate` will exit, but also disconnects all pipelines, so it can be used in exception handling. Stop can then be extended, like it is done in #197

**Comment by SYNchroACK** [comment]
Ok, make sense. Send a pull request to discuss minimal details with you. ;)
Thank you @sebix

**Comment by sebix** [comment]
9a82ce8 splits the functionality in stop() and terminate(). Stop currently closes the pipelines and can be extended by derived classes (using super) to close other connections. If `exit_on_error` is true (default), terminate will be called which exits, this is disabled for tests.

**Comment by SYNchroACK** [comment]
merged

**Comment by sebix** [comment]
Keep this issue in mind for #345
