### ISSUE TITLE
On Windows 10 using Msys2 / Mingw64 - ModuleNotFoundError: No module named 'grp'

### ISSUE THREAD

**Issue by bill-e-ghote** [certtools/intelmq#2483]
IntelMQ seems to be of a *nix slant in this environment. I don't know of any provider for this module. Please advise.
```
$ intelmqsetup.exe --help
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:/Users/user/Wares/Python/bin/intelmqsetup.exe/__main__.py", line
4, in <module>
  File "C:/Users/user/Wares/Python/lib/python3.11/site-packages/intelmq/bin
/intelmqsetup.py", line 27, in <module>
    from grp import getgrnam
ModuleNotFoundError: No module named 'grp'
```

**Comment by kamil-certat** [comment]
Hey,

It's a standard module available on *nix systems: https://docs.python.org/3/library/grp.html

I have to say, Windows isn't in scope of supported systems, and although you may overcome this particular problem by modifying the `intelmqsetup.py` script, I won't expect IntelMQ to work on Windows. We rely heavily on e.g. process management, which may behave differently on Windows.

If you're using Windows, I would suggest trying WSL (Windows Subsystem for Linux) or, the best option, use a virtual machine with one of [supported systems](https://docs.intelmq.org/latest/admin/installation/linux-packages/#supported-os)

**Comment by bill-e-ghote** [comment]
I'm using a work laptop without Admin privs in a tightly regulated $dayjob, so WSL on this system is not likely. I have it running on another work system, will give it a try there. Thanks for the response and advice.

Also, I would expect this issue to be closed / cancelled as not supported. Thanks.

**Comment by sebix** [comment]
Already documented at https://intelmq.readthedocs.io/en/develop/user/installation.html#base-requirements
