### ISSUE TITLE
Improve DevGuide

### ISSUE THREAD

**Issue by SYNchroACK** [certtools/intelmq#251]
* write in dev guide the rules for keus names ('.' , no list and hierarchy)

**Comment by sebix** [comment]
Coding-Rules/Indentation, Coding-Rules/Variable Names and Coding-Rules/Coding Style can be removed as PEP8 is linked.

> Any file name or folder name MUST: be represented with uppercase

Clarify that the variable name is meant.

> Class Names

> Class name of the bot (ex: PhishTank Parser) must correspond to the type of the bot (ex: Parser). Example:

>     class Expert(Bot):

I suggest `ExampleBot(Bot):`, this is currently used, also in the last section of the document.

>
-  Check taxonomy expert bot
-  Check arbor parser bot

Links are broken

**Comment by SYNchroACK** [comment]
On Thu, Aug 20, 2015 at 10:43 AM, Sebastian <notifications@github.com>
wrote:

> Coding-Rules/Indentation, Coding-Rules/Variable Names and
> Coding-Rules/Coding Style can be removed as PEP8 is linked.
>
I know but it to underline the people that never read pep8.


> Any file name or folder name MUST: be represented with uppercase
>
> Clarify that the variable name is meant.
>
Didnt understand...


> Class Names
>
> Class name of the bot (ex: PhishTank Parser) must correspond to the type
> of the bot (ex: Parser). Example:
>
> class Expert(Bot):
>
> I suggest ExampleBot(Bot):, this is currently used, also in the last
> section of the document.
>

Fixed.


>
>    - Check taxonomy expert bot
>    - Check arbor parser bot
>
> Links are broken
>
Fixed


> —
> Reply to this email directly or view it on GitHub
> <https://github.com/certtools/intelmq/issues/251#issuecomment-132957126>.
>



-- 
 Tomás Lima* ,    * »-«* SYNchroACK *»-«

**Comment by sebix** [comment]
On 08/24/2015 01:18 AM, Tomás Lima wrote:
> On Thu, Aug 20, 2015 at 10:43 AM, Sebastian <notifications@github.com>
> wrote:
>
> > Coding-Rules/Indentation, Coding-Rules/Variable Names and
> > Coding-Rules/Coding Style can be removed as PEP8 is linked.
> >
> I know but it to underline the people that never read pep8.
Repetition and duplicate content bloats the document. That irrelevant
information for the project itself. To enforce PEP8 it is not relevant
that these rules are repeated in the project's own dev Guide. It's more
important that the code base itself obeys PEP8 and that all PR have to
be PEP8 conform (If they are not, point it out to the contributors by
commenting the code).
> > > Any file name or folder name MUST: be represented with uppercase
> >
> > Clarify that the variable name is meant.
> >
> Didnt understand...
The variable names should be uppercase, not the file or folder names.

**Comment by SYNchroACK** [comment]
On Mon, Aug 24, 2015 at 8:04 AM, Sebastian <notifications@github.com> wrote:

> On 08/24/2015 01:18 AM, Tomás Lima wrote:
> > On Thu, Aug 20, 2015 at 10:43 AM, Sebastian <notifications@github.com>
> > wrote:
> >
> > > Coding-Rules/Indentation, Coding-Rules/Variable Names and
> > > Coding-Rules/Coding Style can be removed as PEP8 is linked.
> > >
> > I know but it to underline the people that never read pep8.
> Repetition and duplicate content bloats the document. That irrelevant
> information for the project itself. To enforce PEP8 it is not relevant
> that these rules are repeated in the project's own dev Guide. It's more
> important that the code base itself obeys PEP8 and that all PR have to
> be PEP8 conform (If they are not, point it out to the contributors by
> commenting the code).


@aaron can you give your feedback?


>
> > > > Any file name or folder name MUST: be represented with uppercase
> > >
> > > Clarify that the variable name is meant.
> > >
> > Didnt understand...
> The variable names should be uppercase, not the file or folder names.
>
>
https://github.com/certtools/intelmq/commit/dec3e680b70beca42dea317e71cddc5ba3f94122#diff-f337315a2462f5b7d3237f21321b412d

uppercase was wrong, is lowercase.
We are saying that is mandatory to use file and folder names in lowercase.
Its our approach... the idea is to have everything in same "format".
@aaron, do you agree?
