### ISSUE TITLE
(docs) debian and ubuntu installation instructions

### ISSUE THREAD

**Issue by aaronkaplan** [certtools/intelmq#2517]
- The Debian Installation instructions are missing since the change to mkdocs. Previously the section was structured differently: https://github.com/certtools/intelmq/blame/d624988693894e71defdd8b18618f7af98be852c/docs/user/installation.rst#L43
- Ubuntu installation instructions seem to be missing (which repo to add, GPG key installation ,etc )
- People still end up at the wrong documentation site (readthedocs!) Can we automatically redirect them to docs.intelmq.org ?

**Comment by sebix** [comment]
> People still end up at the wrong documentation site (readthedocs!) Can we automatically redirect them to docs.intelmq.org ?

I moved this to https://github.com/certtools/intelmq/issues/2518 as this is independent of the code and the IntelMQ release.
