### ISSUE TITLE
shadowserver documentation: if reports is "", things don't work

### ISSUE THREAD

**Issue by aaronkaplan** [certtools/intelmq#2521]
It was confusing for a user to have "reports": "" in the config but then he would not get any reports.
Instead the reports key must not be present at all, to get all reports. That's confusing and might have to be better explained in the documentation.

**Comment by sebix** [comment]
IMHO the bot should behave the same with
- a parameter not set
- a parameter set with an empty string (or any other suitabe type and an empty value)
