### ISSUE TITLE
Improve ZMQ pipeline

### ISSUE THREAD

**Issue by SYNchroACK** [certtools/intelmq#253]

**Comment by SYNchroACK** [comment]
ZMQ pipeline should reproduce the same behavior as Redis with completly transparency for the user, except the configuration option to select which type of pipeline is should be used.

The reason to have ZMQ pipeline is because in some scenarios, we need to process huge amounts of information in real-time. ZMQ is a good solution for that.

**Comment by sebix** [comment]
That should be the docstring of ZMQ :)

However, what improvements do you address with this issue?

**Comment by SYNchroACK** [comment]
process huge amounts of information in real-time

**Comment by aaronkaplan** [comment]
But the current bottleneck is not the pipeline mechanism. It is the DNS lookup to Cymru. 



---
Mobile

**Comment by Rafiot** [comment]
You may want to give a try to my multiproc queue module :)

**Comment by aaronkaplan** [comment]
On Aug 10, 2015, at 8:33 PM, Raphaël Vinot <notifications@github.com> wrote:

> You may want to give a try to my multiproc queue module :)
> 

*hint hint* ;-)
Yes!
Sure. Hint accepted :)

Just FYI: at the moment we  are rather focussing on integrating intelmq with our internal workflow and then we'll revise performance issues. They are not relevant for us *right now*.
(but will come later).

Best,
a.

**Comment by SYNchroACK** [comment]
That is true if you havê that kind of experts enabled. :)
No dia 10/08/2015 18:21, "AaronK" <notifications@github.com> escreveu:

> But the current bottleneck is not the pipeline mechanism. It is the DNS
> lookup to Cymru.
>
>
>
> ---
> Mobile
>
>

**Comment by Rafiot** [comment]
As long as perf is not a problem, we are good :) I will work on it in a branch soon-ish

**Comment by sebix** [comment]
I removed the zmq implementation for now, it's still incomplete. Needs to be done in future versions, *after* 1.0

If someone want's to work on it, just revert the commit caecef6e93a419480f6b9d49c489c4a0d66e9ab2 and complete it.

**Comment by aaronkaplan** [comment]
> On 03 Feb 2016, at 15:59, Sebastian <notifications@github.com> wrote:
> 
> I removed the zmq implementation for now, it's still incomplete. Needs to be done in future versions, after 1.0
> 
> If someone want's to work on it, just revert the commit caecef6 and complete it.

makes sense.
Did you update the documentation as well?
https://github.com/certtools/intelmq/search?utf8=✓&q=zeromq&type=Code

**Comment by sebix** [comment]
yes.

**Comment by wagner-certat** [comment]
zeromq does not guarantee delivery and it may loose messages during high load. I don't think it is a good choice.

**Comment by aaronkaplan** [comment]
I believe we can close this one, zmq drops stuff. Not a good choice for our purposes right now. Might want to revisit later in a different use-case when dropped messages get re-sent anyway again in the future (such as with f.ex. DNS queries).
