### ISSUE TITLE
Harmonization - message.add method improvements

### ISSUE THREAD

**Issue by SYNchroACK** [certtools/intelmq#254]
Method message.add should have a parameter 'force=True/False' - this flag possibility to define which keys will force the bot to fail or continue without raise any error.
_Example:_
- If 'source.ip' has some problem, the event should follow the normal
  procedure of error handling
- If 'source.asn' has some problem, since its not an important key, the
  event can ignore the value and continue the process

**Comment by sebix** [comment]
I think - without any experience on real world setups - that bots should fail if they behave wrongly.

**Comment by wagner-certat** [comment]
Is this still relevant?

**Comment by SYNchroACK** [comment]
No. It's already implemented

**Comment by SYNchroACK** [comment]
see #778 for more details.
