### ISSUE TITLE
intelmqctl improvements

### ISSUE THREAD

**Issue by SYNchroACK** [certtools/intelmq#257]
- load parameters from all configurations
- bot.py must has static methods to load configurations and then intelmqctl will be able to use them

use the following code: https://github.com/certtools/intelmq/blob/v1.0-final/tests/intelmqctl/intelmqctl.py

**Comment by sebix** [comment]
The methods used by `Bot` class use `utils.load_configuration` to load it and then filter out the interesting section. Using the utility function is easier here and has less overhead.

> load parameters from all configurations

Currently, `RUNTIME_CONF_FILE` is not used, thus there's no functionality needing it.

**Comment by sebix** [comment]
I think this should be fixed in my fork

**Comment by SYNchroACK** [comment]
@sebix is everything mentioned in this issue fixed by your pull req?

**Comment by sebix** [comment]
> * load parameters from all configurations
Default, System, pipeline, runtime and startup are read
> bot.py must has static methods to load configurations and then intelmqctl will be able to use them
I commented above that I don't see the sense here. The functions in utils are used now.

**Comment by SYNchroACK** [comment]
ok cool.
