### ISSUE TITLE
Guess value type utility (source.ip', 'source.fqdn', 'source.url')

### ISSUE THREAD

**Issue by SYNchroACK** [certtools/intelmq#258]
Some keys like 'source.ip', 'source.fqdn', 'source.url' are really crucial for the event context.
When parse fail becasue the ip collumn from the source has an URL, its hard to have good code to handle this and put back the URL from IP collumn to source.url key in event. For this reason, we should create a util that try to guess what type is the value, but must follow an order:
- IPAddress check
- URL check
- FQDN check

Note: it also applies to 'destination.<sub-key>

**Comment by wagner-certat** [comment]
Is this still valid with #841 @SYNchroACK?

**Comment by SYNchroACK** [comment]
> Is this still valid with #841 @SYNchroACK?

With the new changes that you developed in #841 applied to all bots, this issue should be complete with success.
