### ISSUE TITLE
Should we force to have both proxies?

### ISSUE THREAD

**Issue by mauroasilva** [certtools/intelmq#266]
In the lib of the http collector we have:

``` python
...
    if http_proxy and https_proxy:
        proxy = urllib2.ProxyHandler({'http': http_proxy, 'https': https_proxy })
...
```

Should we force to have both proxies or does it make sense to test one of them, like this:

``` python
...
    if http_proxy or https_proxy:
        proxy = urllib2.ProxyHandler({'http': http_proxy, 'https': https_proxy })
...
```

**Comment by aaronkaplan** [comment]
Yes, we should have both please. Otherwise you have the behaviour that you for some download need httpS:// but you only tested for http://. And then it does not work.

**Comment by SYNchroACK** [comment]
@mauroasilva any news regarding this issue?

**Comment by vince-nayal** [comment]
Hi,

I had the same "issue"  (now in lib/bot.py)

Should/could i make a PR to let the user know that he has to set either both or none ?

Something like : 
``` Python
if self.parameters.http_proxy and self.parameters.https_proxy:
    self.proxy = {'http': self.parameters.http_proxy,
                  'https': self.parameters.https_proxy}
else:
    if self.parameters.http_proxy and self.parameters.https_proxy:
        self.logger.warning('Only {}_proxy seems to be set.'
                            'Both http and https proxies must be set'
                            .format('http' if self.parameters.http_proxy else 'https'))
    self.proxy = None
```

**Comment by sebix** [comment]
What happens if one of them is undefined?

**Comment by vince-nayal** [comment]
It ignores the defined one and sets proxy to None

**Comment by sebix** [comment]
Pushed a fix to master. `intelmqctl check` is now also capable of finding this issue.

**Comment by vince-nayal** [comment]
Thanks !
