### ISSUE TITLE
Bot development flow.

### ISSUE THREAD

**Issue by e3rd** [certtools/intelmq#272]
Hi, I am just developing output bot that divides the messages by abuse mail to the lists and once a day sends them.

1) Where should I place the template text for mail. In /opt/intelmq/var/lib/bots/_output-bot_/ , or /opt/intelmq/etc/_output-bot_/ ?

2) Then, I'd like to ask if I am doing the development in the right way, if I am not breaking the project coding standards.
I did it like this:
Mail bot system consists of two modules, output_gather.py (Mail Gather bot) and output_send.py (Mail Send bot). The first is the recipient of pipeline queue, full of messages. In every message, it finds "abuse_mail" field (abuse@example.com) and in redis, it adds an item to the list named "mail:abuse@example.com".
Once a day, Mail Send bot is launched (thanks to rate_limit=84000). It doesn't receive any queue because everything is prepared in redis. It takes all the lists with key "mail:*" and sends it by SMTP.

Note there is no pipeline between Mail Gather and Mail Send, is this okay?

3) For redis connection, I use self.cache as I've seen in other bots. But as I use _list_ data structures, self.cache methods don't suffice. Hence, I use directly self.cache.redis.rpush for list creation and self.cache.redis.lrange for getting list.
Is this okay, or is this pig way?

Thanks a lot for your observation,
 Edvard

**Comment by SYNchroACK** [comment]
Hi @e3rd , thank you very much to raise these questions. As far I can see, the feature that you propose is interesting and I support it although https://github.com/certtools/intelmq-mailer will be updated to fit your needs.

Regarding your questions:
1) /opt/intelmq/var/lib/bots/output-bot/

2) Yap, it breaks the concept. I would suggest something like http://stackoverflow.com/questions/16325039/python-alarm-clock

3) Yes, is not good to access directly.

@e3rd if you want, share the code and I will try to give you some feedback.

again, thank you ;)

**Comment by e3rd** [comment]
2) You mean there should be a thread with a infinite loop that once a day calls the function to send the e-mails? It might be more effective to use system cron.

3) If it's not good to access self.cache.redis to store lists, I'd have to map the lists to standard key value pairs by myself (which is non-efective and we waste the power of redis). Or we may not use redis at all and store the lists in the memory of the bot. (But when system restarts, the data are lost.) Or we may store them to files. I haven't come up with other idea yet.
Intelmq-mailer project should serve as my Mail Send bot (so that Mail Gather would directly give the data to Intelmq-mailer)?

Draft version of the code is in here: https://github.com/CZ-NIC/intelmq/tree/output-bot/intelmq/bots/outputs/mail , two files only, output_gather.py and output_send.py .

Thanks a lot for your time!!
(I'll be back here by 3rd Aug, no rush.)
 E2rd

**Comment by SYNchroACK** [comment]
2) Agree. Cron is also a possible solution ;)

3) "Intelmq-mailer project should serve as my Mail Send bot (so that Mail Gather would directly give the data to Intelmq-mailer)?" Well, if you want to use intelmq-mailer you just need to use mongodb output bot.... 

I think we will have a new solution in near future to fit your needs... inmeanwhile, you can have that solution but keep in mind that breaks the intelmq concept... :S

**Comment by wagner-certat** [comment]
For cron support: see #464

Are there any other open questions?

**Comment by SYNchroACK** [comment]
no answer received
