### ISSUE TITLE
DCU Parser linked in tests, but does not exist

### ISSUE THREAD

**Issue by sebix** [certtools/intelmq#276]
First line of `intelmq/tests/bots/parsers/dcu/lib.py`:

```
from intelmq.bots.parsers.dcu import lib
```

But there's no dcu directory in `intelmq/bots/parsers`.

**Comment by SYNchroACK** [comment]
it was removed

**Comment by aaronkaplan** [comment]
Tomas, we need the DCU bot for us. Why was it simply removed?

**Comment by SYNchroACK** [comment]
It was removed because its a private feed. We need to define between us the policy for that kind of feeds. If you think its better to put here, its ok, but it will give possibility to foreign entities understand which private feeds you are using since you used your account to commit the code.

**Comment by sebix** [comment]
We already have some bots requiring special rights/granted permissions: Alienvault OTX, Fraunhofer DGA, MalwarePatrol Dans Guardian, MaxMind GeoIP, PhishTank, Spamhaus Cert

**Comment by aaronkaplan** [comment]
Tomas, sorry that's not true. DCU is on github (see CIRCL). So, no it is not private. The password for access is private. Please put it back, thank you.

**Comment by SYNchroACK** [comment]
In that case, it will give the possibility to foreign entities to understand which private feeds you are using since you used your account to commit the code.

If you dont have any problem with that, please convert the bot to new version and merge it. Its fine ;)

**Comment by wagner-certat** [comment]
DCU is superseded by CTIP and we have the latter one
