### ISSUE TITLE
MISP Parser Bot

### ISSUE THREAD

**Issue by elhoim** [certtools/intelmq#279]
[MISP](https://github.com/MISP/MISP/) is a tool that it becoming quite popular to share threat intel or receive feeds from partners.

Could you add a parser for it? I suppose the URL collector is sufficient to be able to download data from multiple instances.

**Comment by aaronkaplan** [comment]
On Aug 10, 2015, at 9:58 AM, David André <notifications@github.com> wrote:

> MISP is a tool that it becoming quite popular to share threat intel or receive feeds from partners.
> 
> Could you add a parser for it? I suppose the URL collector is sufficient to be able to download data from multiple instances.
> 

Hi David,

sure. We could. However, let me ask you: what and how much do you want to download from MISP and put into intelmq and where should it end up ?

Because downloading full events and even binary attachments and putting them into intelmq might be currently overkill... Just wondering.
Can you give me a use-case (for my understanding)?

Thanks,
a.

**Comment by elhoim** [comment]
I was thinking mostly IP, domain, hostname, URLs attribute types; just as most blacklists implemented in intelMQ

**Comment by aaronkaplan** [comment]
On Aug 10, 2015, at 10:38 PM, David André <notifications@github.com> wrote:

> I was thinking mostly IP, domain, hostname, URLs attribute types; just as most blacklists implemented in intelMQ

I see. Yes, makes sense.

**Comment by SYNchroACK** [comment]
How do you want to download from MISP?

**Comment by aaronkaplan** [comment]
I Would say via the pymisp API or the rest interface directly?

---
Mobile

**Comment by elhoim** [comment]
If you do the REST interface directly and your normal URL collector then you have one less dependency.
And then you can use whatever global export format that suits you best: CSV, XML, or individual text files per data type.

**Comment by robcza** [comment]
@aaronkaplan is this anything you plan in near future or is MISP integration completely dead at the moment?

**Comment by aaronkaplan** [comment]
On Mon, Mar 28, 2016 at 02:20:41PM -0700, Robert Šefr wrote:
> @aaronkaplan is this anything you plan in near future or is MISP integration completely dead at the moment?
> 

YEs, let's have a MISP expert (for example IP to MISP UUID or domain to
MISP UUID or malware hash to MISP UUID) bot.
We could implement this for example at the hackathon in April?


Best,
a.

> ---
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub:
> https://github.com/certtools/intelmq/issues/279#issuecomment-202584994

-- 
Physicist are there to find the laws of nature. Engineers are there to work around them

**Comment by dmth** [comment]
AFAIK a MISP Parser does exist:
https://github.com/certtools/intelmq/tree/master/intelmq/bots/parsers/misp

Can somebody revise (and close?) this issue?
