### ISSUE TITLE
Data Harmonization - MISP_id

### ISSUE THREAD

**Issue by elhoim** [certtools/intelmq#280]
Just wanted to let you know that MISP ID are not a good way to uniquely identify an event, since those IDs are generated sequentially per MISP instance. Which if you re-install and re-import data from other instances, you may (and most probably will) end up with IDs in a different order.
That's why MISP uses, mostly internally, UUIDs to identify and syncrhonize events.

**Comment by adulau** [comment]
+1 UUIDs are the ones to use.

**Comment by aaronkaplan** [comment]
On Aug 10, 2015, at 10:53 AM, Alexandre Dulaunoy <notifications@github.com> wrote:

> +1 UUIDs are the ones to use.
> 

got it.

**Comment by SYNchroACK** [comment]
https://github.com/certtools/intelmq/blob/master/intelmq/conf/harmonization.conf#L165

**Comment by elhoim** [comment]
UUIDs are not integers, they are bigger than that.
In the DB they are represented as varchar(40), and here is an example of a value taken from an event:
**4f97a63e-e1b0-482a-9526-c059ff32448e**

**Comment by sebix** [comment]
Oops! Will fix that this week :)
