### ISSUE TITLE
Pipeline: give unicode or Ascii?

### ISSUE THREAD

**Issue by sebix** [certtools/intelmq#281]
The Pipeline brokers redis and zeromq (sockets) are using bytes internally (python2 strings), but the input could be unicode (python3 strings).

There are two possibilities:
 * Do the conversion in the Pipeline classes. Would reduce the code in the bots.
 * Collectors and Parsers have to decide on it's own what encoding they want to use in their queues. More flexibility for bots and less overhead.

**Comment by sebix** [comment]
Additionally, it should be clearly defined how Unicode/ASCII input is handled in all steps. #278 shows a bug in Harmonization.

**Comment by SYNchroACK** [comment]
I think 'Do the conversion in the Pipeline classes. Would reduce the code in the bots.' is the best option.  Lets do it?

**Comment by sebix** [comment]
I think it's best and easiest to use unicode in the bots. They should always send unicode to the pipeline an receive unicode from it.

There are already functions to do this conversion in utils. I would put the conversion in the Message class in (un)serialize functions:

    return json.dumps(self) # FIXME: dont know if json take care of encoding issues

`json.dumps` gives string both in Python2 and Python3, but they differ (bytes and unicode). So this won't work in Python3 anymore.
