### ISSUE TITLE
CleanMX Parser

### ISSUE THREAD

**Issue by SYNchroACK** [certtools/intelmq#283]
CleanMX Feed change from CSV to XML. Bot need to be rewritten to support the new format.

**Comment by SYNchroACK** [comment]
this issue is not correct. CleanMX didnt change the format.

**Comment by sebix** [comment]
I thought you want to change from CSV: http://support.clean-mx.de/clean-mx/xmlphishing?response=alive&format=csv to XML: http://support.clean-mx.de/clean-mx/xmlphishing?response=alive&format=xml
And the same for viruses.
