### ISSUE TITLE
Travis-CI -  use automatic builds + test and code coverage

### ISSUE THREAD

**Issue by sebix** [certtools/intelmq#288]
Use github services to use continuous integration systems like [Travis-CI](https://travis-ci.com) for automated builds and check tests. 

Optionally use a tool like [Coverity](https://scan.coverity.com/travis_ci), [Coveralls](https://coveralls.io/) or [CodeClimate](http://docs.travis-ci.com/user/code-climate/) to check coverage (Tracking code lines that are covered by checks).

See a travis-ci example in action: https://github.com/scipy/scipy/pull/5146
Another example of integrated coverage checks: https://github.com/django-compressor/django-compressor/blob/develop/README.rst#django-compressor

**Comment by sebix** [comment]
Continuous integration is implemented now, what do you think of coverage reports?

**Comment by aaronkaplan** [comment]
Great idea!

However, IMHO time is running very quickly an we need still the cert.at CLI tool. I think we should not forget the coverage tests but do them after re CLI tool. 
But maybe you have a different/ better idea and let's discuss. 

A.

---
Mobile

**Comment by SYNchroACK** [comment]
its done, right?

**Comment by sebix** [comment]
No, where's the coverage test?

**Comment by sebix** [comment]
Fixed by #441
