### ISSUE TITLE
Documentation - Bot error behavior undefined.

### ISSUE THREAD

**Issue by sebix** [certtools/intelmq#289]
Documentation lacks information how Bots behave with different settings in error handling:
* `error_procedure`
* `error_max_retries`
* `error_dump_message`
* `error_retry_delay` and others.

Unclear behavior:
* When does the bot stop, and when does the bot retry?
* What is counted as error?
* What does happen to the messages in process? (acknowledge, dump)
* What happens with open pipelines?

**Comment by SYNchroACK** [comment]
## error_log_message

**Description:** [FIXME]
**Values:** [FIXME]



## error_log_exception

**Description:** [FIXME]
**Values:** [FIXME]



## error_procedure

**Description:** in case of an error, this option defines the procedure that bot will adopt.
**Values:** retry, pass

* 'retry' - retry X times, defined in 'error_max_retries' option with a delay between retries defined at 'error_retry_delay' option. If bot reach 'error_max_retries' value, bot will remove the message from pipeline and stop. If the option 'error_dump_message' is enable, the bot will dump the removed message to the dump log.

* 'pass' - will pass to the next message, removing from pipeline the current message. If the option 'error_dump_message' is enable, the bot will dump the removed message to the dump log.



## error_max_retries

**Description:** in case of an error and the value of the 'error_procedure' option is 'retry', bot will try to start processing the current message X times defined at 'error_max_retries' option.
**Values:** (integer value)



## error_retry_delay

**Description:** [FIXME]
**Values:** (integer value)



## error_dump_message

**Description:** [FIXME]
**Values:** true, false



## exit_on_stop

**Description:** [FIXME]
**Values:** true, false



## load_balance

**Description:** [FIXME]
**Values:** true, false



## broker

**Description:** [FIXME]
**Values:** redis, zeromq (under development)

**Comment by SYNchroACK** [comment]
@sebix in your next pull req that change anything in documentation, it could be useful to add the above information. ;)

**Comment by sebix** [comment]
When I push it, I will replace the todos with actual text.
