### ISSUE TITLE
DateTime timezone handling in harmonization

### ISSUE THREAD

**Issue by sebix** [certtools/intelmq#290]
The current implementation fails if the given time string has no timezone information. The code:

    value = dateutil.parser.parse(value)
    value = value.astimezone(pytz.utc)
    value = value.isoformat()

The second line will fail if value is e.g. of format `20150101` with:

    ValueError: astimezone() cannot be applied to a naive datetime

Recommended way to convert timezones is:

    value = pytz.utc.localize(value)

But this again assumes, that UTC is used. The question arises if we can always assume UTC for dates in collected data?

The Malware Domains parser will fail because of this bug.

**Comment by aaronkaplan** [comment]
---
Mobile


> On 18.08.2015, at 10:04, Sebastian <notifications@github.com> wrote:
> 
> The current implementation fails if the given time string has no timezone information. The code:
> 

In log files we need time zone info! Log files without knowledge of the tz are useless and can be thrown away. 
> value = dateutil.parser.parse(value)
> value = value.astimezone(pytz.utc)
> value = value.isoformat()
> The second line will fail if value is e.g. of format 20150101 with:
> 
> ValueError: astimezone() cannot be applied to a naive datetime
> Recommended way to convert timezones is:
> 
> value = pytz.utc.localize(value)
> But this again assumes, that UTC is used. The question arises if we can always assume UTC for dates in collected data?
> 

No!

> The Malware Domains parser will fail because of this bug.
> 

Then the parser needs to be adapted so that it adds the tz info. (Based on external knowledge). 

Assume data within intelmq always has a tz. Without, it's an error.

**Comment by SYNchroACK** [comment]
100% agree with @aaronkaplan

**Comment by sebix** [comment]
So it is a bug in the Malware Domains Parser, it does not add TZ information.

**Comment by aaronkaplan** [comment]
On Aug 18, 2015, at 2:16 PM, Sebastian <notifications@github.com> wrote:

> So it is a bug in the Malware Domains Parser, it does not add TZ information.

That's correct!
And I think you also found a bug in the documentation. We need to have this in the developer guide as info. For a CERT, timestamp information without a time zone essentially makes the whole log line useless since we can not communicate properly about the event then anymore.

That's the background :)

**Comment by sebix** [comment]
> Time

> The time section lists all fields related to time information. This document requires that all the timestamps MUST be normalized to UTC. **If the source reports only a date, do not attempt to invent timestamps.**

All handlers do invent timestamps when there's only a date in the sources, as the data is otherwise invalid.

> observation_time

> The time **a source bot saw the event**. This timestamp becomes especially important should you perform your own attribution on a host DNS name for example. The mechanism to denote the attributed elements with reference to the source provided is detailed below in Reported Identity IOC.(ISO8660)

Currently, the observation time is added by parsers, not be collectors.

**Comment by SYNchroACK** [comment]
@sebix , in the future the time.observation should be added by collectors.

**Comment by sebix** [comment]
On 08/24/2015 12:03 AM, Tomás Lima wrote:
>
> @sebix <https://github.com/sebix> , in the future the time.observation
> should be added by collectors.
>
@aaronkaplan what do you think here?

Either the definition of `time.observation` changes or the bots who add it.

**Comment by SYNchroACK** [comment]
solved?

**Comment by sebix** [comment]
I at least corrected the timezone for one feed/parser, it may be necessary to do it for others also. Most use UTC, but not all.

**Comment by aaronkaplan** [comment]
On Aug 24, 2015, at 12:03 AM, Tomás Lima <notifications@github.com> wrote:

> @sebix , in the future the time.observation should be added by collectors.
But a collector did not split up the data yet and it's not the internal (JSON) format yet at that point.
Only after the parse. Therefore, only the parser can add time.observation IMHO.

It would be more accurate to have it at the collector, but he can't add that info (yet) at this stage IMHO.

Did I miss anything?

a.

**Comment by aaronkaplan** [comment]
On Aug 24, 2015, at 9:12 AM, Sebastian <notifications@github.com> wrote:

> On 08/24/2015 12:03 AM, Tomás Lima wrote:
> >
> > @sebix <https://github.com/sebix> , in the future the time.observation
> > should be added by collectors.
> >
> @aaronkaplan what do you think here?
> 
> Either the definition of `time.observation` changes or the bots who add it.

IMHO the parser can add it. And we can change the definition to say the parser adds it.

**Comment by sebix** [comment]
I do not understand your arguments. The retrieval date is a crucial information. Actually all citations must have a 'retrieved at ..' information, otherwise the citation is not valid.

Imagine the collector fetches data in the morning and the parser crashes. Parser is fixed two days later and you have the data of three days with the same `time.observation` date.

> IMHO the parser can add it. And we can change the definition to say the parser adds it.

We can have a `time.parsed` field, but I don't know why that should be relevant to anyone.

> But a collector did not split up the data yet and it's not the internal (JSON) format yet at that point. Only after the parse. Therefore, only the parser can add time.observation IMHO.

> It would be more accurate to have it at the collector, but he can't add that info (yet) at this stage IMHO.

I don't get the point. Why should the collector not be able to save the current time to the report?! It's the exact same code as in the parser: https://github.com/certtools/intelmq/blob/master/intelmq/bots/collectors/http/collector_http.py#L63

**Comment by aaronkaplan** [comment]
On Sep 2, 2015, at 5:21 PM, Sebastian <notifications@github.com> wrote:

> I do not understand your arguments. The retrieval date is a crucial information. Actually all citations must have a 'retrieved at ..' information, otherwise the citation is not valid.

> 
> Imagine the collector fetches data in the morning and the parser crashes. Parser is fixed two days later and you have the data of three days with the same time.observation date.


> 
> IMHO the parser can add it. And we can change the definition to say the parser adds it.
> 
> We can have a time.parsed field, but I don't know why that should be relevant to anyone.
> 
> But a collector did not split up the data yet and it's not the internal (JSON) format yet at that point. Only after the parse. Therefore, only the parser can add time.observation IMHO.
> 
> It would be more accurate to have it at the collector, but he can't add that info (yet) at this stage IMHO.
> 
> I don't get the point. Why should the collector not be able to save the current time to the report?! It's the exact same code as in the parser: https://github.com/certtools/intelmq/blob/master/intelmq/bots/collectors/http/collector_http.py#L63
> 

Ah!!! in the current version this seems to work because you have reports as well as events.
And a report is a container for events, now.


okay, I was still thinking in the old style of parsers/collectors. Back then the parser was the only one who could split up the data. There was no "report" container around the fetched data.

Got it, this way it will work to set it in the collector. Thx for the clarification and the pointer.
Yes, of course it is more accurate to set it in the collector. No question about that.

a.

**Comment by sebix** [comment]
> Ah!!! in the current version this seems to work because you have reports as well as events. And a report is a container for events, now.

No.
There is the Message class which has a features to hold values specified in harmonization.conf and also validates and sanitizes them.
Then the two classes Event and Report derived from Message. Event has two additional functions, hash and to_dict. The valid field names and types for each class are specified in the configuration.

The pipeline can handle Event and Report and everything derived from Message.

A Report is not a container for events. A report has 4 valid fields: `raw`, `feed.name`, `feed.url` and `time.observation`. An event has these four plus many other valid fields. But the content of `raw` does differ. While the `raw` of a Report has the full report, e.g. a full webpage, csv file or whatever. The `raw` of an event has e.g. one line of this file.

**Comment by aaronkaplan** [comment]
On Sep 3, 2015, at 9:35 AM, Sebastian <notifications@github.com> wrote:

> Ah!!! in the current version this seems to work because you have reports as well as events. And a report is a container for events, now.
> 
> No.
> There is the Message class which has a features to hold values specified in harmonization.conf and also validates and sanitizes them.
> Then the two classes Event and Report derived from Message. Event has two additional functions, hash and to_dict. The valid field names and types for each class are specified in the configuration.
> 
> The pipeline can handle Event and Report and everything derived from Message.
> 
> A Report is not a container for events. A report has 4 valid fields: raw, feed.name, feed.url and time.observation. An event has these four plus many other valid fields. But the content of raw does differ. While the raw of a Report has the full report, e.g. a full webpage, csv file or whatever. The raw of an event has e.g. one line of this file.
> 

I was probably looking at my old version of the repo. Damn.
But thx for the update.

**Comment by SYNchroACK** [comment]
@sebix can we close it?

**Comment by sebix** [comment]
> I at least corrected the timezone for one feed/parser, it may be necessary to do it for others also. Most use UTC, but not all.
