### ISSUE TITLE
UnitTests - reminder to not forget adding this later

### ISSUE THREAD

**Issue by aaronkaplan** [certtools/intelmq#291]
#159 and #282 deal with unit tests.

However, we still need tests for pipeline (Redis - is the connection up and running, can we send and receive data, etc) and other core parts. These tests should be done similarly to #282 (for example the test for utils/). However, the core tests can be done a bit later.

This issue is simply here to remind us that this still needs to be done and should not be forgotten.

**Comment by sebix** [comment]
- [ ] Pipelines need to have a defined behavior for bytes/unicode input.
 - [ ] Harmonization needs clear definitions of valid and invalid formats, which both have to be tested.
 - [ ] The bot class has some tests, covering only very basic functionality

**Comment by sebix** [comment]
- [] Add more input lines to process for parsers, currently only one line of data is used.

**Comment by sebix** [comment]
- [ ] Test if the Bots correctly call `self.acknowledge_message()`.

**Comment by sebix** [comment]
- [ ] All Message class methods needs to be tested with all types available in harmonization.py. See also bug fix in #305

**Comment by wagner-certat** [comment]
>  Tests for intelmqctl

See #691 

> All Message class methods needs to be tested with all types available in harmonization.py. See also bug fix in #305

Not sure what I meant here
