### ISSUE TITLE
Bot improvements

### ISSUE THREAD

**Issue by SYNchroACK** [certtools/intelmq#294]
1)
Add the following line to all bots:
```
from __future__ import unicode_literals
```

2)
All bot should handle None message, no one can do that.

3)
Remove the sys import from bot and add the 'import sys'

**Comment by sebix** [comment]
All parsers can now handle None with e1f39977d9ba483a8b95be2dbe1c1bac695ba545

**Comment by SYNchroACK** [comment]
all fixed with #296

**Comment by sebix** [comment]
No, not fully. The expert and output bots can't handle None yet.
