### ISSUE TITLE
IP harmonization issues

### ISSUE THREAD

**Issue by robcza** [certtools/intelmq#297]
@sebix is it possible that there is something broken in the harmonization.py script? Having problems with IP addresses, had to change something, anyway I'm not sure whether it is not an issue on my side; details here:
https://github.com/certtools/intelmq/commit/7a9aa2d5fa468a7353b8056256f86a12379b0116#commitcomment-12880190
https://github.com/certtools/intelmq/commit/7a9aa2d5fa468a7353b8056256f86a12379b0116#commitcomment-12880220

**Comment by sebix** [comment]
Confirmed, already have the fixes locally.

Currently working on tests for harmonization and the tests for parser bots :)

**Comment by robcza** [comment]
ok, will wait for you pull request to fix it, thank you for the info
:heart:

**Comment by SYNchroACK** [comment]
done.
