### ISSUE TITLE
CERT-EU Malicious URLs Parser and Collector Missing

### ISSUE THREAD

**Issue by sebix** [certtools/intelmq#301]
BOTS file includes:

        "CERT-EU Malicious URLs": {
            "description": "CERT-EU Malicious URLs Parser is the bot responsible to parse the report and sanitize the information.",
            "module": "intelmq.bots.parsers.certeu.parser_malicious_urls",
            "parameters": {
            }

There's neither such a module and nor a matching collector.

**Comment by SYNchroACK** [comment]
Since its a private feed, we decided to remove it from the public repo. We are evaluating how to proceed

**Comment by SYNchroACK** [comment]
Of course, we should remove from BOTS too

**Comment by SYNchroACK** [comment]
fixed

**Comment by antoinet** [comment]
Were there any further discussions on how to go about private feeds? CERT-EU will change its format on August 20th, will probably be adapting the old Bot to accommodate the changes.

**Comment by wagner-certat** [comment]
There are some private feeds documented currently in feeds.yaml / Feeds.md.
