### ISSUE TITLE
HPFeeds collector missing

### ISSUE THREAD

**Issue by sebix** [certtools/intelmq#302]
BOTS file includes in parser section:

        "HPFeeds": {
            "description": "HPFeeds Parser is the bot responsible to parse the report and sanitize the information.",
            "module": "intelmq.bots.parsers.hpfeeds.parser",
            "parameters": {
            }
        },

But there is no corresponding Collector.

**Comment by SYNchroACK** [comment]
True. The code was not converted to the current version and needed a huge review. Its available in v0.9 version and in future if someone need it, we will convert it...

**Comment by SYNchroACK** [comment]
and yes, we should remove from BOTS

**Comment by SYNchroACK** [comment]
fixed
