### ISSUE TITLE
Missing ShadowServer Collectors

### ISSUE THREAD

**Issue by sebix** [certtools/intelmq#303]
2 Parsers exist in BOTS file, however, there's no collector.

        "ShadowServer Chargen": {
            "description": "ShadowServer Chargen Parser is the bot responsible to parse the report and sanitize the information.",
            "module": "intelmq.bots.parsers.shadowserver.parser_chargen",
            "parameters": {
            }
        },
        "ShadowServer Drone": {
            "description": "ShadowServer Drone Parser is the bot responsible to parse the report and sanitize the information.",
            "module": "intelmq.bots.parsers.shadowserver.parser_drone",
            "parameters": {
            }
        },

**Comment by SYNchroACK** [comment]
fixed
