### ISSUE TITLE
IPv6 handling

### ISSUE THREAD

**Issue by sebix** [certtools/intelmq#306]
Currently, many bots do not support IPv6 addresses and are either failing or silently ignoring IPv6 values.

What is the projects policy for IPv6?

If it's not supported yet, there are two possible approaches:
- IPv6 can be ignored if not supported by bots.
- Bots may fail with IPv6 data.

**Comment by SYNchroACK** [comment]
Approach proposed:
* identify which bots will crash with IPv6
* evaluate the complexity of the changes
* if we choose to go through IPv6, apply the changes to support IPv6

**Comment by sebix** [comment]
Not all sources contacted by experts do support IPv6. What to do in these cases?

Ignore and raise a warning? (warning = unexpected, but handled behavior, see https://github.com/certtools/intelmq/blob/master/docs/Developers-Guide.md#log-levels)

**Comment by aaronkaplan** [comment]
---
Mobile


> On 31.08.2015, at 11:42, Sebastian <notifications@github.com> wrote:
> 
> Not all sources contacted by experts do support IPv6. What to do in these cases?
> 


I believe a reasonable approach is:
* Check Which experts are essential (ip2asn for example) and make them ipv6 aware 
* all other bots: ignore v6 for the moment but raise a warning. 
* later fix this after the release

**Comment by SYNchroACK** [comment]
@aaronkaplan agreed!

**Comment by aaronkaplan** [comment]
okay, forgot that we already discussed this in August. Yes #401 can be closed.
Anyway, needs to be done.

**Comment by sebix** [comment]
Still to do:

- [ ] tor nodes
- [ ] reverse dns lookuo
- [ ] abusix
