### ISSUE TITLE
ASN_lookup expert bot error with IPv6

### ISSUE THREAD

**Issue by pedromreis** [certtools/intelmq#313]
Hi all

Got this during the weekend:

```
Bot has found a problem.
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/intelmq-1.0.0-py2.7.egg/intelmq/lib/bot.py", line 117, in start
    self.process()
  File "/usr/local/lib/python2.7/dist-packages/intelmq-1.0.0-py2.7.egg/intelmq/bots/experts/asn_lookup/expert.py", line 43, in process
    info = self.database.lookup(ip)
  File "/usr/local/lib/python2.7/dist-packages/pyasn/__init__.py", line 83, in lookup
    rn = self.radix.search_best(ip_address)
ValueError: inet_pton() returned error
```

**Comment by sebix** [comment]
IPv6 is not supported by pyasn currently, see this issue upstream: hadiasghari/pyasn#14

**Comment by pedromreis** [comment]
ok, tks

**Comment by aaronkaplan** [comment]
On Sep 7, 2015, at 10:53 AM, Sebastian <notifications@github.com> wrote:

> IPv6 is not supported by pyasn currently, see this issue upstream: hadiasghari/pyasn#14
> 

We could probably add a module for ip2asn local lookups iff you have a full BBGP table feed somwhere.
The idea is that this can be grabbed via vtysh (quagga) and get a list of netblocks -> ASN (but note that these are the currently announced netblocks/ASNs as opposed to the ones which are registered).

We wrote that code already once in Perl and Otmar can help out for sure.

**Comment by sebix** [comment]
@aaronkaplan why yet another module for ip-asn-lookup in python? It is far easier to fix pyasn than to write your own module. And we don't have the resources anyway.
The bug is known and the maintainer announced to fix it. No need to make a fuss about it.

**Comment by aaronkaplan** [comment]
On Sep 7, 2015, at 2:49 PM, Sebastian <notifications@github.com> wrote:

> @aaronkaplan why yet another module for ip-asn-lookup in python? It is far easier to fix pyasn than to write your own module. And we don't have the resources anyway.

sure sure... I was speaking theoretically - this comes later of course.

> The bug is known and the maintainer announced to fix it. No need to make a fuss about it.
> 
I think my idea was based on something else. Doesn't matter.. .I'll explain in person.

a.

**Comment by sebix** [comment]
To clarify what we discussed: The pyasn module is also based on BGP table dumps and uses the same algorithms as proposed by Aaron. Nothing will change, we stick to pyasn.

**Comment by aaronkaplan** [comment]
Yes convinced. 

---
Mobile

**Comment by sebix** [comment]
Just saw the bot currently ignores all IPv6 data, but the lib can handle this data -> reopen
