### ISSUE TITLE
Timefilter bot

### ISSUE THREAD

**Issue by robcza** [certtools/intelmq#320]
Lots of feeds provide historical IoCs and there could be several reasons not to process them. You may want to exclude such obsolete events from the output and it could actually improve the performance a little if it would be possible to exclude those events before passing them to the pipeline of experts, hence the ideal positioning of the bot would be right after the parsers, even before deduplicator.

My proposal is to prepare an expert bot with two specific runtime parameters: ```not_before``` and ```not_after``` This should allow even configurations to gather IoCs from specific timeframe.
The timestamp for the comparison would be just and only ```time.source```

It could be completely independent new bot or it could be an extension to the existing filter bot. What do you think?

**Comment by SYNchroACK** [comment]
@robcza I think it should be an extension for the existing filter bot. :)

**Comment by aaronkaplan** [comment]
On Sep 13, 2015, at 4:44 AM, Tomás Lima <notifications@github.com> wrote:

> @robcza I think it should be an extension for the existing filter bot. :)
> 

IMHO: either way - if it is an extension or its own bot, I think it's an excellent idea.

**Comment by robcza** [comment]
Thank you for the comments, will focus on extending the recent filter bot.

**Comment by sebix** [comment]
I would implement it with relative times, i.e. timedeltas (module [datetime.timedelta](https://docs.python.org/3/library/datetime.html#datetime.timedelta)). So e.g.:

no before: 1 month
not after: None (deactivating check, same as empty)

**Comment by aaronkaplan** [comment]
On Sep 13, 2015, at 9:25 PM, Sebastian <notifications@github.com> wrote:

> I would implement it with relative times, i.e. timedeltas (module datetime.timedelta). So e.g.:
> 
> no before: 1 month
> not after: None (deactivating check, same as empty)
> 

makes sense to me, good idea!

**Comment by SYNchroACK** [comment]
+1

**Comment by robcza** [comment]
I like it @sebix will do

**Comment by sebix** [comment]
Implemented by #349
