### ISSUE TITLE
IntelMQ Docker

### ISSUE THREAD

**Issue by robcza** [certtools/intelmq#331]
Hi, I've been toying with IntelMQ in docker for some time now, I think it is really useful to have such a container, however, there are some obstacles I would like to discuss.
https://github.com/robcza/intelmq-dockerhub

1) There is no single IntelMQ process running on the foreground. Docker has no way to realize, whether IntelMQ is still running properly. And to be honest, it is not an easy task to decide, whether the IntelMQ is running properly. Should any crashed bot be considered as the crash of whole IntelMQ?

2) For dockerization purposes it would be useful to have a possibility to log to stdout/stderr or at least to one aggregated file, that could be simply forwarded with tail. Should this be configurable on the global level?

**Comment by sebix** [comment]
> 1) There is no single IntelMQ process running on the foreground. Docker has no way to realize, whether IntelMQ is still running properly. And to be honest, it is not an easy task to decide, whether the IntelMQ is running properly. Should any crashed bot be considered as the crash of whole IntelMQ?

```bash
pgrep -f 'python -m intelmq.bots'
```
> 2) For dockerization purposes it would be useful to have a possibility to log to stdout/stderr or at least to one aggregated file, that could be simply forwarded with tail

The logger can be extended to log to even more destinations. Currently, it's one file and stderr. It's possible to add syslog here (depending on config)

**Comment by robcza** [comment]
1) ```pgrep -f 'python -m intelmq.bots'``` actually did not answer the question "Is IntelMQ healthy and running or should the whole botnet be redeployed?"
Simple attitude would be - redeploy on any crashed bot.

2) For dockerization purposes syslog is not needed, as this could be done on the docker level. I would suggest adding a system.conf attribute ```"combined_logging" : <true/false>```
```false``` option would log in the same manner as it is right now, ```true``` would create one common log file. The same for the dump files

**Comment by sebix** [comment]
> 1) Docker has no way to realize, whether IntelMQ is still running properly.
I can give you an answer on how to determine if any bot is running. I have no idea what the usage of docker is and what it does, so I can't give you more hints.

2) Seems reasonable for me, @SYNchroACK what do you think?

**Comment by SYNchroACK** [comment]
>> 1) Docker has no way to realize, whether IntelMQ is still running properly.
>
>I can give you an answer on how to determine if any bot is running. I have no idea what the usage of >docker is and what it does, so I can't give you more hints.
>
me 2
>
>2) Seems reasonable for me, @SYNchroACK what do you think?
agreed

**Comment by SYNchroACK** [comment]
Current task that needs to be done from this issue is:

> For dockerization purposes syslog is not needed, as this could be done on the docker level. I would suggest adding a system.conf attribute "combined_logging" : <true/false>
false option would log in the same manner as it is right now, true would create one common log file. The same for the dump files

**Comment by wagner-certat** [comment]
To solve the `combined_logging` issue we could just use the `logging_path` parameter which could be a file.

Would this be fine for you?

**Comment by robcza** [comment]
I guess the file could be even /dev/stdout, which is ideal for the docker purposes

**Comment by wagner-certat** [comment]
Currently we log to /dev/stderr, so you can just redirect it.

Btw I also have a patch which modifies the Stream logging to log to stdout or sterr based on the log level. Would that fit for docker too?

**Comment by wagner-certat** [comment]
> Currently we log to /dev/stderr, so you can just redirect it.

P.S.: For the interactive mode `intelmqctl run ...`

**Comment by robcza** [comment]
Still, there would have to a a single master process to run all those ```intelmqctl run ...``` processes. Could be a supervisord, but I'd rather leave maintenance of individual bot to the native intelmq mechanism.
The logging is a great help, thank you.

**Comment by wagner-certat** [comment]
> Still, there would have to a a single master process to run all those ```intelmqctl run ...``` processes. Could be a supervisord, but I'd rather leave maintenance of individual bot to the native intelmq mechanism.

Does this mechanism need to be blocking/running in foreground?

**Comment by robcza** [comment]
Yes, the docker container is terminated as soon as the main process terminates. You need a single running process on the foreground.

**Comment by wagner-certat** [comment]
If I understood it correctly, all bots need to run in *one* container?
