### ISSUE TITLE
install: bug with requirements installation and documentation

### ISSUE THREAD

**Issue by aaronkaplan** [certtools/intelmq#334]
Environment: Debian wheezy.

It seems that the version of mock (>= 1.1.1) as written in REQUIREMENTS2 is not working for Debian Wheezy.
Possible fix: require only 0.8.0 

Second documentation bug: the UserGuide does not mention that postgresql-9.x as well as postgresql-server-dev-9.x is required.

**Comment by SYNchroACK** [comment]
Regarding 1st issue, its done 1183c2799e4efdec45e19e9dbfd4f8ccc58ed705

Regarding 2nd, well, we need to improve the specific documentation for each bot. Maybe, centralize everything in /docs/

**Comment by sebix** [comment]
> Regarding 1st issue, its done 1183c27
What has that commit to do with mock?!
And @aaronkaplan you only need mock if you want to run the tests, so you can just ignore this.

> Second documentation bug: the UserGuide does not mention that postgresql-9.x as well as postgresql-server-dev-9.x is required.
Only when you want to use postgres output bot.
