### ISSUE TITLE
Custom python environment

### ISSUE THREAD

**Issue by mauroasilva** [certtools/intelmq#343]
When you install IntelMQ assuming you'll use python 3, there is no way to tell intelmq it should run with the python 3 environment (except for changing the default of the whole system).

I think one of the more flexible approaches would be to have a environment variable like INTELMQ_PYTHON which would define the executable used to run intelmq, so... if there was no environment variable the default "python" would be used, but we could do something like:

```
export INTELMQ_PYTHON=python3
```

and from this point forward everything in intelmq would use the python3 executable.

What do you think?

**Comment by aaronkaplan** [comment]
On Sep 23, 2015, at 7:03 PM, mauroasilva <notifications@github.com> wrote:

> When you install IntelMQ assuming you'll use python 3, there is no way to tell intelmq it should run with the python 3 environment (except for changing the default of the whole system).
> 
> I think one of the more flexible approaches would be to have a environment variable like INTELMQ_PYTHON which would define the executable used to run intelmq, so... if there was no environment variable the default "python" would be used, but we could do something like:
> 
> export INTELMQ_PYTHON=python3
> 
> and from this point forward everything in intelmq would use the python3 executable.
> 
> What do you think?
> 

I believe having the shebangs set to #!/usr/bin/python
is the right thing to do. If someone wants to run with python3, he/she can simply set the alternatives
to point to the right version.

My 2 cents,
a.

**Comment by mauroasilva** [comment]
I would normally agree with you... but, won't setting the alternatives to python3 break a few things in CentOS? Someone gave me feedback that it would break a few things...

If, after some tests, we are comfortable with recommending people to change the python version for the whole system, and we are certain it won't break stuff, then I'm totally in favor your idea. If it is not possible, and we really wan't people to adopt the python3 version, then we should find some solution for those who have problems.

Besides... instead of the export we could simply have some kind of "config.py" that people would run and would configure a few basic things for IntelMQ like:
path for installation
python environment
what kind of stuff should be installed (should mongo be installed? should postgres?)
etc

Or maybe even do something like that in the setup.py...

Something that would be user friendly, have very little impact in the code, but would give the flexibility to support other versions.

**Comment by aaronkaplan** [comment]
On Sep 24, 2015, at 1:05 AM, mauroasilva <notifications@github.com> wrote:

> I would normally agree with you... but, won't setting the alternatives to python3 break a few things in CentOS? Someone gave me feedback that it would break a few things...
> 
Well, the other alternative is of course virtualenv... if you can not change your system default python version.
In both cases, I am for changing the stuff to #!/usr/bin/env python  or so.


> If, after some tests, we are comfortable with recommending people to change the python version for the whole system, and we are certain it won't break stuff, then I'm totally in favor your idea.
I believe the idea is independent of changing the whole system setup or not , see above.

> If it is not possible, and we really wan't people to adopt the python3 version, then we should find some solution for those who have problems.
> 
see above.

> Besides... instead of the export we could simply have some kind of "config.py" that people would run and would configure a few basic things for IntelMQ like:
> path for installation
> python environment
> what kind of stuff should be installed (should mongo be installed? should postgres?)
> etc
> 
No, I don't like that . Eventually I 'd rather have .deb or Redhat packages. Where you just yum install or apt-get install.
For those, answering questions is not a good idea.

Also, it might break Travis-CI testing.

**Comment by sebix** [comment]
>     export INTELMQ_PYTHON=python3
> and from this point forward everything in intelmq would use the python3 executable.

Yep, quite easily possible. The bots are started in `intelmqctl`, see `__bot_start` [on line 307](https://github.com/certtools/intelmq/blob/master/intelmq/bin/intelmqctl#L307), read the environment variable with `os.environ['INTELMQ_PYTHON']` and use it there.

> Well, the other alternative is of course virtualenv... if you can not change your system default python version.

I have doubts, we hardcoded `/opt/intelmq` :)

> In both cases, I am for changing the stuff to #!/usr/bin/env python or so.

There are no shebangs requiring a specific version. Only the files in bin/ have shebangs (`#!/usr/bin/env python`), the bots are started by intemqctl by calling `python -m ...` as stated above.

**Comment by aaronkaplan** [comment]
---
Mobile


> On 24.09.2015, at 11:19, Sebastian <notifications@github.com> wrote:
> 
> export INTELMQ_PYTHON=python3
> and from this point forward everything in intelmq would use the python3 executable.
> 
> Yep, quite easily possible. The bots are started in intelmqctl, see __bot_start on line 307, read the environment variable with os.environ['INTELMQ_PYTHON'] and use it there.
> 
> Well, the other alternative is of course virtualenv... if you can not change your system default python version.
> 
> I have doubts, we hardcoded /opt/intelmq :)
> 

Oh damn.

**Comment by mauroasilva** [comment]
> export INTELMQ_PYTHON=python3
> 
>     and from this point forward everything in intelmq would use the python3 executable.
> 
> Yep, quite easily possible. The bots are started in intelmqctl, see __bot_start on line 307, read the environment variable with os.environ['INTELMQ_PYTHON'] and use it there.

Yes, I know it is possible since I was one of its developers =P The only reason I made an issue was so we could discuss the best approach.
> 
>     Well, the other alternative is of course virtualenv... if you can not change your system default python version.
> 
> I have doubts, we hardcoded /opt/intelmq :)
> 
>     In both cases, I am for changing the stuff to #!/usr/bin/env python or so.
> 
> There are no shebangs requiring a specific version. Only the files in bin/ have shebangs (#!/usr/bin/env python), the bots are started by intemqctl by calling python -m ... as stated above.

Agreed, the environment "dependencies" are both at the intelmqctl itself and at the command string that is run from within the ctl. 
Although the first can easily be overcome by doing ```python3 /opt/intelmq/bin/intelmqctl``` instead of ```/opt/intelmq/bin/intelmqctl```, I think that is kind of ugly.
The second "dependency" I believe can be easily overcome by the environment variable as I said earlier.

**Comment by SYNchroACK** [comment]
+1 os.environ['INTELMQ_PYTHON']

Lets solve it... :)

**Comment by sebix** [comment]
I implemented this in 538a5bd8df502812b88b9fc63bd87f88eaaa351a. How can this feature be used by intelmq-manager @mauroasilva, could you document it?
