### ISSUE TITLE
filter bot - add example

### ISSUE THREAD

**Issue by aaronkaplan** [certtools/intelmq#352]
I am missing an example config snippet in the filter bot.

**Comment by SYNchroACK** [comment]
@aaronkaplan currently, intelmq has some configs which automatically are installed in /opt/intelmq/etc

https://github.com/certtools/intelmq/tree/master/intelmq/conf

Do you want a full configuration for all bots? Some bots needs specific parameters like API keys, etc..

Whats is the best approach in your opinion?

**Comment by aaronkaplan** [comment]
yes, I am working on an example/ directory which has sane default values for all bots.
If some bot needs an API key, so be it, let's have it there with <INSERT-YOUR-API-KEY> as a text and have the bot crash .
Note: these are all **examples* in an example/ subdirectory.
People will be smart enough to copy & paste & modify from the example/ directory.

That\s my opinion.

**Comment by SYNchroACK** [comment]
Yes, I agree.

**Comment by sebix** [comment]
What's the current status here? Concerning the new filterbot, docs are here: https://github.com/certtools/intelmq/tree/master/intelmq/bots/experts/filter

**Comment by aaronkaplan** [comment]
outdated. See the newer discussion in #569
