### ISSUE TITLE
RTIR Collector bot

### ISSUE THREAD

**Issue by aaronkaplan** [certtools/intelmq#354]
We need a bot which can connect to RT / RTIR via its RESTful API and 
  * select all tickets which are not owned, match a specific user and queue ("incident-reports" by default) and match a specific subject
  * remember these ticket ids (for adding them later to the events)
  * assign these tickets to a user ("intelmq" by default)
  * fetch the attachments of the ticket, check if their filename matches a regexp
  * potentially unzip/gunzip the attachments
  * potentially decrypt (gpg) the attachments
  * and pass on the attachment's data according to the pipeline setup

The corresponding parser should be able to parse the (usually it's a CSV) file and **add the ticket ID** to the event.

**Comment by sebix** [comment]
I implemented the mentioned features, except for none:

> potentially decrypt (gpg) the attachments

This is quite tricky, in terms of 'needs discussion'. Gnupg [can easily be used](https://pythonhosted.org/python-gnupg/), but there are some question. Should an agent be used? Should the bot have access to the key-files, or should there be an intermediate software separating intelmq from gnupg? Or do an expert bot for gpg-decryption?

**Comment by sebix** [comment]
Do you think that the missing gnupg support is a blocking issue for 1.0?

**Comment by sebix** [comment]
Well, it is implemented, just the local keyring has to be configured accordingly, the implementation depends on it.

**Comment by aaronkaplan** [comment]
> On 09.02.2016, at 09:55, Sebastian <notifications@github.com> wrote:
> 
> Do you think that the missing gnupg support is a blocking issue for 1.0?
> 
IMHO this is pretty arbitrary if it is in 1.0 or 1.1 
Stability and parsing stability should be paramount for 1.0. Otherwise we have too many events stuck in dump files. 

My 2 cents
