### ISSUE TITLE
fix docs/Bots.md file

### ISSUE THREAD

**Issue by aaronkaplan** [certtools/intelmq#355]
I see a lot of FIXMEs in the docs/Bots.md . We should fix this.

**Comment by bernhardreiter** [comment]
Took a brief look:
We have 41 FIXMEs in https://github.com/certtools/intelmq/blob/37a3db9850c7ae67f586693b3393d5b5086d2177/docs/Bots.md
`grep FIXME Bots.md  | wc -l`

* 17 Bots have a fixme, mostly Configuration Parameters fixes:
 * HTTP
 * Mail (URL)
 * Mail (Attach)
 * Alien Vault OTX
 * Abusix
 * ASN Lookup
 * Cymru Whois
 * Deduplicator
 * Filter
 * MaxMind GeoIP
 * Reverse DNS
 * RipeNCC Abuse Contact
 * Taxonomy
 * Tor Nodes
 * Postgresql
 * REST API
 * TCP

To get an overview, I've used
` grep -e '^### \|FIXME' docs/Bots.md`

**Comment by bernhardreiter** [comment]
I've split of fix outputs/postgresql docs in Bots.md and README.md #711, so we are down to 16 bots in this issue. :)

**Comment by sebix** [comment]
It's a bit more than that as I also mentioned here: https://github.com/certtools/intelmq/pull/706#issuecomment-248983101

**Comment by wagner-certat** [comment]
Obsoleted by #757
