### ISSUE TITLE
modify bot: add a sane set of default matching rules

### ISSUE THREAD

**Issue by aaronkaplan** [certtools/intelmq#356]
The modify bot needs to have a list of sane and tested (!) default rules (if-then matching rules) for all provided bots/feeds.

**Comment by sebix** [comment]
Can we just use the evolving config of our internal setup?

**Comment by aaronkaplan** [comment]
re-visit the modify bot user experience in version 1.1

**Comment by wagner-certat** [comment]
solved by malware name mapping (if not, provide a better description of the issue)
