### ISSUE TITLE
create an example *.conf setup which works out of the box

### ISSUE THREAD

**Issue by aaronkaplan** [certtools/intelmq#357]
We need an example config setup which works just straight out of the box.
I'll add it to an example/ subdirectory.

**Comment by SYNchroACK** [comment]
The following information represents an example for runtime configuration:

**Runtime configuration**
* * *
**File location in repository:** intelmq/conf/examples/runtime.conf
**File location in installation folder:** /opt/intelmq/conf/examples/runtime.conf

Is it ok?

**Comment by aaronkaplan** [comment]
important for usability.
The current example set is quite small. Need to include at least 5 OSINT feeds.
