### ISSUE TITLE
ENH: feodotracker / abuse.ch bots - need to set malware.name in parser

### ISSUE THREAD

**Issue by aaronkaplan** [certtools/intelmq#362]
The malware.name field does not seem to get set in the Abuse.ch bots.

**Comment by robcza** [comment]
To associate the malware name is necessary to know the source feed. The feed.code could be helpful, however there are no codes set yet. I see two possible solutions here:

1. adjust the parser to set the malware.name according to the feed.code
2. add malware.name attribute to the report and inherit it to the events in the parser

Option #1 works for me, however depends on properly set feed.code attribute. Is anyone working on that?

**Comment by sebix** [comment]
What about using the Feed URLs? The feed code is for (pseudo-) anonymization of feeds as far as I understood. So, it's not relevant for intelmq at all, only afterwards in databases and can be set arbitrarily. @aaronkaplan can you give your comment here?

**Comment by aaronkaplan** [comment]
@sebix: you mean ```feed.url``` ? Yes, also OK. But I think we need in general more info (feed.name, feed.url, feed.code, ...)  in the abuse.ch bots for the intelmqcli tool afterwards.

**Comment by robcza** [comment]
Should be successfully implemented https://github.com/certtools/intelmq/pull/387

**Comment by dmth** [comment]
> Should be successfully implemented #387

Why is this still open?
