### ISSUE TITLE
intelmqcli: request - please implement filter for specific feeds

### ISSUE THREAD

**Issue by aaronkaplan** [certtools/intelmq#363]
At work a feature request appeared: can you please implement a command line parameter for intelmqctl so that it will only fetch data from a specific feed. For example:

```
$ intelmqcli  --feed=abuse.ch ....
```

Thank you!

**Comment by sebix** [comment]
There's no intelmqcli in this repository, you want to create this issue at @certat

**Comment by aaronkaplan** [comment]
oh yeah, sorry... "ctl" looks like "cli" ;-)
