### ISSUE TITLE
ENH: log file rotation

### ISSUE THREAD

**Issue by aaronkaplan** [certtools/intelmq#367]
Usually in *nix we have nice tools for log file rotation such as logrotate(1)

Here is a proposal for a logroate.d/intelmq could look like:

```
/opt/intelmq/var/log/*.log {
        weekly
        su intelmq intelmq
        missingok
        copytruncate
        maxsize 50m
        rotate 52
        compress
        delaycompress
        notifempty
        create 644 intelmq intelmq
}

/opt/intelmq/var/lib/bots/file-output/events.txt {
        weekly
        su intelmq intelmq
        missingok
        copytruncate
        maxsize 50M
        rotate 52
        compress
        delaycompress
        notifempty
        create 640 intelmq intelmq
}
```

**Note**: this is far from perfect. In fact, if you use this, it will copy over each file to a $file.1 and then later compress it with gzip. However, in the meantime, intelmq-manager will try to open the new (empty) file and will complain.
The python bots however, still have the old file handle and will write to $file.1
So... this is just a proposal and I'd like to know if you have a better idea how to do this properly without any unexpected results for the user.

Otherwise, we risk that the log files get very very large very quickly.

**Comment by SYNchroACK** [comment]
As we discussed, we should use logrotate and that procedure should be documented in User-Guide

Regarding file handler, we agreed that logging from intelmq should be prepared (need code changes) to behave normally even with log rotation.

**Comment by sebix** [comment]
There are some possibilities given by the logrotate handlers: https://docs.python.org/2/library/logging.handlers.html

- WatchedFileHandler, appropriate in a logrotate setup

  > If the file changes, it is closed and reopened using the file name.
- RotatingFileHandler

  > You can use the maxBytes and backupCount values to allow the file to rollover at a predetermined size. When the size is about to be exceeded, the file is closed and a new file is silently opened for output.
- TimedRotatingFileHandler

  > The specified file is opened and used as the stream for logging. On rotating it also sets the filename suffix. Rotating happens based on the product of when and interval.
- SysLogHandler

  > The SysLogHandler class, located in the logging.handlers module, supports sending logging messages to a remote or local Unix syslog.

**Comment by aaronkaplan** [comment]
@mauroasilva , @robcza, @SYNchroACK , @e3rd: would it be OK for you all if we change the logger to use syslog **by default** (and of course provide example rsyslogd.conf and logrotate.d/intelmq config examples in a contrib/ subdirectory)?

Let me and @sebix know please what you think.

Our reasoning is that syslog is a standard tool for unix. We should integrate with standard tools and therefore monitoring becomes much easier. 

This issue arose because we are integrating intelmq into our certat monitoring.

**Comment by robcza** [comment]
:+1: for me, had some troubles with the recent logging, would manage syslog easier

**Comment by sebix** [comment]
Implemented in my feature branch:

https://github.com/sebix/intelmq/blob/bugfixes/intelmq/lib/utils.py#L187
https://github.com/sebix/intelmq/blob/bugfixes/intelmq/lib/bot.py#L51
https://github.com/sebix/intelmq/blob/bugfixes/intelmq/conf/defaults.conf#L22
https://github.com/sebix/intelmq/blob/bugfixes/docs/User-Guide.md#system-configuration

Do you want to have syslog as default? (my personal opinion: no)
Where should intelmqctl log to? it logs, as it is called by the intelmq-manager.

**Comment by aaronkaplan** [comment]
> On 24 Nov 2015, at 15:48, Sebastian <notifications@github.com> wrote:
> 
> Implemented in my feature branch:
> 
> https://github.com/sebix/intelmq/blob/bugfixes/intelmq/lib/utils.py#L187
> https://github.com/sebix/intelmq/blob/bugfixes/intelmq/lib/bot.py#L51
> https://github.com/sebix/intelmq/blob/bugfixes/intelmq/conf/defaults.conf#L22
> https://github.com/sebix/intelmq/blob/bugfixes/docs/User-Guide.md#system-configuration
> 
> Do you want to have syslog as default? (my personal opinion: no)

IMHO : yes

> Where should intelmqctl log to? it logs, as it is called by the intelmq-manager.
> 
syslog as well. I don’t see a reason why not.


But let’s hear what other (Robert etc) are saying?

**Comment by mauroasilva** [comment]
My personal opinion is to have syslog as a possibility but not as default. I think the default should be to have IntelMQ logging, as it is now, on a segregated folder that can be configured with a separate log file for each bot. 

About intelmqctl... it should log to stdout/stderr by default and have a flag to log it to other means (such as syslog).

**Comment by sebix** [comment]
> About intelmqctl... it should log to stdout/stderr by default and have a flag to log it to other means (such as syslog).

Of course ctl logs to stdout/stderr. logging to file is only additional in this case.

Other opinions regarding syslog as default @robcza  @e3rd?

**Comment by robcza** [comment]
Configurable syslog is fine by me, does not have to be default. I like the implementation by @sebix. I miss just one important thing, but that could be specific for our needs. Our logging goes through stdout, because we run intelmq in Docker, that means we have to get all of the logs to the stdout somehow.

Tailing all of the log files - not really reliable, as the log files have to exist at the right moment we are calling tail. Having one or two files (e.g. botnet.log and botnet.dump) would make the thing easy and reliable for us. Creating the log files during runtime is cumbersome to process in Docker.

**Comment by sebix** [comment]
> that means we have to get all of the logs to the stdout somehow.

What about using a separate syslog instance? https://docs.python.org/2/library/logging.handlers.html#logging.handlers.SysLogHandler
This possibility is implemented in intelmq already, just give the address-tuple in the config file:
https://github.com/certtools/intelmq/blob/master/intelmq/lib/utils.py#L212
