### ISSUE TITLE
FQDN with trailing dot or not?

### ISSUE THREAD

**Issue by sebix** [certtools/intelmq#369]
The current implementation allows bots variants, with and without the trailing dot for the root zone. Sanitize does not add or remove it.

    >>> intelmq.lib.harmonization.FQDN.is_valid(u'foobar.example.')
    True
    >>> intelmq.lib.harmonization.FQDN.is_valid(u'foobar.example')
    True
    >>> intelmq.lib.harmonization.FQDN.sanitize(u'foobar.example')
    u'foobar.example'
    >>> intelmq.lib.harmonization.FQDN.sanitize(u'foobar.example.')
    u'foobar.example.'

This can potentially lead to duplicates.

Which variant do you prefer?

**Comment by SYNchroACK** [comment]
'foobar.example'

**Comment by robcza** [comment]
Talking of indicators of compromise I think foobar.example and foobar.example. carry exactly the same information. As I would expect from IntelMQ, that the output is normalized I prefer the variant, when sanitization always produces fqdn without trailing dot.

**Comment by sebix** [comment]
@aaronkaplan What do you think here?

**Comment by aaronkaplan** [comment]
> On 20 Oct 2015, at 17:12, Sebastian <notifications@github.com> wrote:
> 
> @aaronkaplan What do you think here?
> 

Robert’s proposal is fine for me.
It’s easy to rtrim(‘\.’) at the end.

**Comment by sebix** [comment]
Ok, we have a consensus here. Trailing dot is not allowed and will be removed in sanitation.

**Comment by aaronkaplan** [comment]
> On 20 Oct 2015, at 17:18, Sebastian <notifications@github.com> wrote:
> 
> Ok, we have a consensus here. Trailing dot is not allowed and will be removed in sanitation.

Yes
