### ISSUE TITLE
BUG: parser dismissing whole report on exception

### ISSUE THREAD

**Issue by robcza** [certtools/intelmq#374]
I have a trouble with hphosts-parser for several days now. First record in the list is ```127.0.0.1	-ads.avast.dwnldfr.com``` which is obviously malformed fqdn and parser raises an exception. So far that is an expected behavior.
The think is, I would expect parser to continue with following lines and not to purge the rest of the report. I would suggest parser to catch the sanitization exception and log it instead of passing them further and continue with the parsing cycle.

```
2015-10-22 12:23:32,131 - hphosts-parser - DEBUG - Receiving Message.
2015-10-22 12:23:37,586 - hphosts-parser - DEBUG - Receive message u'{"raw": "IyBocEhvc3RzIGxhc3QgdXBkYXRlZCBvbjoJCTExLzEwLzIwMTUNCiMgaHBIb3N0cyBsYXN0IHZlcmlmaWVkIGJ5IFN0ZXZlbiBCdXJuOgkxMS8xMC8yMDE1DQojDQo
jIElNUE9SVEFOVDoJUmVuYW1lIHRoaXMgZmlsZSB0byAiSE9TVFMiIChubyAudHh0IGV4dGVuc2lvbikNCiMNCiMgU3VwcG9ydDoJaHR0cDovL215c3RlcnlmY20uY28udWsvP21vZGU9Y29udGFjdA0KIwkJaHR0cDovL2ZvcnVtLmhvc3RzLWZpbGUubmV0DQojDQojIERv
d25sb2FkOglodHRwOi8vaG9zdHMtZmlsZS5uZXQvP3M9RG93bmxvYWQNCiMgTWlycm9yczoJaHR0cDovL2hvc3RzLWZpbGUubmV0Lz9zPUhlbHAjZGxtaXJyb3JzDQojDQojIEludGVybWl0dGVudCB1cGRhdGV'...
2015-10-22 12:23:38,021 - hphosts-parser - ERROR - Bot has found a problem.
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/intelmq-1.0.0-py2.7.egg/intelmq/lib/bot.py", line 95, in start
    self.process()
  File "/usr/local/lib/python2.7/dist-packages/intelmq-1.0.0-py2.7.egg/intelmq/bots/parsers/hphosts/parser.py", line 45, in process
    event.add("source.fqdn", values[1], sanitize=True)
  File "/usr/local/lib/python2.7/dist-packages/intelmq-1.0.0-py2.7.egg/intelmq/lib/message.py", line 108, in add
    raise exceptions.InvalidValue(key, value, reason=valid_value[1])
InvalidValue: invalid value u'-ads.avast.dwnldfr.com' (<type 'unicode'>) for key u'source.fqdn' regex did not match.
2015-10-22 12:23:38,022 - hphosts-parser - INFO - Last Correct Message(event): None.
```

**Comment by sebix** [comment]
Expected behavior. The message (report) is dumped (default config). To process it again, use the intelmqdump tool.

But the bot will fail again of course. Parsers need to skip this one line (dump it) and continue. The current behavior works only for experts and output bots.

**Comment by robcza** [comment]
Do you think the fix could possibly happen on the lib level or does this mean modification of all parsers?

**Comment by sebix** [comment]
Two possibilities:

1. The parsers can dump individual lines (in case of csv and similar) or values (in case of json and similar) so they can be inspected with intelmqdump afterwards
2. The parser skips datasets (lines) in case of essential invalid values like the FQDN.

In both cases the parsers need to be touched.

**Comment by SYNchroACK** [comment]
This approach was already proposed by others and we found that it will break the simplicity of IntelMQ. We need to be really careful when we decide to add this kind of features. So, it will depend of the technical solution but i will probably not support this change.

**Comment by sebix** [comment]
Yeah, I'm aware of this. What would be another valid solution for this problem?

**Comment by SYNchroACK** [comment]
In fact, I dont have a good answer. :(
My current approach is to keep the simplicity and "send" the error fix procedure to "human side" (intelmq sysadmin). I know... its not the best solution... but i'm afraid that new "expert" feature of parsers will kill the simplicity for new users.... dont know.... :S

**Comment by robcza** [comment]
The only solution I see, where parsers do not have to be touched is a following one:
 - adding new attribute to the Event class ```self.erroneous = False```
 - sanititzation error would result in operation ```self.erroneous = True``` on the Event level, but the processing goes on
 - ```self.send_message(event)``` would check ```event.erroneous``` state and dump it if True

Parser does not have to be aware of this and just inconsistent lines/objects are dismissed

**Comment by SYNchroACK** [comment]
@robcza how should bot catch the exception?

**Comment by robcza** [comment]
Is it necessary to raise the exception on the ```Message``` level? I mean during sanitation, you can just set the error flag here https://github.com/robcza/intelmq/blob/master/intelmq/lib/message.py#L121

Maybe even save the exception to dump it later during send_message(event), but keep the bot going.

**Comment by SYNchroACK** [comment]
hum... i will describe a little bit just to give context to my perspective:

a. In parsers you define the `def process():`.
b. Imagine in the middle of the report processing, something crash due a bad line in the middle of report.
c. In the current version, it will raise an exception because the bot cant understand which kind of line it is and, in `def start()` method at bot.py, the exception will be catch. So... the send_message method  will never be executed. 

q. Knowing this, in your perspective, how can we use `self.erroneous = True`? I would suggest to write "pseudo code" in the lib/bot.py and put here...its better to understand... ;)

**Comment by aaronkaplan** [comment]
---
Mobile


> On 30.10.2015, at 19:07, Tomás Lima <notifications@github.com> wrote:
> 
> hum... i will describe a little bit just to give context to my perspective:
> 
> a. In parsers you define the def process():.
> b. Imagine in the middle of the report processing, something crash due a bad line in the middle of report.
> 

I think you are addressing the problem at the wrong level here. IMHO the task of the parser is to guarantee that a) either a line is valid or b) that it's invalid and in that case it might get logged or ignored. But a parser must never crash. It has a regexp or context free grammar that will deterministcally guarantee a maximum running time and a clear output (valid or invalid). And nothing else.  Never crash in the parser. 
If an event is valid, it will be converted to our internal format. 


This line if thinking is highly inspired by the langsec community. 
Take a look google:// langsec. 

If we do it like this then we can give the rest I the processing queue some guarantees. And I think that's good. 

Also this helps to keep out trash. 

My 2 cents,
What do you think about this approach?

**Comment by robcza** [comment]
Check this: https://github.com/robcza/intelmq/commit/2cb321d2f230fbfc28fe6e9db201703d181f33e4
Just tested and works (meaning "parsers are not stopped on malformed line, sanitized events are processed"). 
- e.g.: ```exception``` could be actually a list filled with all the exceptions encountered throughout the event creation and processing
- I'm not sure whether I haven't affected other part of IntelMQ
- It does not seem very nice in terms of "nice code", but does not seem that bad as well :)

**Comment by SYNchroACK** [comment]
> ---
> Mobile
>  On 30.10.2015, at 19:07, Tomás Lima <notifications@github.com> wrote:
> 
>  hum... i will describe a little bit just to give context to my perspective:
> 
>  a. In parsers you define the def process():.
>  b. Imagine in the middle of the report processing, something crash due a bad line in the middle of report.
> I think you are addressing the problem at the wrong level here. IMHO the task of the parser is to guarantee that a) either a line is valid or b) that it's invalid and in that case it might get logged or ignored. But a parser must never crash. It has a regexp or context free grammar that will deterministcally guarantee a maximum running time and a clear output (valid or invalid). And nothing else.  Never crash in the parser.
> If an event is valid, it will be converted to our internal format.
> 
> 
> This line if thinking is highly inspired by the langsec community.
> Take a look google:// langsec.
> 
> If we do it like this then we can give the rest I the processing queue some guarantees. And I think that's good.
> 
> Also this helps to keep out trash.
> 
> My 2 cents,
> What do you think about this approach?

@aaronkaplan , look, I just describe the current behavior of any bot types, including parsers. In the current situation, if a report is a csv but some line is broken, bot will crash but since we have try:except , error handling procedure will keep bot running in order to try process the same report again. So, this is the current behavior.

If we start talking about the perfect concept for bot behavior, ok, I agree with you.

but... the problem is... I don't see a simple and easy way (for new developers) to apply that kind of procedure that you and Robert described. Neverthless, you guys can have another approach which can easily solve the problem... lets discuss.

Conceptually, we agree. Lets see in practice.

**Comment by robcza** [comment]
This is the behavior of my solution proposed earlier
```
2015-10-30 21:28:51,388 - hphosts-parser - INFO - Start processing.             
2015-10-30 21:28:51,857 - hphosts-parser - WARNING - invalid value u'-ads.avast.dwnldfr.com' (<type 'unicode'>) for key u'source.fqdn' regex did not match.     
2015-10-30 21:28:52,117 - hphosts-parser - INFO - Processed 500 messages.       
2015-10-30 21:28:52,265 - hphosts-parser - WARNING - invalid value u'0aaslocum_1.medicbfgb.ru' (<type 'unicode'>) for key u'source.fqdn' regex did not match.   
2015-10-30 21:28:52,363 - hphosts-parser - INFO - Processed 1000 messages.      
2015-10-30 21:28:52,630 - hphosts-parser - INFO - Processed 1500 messages.      
2015-10-30 21:28:52,953 - hphosts-parser - INFO - Processed 2000 messages.      
2015-10-30 21:28:52,997 - hphosts-parser - WARNING - invalid value u'119_51377620.ampnetwork.net' (<type 'unicode'>) for key u'source.fqdn' regex did not match.
2015-10-30 21:28:53,310 - hphosts-parser - INFO - Processed 2500 messages.      ```

**Comment by SYNchroACK** [comment]
> Check this: robcza@2cb321d
> Just tested and works (meaning "parsers are not stopped on malformed line, sanitized events are processed").
> 
> Should this be an acceptable direction, there is stil huge space for improvements:
> 
> exception could be actually a list filled with all the exceptions encountered throughout the event creation and processing
> I'm not sure whether I haven't affected other part of IntelMQ
> It does not seem very nice in terms of "nice code", but does not seem that bad as well :)

@robcza , I think your solution solves part of problem, yes... and I think with some improvements is actually one of the best approaches that I see. So, we agree. ;)

but... when I started discuss this issue, I always think in other kind of situation like the following:

OpenBL Parser Bot (https://github.com/certtools/intelmq/blob/master/intelmq/bots/parsers/openbl/parser.py):
```
...
        raw_report = utils.base64_decode(report.value("raw"))
        for row in raw_report.split('\n'):

            row = row.strip()

            if len(row) == 0 or row.startswith('#'):
                continue

            splitted_row = row.split()
            event = Event(report)

            columns = ["source.ip", "time.source"]

            for key, value in zip(columns, splitted_row):
...
```

Report sample:
```
# source ip	date
103.16.140.113	1446240318
58.137.190.205	1446240101
```

Report example with a bug:
```
# source ip	date
103.16.140.113	1446240318
58.137.190.205	1446240101
61.219.249.14	1446239471
104.239.174.151	1446238767	1446238767
61.219.249.11	1446239472
61.219.249.15	14462312471
```

In the 'Report example with a bug' example, parser will not ignore (even with your proposal) the last line. It will process the first 3 events, crash in 4th event and will start again after error_retry_delay parameter.

So, I agree with your solution but Im trying to find the best solution for all this kind of situations...
@robcza , do you see any good approach to handle these situations?

Thank you guys for your time to discuss these approaches... :)

**Comment by robcza** [comment]
thank you for the summary @SYNchroACK 
Though it seems to me this particular example won't crash the parser, I got your point. I think there are two levels of what could go wrong:
- malformed data type (incomplete records, unsupported characters/format, etc.)
  - that is why we do the sanitation and anyone working on a parser should just rely on the sanitation process without having to check the record by himself
  - my proposal could handle this
- malformed report (blank lines, comments, additional column, completely different format, etc.)
  - my proposal does not handle this situation
  - there could be a straightforward framework to iterate the report and allow only valid "lines" to go through to the Event processing part, where the sanitation process kicks in
  - at this time, every parser implements own logic for report verification - it is kind of messy and allows the programmer to introduce bugs

**Comment by SYNchroACK** [comment]
@robcza excellent comment!!! I agree with your perspective. We need to evaluate an approach to handle 'malformed report'. ;)
Lets continue discussing and present some technical approaches.

**Comment by sebix** [comment]
New proposal: Use generators! Splitting parsers into multiple functions has several great advantages. Three components:

1. The generator, giving individual pieces of data (events, lines). Also reads metadata and provides it for the next stage:
2. The parser itself. Processes them and creates events.
3. A function to rebuild a valid document, in case the parser crashes. Only contains general metadata/headers plus the problematic line.

Demo code:
```python
text = """# source ip date
# all times 2016-03-01T00:00+00
103.16.140.113
58.137.190.205
61.219.249.14
104.239.174.151
61.219.249.11
61.219.249.15"""

header = ""
source_time = None

def generator(text):
    for line in text.splitlines():
        if line.startswith('#'):
            if 'time' in line:  # metadata needed for the parser
                global source_time
                source_time = line[12:]
            global header
            header += line+'\n'
            continue
        yield line  # valid line, given to the parser

def parse_item(line):
    # create event
    print(line, source_time)

def construct_line(line):
    return header+line
```

This is what the bot class should handle:
```bash
>>> a = generator(text)
>>> parse_item(next(a))
103.16.140.113 2016-03-01T00:00+00
>>> parse_item(next(a))
58.137.190.205 2016-03-01T00:00+00
>>> construct_line(next(a))
'# source ip date\n# all times 2016-03-01T00:00+00\n61.219.249.14'
```

**Comment by robcza** [comment]
I like it @sebix and I think it alligns with my understanding and expectations of behavior of a parser. Behavior on failure should be configurable. I can see valid use cases, where you just want to get rid of unparsed data.

**Comment by robcza** [comment]
Thank you @sebix I like the solution
