### ISSUE TITLE
unittest: config

### ISSUE THREAD

**Issue by SYNchroACK** [certtools/intelmq#375]
Need some help to understand the following behavior (im trying to catch the unittest developments):

When I change the following value (https://github.com/certtools/intelmq/blob/master/intelmq/lib/test.py#L33) nothing change. I found that I need to change also in https://github.com/certtools/intelmq/blob/master/intelmq/tests/lib/test_bot.py#L41

This happens because intelmq/lib/test.py is just a template with some generic config parameters?

Thank you in advance.

**Comment by sebix** [comment]
- `intelmq/tests/lib/test_bot.py` tests the bot class itself
- `intelmq/lib/test.py` is the template for the bot-tests

They are similar but not equal, though they could share more they have in common.
