### ISSUE TITLE
MISP Expert Bot

### ISSUE THREAD

**Issue by SYNchroACK** [certtools/intelmq#377]
Documentation: http://www.circl.lu/assets/files/PyMISP.pdf

```
from pymisp.api import PyMISP
x = PyMISP(url='http://<...>', key='<...>', ssl=True, out_type='json')
x.search_all(self, '<ip>')
```

**Comment by dmth** [comment]
Is this Issue still valid? @Rafiot created a MISP-Bot, didn't he?

**Comment by sebix** [comment]
We don't have an expert, only collector and parser. The expert does lookups on MISP's database for non-MISP events.

**Comment by Rafiot** [comment]
Good point, I should implement one.

**Comment by SYNchroACK** [comment]
@Rafiot any good news on this? :D

**Comment by Rafiot** [comment]
Not at all, I didn't had time to work on it :(

**Comment by wagner-certat** [comment]
@SYNchroACK What is the use-case you are looking at? What kind of data do you expect from MISP and how you want to process the resulting data?

**Comment by wagner-certat** [comment]
We have a MISP Expert now: #1475
