### ISSUE TITLE
n6 STOMP bot needed

### ISSUE THREAD

**Issue by aaronkaplan** [certtools/intelmq#378]
Integrate the n6 STOMP protocol bot

**Comment by SYNchroACK** [comment]
I would change to milestone v1.1 because we really need to finish the v1.0 in terms of core changes. Whats your opinion @aaronkaplan ?

I think we have a lot to do to finish the v1.0:
https://github.com/certtools/intelmq/issues?q=is%3Aopen+is%3Aissue+milestone%3A%22Release+1+-+v1.0%22

**Comment by aaronkaplan** [comment]
> On 27 Oct 2015, at 18:03, Tomás Lima <notifications@github.com> wrote:
> 
> I would change to milestone v1.1 because we really need to finish the v1.0 in terms of core changes. Whats your opinion @aaronkaplan ?
> 

I have it nearly finished and for us it’s part of v1.0 :)
Anyway, I’ll contribute it. That’s why the issue was assigned to myself :)

**Comment by SYNchroACK** [comment]
ok Aaron. Agreed ;)
