### ISSUE TITLE
dga collector downloads its data too often under certain conditions

### ISSUE THREAD

**Issue by aaronkaplan** [certtools/intelmq#385]
I noticed with the DGA collector bot that a weird error condition can occur:
1. the collector bot will download the data (it is a lot of data!)
2. the disk is full -> redis will have a pipeline error
3. the bot will through a stack trace and retry in error_retry_delay (= 15 sec by default) again.
4. goto 1. 

-> therefore the collector bot will create a huge load on the source feed's site and download a large file every 15 seconds. That's too much.

**Comment by aaronkaplan** [comment]
solution: go through all bots in BOTS and define meaningful ```error_retry_delay``` values **and** have proper monitoring if bots crash

**Comment by SYNchroACK** [comment]
@wagner-certat @aaronkaplan still an issue?

**Comment by wagner-certat** [comment]
AFAIK setting error_retry_delay higher and using cronjobs is the solution for this
