### ISSUE TITLE
bug: intelmqctl tool does not properly list queues

### ISSUE THREAD

**Issue by aaronkaplan** [certtools/intelmq#389]
How to repeat:

```sudo -Eu intelmq /opt/intelmq/bin/intelmqctl -s queues```
-> no output

```sudo -Eu intelmq /opt/intelmq/bin/intelmqctl -s queues --type json ```
-> meaningful output

**Comment by aaronkaplan** [comment]
@sebix could not reproduce this. Weird... I have a standard setup

**Comment by mauroasilva** [comment]
@aaronkaplan you are right. When intelmqctl is run with the ```--type json``` flag, the result is printed into stdout, if no flag is given the result is printed into the intelmqctl log file. Should the default be to print to stdout? If yes, should we add something like ```--output log|stdout``` to choose where the information is written to?

**Comment by aaronkaplan** [comment]
> On 05 Nov 2015, at 19:52, mauroasilva <notifications@github.com> wrote:
> 
> @aaronkaplan you are right. When intelmqctl is run with the --type json flag, the result is printed into stdout, if no flag is given the result is printed into the intelmqctl log file. Should the default be to print to stdout?

yes.
I think it needs to be consistent :)
And yes, as a user I would expect the parameter to show me output on stdout.

> If yes, should we add something like --output log|stdout to choose where the information is written to?
> 
IMHO stdout is enough.

My 2 cents,
a.

**Comment by mauroasilva** [comment]
@sebix you changed the intelmqctl based on an issue #218, does it make sense to have an ```--output```  flag so the user can control the output?

**Comment by sebix** [comment]
Do you want another output-type to only write the result to the log file? I would just fix the bug that the result is not printed to stdout/stderr.

**Comment by mauroasilva** [comment]
Hmm... so you mean write both to log and stdout?

**Comment by aaronkaplan** [comment]
anything :) As long as it's on stdout.

**Comment by robcza** [comment]
+1 for stdout flag

**Comment by sebix** [comment]
@mauroasilva @robcza does `intelmqctl -s queues` does show output for you? Can't think of a possibility why `-s queues` does not give an output and all others work. Except the `bin/intelmqctl` file is modified of course.

**Comment by mauroasilva** [comment]
@sebix the reason ```list_queues``` doesn't print and ```list_bots``` does is because the ```list_queues``` is calling the ```log_list_queues``` method which right now is only printing to log, but ```list_bots``` is calling ```print``` directly.

All bot/botnet related methods also just print to log file unless you call it with the json flag.

**Comment by sebix** [comment]
Where's the problem? `log_list_queues` calls `logger.info`. logger is defined in `IntelMQContoller.__init__` as `logger = utils.log('intelmqctl', log_level='DEBUG')`. Ok, let's look at `utils.log`. There we find `if stream is None: console_handler = logging.StreamHandler(sys.stderr)` and `None` is default for `stream`. So by default the logger also prints to stderr.

**Comment by mauroasilva** [comment]
Hmm... maybe you have a change in the intelmqctl we don't because if you look here: https://github.com/certtools/intelmq/blob/master/intelmq/lib/utils.py#L223 there is no ```if stream is None```

**Comment by sebix** [comment]
Oh yes, that fix is only in my current dev branch since end of october.
https://github.com/sebix/intelmq/blob/bugfixes/intelmq/lib/utils.py#L224
Will do a PR at the end of the day.

**Comment by mauroasilva** [comment]
Ok, great ;)

**Comment by sebix** [comment]
Fixed by #395: https://github.com/certtools/intelmq/blob/master/intelmq/lib/utils.py#L227
