### ISSUE TITLE
Packaging and distribution

### ISSUE THREAD

**Issue by sebix** [certtools/intelmq#391]
As we come closer to a final stable version, we need to think more about distribution and packaging.

I want to address some topics:
- Remove support for old `setup.py` in favor of pip. setup.py has many disadvantages. See e.g. the numpy-discussion list: [[Numpy-discussion] Proposal: stop supporting 'setup.py install'; start requiring 'pip install .' instead](https://mail.scipy.org/pipermail/numpy-discussion/2015-October/074086.html)
- do we want to provide packages? Or should users require to clone and checkout the current tags (releases)?
  - if, yes, upload wheel packages to pypi
  - [Python Packaging Guide](https://packaging.python.org/en/latest/)
- automatically test these packages: [Build and test wheel packages on Linux, OSX & Windows](http://www.pyvideo.org/video/3473/build-and-test-wheel-packages-on-linux-osx-win)

**Comment by aaronkaplan** [comment]
> On 03 Nov 2015, at 21:39, Sebastian <notifications@github.com> wrote:
> 
> As we come closer to a final stable version, we need to think more about distribution and packaging.
> 
> I want to address some topics:
> 
> 	• Remove support for old setup.py in favor of pip.

Ahm… I know for sure that at certat we’ll have to deal with debian packages. Otherwise our ops folks will slice us up into small tiny pieces ;)

Is there a way to have both pip and .deb packages?

**Comment by sebix** [comment]
> Is there a way to have both pip and .deb packages?

I don't know an argument against it.

**Comment by aaronkaplan** [comment]
> On 10 Nov 2015, at 11:43, Sebastian <notifications@github.com> wrote:
> 
> Is there a way to have both pip and .deb packages?
> 
> I don't know an argument against it.
> 

okay, —verbose:
Is there a tool which can generate / supports both formats ? Or is it all done manually?

**Comment by elationfoundation** [comment]
I was just looking into this for another project and the best explanation of the "proper" way to do this that I found was in this stack-overflow post. https://askubuntu.com/questions/327543/how-can-a-debian-package-install-python-modules-from-pypi

**Comment by sebix** [comment]
wheel packages via pip - done!

Are deb/rpm-packages necessary for milestone 1.0 or for future versions? We are past due by 4 months for 1.0

**Comment by aaronkaplan** [comment]
At least for certat "production" state I'd say yes. 

---
Mobile

**Comment by dmth** [comment]
A configuration to build *.deb Packages exists in
https://github.com/Intevation/intelmq/tree/deb-packaging

A bunch of recommended dependencies exist for intelmq (stomp, imbox, pyasn).

We've also done that for intelmq-manager.
