### ISSUE TITLE
Missing gnutls/gnutls.h on Debian 8 due to missing libgnutls28-dev

### ISSUE THREAD

**Issue by seamustuohy** [certtools/intelmq#392]
I was installing intelmq on a headless Debian 8 machine following the Python3 instructions when I encountered an error in my install. After typing in ```pip3 install -r REQUIREMENTS```  in the [installation instructions](https://github.com/certtools/intelmq/blob/master/docs/User-Guide.md#python-34-recommended-1) I encountered an fatal error that stated that I was missing ```gnutls/gnutls.h:``` 

It seems that on headless Debian installations libgnutls28-dev is not installed and is required for these instructions to finish. I ran ```apt-get install libgnutls28-dev``` and re-tried ```pip3 install -r REQUIREMENTS``` and it completed successfully. It might make sense to add libgnutls28-dev to the apt-get instructions just in case a user is on a headless system that does not have it installed by the user-space packages.

**Comment by sebix** [comment]
Which package requires the `gnutls.h`? I suspect zmq as it is the only package which needs to be compiled.

On Ubuntu 14.04 the package `libcurl4-gnutls-dev` (mentioned as requirement) depends on `libgnutls-dev`. Does a package `libgnutls-dev` exist on Debian 8 as virtual package for `libgnutls28-dev`? Would make the installation instructions a bit easier to read.

**Comment by elationfoundation** [comment]
The error occurs when pip is building the pycurl extension. ```src/pycurl.h:164:30``` has the fatal error because of the line ```#include <gnutls/gnutls.h>. It looks like there is a libgnutls-dev. I just grabbed libgnutls28-dev because apt-file pointed at that package as the one with gnutls.h.

**Comment by sebix** [comment]
Interesting that `libgnutls28-dev` is not necessary on all platforms, I committed a documentation fix, should get merged today or tomorrow.

**Comment by sebix** [comment]
fixed by c351b568003c3df18babd7228a2e7ab98a626b70
