### ISSUE TITLE
need to fix default processing behaviour: no stopping on failures of individual events

### ISSUE THREAD

**Issue by aaronkaplan** [certtools/intelmq#402]
(this is related to Tomas' PR)

As discussed today with @sebix we need to change the default behaviour of intelmq bots:

  1. a parser but **MUST** accept only those events that he can parse. Everything else gets dumped (logged) (for potential analysis and later re-injection via the dumptool). After an event got sucessfully parsed, the later bots (experts , output) can rely on valid data. But they can not rely on all the necessary data being there.
  2. an expert bot or output bot **MUST** assume that data it receives is incomplete (though it can assume that it's syntactically and semantically valid). If some key-value pairs in an event are missing, it **MUST** either assume sane default values and complain (log) and continue to pass on the event OR it **MUST** reject the event (dump it - as above) and continue with the next event. It must never stop processing.
  3. administrators of the system MUST have an easy way to figure out how many events were dumped in each processing stage (could this be shown in the intelmq-manager?) and give the possibility to edit the data and reinject it at the right place (-> dump tool)
  4. All of this needs to be documented in a tutorial-style walk through
  5. Add test-cases to each bot for failing data

**Comment by mauroasilva** [comment]
1. Completely agree.
2. Agreed. Parser, Expert and Output bots should always terminate with either an '''acknowledge_message''' or a '''dump_message'''.
3. By processing stage you mean, in which bot it was dumped? Because each bot has it's own dump file.
4. Agreed.
5. Agreed.

**Comment by aaronkaplan** [comment]
done.
