### ISSUE TITLE
merge certat repo with certtools

### ISSUE THREAD

**Issue by aaronkaplan** [certtools/intelmq#403]
As discussed today - it makes more sense to combine the certat/intelmq github repo with the main certtools/intelmq repo. Please let's have the certat specific bots added under for example contrib/.
Also a README.md for each of them - to explain that they are certat specific but can serve as an example for other users might make sense.

This way other users can at least discover it.

**Comment by mauroasilva** [comment]
Hmm... is having a contrib folder really the way we want to go? My personal opinion is that we should keep it separate. We can create a repo for it under the certtools and a link to it in the README or something like that, but I think everything in the main repo should be up to date and functional, and to have a contrib folder would mean we would have to make sure every contrib bot would function as we upgrade the core.

**Comment by aaronkaplan** [comment]
> On 23 Nov 2015, at 16:18, mauroasilva <notifications@github.com> wrote:
> 
> Hmm... is having a contrib folder really the way we want to go? My personal opinion is that we should keep it separate.

It is a matter of having too much complexity with merges from different repos.
I think it’s easier to put it to a contrib/ subfolder. Especially because other CERTs also were interested in the specific code (RTIR interface, etc)

> We can create a repo for it under the certtools
nonon :) It is already a repo. No more extra repos please :) It’s too much for me hehe.

> and a link to it in the README or something like that, but I think everything in the main repo should be up to date and functional, and to have a contrib folder would mean we would have to make sure every contrib bot would function as we upgrade the core.
No, it does not mean that. It’s just a collection of additional stuff that you can look at but don’t have to look at for getting the core intelmq to run.

My 2 cents,
a.

**Comment by mauroasilva** [comment]
On Mon, Nov 23, 2015 at 3:22 PM, AaronK <notifications@github.com> wrote:

>
> > On 23 Nov 2015, at 16:18, mauroasilva <notifications@github.com> wrote:
> >
> > Hmm... is having a contrib folder really the way we want to go? My
> personal opinion is that we should keep it separate.
>
> It is a matter of having too much complexity with merges from different
> repos.
> I think it’s easier to put it to a contrib/ subfolder. Especially because
> other CERTs also were interested in the specific code (RTIR interface, etc)
>
I agree with a solution to share those bots with the community but if we
look at examples like Logstash, they also use a repo for the core and
another for plugin/extra stuff... I know it is not quite the same but I'm
not sure if having stuff that is not actively maintained in a folder within
the main repo could push new users away because they get frustrated that
stuff in the main repo is not working properly. Don't you agree?


> > We can create a repo for it under the certtools
> nonon :) It is already a repo. No more extra repos please :) It’s too much
> for me hehe.
>

Ok... instead of creating we could move the certat repo to certtools or
something like that.

**Comment by aaronkaplan** [comment]
decided against it for the moment

**Comment by aaronkaplan** [comment]
we stayed with a separate certat repo.
We will continue to put cert.at specific code there and port it over to the main repo, as soon as it is
 1. generic enough and
 2. stable enough.
