### ISSUE TITLE
Malware Domain List parser doesn't sanitize IP properly

### ISSUE THREAD

**Issue by putsi** [certtools/intelmq#406]
Malware domain list parser fails to parse rows where IP-column contains URL.
For example [this entry](http://www.malwaredomainlist.com/mdl.php?search=38yes3.exe) fails to parse and results in following exception:

```
==> /opt/intelmq/var/log/malware-domain-list-parser.log <==
  File "/usr/local/lib/python3.4/dist-packages/intelmq-1.0.0-py3.4.egg/intelmq/bots/parsers/malwaredomainlist/parser.py", line 47, in process
    event.add(key, value, sanitize=True)
  File "/usr/local/lib/python3.4/dist-packages/intelmq-1.0.0-py3.4.egg/intelmq/lib/message.py", line 121, in add
    raise exceptions.InvalidValue(key, old_value)
intelmq.lib.exceptions.InvalidValue: invalid value '155.133.18.117/38yes3.exe' (<class 'str'>) for key 'source.ip' :
```

**Comment by aaronkaplan** [comment]
Hi Putsi, Yes, I found the same bug yesterday and made a patch specifically for the malware domain list parser . As you noted, sometimes the malware domain list feed actually supplies something which is like a URL (but with IP addresses) in the ip field. I think we can salvage the IP address from that info. 

The patch is not yet upstream but will send it there soon.

**Comment by putsi** [comment]
:thumbsup: :thumbsup:

**Comment by sebix** [comment]
Not fixed yet, reopen.
