### ISSUE TITLE
Fix comma on BOTS file

### ISSUE THREAD

**Issue by rmkml** [certtools/intelmq#407]
Hi,
First, Thx for a great project!
Please add a comma on line 865 BOTS file:

861: "N6Stomp": {
862:             "description": "N6 Collector - CERT.pl's N6 Parser - N6 feed via STOMP interface",
863:             "module": "intelmq.bots.parsers.n6.parser_n6stomp",
864:             "parameters": {}
865:         } # <- needed here
866:         "OpenBL": {

Regards
@Rmkml

**Comment by mauroasilva** [comment]
Hey thanks a lot, you are right. It's already fixed ;)
