### ISSUE TITLE
geoip / asn lookup - keep the source data up-to-date

### ISSUE THREAD

**Issue by robcza** [certtools/intelmq#408]
This is low priority issue, however I'm sure everyone will have to deal with this sooner or later. There is no mechanism in IntelMQ to keep local databases used for different sort of lookups up-to-date. E.g. you download maxmind geoip database, you run the IntelMQ botnets and several days later you run expert bot with outdated data.
- Should this be handled by IntelMQ itself? - I think yes, but it introduces another complexity
- If not, do you handle it byt a set of external script updating the databases and restarting the bots?

**Comment by sebix** [comment]
We can provide commandlines for cronjobs in a future vendor directory (as with logration and rsyslog config examples). Same applies to asn-lookup databases.

**Comment by aaronkaplan** [comment]
> On 02 Dec 2015, at 12:24, Robert Šefr <notifications@github.com> wrote:
> 
> This is low priority issue, however I'm sure everyone will have to deal with this sooner or later. There is no mechanism in IntelMQ to keep local databases used for different sort of lookups up-to-date. E.g. you download maxmind geoip database, you run the IntelMQ botnets and several days later you run expert bot with outdated data.
> 
> 	• Should this be handled by IntelMQ itself? - I think yes, but it introduces another complexity

IMHO no.
But we can provide example update scripts which can be run by cron(1) in a contrib/ subfolder.

My opinion...

**Comment by aaronkaplan** [comment]
> On 02 Dec 2015, at 19:34, Sebastian <notifications@github.com> wrote:
> 
> We can provide commandlines for cronjobs in a future vendor directory (as with logration and rsyslog config examples). Same applies to asn-lookup databases.
> 
Yes, sorry - just saw that you answered in the same way :) I agree!

**Comment by robcza** [comment]
I think putting those examples in the bot readme would be the proper place. And would be appreciated by anyone using them. By me for instance :)

**Comment by aaronkaplan** [comment]
> On 04 Dec 2015, at 09:58, Robert Šefr <notifications@github.com> wrote:
> 
> I think putting those examples in the bot readme would be the proper place. And would be appreciated by anyone using them. By me for instance :)
> 

Agreed!
Will do :)

**Comment by mauroasilva** [comment]
I also agree with the approach to not adding that logic to the bots themselves but have some kind of script to do it. Putting the script itself into the readme can be a little awkward unless it is 2/3 lines, so we may need a different solution for the general case. Maybe a mention of the location of the update-script into the readme but the script itself is elsewhere.

**Comment by robcza** [comment]
@aaronkaplan can I ask you for the examples?

**Comment by aaronkaplan** [comment]
> On 28 Dec 2015, at 14:42, Robert Šefr <notifications@github.com> wrote:
> 
> @aaronkaplan can I ask you for the examples?
> 

Yes, sorry need to add them to a contrib/ folder.

**Comment by robcza** [comment]
@aaronkaplan Thank you!

**Comment by aaronkaplan** [comment]
> On 10 Jan 2016, at 23:14, Robert Šefr <notifications@github.com> wrote:
> 
> Closed #408.

Did you test it?
What I do not like about the pyasn update script: it relies on FTP. And thus is not so easy to get through a proxy.
It also does not support the ftp_proxy env vars either.
But that's an issue in the pyasn library.


a.
