### ISSUE TITLE
sanitize=True as default?

### ISSUE THREAD

**Issue by sebix** [certtools/intelmq#415]
We almost always use `event.add(key, val, sanitize=True)`, mostly because of bytes -> string conversion, but also cleanups (trim, lower case) or applying functions (base64). Can you think of any case where it might be a bad idea to have `sanitize=True` as default value for `event.add`?

**Comment by aaronkaplan** [comment]
no

**Comment by aaronkaplan** [comment]
What's the status on this discussion? Can we close it and make sanitize=True the default (implicit) behaviour?

**Comment by mauroasilva** [comment]
I agree that default sanitization makes sense. If any bot needs something to be added and not sanitized it should be forced to have ```sanitize = False```
