### ISSUE TITLE
error reporting: if some parser / bot fails, have the possibility to email the errors

### ISSUE THREAD

**Issue by aaronkaplan** [certtools/intelmq#417]
Having the errors in the log file is nice, but our NOC team says we'd like to be notified actively.
Think about a mechanism how to alert NOC team handlers of stack traces / error messages so that
1. we know that it's happening
2. the NOC team gets overloaded with too many stack traces. So, please aggregate it.

**Comment by sebix** [comment]
> the NOC team gets overloaded with too many stack traces. So, please aggregate it.

[logcheck](http://linux.die.net/man/8/logcheck) can do this. We could provide the regexes, for ignore and violation rules.

**Comment by wagner-certat** [comment]
example logcheck settings are available in contrib
