### ISSUE TITLE
(Ubuntu 14.04,Python 3.4) Dependecy to 'psutil' missing

### ISSUE THREAD

**Issue by imifos** [certtools/intelmq#422]
Hi there,

I tested the installation on the above said configuration and had a problem with a missing dependency to 'psutil' (compared to what's described in the https://github.com/certtools/intelmq/blob/master/docs/User-Guide.md)

> https://github.com/giampaolo/psutil/blob/master/INSTALL.rst
> apt-get install gcc python-dev
> wget https://bootstrap.pypa.io/get-pip.py
> python get-pip.py
> pip install psutil

...solved that for me.

All the best :)
/tc

**Comment by aaronkaplan** [comment]
Hello! 

Thanks for letting us know. 

---
Mobile

**Comment by sebix** [comment]
What operating system do you use? pip versions are quite old unfortunately for some OS, eg. Cent OS 7 (installation of current pip is documented for this one in the docs). 

We do have psutil in the REQUIREMENTS files.

**Comment by imifos** [comment]
UBUNTU 14.4.3 LTS. I haven't read documents, I just followed the installation guide in the master/User-Guide.md.
Best,/tc

**Comment by sebix** [comment]
I guess installation of psutil (via pip) failed, but hasn't been noticed in the wall of text-output. added the requirement to the docs. Thanks @imifos
