### ISSUE TITLE
Installing custom Bots

### ISSUE THREAD

**Issue by kevthehermit** [certtools/intelmq#440]
Im writing output bots and will soon start writing collector / parser bots. 
How do you correctly install them. 

At the moment i am backing up my config files. running the python setup.py install then restoring my config. 

This works and my bots are installed, and run correctly. the issue im having is its clearing all my cache and queues, so when i start the bots again im getting duplicate data go in to my splunk instance. 

Is there another way to install them, was hoping to just drop them in to a folder in /opt/intelmq somewhere but there isnt a file path for them. 

Thanks.

**Comment by aaronkaplan** [comment]
> On 22 Jan 2016, at 14:15, kevthehermit <notifications@github.com> wrote:
> 
> Im writing output bots and will soon start writing collector / parser bots.
> How do you correctly install them.
> 
> At the moment i am backing up my config files. running the python setup.py install then restoring my config.
> 
> This works and my bots are installed, and run correctly. the issue im having is its clearing all my cache and queues, so when i start the bots again im getting duplicate data go in to my splunk instance.
> 

I usually send all the collectors/parsers to a deduplicator bot and then do the rest of the processing.
This way the duplicates get filtered out.

**Comment by sebix** [comment]
>Im writing output bots and will soon start writing collector / parser bots.
How do you correctly install them.

>At the moment i am backing up my config files. running the python setup.py install then restoring my config.

Yeah, installing the whole software again is currently the only option. Any change here will not happen before the 1.0, our focus is on other issues until then.

It may be appreciable to have a simpler method to
- install custom bots more easily
- utilities to develop, deploy (locally) and run bots. I have parts of this on my local machine, I can push it next week.

Unfortunately, the first issue will not be so easy to solve.

> This works and my bots are installed, and run correctly. the issue im having is its clearing all my cache and queues, so when i start the bots again im getting duplicate data go in to my splunk instance.

Redis (where cache and queues are living) should be untouched by the installation. But as the collectors will have to be restarted, they provide you with much of data. As Aaron said, a deduplicator is necessary anyway.

> Is there another way to install them, was hoping to just drop them in to a folder in /opt/intelmq somewhere but there isnt a file path for them.

Python Packages are installed to `/usr/local/lib/python{3.4,2.7}/dist-packages/`

**Comment by kevthehermit** [comment]
Yeah thanks have a dedup in line now and that seems to be playing nicely. Love this platform. Im reinstalling to add new bots. Not a major hassle.  I noticed an issue with the update guide. The guide says to ```cp -R /opt/intelmq``` and then replace it afterwards. 

This replaces the conf files in etc/ but also replaces the files in bin/ etc. so any update to these files would never actually get updated as you always replace them with old ones. 

should this not be ```cp -R /opt/intelmq/etc/```

**Comment by sebix** [comment]
Thanks, directly fixed that one in master.

**Comment by aaronkaplan** [comment]
> On 26 Jan 2016, at 11:00, kevthehermit <notifications@github.com> wrote:
> 
> Yeah thanks have a dedup in line now and that seems to be playing nicely. Love this platform. Im reinstalling to add new bots. Not a major hassle. I noticed an issue with the update guide. The guide says to cp -R /opt/intelmq and then replace it afterwards.
> 
> This replaces the conf files in etc/ but also replaces the files in bin/ etc. so any update to these files would never actually get updated as you always replace them with old ones.
> 
> should this not be cp -R /opt/intelmq/etc/

Agreed you are right! Thanks for noticing :)

**Comment by sebix** [comment]
Hi,

intelmq is now installable via pip, both from pypi (`pip install -U intelmq`) and locally (`pip install -eU .`). See also the documentation: https://github.com/certtools/intelmq/wiki/Developers-Guide

Please comment or reopen if you encounter uncertainties, problems etc.

**Comment by exitnode** [comment]
I wrote my own Bot and added it to the BOTS file. It works when manually executed like this:

`intelmqctl run tldextract-Expert`

The problem is that it is not controllable e.g. via IntelMQ Manager since there is no file "/usr/bin/intelmq.bots.experts.tldextract.expert". Manually creating and editing this file leads to the following error:

`$ /usr/bin/intelmq.bots.experts.tldextract.expert
Traceback (most recent call last):
  File "/usr/bin/intelmq.bots.experts.tldextract.expert", line 11, in <module>
    load_entry_point('intelmq==2.2.1', 'console_scripts', 'intelmq.bots.experts.tldextract.expert')()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 489, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2792, in load_entry_point
    raise ImportError("Entry point %r not found" % ((group, name),))
ImportError: Entry point ('console_scripts', 'intelmq.bots.experts.tldextract.expert') not found`

This is how the file looks like:
```
#!/usr/bin/python3
# EASY-INSTALL-ENTRY-SCRIPT: 'intelmq==2.2.1','console_scripts','intelmq.bots.experts.tldextract.expert'
__requires__ = 'intelmq==2.2.1'
import re
import sys
from pkg_resources import load_entry_point

if __name__ == '__main__':
    sys.argv[0] = re.sub(r'(-script\.pyw?|\.exe)?$', '', sys.argv[0])
    sys.exit(
        load_entry_point('intelmq==2.2.1', 'console_scripts', 'intelmq.bots.experts.tldextract.expert')()
    )
```

The configuration inside the BOTS file:
```
        "tldextract": {
            "description": "REDACTED",
            "module": "intelmq.bots.experts.tldextract.expert",
            "parameters": {}
        }
```

The bot itself is located in /usr/lib/python3/dist-packages/intelmq/bots/experts/tldextract/expert.py and looks like this:

```
# -*- coding: utf-8 -*-
from urllib.parse import urlparse

from intelmq.lib.bot import Bot
import tldextract


class TLDExtractExpertBot(Bot):

    def process(self):
        event = self.receive_message()

        [...LOGIC...]

        self.send_message(event)
        self.acknowledge_message()

BOT = TLDExtractExpertBot
```

What else is there to do? Is there a tool that installs self-developed bots so it will be correctly recognized by IntelMQ? Did I miss something?
