### ISSUE TITLE
Log path not found:

### ISSUE THREAD

**Issue by kevthehermit** [certtools/intelmq#442]
When i create a new collector / parser the install runs ok but when i use the web manager it fails to start with no logs generated. 

```
tail /opt/intelmq/var/log/intelmqctl.log
2016-01-28 13:55:03,001 - intelmqctl - ERROR - Log path not found: /opt/intelmq/var/log/dynamoo-parser.log
2016-01-28 13:55:04,632 - intelmqctl - ERROR - Log path not found: /opt/intelmq/var/log/dynamoo-phishing-collector.log
2016-01-28 13:55:05,818 - intelmqctl - ERROR - Log path not found: /opt/intelmq/var/log/dynamoo-parser.log

```

fix by:

```
root@intel:~# sudo -i -u intelmq
intelmq@intel:~$ touch /opt/intelmq/var/log/dynamoo-parser.log
intelmq@intel:~$ touch /opt/intelmq/var/log/dynamoo-phishing-collector.log

```

**Comment by sebix** [comment]
Thanks for your report.

I will have a look next week, but looks like the intelmq-manager wants to read the logs, before the bot has been started for the first time. In this case, it's an issue for the manager.

**Comment by mauroasilva** [comment]
Hello, 

I made a fix to the way intelmq-manager was loading the logs, can you see if it fixes your problem please?

**Comment by aaronkaplan** [comment]
@kevthehermit does that work now for you?

**Comment by kevthehermit** [comment]
Sorry for the delay, just updated, still getting the error. Will post more detail when i get a chance.
