### ISSUE TITLE
bot: ipasn expert is incomplete

### ISSUE THREAD

**Issue by aaronkaplan** [certtools/intelmq#443]
Summary: some IP addresses can't be matched against an ASN, however, in other databases (stats.ripe.net, team cymru, etc) they **can** be matched against an ASN. 
My conclusion is that the pyasn library / data source is incomplete and we should ditch it for something else IMHO.

Proof (from an interactive ipython session with the latest RIB file from pyasn):

```
In [1]: import pyasn

In [2]: database = pyasn.pyasn("ipasn.dat")

In [3]: info = database.lookup("5.167.67.85")

In [4]: print info
(None, None)
```

However, lookup up that data in whois returns:

```
% whois -r 5.167.67.85
% This is the RIPE Database query service.
% The objects are in RPSL format.
%
% The RIPE Database is subject to Terms and Conditions.
% See http://www.ripe.net/db/support/db-terms-conditions.pdf

% Note: this output has been filtered.
%       To receive output for a database update, use the "-B" flag.

% Information related to '5.167.64.0 - 5.167.71.255'

% Abuse contact for '5.167.64.0 - 5.167.71.255' is 'abuse@domru.ru'

inetnum:        5.167.64.0 - 5.167.71.255
netname:        ERTH-YOLA-PPPOE-12-NET
(...)
role:           Network Operation Center CJSC ER-Telecom Company Mari El branch
(...)
% Information related to '5.167.64.0/22AS41786'

route:          5.167.64.0/22
origin:         AS41786
(...)
source:         RIPE # Filtered

```

So that data exists.

**Comment by aaronkaplan** [comment]
Maybe we also need a chain of ip2asn database lookups.

**Comment by sebix** [comment]
Please report issues related to pyasn itself at it's bugtracker: https://github.com/hadiasghari/pyasn/issues

**Comment by aaronkaplan** [comment]
> On 02 Feb 2016, at 09:15, Sebastian <notifications@github.com> wrote:
> 
> Please report issues related to pyasn itself at it's bugtracker: https://github.com/hadiasghari/pyasn/issues
> 

@sebix, sorry no this is an issue we deal with at intelmq. Yes, sure it helps to report that upstream.
But it will be a reality for ever that some sources/databases have incomplete data. Hence the question is **for us**: how do **we** deal with it?
Let's discuss this today and come up with a solution.

I put this in a ticket so that I do not forget to discuss this :)
That's why it's a ticket.

best,
a.

**Comment by dmth** [comment]
@aaronkaplan does this issue still appear, when using other sources for the data, e.g. the dumps from ripe we used in the blog post?

In case of chaining: What if two databases have contradictory information? How to tell which data was used? Who is to "blame" in case of errors, wrong data, etc?

**Comment by aaronkaplan** [comment]
Yes, this issue actually can be still observed in practice. I guess the best approach would be to have a chain of experts:

```
   --> pyasn's asn_lookup ---> stats.ripe.net lookup --> ... (possibly a live BGP routing table) ... -->
                                                 ^--- this only adds the ASN field if it does not already exists
```

We have  a couple of thousands rows in the eventDB which don't have an ASN. We need to re-inject them into intelmq. So, yes, this does happen.

**Comment by wagner-certat** [comment]
We have multiple sources for ASN data.
