### ISSUE TITLE
Fresh Installation failing: No module named intelmq.lib.pipeline

### ISSUE THREAD

**Issue by bitvijays** [certtools/intelmq#452]
Hello Everyone, Thank you for creating and supporting such a great tool. I was trying to install intelmq and use it basically to collect twitter feeds from packetstorm. However, I am facing few difficulties such as after doing a fresh install of intelmq.

When I start
```console
$ su - intelmq
# intelmqctl 
Traceback (most recent call last):
  File "/opt/intelmq/bin/intelmqctl", line 14, in <module>
    from intelmq.lib.pipeline import PipelineFactory
ImportError: No module named intelmq.lib.pipeline
```
I tried searching this error but couldn't found much. Would appreciate any help in resolving this. 
Also, any documentation on setting up a twitter feed would be great.

Cheers,
bitvijays

**Comment by sebix** [comment]
>     % intelmqctl
>     Traceback (most recent call last):
>     File "/opt/intelmq/bin/intelmqctl", line 14, in
>     from intelmq.lib.pipeline import PipelineFactory
>     ImportError: No module named intelmq.lib.pipeline

Which OS and which commands did you use to install it? I'll try to reproduce.

Please note, that the software is still in alpha stage. The installation has been vastly improved in #451, which I just merged as there were no objections, but still need some testing and feedback from others.

> Also, any documentation on setting up a twitter feed would be great.

We don't have one yet. Could you give a link, so someone has the chance to implement it?

**Comment by bitvijays** [comment]
Thanks sebix. Appreciate your support on this.

I am trying to install this on Kali Linux 2.0 and followed the User-Guide mentioned here for Python 3: https://github.com/certtools/intelmq/blob/master/docs/User-Guide.md

Twitter feed which I want to follow is https://twitter.com/packet_storm.

Actually, I previously installed intelmq ( not sure if it was working then ), so uninstalled it using rm -rf /opt/intelmq. Let me know if there is something else which can be used to uninstall or trying again?

Cheers,
bitvijays

**Comment by sebix** [comment]
> I am trying to install this on Kali Linux 2.0 and followed the User-Guide mentioned here for Python 3: https://github.com/certtools/intelmq/blob/master/docs/User-Guide.md

> Actually, I previously installed intelmq ( not sure if it was working then ), so uninstalled it using `rm -rf /opt/intelmq`. Let me know if there is something else which can be used to uninstall or trying again?

Removing `/opt/intelmq` does not remove the libraries in `/usr/local/lib/python*/dist-packages/intelmq*`. Use `pip uninstall intelmq` or running rm on that directory to do this. Alternatively, an upgrade with `pip install -U intelmq` always includes a uninstallation.
I pushed a few changes in the meantime, so please pull them first if you have a local copy of the repository. (Or do `pip install intelmq -U --pre`)

> Twitter feed which I want to follow is https://twitter.com/packet_storm.

How you want to parse this data? There are no identities listed. have a look at our Data [Harmonization document](https://github.com/certtools/intelmq/wiki/Data-Harmonization) and especially the last section about minimum requirements.

**Comment by bitvijays** [comment]
Thanks sebix. :) That solved the installation issue. Will look over the Data Harmonization document. Majorly, the idea was to store the tweets of packet_storm and other sources, locally on disk for a quick referral during the penetration testing. As, twitter only allows the scraping of 3200 previous tweets. Don't want to miss any.

Thanks again.

**Comment by sebix** [comment]
> Majorly, the idea was to store the tweets of packet_storm and other sources, locally on disk for a quick referral during the penetration testing. As, twitter only allows the scraping of 3200 previous tweets. Don't want to miss any.

You will have to write your own parser for this. The collector is independent of the data's topology (and format etc) but nevertheless we don't have one currently. But a possible use-case of course.
