### ISSUE TITLE
Automatic unzipping: problematic?

### ISSUE THREAD

**Issue by sebix** [certtools/intelmq#460]
Automatic unzipping for downloaded files is done by the http collector and the upcoming ftp collector by #455. Think of some formats, that use zip as containers (e.g. nearly all office formats). Unzipping them breaks the content/parsing. 

We could look at the mimetype to decide whether we unzip or not. Or do you think we will either never have these problems?

**Comment by robcza** [comment]
The point with office file formats is valid, however not probable in current state of IntelMQ (there are no office parsers). Checking the extension ```if == "zip"``` seems sufficient and will work with http as we as ftp.

**Comment by robcza** [comment]
do you agree with the extension checking as a sufficient solution?

**Comment by sebix** [comment]
Yeah, we will see in the future :)

We can always add a config option to manually override the zip-detection if needed. I always think about forward- and backward-compatibility...
