### ISSUE TITLE
stop bot problems

### ISSUE THREAD

**Issue by shirio57** [certtools/intelmq#463]
When I stop the botnet, every bots are stopped but the process of every bots is still running.
What can solve this ?

OS: red hat 7

**Comment by shirio57** [comment]
Problem found.
I try to kill a bot via "sudo htop" and using SIGINT as it is in the intelmqctl and it doesn't work.
Is it possible to change it ?

**Comment by sebix** [comment]
Was the process running as user intelmq (or root)? What does the log of the bot show?

**Comment by shirio57** [comment]
Nothing on the log, last line is bot is starting

I start the botnet with manager GUI so with "sudo -u intelmq /usr/local/bin/intelmqctl %s" so it should be intelmq as user.
When I do "ps -u intelmq" I have all the bots.
When I try to stop them by the manager there are still running. And even after by command line.

It is only when I do everything by command line that I can start and stop everything correctly.

**Comment by sebix** [comment]
Ok, it's the manager. Probably duplicate of certtools/intelmq-manager#42
Unfortunately I can't test this on red hat systems.

@mauroasilva can you have a look?

**Comment by sebix** [comment]
duplicate of #411
