### ISSUE TITLE
ENH: please let's make intelmq LSB compatible

### ISSUE THREAD

**Issue by aaronkaplan** [certtools/intelmq#470]
While /opt etc is all nice, once we move to debian packages (.deb) or RPMs, we should really be [LSB compatible](https://en.wikipedia.org/wiki/Linux_Standard_Base). 
This includes startup scripts (/etc/init.d/*... ).

**Comment by sebix** [comment]
Does this mean we abandon `/opt/intelmq` entirely? AFAIR the decision of using this directory was to separate it from the rest of the system,

This also includes rejigging the logging entirely

**Comment by aaronkaplan** [comment]
On Mon, Apr 11, 2016 at 02:59:20AM -0700, Sebastian wrote:
> Does this mean we abandon `/opt/intelmq` entirely? AFAIR the decision of using this directory was to separate it from the rest of the system,
> 
> This also includes rejigging the logging entirely

To be discussed. I think this was a discussion point.

**Comment by aaronkaplan** [comment]
should be solved by the Debian packaging PR: #595
