### ISSUE TITLE
Maxmind-geoip-expert won't start

### ISSUE THREAD

**Issue by chappi6** [certtools/intelmq#473]
Hi , 

I have a problem with the Maxmind-Geoip-expert . 
It wont start.... 
Actually there are no logs which describe the problem. 
The only entry i can find is that intelmqctl says maxmind geoip-expert is running 
The other experts and parsers are running well. 
I have taken the Geoip db file from the script which is under intelmq/contrib/cron-jobs/maxmind
Any ideas how to get logs out to find the problem?

**Comment by sebix** [comment]
Do you have `geoip2`package installed?
Try running this as intelmq user: `python3 -m intelmq.bots.experts.maxmind_geoip.expert bot-id-here` and replace the bot with what you have configured.

**Comment by chappi6** [comment]
jup geoip2 package was missing. 
Error from the command python3 -m intelmq.bots.experts.maxmind_geoip.expert
was 
Import Error: No module named 'geoip2'
I have no version geoip2 2.2.0 install 
if somebody needs it command for installing is: 
pip install geoip2 

is it possible to add the libary into the REQUIREMENTS file? So it would be possible to avoid this error ;)
