### ISSUE TITLE
Harmonization/regex for malware.name error on "yahoo!"

### ISSUE THREAD

**Issue by pedromreis** [certtools/intelmq#478]
```shell
  File "/home/intelmq/intelmq-src/intelmq/bots/parsers/cleanmx/parser_phishing.py", line 73, in process
    event.add(key, value)
  File "/home/intelmq/intelmq-src/intelmq/lib/message.py", line 125, in add
    raise exceptions.InvalidValue(key, value, reason=valid_value[1])
intelmq.lib.exceptions.InvalidValue: invalid value 'yahoo!' (<class 'str'>) for key 'malware.name' regex did not match.
```

regex change? what do you propose?

**Comment by pedromreis** [comment]
same for at&t..

**Comment by sebix** [comment]
> regex change? what do you propose?

You can of course do that. The other question, what values do we allow for the (standardized!) malware name. This field was proposed to hold a malware family name. I do not understand what `yahoo!` should be a malware name...

ping @certtools/intelmq-contributors

**Comment by aaronkaplan** [comment]
I think we should be more tolerant to allow all printable characters.
