### ISSUE TITLE
Alienvault OTX collector with proxy

### ISSUE THREAD

**Issue by pedromreis** [certtools/intelmq#479]
Current recipe to use Alienvault collector does not work to me.
I propose the following:

1. instead of using `./OTXv2.py` file, install OTX python sdk in the system
2. On `collector.py`:

    Change:    `from .OTXv2 import OTXv2`
    To:            `from OTXv2 import OTXv2`
    and
    Change:    `otx = OTXv2(self.parameters.api_key)`
    To:            `https_proxy = getattr(self.parameters, 'http_ssl_proxy', None)`
                     `otx = OTXv2(self.parameters.api_key,https_proxy)`

This works for me.
PR

**Comment by sebix** [comment]
They do not provide a pypi package yet, see AlienVault-Labs/OTX-Python-SDK#11. Additionally they do not have any stable realeses yey. We could either link their master branch (what I highly discourage, as it's an unstable development branch) or continue with the current procedure until these organizational problems are fixed upstream. I already offered my help to release packages, there's not much I can do more about this.

Concerning the proxy: Yes, looks good. I can't test it unfortunately, did you?

**Comment by pedromreis** [comment]
The proxy works with the new OTX-Python-SDK installed system-wide, not with the OTXv2.py bundled in intelmq. I guess its possible with a minor tweak to use the OTX sdk without system wide installation, but I didn't test it: just put both IndicatorTypes.py and OTXv2.py from latest sdk and make IndicatorTypes.py import local in OTXv2.py. I'll try this tomorrow if I can.

**Comment by sebix** [comment]
How you installed the SDK is not relevant for the proxy-question. Please test if the proxying works, then I can implement it in master.

**Comment by pedromreis** [comment]
With the new SDK version, the proxy works.
