### ISSUE TITLE
collector_http_stream.py in python3 not working

### ISSUE THREAD

**Issue by pedromreis** [certtools/intelmq#480]
Hi.
Not working due "data" type changed to byte in python3.
Workaround to test it:

    for line in data.decode('UTF-8').split('\n'):

BTW any parser handles json input?

PR

**Comment by sebix** [comment]
Thanks for the report, pushed a fix to master.

Which feed/source did you use to test the bot?
Currently, there is no generic JSON-parser. The [fraunhofer dga parser](https://github.com/certtools/intelmq/blob/master/intelmq/bots/parsers/fraunhofer/parser_dga.py) parses JSON.

**Comment by pedromreis** [comment]
Tks, 
I'm trying to process Bitsighttech feeds.
I'll look at that parser to see if I can use/adapt it.

Tks
