### ISSUE TITLE
Need help... parsing a message

### ISSUE THREAD

**Issue by pedromreis** [certtools/intelmq#481]
Sorry, I'm not a professional programmer, new to Python and cant get this right.
The message that arrives at the parser is like this:
```json
{"_ts":1460816182,"env":{"server_addr":"195.22.28.196","request_method":"POST","remote_addr":"186.149.252.226","server_port":"80","remote_port":"60812","server_name":"cellmonitoring.co"},"trojanfamily":"MobileSpy","_geo_env_remote_addr":{"country_name":"Dominican Republic"}}
```

Where:
* `_ts`  = Timestamp in ????  => `time.observation`
* `env.remote_addr` = IP that accessed the sinkhole  => `source.ip`
* `env.remote_port` = Port that accessed the sinkhole => `source.port`
* `env.server_addr` = Sinkhole IP => `destination.ip`
* ...
* `trojanfamily` = Malware name => `malware.name`
* `_geo_env_remote_addr.country_name` = Country location of the IP => `source.geolocation.country`

Need help to import and access the "nested" values from the message..

Tks

PR

**Comment by sebix** [comment]
> Need help to import and access the "nested" values from the message..

This is a dictionary: https://docs.python.org/3/tutorial/datastructures.html#dictionaries

**Comment by pedromreis** [comment]
Yes, I know. 
I'm going to investigate a little more.
