### ISSUE TITLE
output to a REDIS queue

### ISSUE THREAD

**Issue by pedromreis** [certtools/intelmq#482]
I need to send the message to a REDIS queue to be consumed by another program.
Presently I created a "null redis output bot" that makes nothing, only to create the queue that I need so then previous expert bot sent the info there.
Is there a better way?

PR

**Comment by sebix** [comment]
Have a look at the pipeline implementation: https://github.com/certtools/intelmq/blob/master/intelmq/lib/pipeline.py#L95
Especially this line: `self.pipe.lpush(destination_queue, message)`

Docs: https://redis-py.readthedocs.org/en/latest/

**Comment by pedromreis** [comment]
Ok, I will look at that.

Tks
