### ISSUE TITLE
Need some help on a debug point

### ISSUE THREAD

**Issue by pedromreis** [certtools/intelmq#489]
Sorry about the noob question.
Who can i make a debug point in a parser that prints the report that receives?
And after that the message that sends forward.

Thanks

**Comment by pedromreis** [comment]
I think 
        print (report.deep_copy())
and
        print ( event.to_json() )
Does what I need

**Comment by sebix** [comment]
Just printing `report` or `event` works too. With `repr()` around you get more details on data types.

```python
print(repr(report))
```

The variables are just extended dictionaries.
