### ISSUE TITLE
Modify bot only accepts string fields as parameter?

### ISSUE THREAD

**Issue by pedromreis** [certtools/intelmq#501]
Or I'm I making something wrong...
If I have a `modify.conf` like:

```python
{
"default": {
    "set_target_tag": [{
            "source.asn": "65500"
        }, {
            "event_description.target": "My company"
        }]
    }
}
```

I get:

```python
Traceback (most recent call last):
  File "/usr/lib/python3.4/site-packages/intelmq-1.0.0.dev4-py3.4.egg/intelmq/lib/bot.py", line 102, in start
    self.process()
  File "/usr/lib/python3.4/site-packages/intelmq-1.0.0.dev4-py3.4.egg/intelmq/bots/experts/modify/expert.py", line 55, in process
    if matches(event, default_cond, rule_cond):
  File "/usr/lib/python3.4/site-packages/intelmq-1.0.0.dev4-py3.4.egg/intelmq/bots/experts/modify/expert.py", line 26, in matches
    if not re.search(rule, event[name]):
  File "/usr/lib64/python3.4/re.py", line 170, in search
    return _compile(pattern, flags).search(string)
TypeError: expected string or buffer
```

**Comment by sebix** [comment]
Thanks for the report. Pushed a fix to master. Make sure, the types in the event and the rules do match (in your example, asn is a string).

**Comment by pedromreis** [comment]
Hi.
So, how can I get a regex on a int field?
If I want to match all ^64[0-9][0-9][0-9] how should I do?
Using the above does not work if I put between "" or out.

**Comment by sebix** [comment]
Okay, so I propose:
* If the types do match, and the types are not string, do a `==` comparison.
* If the types do not match
  * if rule is string and data is int or float, convert data to string and do a `re.search`
  * warn otherwise

**Comment by pedromreis** [comment]
So we can match, for example:

"source.port": 443 
or
"source.port": "80|443"

Is that it? Like it :)

**Comment by sebix** [comment]
You can now use this:
```python
"Standard Protocols": {
    "http": [{
            "source.port": "^(80|443)$"
        }, {
            "protocol.application": "http"
        }]
    }
```
