### ISSUE TITLE
Can intelmq communicate with splunk?

### ISSUE THREAD

**Issue by Hacker-One** [certtools/intelmq#504]
I want to know that how can intelmq communicate with splunk?

**Comment by SYNchroACK** [comment]
For those who also need this feature working:

1. Configure Splunk to be able to receive logs(intelmq events) to a tcp port
2. Use tcp output bot and configure accordingly to the Splunk configuration that you applied.

**Comment by aaronkaplan** [comment]
Tomas this sounds very much like it could be an FAQ item. Shall we add it to the FAQ?

---
Mobile

**Comment by SYNchroACK** [comment]
Good idea! Done f73d0eb
