### ISSUE TITLE
Documentation in docs/ vs. Wiki

### ISSUE THREAD

**Issue by dmth** [certtools/intelmq#511]
Matthew Duncan discovered that the documentation differs between the .md files in docs/ and the github-wiki. It is unclear which instructions have to be used.

https://github.com/certtools/intelmq/blob/master/docs/User-Guide.md
vs.
https://github.com/certtools/intelmq/wiki/User-Guide

We should clean this up and focus on writing documentation only once.
It's not good to maintain the docs in two places.

Proposal:
- Drop User-Guides from docs/ directory and only maintain information for developers there.
- Drop Developers-Guide from Wiki

**Comment by aaronkaplan** [comment]
On Wed, May 11, 2016 at 03:08:14AM -0700, Dustin Demuth wrote:
> Matthew Duncan discovered that the documentation differs between the .md files in docs/ and the github-wiki. It is unclear which instructions have to be used.
> 
Nice catch. The wiki is outdated.

> https://github.com/certtools/intelmq/blob/master/docs/User-Guide.md
> vs.
> https://github.com/certtools/intelmq/wiki/User-Guide
> 
> We should clean this up and focus on writing documentation only once.
Agreed!

> It's not good to maintain the docs in two places.
> 

Let's kick out the wiki pages.
This will move to the official web page.

> Proposal:
> * Drop User-Guides from docs/ directory and only maintain information for developers there.
> * Drop Developers-Guide from Wiki
> 
> ---
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/certtools/intelmq/issues/511

--

**Comment by sebix** [comment]
As the wiki is just another git-repository, `docs/` could also be a submodule containing the wiki.

**Comment by aaronkaplan** [comment]
On Wed, May 11, 2016 at 09:32:45AM -0700, Sebastian wrote:
> As the wiki is just another git-repository, `docs/` could also be a submodule containing the wiki.

Also possible. But what I am saying is that docs/ (the current version)
is the most up to date one. 


> 
> ---
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub:
> https://github.com/certtools/intelmq/issues/511#issuecomment-218515032

--

**Comment by dmth** [comment]
From my Point of view, we did not come to an Agreement about Documentation, right?
How to do things now?

**Comment by sebix** [comment]
I now pushed docs/ to the wiki. Some links are broken (would need some automatic replacement with a script), is this acceptable for you @aaronkaplan? Or should be remove them and point to docs/ only?

**Comment by aaronkaplan** [comment]
IMHO : fewer places for documentation (actually, *one* place!) is the way to go.

**Comment by bernhardreiter** [comment]
If the wiki is just a copy of the source code documentation files from some point in time, we should just remove the contents of the wiki. To only have one place for the documentation, which then for the source code related stuff is the repo. (Like @aaronkaplan says.)

**Comment by dmth** [comment]
Is the wiki still maintained manually by pushing the docs folder to it? Can't we simply delete the wikis content and point to the docs/ folder, as @aaronkaplan suggested?

**Comment by sebix** [comment]
> Is the wiki still maintained manually by pushing the docs folder to it?

Yes, I do it regularly.

> Can't we simply delete the wikis content and point to the docs/ folder, as @aaronkaplan suggested?

I don't know the status of this.

**Comment by wagner-certat** [comment]
Wiki has been removed yesterday by @aaronkaplan
