### ISSUE TITLE
Send multiple messages at once

### ISSUE THREAD

**Issue by ondj** [certtools/intelmq#513]
Some collectors Report contain multiple Event, so parser in one `process` call receive one and send multiple messages. But this is vulnerable, because for example in this simple implementation is source IP address invalid or some other exception is thrown and `error_procedure` is set to `pass` (which is a default behavior), events processed before the invalid event are duplicated because bot tries to parse Report multiple times.

```python
def process(self):
    report = self.receive_message()
    for parsed in parse(report):
    	event = Event(report)
    	event.add("source.ip", parsed.source_ip)
    	self.send_message(event)
    self.acknowledge_message()
```

It can by solved by:
* adding ability to send_message to send multiple at once. Then, the usage look like:
```python
def process(self):
    report = self.receive_message()
    events = []
    for parsed in parse(report):
    	event = Event(report)
    	event.add("source.ip", parsed.source_ip)
    	events.push(event)
    self.send_message(events)
    self.acknowledge_message()
```
* or `send_message` will only store events in memory and are send at once after `acknowledge_message` call (but this is not suitable for collectors).
* or (my preffered variant) add new `send_message_and_acknowledge` which can take one message or multiple messages.

Little advantage is, that sending multiple messages is faster because `lpush` Redis method supports multiple arguments.

**Comment by sebix** [comment]
Yes, this is a simple fix. But tough I would prefer this:

```python
self.send_message(*events)
```
As we do not need to check for the argument's type in the function.

But I'm working on a new architecture for parsers, which should solve this issue too.
