### ISSUE TITLE
Multiple issues with Shadowserver Drone Parser

### ISSUE THREAD

**Issue by dmth** [certtools/intelmq#524]
The Shadowserver Drone Parser does not work as expected.
intelmq/bots/parsers/shadowserver/drone_parser.py

- [x] [l47](https://github.com/certtools/intelmq/blob/master/intelmq/bots/parsers/shadowserver/drone_parser.py#L47) `dictreader=True` is not an allowed parameter anymore. I guess this affects all Shadowserver parsers. This is easy to fix

- [x] [l72](https://github.com/certtools/intelmq/blob/master/intelmq/bots/parsers/shadowserver/drone_parser.py#L72) If `count = ''` this does not work. This is easy to fix

- [x]  The data I received has different headers than the specification on [Shadowserver.org ](https://www.shadowserver.org/wiki/pmwiki.php/Services/Botnet-Drone-Hadoop)
Received Data:
`"timestamp","ip","port","asn","geo","region","city","hostname","type","infection","url","agent","cc_ip","cc_port","cc_asn","cc_geo","cc_dns","count","proxy","application","p0f_genre","p0f_detail","machine_name","id","naics","sic","cc_naics","cc_sic","sector","cc_sector","ssl_cipher","family","tag","public_source"`

- [x] [l66](https://github.com/certtools/intelmq/blob/master/intelmq/bots/parsers/shadowserver/drone_parser.py#L66) The field 'cc' is called 'cc_ip' in my Dataset. Documentation differs from reality.

- [x] [l62](https://github.com/certtools/intelmq/blob/master/intelmq/bots/parsers/shadowserver/drone_parser.py#L62) assumes that the value in `row['url']` is a valid URL according to the DHO. Unfortunately it is not. It might be required to guess / determine the url. This might be done by deriving it from the fields: `cc_dns`, `application` and `port`. But there might still be some magic involved as those do not always contain a sufficient amount of data to determine the full url.

**EDIT / Solution** 
See https://github.com/certtools/intelmq/issues/524#issuecomment-226443897

**Comment by dmth** [comment]
@gsiv told me there are even more problems:

- [ ] [l71](https://github.com/certtools/intelmq/blob/master/intelmq/bots/parsers/shadowserver/drone_parser.py#L71) `event.add('destination.reverse_dns', row['cc_dns'])` Data also contains IP-Addresses in this field. It might be that those could be looked up to get a Hostname, but that's not the job of a parser. How to handle this invalid data?

**Comment by dmth** [comment]
To get this working fast:

Is it safe to surround the `event.add()` actions which fail in here with a `try, exept KeyError` block, and log a warning, which explains theproblem? 
This would prevent the bot from failing and dumping the message.

**Comment by aaronkaplan** [comment]
On Wed, May 18, 2016 at 11:55:27PM -0700, Dustin Demuth wrote:
> To get this working fast:
> 
> Is it safe to surround the `event.add()` actions which fail in here with a `try, exept KeyError` block, and log a warning, which explains theproblem? 
> This would prevent the bot from failing and dumping the message. 


well, you can configure the bots to "fail softly", i.e. dump the message
but resume with the next one.

However, that will cost speed....

**Comment by dmth** [comment]
You might want to have a look at our improved Shadowserver Parser

**Comment by dmth** [comment]
We radically redesigned the Shadowserver parser.

See https://github.com/Intevation/intelmq/tree/shadowserver-feeds

Once those go upstream, this issue is resolved.

Can someone please tag this issue appropriately?

**Comment by sebix** [comment]
@dmth How do you want it tagged? Include `fixes certtools/intelmq#524` in one of your commit messages.

**Comment by dmth** [comment]
Can do that. Do we have sth. like: "Fixed in feature branch"?

**Comment by aaronkaplan** [comment]
can we close this one?

**Comment by sebix** [comment]
ui, I missed this one in cd8b4e4e4bbb700bc1cc2a9ddd0e3106d465a28c

**Comment by aaronkaplan** [comment]
> On 19 Jul 2016, at 18:56, Sebastian <notifications@github.com> wrote:
> 
> ui, I missed this one in cd8b4e4

okay.
Do you still want to merge it in?
I'll fix the test cases for shadowserver now...

**Comment by sebix** [comment]
> Do you still want to merge it in?

Merge what? This commit is merged. I forgot to close/mention this issue.

**Comment by aaronkaplan** [comment]
> On 19 Jul 2016, at 19:30, Sebastian <notifications@github.com> wrote:
> 
> Do you still want to merge it in?
> 
> Merge what? This commit is merged. I forgot to close/mention this issue.
> 
Ah.
ok. also good :)
