### ISSUE TITLE
Taxonomy Expert: KeyError: 'other'

### ISSUE THREAD

**Issue by dmth** [certtools/intelmq#525]
```
tail -f var/log/taxonomy-expert.log 
2016-05-18 17:13:05,180 - taxonomy-expert - DEBUG - Receive message '{"time.source": "2016-05-15T06:46:05+00:00", "time.observation": "2016-05-18T15:05:00+00:00", "__type": "Event", "feed.accuracy": 100.0, "raw": "<stripped>", "source.asn": <stripped>, "source.ip": "<stripped>", "classification.type": "other", "feed.name": "<stripped>"}'
2016-05-18 17:12:35,145 - taxonomy-expert - ERROR - Bot has found a problem.
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/intelmq/lib/bot.py", line 102, in start
    if not starting and (error_on_pipeline or error_on_message):
  File "/usr/lib/python3/dist-packages/intelmq/bots/experts/taxonomy/expert.py", line 40, in process
    taxonomy = TAXONOMY[event_type]
KeyError: 'other'
```
but, the classification https://github.com/certtools/intelmq/blob/master/intelmq/lib/harmonization.py#L157 explicitly allows other as valid value.

I think `other` is missing in the `TAXONOMY` dict.

**Comment by aaronkaplan** [comment]
On Wed, May 18, 2016 at 08:18:38AM -0700, Dustin Demuth wrote:
> ```
> tail -f var/log/taxonomy-expert.log 
> 2016-05-18 17:13:05,180 - taxonomy-expert - DEBUG - Receive message '{"time.source": "2016-05-15T06:46:05+00:00", "time.observation": "2016-05-18T15:05:00+00:00", "__type": "Event", "feed.accuracy": 100.0, "raw": "<stripped>", "source.asn": <stripped>, "source.ip": "<stripped>", "classification.type": "other", "feed.name": "<stripped>"}'
> 2016-05-18 17:12:35,145 - taxonomy-expert - ERROR - Bot has found a problem.
> Traceback (most recent call last):
>   File "/usr/lib/python3/dist-packages/intelmq/lib/bot.py", line 102, in start
>     if not starting and (error_on_pipeline or error_on_message):
>   File "/usr/lib/python3/dist-packages/intelmq/bots/experts/taxonomy/expert.py", line 40, in process
>     taxonomy = TAXONOMY[event_type]
> KeyError: 'other'
> ```
> but, the classification https://github.com/certtools/intelmq/blob/master/intelmq/lib/harmonization.py#L157 explicitly allows other as valid value.
> 
> I think `other` is missing in the `TAXONOMY` dict.


True, I came across this as well.
Should be added IMHO. Thx, nice catch.

**Comment by dmth** [comment]
Issue fixed with https://github.com/Intevation/intelmq/commit/c40a4f168c7fca4b91685b8f1788375ca1908bd9 Please merge upstream. Do you need a PR for this change?

**Comment by sebix** [comment]
Thanks, cherry-picked it.

**Comment by aaronkaplan** [comment]
On Wed, May 18, 2016 at 11:42:12PM -0700, Dustin Demuth wrote:
> Issue fixed with https://github.com/Intevation/intelmq/commit/c40a4f168c7fca4b91685b8f1788375ca1908bd9 Please merge upstream. Do you need a PR for this change?
> 

yes, please. This makes it easier.
thx

**Comment by aaronkaplan** [comment]
On Thu, May 19, 2016 at 12:11:45AM -0700, Sebastian wrote:
> Thanks, cherry-picked it.

okay, I saw this too late. Pls. ignore my previous mail then.
