### ISSUE TITLE
How to deal the repeated data using intelmq bots

### ISSUE THREAD

**Issue by Hacker-One** [certtools/intelmq#528]
Because of some feeds full provide the data,When we collecte the data sometimes they are repeated from the feed. How to deal the repeated data using intelmq bots?

**Comment by aaronkaplan** [comment]
On Thu, May 19, 2016 at 10:33:29PM -0700, Hacker-One wrote:
> Because of some feeds full provide the data,When we collecte the data sometimes they are repeated from the feed. How to deal the repeated data using intelmq bots?
> 


Hi HackerOne,

take a look at the deduplicator expert.
Basically you can say how long an event should be cached. Redis will
expire it automatically after $ttl seconds. 
The deduplicator will check if an event is already cached. If yes, don't
forward it in the pipeline, if no, cache it and forward it.

It's that simple :)

Hope it helps,
a.

**Comment by Hacker-One** [comment]
OK，thanks！

**Comment by aaronkaplan** [comment]
closing.
