### ISSUE TITLE
Intelmqdump also shows bots which do not have dumps to recover

### ISSUE THREAD

**Issue by dmth** [certtools/intelmq#531]
After recovering a dump with "recover all" the tool says the dump is recovered but still lists the failed bot. Is this behaviour intended?

```
intelmq@76edb4ec262f:~$ intelmqdump       
 id: name (bot id)         content
  0: myspecial-parser 1 dumps
Which dump file to process (id or name)? 0

processing myspecial-parser: 1 dumps
  0: 2016-05-13T15:03:24.598985 AttributeError: 'NoneType' object has no attribute 'encode'
delete (e)ntries, (d)elete file, recover (a)ll, (r)ecover by ids, (q)uit, (s)how by ids? a
Recovered dump 0.

Processing myspecial-parser: 0 dumps
delete (e)ntries, (d)elete file, recover (a)ll, (r)ecover by ids, (q)uit, (s)how by ids? q

intelmq@76edb4ec262f:~$ intelmqdump 
 id: name (bot id)         content
  0: myspecial-parser 0 dumps
Which dump file to process (id or name)? 
```

**Comment by sebix** [comment]
Yes, recovering all dumps does not delete the file automatically. This is an extra step. And empty files are listed too.

Would you expect that
* empty files are not listed and/or
* files are deleted if everything is recovered
* empty files are deleted if no action on the file is performed (eg. listing the dumps)
?

**Comment by dmth** [comment]
Thanks for your fast answer.

> Would you expect that
>  *  files are deleted if everything is recovered
I'd expect that no empty dump-files exist.

This might facilitate the detection of failing bots (do sth. like `find var/log -name "*.bot"` regularly and send mail if a result is found)
