### ISSUE TITLE
Tor nodes bot: database file does not exist

### ISSUE THREAD

**Issue by ondj** [certtools/intelmq#533]
Remote file https://internet2.us/static/latest.bz2 referenced from `tor_nodes` expert bot README and `update-tor-nodes` script does not exist (request returns 404 error)

As an alternative, it is possible to use file https://check.torproject.org/exit-addresses, but it is in a different form a bot must be changed.

**Comment by aaronkaplan** [comment]
Let me check that. It should exist. I run it. 

---
Mobile

**Comment by aaronkaplan** [comment]
Works again. Sorry nginx was not on auto start. 

---
Mobile
