### ISSUE TITLE
Import script for the RIPE database

### ISSUE THREAD

**Issue by rolandgeider** [certtools/intelmq#539]
There is currently no import script to read in (parts) of the RIPE database (ftp://ftp.ripe.net/ripe/dbase/). Since we need this for the contact database for certbund, I'll start looking into this, perhaps there are already python parser for the format.

**Comment by ondj** [comment]
What information do you want to import? We import NETNAME and DESCR with an own bot with a persistent connection to RIPE, so without downloading the whole RIPE database. I can send a pull request with our bot, but it is also necessary to add fields to harmonization.

**Comment by rolandgeider** [comment]
@ondj thanks for the offer, at the moment we only need the ASNs, organisations and contacts but we will need to import networks in the future.

For transparency, the current code is available on the [certbund-contact](https://github.com/Intevation/intelmq/blob/certbund-contact/intelmq/bots/experts/certbund_contact/) branch

**Comment by sebix** [comment]
@ondj We'd welcome a PR or a thread on the intelmq-dev list to discuss this!

**Comment by dmth** [comment]
@rolandgeider can you please comment on the current state of work?

**Comment by rolandgeider** [comment]
We can import organisations, roles and ASNs. There is a problem at the moment where not all contacts associated with an organisation are imported (e.g. the ones linked only through the abuse-c are ignored). I'm working on that

**Comment by dmth** [comment]
Much work was done on this topic. You can find a working importer for ASN here:

https://github.com/Intevation/intelmq/tree/certbund-contact/intelmq/bots/experts/certbund_contact

See README-ripe-import.md for Reference.

**Comment by dmth** [comment]
Possible next step: Add ripe-delegated list to ASN-Import in oder to add CC Information

**Comment by dmth** [comment]
> Possible next step: Add ripe-delegated list to ASN-Import in oder to add CC Information
This Step is also done. In addition a Diff-Tool exists which will show the differences of a ripe dump to the previously imported state.

**Comment by wagner-certat** [comment]
@aaronkaplan Do you want to do this before 1.0 or can we postpone this?

**Comment by wagner-certat** [comment]
Solved by [certbund-contact](https://github.com/Intevation/intelmq/tree/certbund-contact) and [do-portal](https://github.com/certat/do-portal/)
