### ISSUE TITLE
Feed name is missing in several Shadow Server BOTS entries

### ISSUE THREAD

**Issue by pedromreis** [certtools/intelmq#544]
Example:
```json
"ShadowServer Microsoft Sinkhole": {
            "description": "ShadowServer Microsoft Sinkhole Collector is the bot responsible to get the report from source of information. https://www.shadowserver.org/wiki/pmwiki.php/Services/Microsoft-Sinkhole",
            "module": "intelmq.bots.collectors.mail.collector_mail_attach",
            "parameters": {
                "attach_regex": "csv.zip",
                "attach_unzip": true,
                "folder": "Inbox.shadowserver",
                "mail_host": "<host>",
                "mail_password": "<password>",
                "mail_ssl": true,
                "mail_user": "<user>",
                "rate_limit": "3600",
                "subject_regex": "Shadowserver [^ ]+ Microsoft Sinkhole Report"
            }
},
```

Collector fails on: `report.add("feed.name", self.parameters.feed)`

**Comment by sebix** [comment]
Will be solved by new parsers developed by @dmth here: https://github.com/Intevation/intelmq/tree/shadowserver-feeds/intelmq/bots/parsers/shadowserver

**Comment by dmth** [comment]
Currently I'm not setting the `feed.name` in the parser. I should do so.

**Comment by dmth** [comment]
@pedromreis I just pushed a new version of the shadowserver **parsers** to https://github.com/Intevation/intelmq/tree/shadowserver-feeds would you mind to test and add some expertise if the field mapping is correct in config.py

They were tested with data coming from a file (for botnet-drone-hadoop). I didn't look into a way to collect the data from a mailbox. The "Generic Mail URL Fetcher" is supposed to work in this case.

**Comment by pedromreis** [comment]
@dmth Will do for sure, if not today tomorrow. Tks!
