### ISSUE TITLE
Large reports don't fit into one redis message.

### ISSUE THREAD

**Issue by dmth** [certtools/intelmq#547]
As mentioned in the newsletter, large (> 500MB) reports do not fit into the message queue.

We expect an updated redis > 3.2 should work for these large messages.
But this is not yet tested.
- [ ] Who is running a very recent redis and could verify this?
- [x] In addition: the length limit in https://github.com/certtools/intelmq/blob/master/intelmq/etc/harmonization.conf#L336 should be removed.

_EDIT by sebix: checklist_

**Comment by dmth** [comment]
Did you run a test how the application performs with large (>512 MB) reports now? If yes, which Redis version did you use?

**Comment by aaronkaplan** [comment]
We never encountered some large reports like this in practice. So we did not come across it yet. Need to test via generated reports.

**Comment by sebix** [comment]
No success with redis 3.2.1 so far. On server side I get this:

> 7491:M 19 Jul 12:41:46.548 - Protocol error from client: id=38 addr=127.0.0.1:47459 fd=5 name= age=15 idle=0 flags=N db=0 sub=0 psub=0 multi=-1 qbuf=16384 qbuf-free=16384 obl=42 oll=0 omem=0 events=r cmd=lpush
> 7491:M 19 Jul 12:41:46.699 - Protocol error from client: id=39 addr=127.0.0.1:47460 fd=5 name= age=0 idle=0 flags=N db=0 sub=0 psub=0 multi=-1 qbuf=16384 qbuf-free=16384 obl=42 oll=0 omem=0 events=r cmd=NULL

On client side:
```python
>>> r.lpush('a', '01'*260*1024*1024)
Traceback (most recent call last):
  File "<ipython-input-62-2885976fd64e>", line 1, in <module>
    r.lpush('a', '01'*260*1024*1024)
  File "/usr/local/lib/python3.4/dist-packages/redis/client.py", line 1227, in lpush
    return self.execute_command('LPUSH', name, *values)
  File "/usr/local/lib/python3.4/dist-packages/redis/client.py", line 578, in execute_command
    connection.send_command(*args)
  File "/usr/local/lib/python3.4/dist-packages/redis/connection.py", line 563, in send_command
    self.send_packed_command(self.pack_command(*args))
  File "/usr/local/lib/python3.4/dist-packages/redis/connection.py", line 556, in send_packed_command
    (errno, errmsg))
ConnectionError: Error 104 while writing to socket. Connection reset by peer.
```

But also see the docs at http://redis.io/topics/data-types
> A String value can be at max 512 Megabytes in length.

Additionally, antirez/redis#757 is not yet closed.

Seems we have to use another queuing system like ZMQ to process large messages.

**Comment by dmth** [comment]
I asked on intelmq-dev if someone knows a workaround.

**Comment by aaronkaplan** [comment]
Result of the discussion: need to either
  1. split large input blocks into multiple reports (see intelmq-dev list)
or
  2. use other MQ libraries such as zmq.

**Comment by bernhard-herzog** [comment]
As it turns out, https://github.com/sebix/intelmq/commit/1ee2ba302dac817fd112c1f739e53286d80d2bb1 while lifting the length restriction of the raw field for the message class, actually leads to a shorter length limit in the events database: `intelmq_psql_initdb.py` uses 2000 as length of `Base64` fields if no length is given. This makes matters worse than before for the postgresql output bot. I'm working on a fix that will at least solve out immediate problem.

**Comment by dmth** [comment]
We circumvented this problem by splitting large reports into blocks.
ATM I doubt that a PR was created for it.
https://github.com/certtools/intelmq/compare/master...Intevation:dev-split-csv-reports

Feel free to merge this upstream if appropriate.

**Comment by sebix** [comment]
postponed to 1.1

**Comment by wagner-certat** [comment]
Not possible in redis -> only amqp #1179 or other message queues can solve this
