### ISSUE TITLE
Enable separate packaging of bots by allowing addition and removals to the config.

### ISSUE THREAD

**Issue by bernhardreiter** [certtools/intelmq#552]
The problem:
Some bots have different requirements from the core of intelmq. Example: a contact bot with postgresql.
It makes sense to enable separate packaging of bots. With current intelmq (26d112873381f91cb6c6fedb5ddef2f32b4bf46d) there is a file https://github.com/certtools/intelmq/blob/master/intelmq/bots/BOTS
which holds basic info about each bot.

Adding or removing a bot would need to add or remove a section in this file.
As discussed in April 2016 on http://lists.cert.at/pipermail/intelmq-dev/2016-April/thread.html
people agree that this situation should be improved with a number of suggestions.

Previous related issues are #368 and #267 
(I lack the permission rights to rename and refocus  #368, so I am opening this one)

**Comment by aaronkaplan** [comment]
+1
