### ISSUE TITLE
Debian-Packages must include bots' documentation files.

### ISSUE THREAD

**Issue by bernhardreiter** [certtools/intelmq#556]
In general should the documentation of the bots be included in the package.

Example:
The debian Package intelmq (1.0.0~dev4+intevation.1.2~alpha3) from
https://github.com/Intevation/intelmq/blob/deb-packaging/debian/changelog 
does not package all README.md files from bots. 
E.g. the postgresl/README.md is missing.

@gsiv is this something you can look into?

**Comment by gsiv** [comment]
On Thu, Jul 07, 2016 at 06:29:59AM -0700, Bernhard E. Reiter wrote:
> @gsiv is this something you can look into?

Yes, I'll look into it.
