### ISSUE TITLE
Debian-Packages: permissions of /opt/intelmq problems with .ssh/authorized_keys

### ISSUE THREAD

**Issue by bernhardreiter** [certtools/intelmq#559]
https://github.com/certtools/intelmq/blob/3e82335a8ee75b525d9c89b87a42c532bd509ed2/debian/intelmq.postinst has the problem that Ubuntu 14.04 sshd does not want to allow connections
via .ssh/authorized_keys if a home directory is group writable.

```sh
        useradd -d /opt/intelmq -U -s /bin/bash intelmq
    chmod -R g+w /opt/intelmq
```

The resulting error message in /var/log/auth.log looks like
```
Jul  7 17:06:24 ubuntu sshd[10993]: Authentication refused: bad ownership or modes for directory /opt/intelmq
```

intelmq-manager will have to write some files in the directory with the "intelmq" group.
Two possible solutions:
 1. check that the top level directory does not need to be written and remove the line
 2. use a different home directory for the intelmq user

@swilde created the file initially.

**Comment by aaronkaplan** [comment]
@dmth your turf

**Comment by dmth** [comment]
@gsiv is currently handling the packaging stuff. He might be interested in this ;)
