### ISSUE TITLE
n6 Collector Documentation

### ISSUE THREAD

**Issue by dmth** [certtools/intelmq#562]
With the current documentation it is not possible for "outsiders" to configure the n6 collector the right way.

 * It is not clear how "exchange" has to be configured
 * It is not clear which format KEY, and CERT and CA-File should have
 * It is not clear if the CA-File is mandatory

In addition: After configuration of the bot, it is not visible from output of:
`python3 -m intelmq.bots.collectors.n6.collector_stomp n6stomp-collector`
if a connection is successfull and if not why not.

**Comment by aaronkaplan** [comment]
> On 11 Jul 2016, at 15:39, Dustin Demuth <notifications@github.com> wrote:
> 
> With the current documentation it is not possible for "outsiders" to configure the n6 collector the right way.
> 
> 	• It is not clear how "exchange" has to be configured

Well, you get this parameter from CERT.pl
It's a string.

> 	• It is not clear which format KEY, and CERT and CA-File should have
Likewise. You need to talk with CERT.pl

> 	• It is not clear if the CA-File is mandatory
Yes, it is . Likewise, you get that from CERT.pl

> In addition: After configuration of the bot, it is not visible from output of:
> python3 -m intelmq.bots.collectors.n6.collector_stomp n6stomp-collector
> if a connection is successfull and if not why not.
> 

It's a bug which was introduced by the parser architecture changes.
See #560
Working on it now.

**Comment by dmth** [comment]
Let's focus on the documentation in this issue:

>> *  It is not clear how "exchange" has to be configured

> Well, you get this parameter from CERT.pl
> It's a string.

Yes, but it's not visible here which parts of this string should be inserted here.
Is it `exchange/nnn/*.*.*/` or just `nnn/*.*.*` or `*.*.*` because the bot is intelligent enough to read the nnn from the Certificate?


>> * It is not clear which format KEY, and CERT and CA-File should have

> Likewise. You need to talk with CERT.pl

My formulation was unclear. More Specific:
Which Fileformat / Encoding does the N6 Collector expect? PEM, DER, ...

>> * It is not clear if the CA-File is mandatory

>Yes, it is . Likewise, you get that from CERT.pl

The bot already ships a CA.pem file. I see that this is not used by the bot when no other file was specified.

**Comment by aaronkaplan** [comment]
I think all of these answers will be automatically answered by talking with CERT.pl. In this case , since it is a private feed, I think the solution is really to talk to them.

**Comment by dmth** [comment]
Reopenend. Talking to a third party in order to ask "how shall I use this software" is not a valid solution for anybody.

**Comment by dmth** [comment]
Please reopen this issue.
Asking a third party how to configure this software is not a valid solution from my point of view.

**Comment by sebix** [comment]
> In addition: After configuration of the bot, it is not visible from output of:
`python3 -m intelmq.bots.collectors.n6.collector_stomp n6stomp-collector`
if a connection is successfull and if not why not.

As this issue has been closed, is this one also fixed?

**Comment by dmth** [comment]
> As this issue has been closed, is this one also fixed?

No, It's not. But it is a different topic.

**Comment by aaronkaplan** [comment]
@dmth I think you mis-understood something here. Let's talk on the phone or so and I can explain.

**Comment by aaronkaplan** [comment]
okay, cant' reach you. Anyway, the point is that cert.pl is not  a "third party" for this feed. It is the feeder. You get all the parameters from there. In the format that they give it to you and that the n6stomp-collector needs. So I think the ticket is ok as it is now. If you have a different opinion, maybe it's best to talk over phone so that I can understand what you mean.

**Comment by aaronkaplan** [comment]
re-opening because it seems we want some info if the connection was succesful.

**Comment by dmth** [comment]
Hi @aaronkaplan, please excuse my absence, I was on vacation for the end of last week.

Let's talk about this topic in the upcoming conf call, ok?

**Comment by aaronkaplan** [comment]
> On 18 Jul 2016, at 10:10, Dustin Demuth <notifications@github.com> wrote:
> 
> Hi @aaronkaplan, please excuse my absence, I was on vacation for the end of last week.
> 
> Let's talk about this topic in the upcoming conf call, ok?
> 

Sure , no problem.
