### ISSUE TITLE
configuration format

### ISSUE THREAD

**Issue by sebix** [certtools/intelmq#570]
While JSON is great as data format it's very ugly for configuration. No comments, not intuitive to read etc.

To start the discussion, I start with some possible requirements:

A configuration should
- be hierarchical
- hold different types, matching python types: string, numbers, boolean, null, lists and dictionaries
- allow comments
- hold documentation (tooltip help for manager) per value
- define possible types/values

**Comment by ondj** [comment]
I think it is possible to use YAML format, which complies first three points. But for last two it is necessary to use some validation schema, for example [Kwalify](http://www.kuwata-lab.com/kwalify/) ([Python version](https://github.com/grokzen/pykwalify)) or transform it to JSON and use mutch more supported JSON schema.

**Comment by bernhardreiter** [comment]
Hi, 
I'd be more interested in what the configuration should be used for to determine a good new configuration (syntax/language).

If a configuration should mainly be done by tools, especially webbased tools, the requirements
for comment sections within the syntax does not make sense to me. A tool could only work
on contents that is within the data itself, so  comment become a field or a value.

What is the idea behind being hierarchical? Configuration should be as simple as possible.

**Comment by aaronkaplan** [comment]
---
Mobile

> On 12.10.2016, at 09:53, Bernhard E. Reiter <notifications@github.com> wrote:
> 
> Hi, 
> I'd be more interested in what the configuration should be used for to determine a good new configuration (syntax/language).
> 
> If a configuration should mainly be done by tools, especially webbased tools, the requirements
> for comment sections within the syntax does not make sense to me. A tool could only work
> on contents that is within the data itself, so comment become a field or a value.
> 

Well there are also humans which read pure text files. Comments in general (in whatever form) make sense IMHO. 
> What is the idea behind being hierarchical?
> 

The possibility for inheritance of default values by the upper levels of the hierarchy. 
It's another way of saying "do not repeat yourself" 
> Configuration should be as simple as possible.
> 
Absolutely agree!!! But if it's a wall of text (due to repetition) then it's not simple anymore. 
My 2 cents.
A.

**Comment by sebix** [comment]
* Elektra: https://freedesktop.org/wiki/Software/Elektra/ https://github.com/ElektraInitiative/libelektra
* YAML: http://yaml.org/

**Comment by bernhardreiter** [comment]
Elektra looks like overkill.

**Comment by bernhardreiter** [comment]
An alternative could be https://hjson.org ; H-JSON or Human-JSON.
For a comparision see https://hjson.org/faq.html#but-yaml-hocon-
there are python parsers and it keeps the json aspect.

(There is also https://docs.python.org/3/library/configparser.html).

@aaronkaplan can give me an example for a use case for hierarchical configuration?
 If we had sections, a default section might often be enough.

**Comment by wagner-certat** [comment]
> (There is also https://docs.python.org/3/library/configparser.html).

Looks promising too.

* Allows definition of default and fallback values
* Allows using variables

**Comment by wagner-certat** [comment]
Here is a solution which converts IntelMQ-configuration from YAML to JSON:

https://stackoverflow.com/questions/42226922/yaml-to-json-ruby

**Comment by wagner-certat** [comment]
We have YAML now and reduced the number of configuration files to just two
