### ISSUE TITLE
Generation of test cases

### ISSUE THREAD

**Issue by Rafiot** [certtools/intelmq#571]
I updated the MISP parser bot (https://github.com/Rafiot/intelmq/commit/ac52e035656e6222e6b3efcabeb3d645a1c053eb) and the test cases are broken. I would like to fix it before doing a pull request, but updating `EXAMPLE_EVENT` in `test_parser.py` seems non-trivial (seems to requires a lot of manual fiddling). Am I missing something?

**Comment by sebix** [comment]
You can read raw-data [from files](https://github.com/certtools/intelmq/blob/master/intelmq/tests/bots/parsers/shadowserver/test_snmp.py#L15) (or write it as text in the testfile and then convert it to base64) and [don't need to wrap them](https://github.com/certtools/intelmq/blob/master/intelmq/tests/bots/parsers/shadowserver/test_snmp.py#L26).

Nose gives a nice diff on dictionaries.

But yes, we could automate it partly, would make some things easier for beginners :)

**Comment by Rafiot** [comment]
Ok, I'll fix it and depending how much it annoys me, I'll think about a way to automate it :p  (I think I'll have to update the MISP bot a few more times). 
And the same thing goes for the json files :)

**Comment by Rafiot** [comment]
Loading a file is way easier and does the trick, closing.
