### ISSUE TITLE
Start a working chain with intelmqctl

### ISSUE THREAD

**Issue by sebix** [certtools/intelmq#572]
We had an idea for a `start-chain` command for easier testing:

``` bash
intelmqctl start-chain foobar-collector
```

This would start the named bot and all bots which "depend" on this one (recursive search in the pipline-tree, direction collector→output).

**Comment by sykaeh** [comment]
I was missing a command like this one today. I currently have three different groups of bots that process different information and are unrelated to each other. Currently I can either start all of the bots or only individual ones. It would be great if I could start/stop a group of bots at the same time.

**Comment by sebix** [comment]
On 11/24/2016 01:13 PM, Sybil Ehrensberger wrote:
>
> It would be great if I could start/stop a group of bots at the same time.
>
This is not what this issue is about, but it can be solved with sytemd
unit's quite easily (as units group services).

Once I've written/generated service files for all bots, we need to
overthink the capabilities of intelmqctl again (could be an interface
for systemd).

**Comment by wagner-certat** [comment]
See #694 for a more detailed issue.
