### ISSUE TITLE
dump files: locking mechanism

### ISSUE THREAD

**Issue by sebix** [certtools/intelmq#574]
#573 emits a warning in intelmqdump if the bot is running. But this is not enough to mitigate race-conditions, as a bot could be started during recovering. Both bot and intelmqdump have to lock the file before working on it.

https://pypi.python.org/pypi/filelock/

**Comment by sebix** [comment]
Other possibilities:

 - One line per dump (in JSON-format), allows easy appending
 - an error pipeline queue
 - one file per dump

**Comment by wagner-certat** [comment]
> One line per dump (in JSON-format), allows easy appending

Does not help either. Locking file descriptors can be done with: https://docs.python.org/3.5/library/fcntl.html#fcntl.flock

**Comment by wagner-certat** [comment]
Rewriting intelmqdump is something for the next feature release

**Comment by wagner-certat** [comment]
fixed in 1b18e23e41fe63251034af0573ec596f8e645d9d
