### ISSUE TITLE
clean up test-data

### ISSUE THREAD

**Issue by aaronkaplan** [certtools/intelmq#583]
Some test data has IP addresses (both in the raw field of the test message and in the expected answer message). 
This needs to be cleaned up.

Please replace every public IP with IPs in the form: 1.2.3.4 or 5.6.7.8 or similar - IPs which are obviously test data. 
Please do _not_ replace by RFC1918 IP addresses, because if we want to use that data for full integration tests, an RFC1918 filter might filter these out... So RFC1918 IPs are special IPs for testing.

**Comment by dmth** [comment]
Status **Shadowserver Parser**: We provide CSV-Files for:
- Open-Chargen
- drone-hadoop
- microsoft-sinkhole
- qotd
- snmp

Those seem to be identical to the data provided by shadowserver as example in the follwing cases:

- [x] open-chargen
- [x] drone-hadoop
- [x] microsoft-sinkhole
- [x] qotd
- [x] snmp

This makes the issue uncritical for shadowserver data.

**Comment by sebix** [comment]
RFC1918 currently removes reserved and internal IPs/domains. We should split this (and activate only reserved by default). Then we can use internal IPs too.

**Comment by aaronkaplan** [comment]
@sebix : I don't 100% understand the RFC1918 comment. What do you want to split?

**Comment by aaronkaplan** [comment]
@dmth okay regarding shadowserver sample data. Good! Let's simply reference it in the code in this case so that we can be sure that everyone understands that it is already publicly provided data / IPs by shadowserver (not by us).

**Comment by sebix** [comment]
@aaronkaplan See the list of filtered IPs in RFC1918:
https://github.com/certtools/intelmq/blob/master/intelmq/bots/experts/rfc1918/expert.py#L30

We treat internal IP the same as documentation IPs. We can make the removal of internal IPs optional.

**Comment by aaronkaplan** [comment]
yes I am aware of the RFC1918 bot. But I don't get what you mean ;-)) Let's talk in person later...

**Comment by dmth** [comment]
for a lot of shadowserver-parser we have pseudonomized test-data in https://github.com/Intevation/intelmq/tree/dev-shadowserver-test-feeds/intelmq/tests/bots/parsers/shadowserver/newfeeds there is also an awk script to generate new data from existing datasets.

**Comment by wagner-certat** [comment]
moving this to 1.0.1

**Comment by aaronkaplan** [comment]
uncritical
