### ISSUE TITLE
intelmqdump tool: documenting a bug (?) in re-inserting messages

### ISSUE THREAD

**Issue by aaronkaplan** [certtools/intelmq#586]
Trying to re-insert messsages from the failed parsing in elasticsearch-parser results in trying to reinsert the very same message over and over again.
Do we have an enless loop there?
Need to inspect.

**Comment by bernhardreiter** [comment]
Is there a simple way to reproduce the problem situation? If so, it's helpful to list it here.

**Comment by sebix** [comment]
intelmqdump has been improved meanwhile and it is not clear what this issue is about
