### ISSUE TITLE
Harmonization type for lowercase strings

### ISSUE THREAD

**Issue by sebix** [certtools/intelmq#587]
Result of discussion in #585:
Define a new harmonization type for lowercase-only strings. Sanitation automatically converts them to lowercase.

* apply for types in harmonization e.g. protocol names etc.
* eventually remove regex-checks which are now obsolete
* add tests

**Comment by aaronkaplan** [comment]
actually i think I can solve it easier: add a new iregex type in the harmonisation.

**Comment by sebix** [comment]
But don't we want to convert the strings to lower case too? Just ignoring the case could lead to many other potential issues, like duplicates.

**Comment by bernhardreiter** [comment]
bin/intelmq_psql_initdb.py has not been considered.
It does not know the new type and it still has the old UUID type.
