### ISSUE TITLE
Error handling in shadowserver parser

### ISSUE THREAD

**Issue by bernhard-herzog** [certtools/intelmq#592]
This came up on IRC. Instead of only answering there it seemed better to
have it in a more permanent place.
# Error handling in shadowserver parser

Some thoughts and suggestions about the error handling in the
shadowserver parser:
1. All places where the conversion functions are called should handle
   exceptions raised by them consistently. Currently (revision
   64515a463e4bf) there's only one place where exceptions are handled
   explicitly. It's not clear what makes that one place so special and
   why handling all exceptions is actually correct.
   
   Probably the best way to ensure consistency is to have only one
   place where the conversion function is called.
2. We should define what the interface of the conversion function is.
   How does it indicate that the value is to be ignored? How does it
   indicate an error in the feed?
# Interface of the conversion functions

There are two kinds of conversion functions. One can be called with one
parameter, the other with two parameters. In both cases, the first
parameter is the value of a field of one shadowserver event. The second
parameter is the entire raw shadowserver event as a dictionary. With
respect to error handling, both kinds can be treated the same way.

For the result of the conversion, three cases have to be considered:
- The value can be converted successfully
  
  In this cases, the conversion function returns the value to be stored
  in the IntelMQ event. This value must be a value allowed by IntelMQ
  for the field the value is intended for (see below for more about
  this aspect). Notably, this excludes None and the empty string,
  because Message.add does not allow these values, which lets us reuse
  None for the second case:
- The value is to be ignored.
  
  In this case, the conversion function returns `None`.
  
  The most likely case is that the raw shadowserver value is an empty
  string indicating that there is no value for the field.
- The value is invalid.
  
  In this case the whole event should be considered suspect and no
  IntelMQ event should be created. The conversion function indicates
  this by throwing an exception.
  
  For instance, a field that should either be empty or contain a
  decimal integer contains something that cannot be parsed as an
  integer. The reason for this could be actual invalid data
  (corruption, malicious input or incompatible upstream changes) or a
  programming error (e.g. the wrong column name or conversion function
  was used in the configuration).

The caller of the conversion function should probably not catch the
exceptions. The caller of the `parse_line` method already catches all
exceptions and dumps the contents of the failed line.
# Validation by `Message.add`

After the conversion, the value is stored in the event object with the
`add` method, which does some more validation which can also fail. I
suggest writing the conversion functions and choosing conversion
functions in the configuration, so that they always return a value
suitable for the add method, if they can successfully convert the value
at all (otherwise return `None` or raise an exception, as described
above). The reasoning here is that if the conversion produces a value
that cannot be stored in the event object, the conversion is defective
in some way (e.g. a bug in the conversion function, the wrong conversion
function was specified `config.py`, etc.) and indicates a programming
error (it can't be an error in the feed data because then the conversion
should have failed already).

This suggests that exceptions raised by `add` like those raised by the
conversion functions should not be caught. The current implementation
differs from this for the optional fields where the value is stored in
"extra" if the add method raises an exception. It's not clear to me that
that is actually a good idea in all cases.

**Comment by aaronkaplan** [comment]
I don't quite agree with

> In this case the whole event should be considered suspect and no
> IntelMQ event should be created. The conversion function indicates
> this by throwing an exception.

I think this depends. If the conversion would happen in some non-important field (let's say comment or "extra") we should continue with the line.


What **really** bothers me with the current conversion function is that the error messages are 
  1. non trivial to read (not obvious)
  2. they don't say why something failed (what did it try to convert and why did it not happen)
  3. what the action was: continue, ignore this line, stop

**Comment by sebix** [comment]
You analysis is correct.

> The current implementation
differs from this for the optional fields where the value is stored in
"extra" if the add method raises an exception. It's not clear to me that
that is actually a good idea in all cases.

That's why they are called optional. If you think the conversion of some fields is important and should not be skipped, move the field from optional to required.

Apart from this, do you suggest any other changes to the error handling (i.e. catching exceptions).

**Comment by sebix** [comment]
> All places where the conversion functions are called should handle
exceptions raised by them consistently. Currently (revision
64515a4) there's only one place where exceptions are handled
explicitly. It's not clear what makes that one place so special and
why handling all exceptions is actually correct.

What makes this place special is that this place handles the optional fields and as fallback we add the data to extra. This does not apply to the required fields, where we want to fail.

> We should define what the interface of the conversion function is.
How does it indicate that the value is to be ignored? How does it
indicate an error in the feed?

Fail.

**Comment by wagner-certat** [comment]
It's unclear what is missing here -> closing.
