### ISSUE TITLE
shadowserver parser: can't parse open redis feed

### ISSUE THREAD

**Issue by aaronkaplan** [certtools/intelmq#600]
```
2016-07-22 18:00:38,243 - openredis-parser - ERROR - Failed to parse line.
Traceback (most recent call last):
  File "/home/aaron/intelmq/intelmq/lib/bot.py", line 461, in process
    events = list(filter(bool, self.parse_line(line, report)))
  File "/home/aaron/intelmq/intelmq/bots/parsers/shadowserver/parser.py", line 182, in parse_line
    event.add('raw', self.recover_line(raw_line))
  File "/home/aaron/intelmq/intelmq/bots/parsers/shadowserver/parser.py", line 198, in recover_line
    out += ','.join(ordered_line) + '\n'
TypeError: sequence item 13: expected str instance, NoneType found
2016-07-22 18:00:38,243 - openredis-parser - INFO - Dumping message from pipeline to dump file.
```

**Comment by bernhard-herzog** [comment]
We ran into this as well. Our analysis so far is that it's a defect in conv_csv_shadowserver which returns None for values like `"0123"` or `" 123"` where `str(int(value)) == value` evaluates to False.

**Comment by aaronkaplan** [comment]
wow, thanks for the comment. I will investigate further there.

**Comment by sebix** [comment]
> We ran into this as well. Our analysis so far is that it's a defect in conv_csv_shadowserver which returns None for values like `"0123"` or `" 123"` where `str(int(value)) == value` evaluates to False.

Maybe it can be replaced by a more lax check, e.g. only:
```python
try:
    int(value)
    return value
except ValueError:
```

(This has been added by me, not @dmth)

**Comment by bernhard-herzog** [comment]
That should at least take care of the immediate problem.

This issue is actually part of a more general problem: The code that fails tries to reconstruct the raw CSV Data that went into the event. There are more problems with this than just this issue:

 - Strings containing double quotes would end up producing incorrect CSV. This may not be a
   problem in practice if shadowserver actually gives guarantees about this, though.

 - The base class also uses `recover_line` for lines for which `parse_line` raises an exception. In
   that case, the values are not converted with `conv_csv_shadowserver` before they're dumped.
   This can also lead to incorrect CSV, AFAICT

**Comment by aaronkaplan** [comment]
okay, Thanks @bernhard-herzog for the analysis! I was just in quick-fix mode :)
I agree, this whole parse should be looked at again and made 
  1.  more stable and robust
  2. clearer and easier to debug
  3. have better error handling (see #592 )

**Comment by sebix** [comment]
On 07/22/2016 07:52 PM, Bernhard Herzog wrote:
>
>  *
>
>     Strings containing double quotes would end up producing incorrect
>     CSV. This may not be a
>     problem in practice if shadowserver actually gives guarantees
>     about this, though.
>
How does such data look like? As I did not have such samples, I was not
able to consider these cases.
>
>  *
>
>     The base class also uses |recover_line| for lines for which
>     |parse_line| raises an exception. In
>     that case, the values are not converted with
>     |conv_csv_shadowserver| before they're dumped.
>     This can also lead to incorrect CSV, AFAICT
>
Why do we need the CSV-representation of the line to throw an exception?
The recovered line is in the dump.

**Comment by swilde** [comment]
As I'm currently working to get a bunch of shadow server feed working for our customer I'll look into getting recover_line() of the shadowserver parser more robust, stay tuned...

**Comment by sebix** [comment]
Have a look at my fixes too: https://github.com/sebix/intelmq/blob/bugfixes/intelmq/bots/parsers/shadowserver/parser.py#L199

**Comment by swilde** [comment]
Intevation/intelmq@ea66a97a51aea75f93686fc137083c5225f604d0 replaces the custom code, which tried to recreate something looking like the original data from the feed, with the standard csv writer.

This fixes the original bug in `conv_csv_shadowserver` (by removing it) as well as the quoting problems pointed out by @bernhard-herzog.

Despite looking less like the original input it's no regression IMO, as the old code only used heuristics to make the result look a bit more like the original input, so the new code just stoppes pretending.

In case we would really want to embed the unaltered original data in the _raw_-field, we would have to find a way to preserve the original data during parsing and pass it on.  For now I think it wouldn't be worth the trouble.
