### ISSUE TITLE
shadowserver parser: test list

### ISSUE THREAD

**Issue by aaronkaplan** [certtools/intelmq#606]
Please test the following feeds with the shadowserver parser:
## Untested
- [ ] Botnet-Drone-Hadoop
- [ ] Open-SNMP
- [ ] Open-SSDP
- [ ] Microsoft-Sinkhole
- [ ] Sinkhole-HTTP-Drone
- [ ] Open-m DNS

## Tested, works
- [x] Open-Portmapper
- [x] Open-Memcached (see #603 )
- [x] Open-Elasticsearch 
- [x] Open-MSSQL
- [x] Open-NetBIOS
- [x] Open-Chargen
- [x] Open-TFTP
- [x] Ssl-Scan
- [x] NTP-Monitor
- [x] DNS-open-resolvers
- [x] Open-Redis
- [x] Open-QOTD
- [x] Open-NATPMP
- [x] Open-XDMCP
- [x] Open-Mongo DB (see #607 . Now closed. works)
## Deprecated?
- [x] Open-IPMI (Deprecated? note: we see sporadic ipmi data)

**Comment by dmth** [comment]
Just to be sure, the feeds worked before the parser was migrated to the new parser architecture.

The checklist has no function for people who are using this issue, as they (including me) can't edit it. So I don't know why I've been assigned to this issue.

**Comment by sebix** [comment]
yes, most of the bugs are fixed in https://github.com/certtools/intelmq/tree/shadowserver-bugfixes

We are currently testing all these in our production env. (works so far)

**Comment by aaronkaplan** [comment]
A lot of these were done in #648

**Comment by dmth** [comment]
AFAIK Shadowserver has changed the format of  Microsoft-Sinkhole and Sinkhole-HTTP-Drone feed by adding some extra fields.

**Comment by aaronkaplan** [comment]
For example?

**Comment by dmth** [comment]
those seem to be:
- cc_ip
- cc_asn
- cc_geo

**Comment by wagner-certat** [comment]
With the exception of null bytes (which is tracked in #967) there haven't been any problems with this parser. I think we can close this.
