### ISSUE TITLE
usability: check log levels and more detailed messages

### ISSUE THREAD

**Issue by aaronkaplan** [certtools/intelmq#614]
- Please run the whole network of bots in each debug level and observe the log messages if they make sense.
- Fix meaningless log messages.
- If there is a log message, it needs to clearly indicate possible actions for users/admins to take.

Example of a message which basically says nothing:

```
maxmind-geoip-expert - WARNING - Empty message received.
```

in WARNING mode.

**Comment by sebix** [comment]
Empty messages are invalid and should not happen. There's (probably?) a bug somewhere causing this. At least, empty messages are not created intentionally. That's why I have chosen warning level.

The same applies to reports without raw field. We can handle such messages (dropping), but nevertheless, it should not happen.

**Comment by aaronkaplan** [comment]
> On 26 Jul 2016, at 09:20, Sebastian <notifications@github.com> wrote:
> 
> Empty messages are invalid and should not happen. There's (probably?) a bug somewhere causing this. At least, empty messages are not created intentionally. That's why I have chosen warning level.
> 
> The same applies to reports without raw field. We can handle such messages (dropping), but nevertheless, it should not happen.

Sure, I agree.
But I guess my comment was more general. I simply noticed it in this case.
A message like this does not give the user any clue if anything is expected from the user. If we tell the use a warning message or error message, then there must be the option of some action IMHO.

It's more of a general usability issue I guess.

**Comment by sebix** [comment]
Conclusion: Log messages should be more verbose and explain the situation, e.g.:
> Empty message received. Some previous bot sent invalid data.
> Report without 'raw' data received and is ignored. Previous bot sent invalid data.
