### ISSUE TITLE
Unicode or ASCII domains for FQDNs?

### ISSUE THREAD

**Issue by sebix** [certtools/intelmq#622]
Currently, both representations are valid. But we should convert them to only one representation, avoiding duplicates.

``` python
>>> harm.FQDN.is_valid('ö1.at')
True
>>> harm.FQDN.is_valid('xn--1-0ga.at')
True
```

**Comment by aaronkaplan** [comment]
---
Mobile

> On 28.07.2016, at 15:00, Sebastian <notifications@github.com> wrote:
> 
> Currently, bot representations are valid. But we should convert them to only one representation, avoiding duplicates.
> 
> >>> harm.FQDN.is_valid('ö1.at')
> True
> >>> harm.FQDN.is_valid('xn--1-0ga.at')
> True

You mean normalize ?
I am for the xn-- standard in this case.

**Comment by aaronkaplan** [comment]
okay, decision: normalisation is IDN ("xn--" format)

**Comment by SYNchroACK** [comment]
@aaronkaplan +1 ;)
