### ISSUE TITLE
AttributeError: 'module' object has no attribute 'MalwareName'

### ISSUE THREAD

**Issue by pedromreis** [certtools/intelmq#623]
Hi

I'm having the following error in some parsers (so far cleanmx and abusech)

"traceback": "Traceback (most recent call last):\n  File \"/usr/lib/python3.4/site-packages/intelmq-1.0.0.dev4-py3.4.egg/intelmq/lib/bot.py\", line 121, in start\n    self.process()\n  File \"/usr/lib/python3.4/site-packages/intelmq-1.0.0.dev4-py3.4.egg/intelmq/bots/parsers/cleanmx/parser_virus.py\", line 79, in process\n    event.add(key, value)\n  File \"/usr/lib/python3.4/site-packages/intelmq-1.0.0.dev4-py3.4.egg/intelmq/lib/message.py\", line 119, in add\n    value = self.__sanitize_value(key, value)\n  File \"/usr/lib/python3.4/site-packages/intelmq-1.0.0.dev4-py3.4.egg/intelmq/lib/message.py\", line 198, in __sanitize_value\n    class_reference = getattr(intelmq.lib.harmonization, class_name)\nAttributeError: 'module' object has no attribute 'MalwareName'\n"

What is the problem?

PR

**Comment by sebix** [comment]
Update your harmonization.conf, MalwareName has been removed and replaced by LowercaseString

**Comment by dmth** [comment]
>Update your harmonization.conf, MalwareName has been removed and replaced by LowercaseString

Are you sure, that everybody is aware of this?

**Comment by sebix** [comment]
> Are you sure, that everybody is aware of this?

We could announce it on the mailinglist, but throwing warnings is not possible for harmonization-classes unfortunately (which is needed for announcing a deprecation).

**Comment by dmth** [comment]
Do please! It's even better to anounce changes like that BEFORE pushing them....

**Comment by pedromreis** [comment]
Ahhh, damn, offcourse. 
Tks @sebix

**Comment by dmth** [comment]
By the way: This issue is about the datatype `MalwareName` not the attribute `Malware.Name`
