### ISSUE TITLE
Shadowserver open-m DNS has wrong name

### ISSUE THREAD

**Issue by dmth** [certtools/intelmq#624]
The Shadowserver config has to be fixed for open-m DNS.

The latest renaming  of keys and feed names of the Shadowserver parser, caused some trouble.

But the renaming is still incomplete. See `open-m DNS`

Recent key: `Open-m DNS` ecpected key for the new naming scheme: `Open-mDNS`.

Please also update Readme accordingly.

**Comment by sebix** [comment]
Fixed by #625
