### ISSUE TITLE
problème d’utilisation 

### ISSUE THREAD

**Issue by benmohame** [certtools/intelmq#627]
après installation je reçois ces messages d'erreur : 

> failed to obtain JSON:http: //localhost/php/load_configs.php? file=bots with error: parserverror, syntaxError: Unexpected token < in JSON at position 0

et aussi

> failed to obtain JSON:http://localhost/Php/load_configs.php? file startup with error: parseverror, syntaxerror: Unexpected token < in JSON at position 0
 
svp besoin d'aide pour l'utulisation de intelmq

**Comment by sebix** [comment]
Most of us don't speak french, please continue in english here. Translation:

> After the installation I get this error message: ...

> And this one: ...

> Please help me to install intelmq

Can your webserver execute intelmqctl?

    sudo -u www-data sudo -u intelmq /usr/local/bin/intelmqctl

See also https://github.com/certtools/intelmq-manager/blob/master/docs/INSTALL.md#install

**Comment by dmth** [comment]
@benmohame Have you been able to solve your installation-troubles?

**Comment by dmth** [comment]
As there is no response @sebix please close this issue.
