### ISSUE TITLE
Busy wait with many logentries filling up logfiles with redis

### ISSUE THREAD

**Issue by bernhardreiter** [certtools/intelmq#630]
We have seen an unusable system because of logfiles filling up the disc.
The cause are several "Empty message received." entries, several per milisecond.

Our hypothesis: 
Introduced with certtools/intelmq/issues/439 (reloading of bots on SIGHUB) by @sebix in
https://github.com/certtools/intelmq/commit/e1795d225cfe83a8c381f09f0b49328fbc214385
an exception is caught and receive() which should be blocking returns "None" which
triggers a direct retry in intelmq/lib/bot.py receive_message().

Possible hotfix: Check for 
  `if message is None`
and retry only once.
The question is: Why is the exeception raised and caught in the first place? Our wild idea:
maybe the signal handling procedure does something dirty, so that the first call to redis
fails with the connection erroe. 

```
2016-08-04 14:42:30,551 - shadowserver-parser-Microsoft-Sinkhole - WARNING - Empty message received.
2016-08-04 14:42:30,551 - shadowserver-parser-Microsoft-Sinkhole - WARNING - Empty message received.
2016-08-04 14:42:30,551 - shadowserver-parser-Microsoft-Sinkhole - WARNING - Empty message received.
2016-08-04 14:42:30,552 - shadowserver-parser-Microsoft-Sinkhole - WARNING - Empty message received.
2016-08-04 14:42:30,552 - shadowserver-parser-Microsoft-Sinkhole - WARNING - Empty message received.
2016-08-04 14:42:30,553 - shadowserver-parser-Microsoft-Sinkhole - WARNING - Empty message received.
2016-08-04 14:42:30,553 - shadowserver-parser-Microsoft-Sinkhole - WARNING - Empty message received.
2016-08-04 14:42:30,553 - shadowserver-parser-Microsoft-Sinkhole - WARNING - Empty message received.
```

EDIT by @sebix: markup

**Comment by bernhardreiter** [comment]
What is the use case for "reload" anyway? 
Bots usually will not have much startup time, so why does reload makes sense?

Is it some sort of "graceful" restart which will not interrupt the current processing of the bot?
(In case of collector bots, they may not have insert everything at time of getting the signal.)

**Comment by sebix** [comment]
yes, see #439 

we could also change the handling a bit: ignore the signal totally and save a flag. When process() or it's sleeping ends then reload and continue. I think this is much less-interruptive. But i'm not sure it's possible tough.

**Comment by aaronkaplan** [comment]
> On 11 Aug 2016, at 11:29, Sebastian <notifications@github.com> wrote:
> 
> yes, see #439
> 

Yes, we need this for
a) config file changes & reloading (without re-starting everything)
b) logrotation

**Comment by sebix** [comment]
Did you try the hotfix in your setup?

I tried to simulate our currently implemented signal handling and get the `redis.exceptions.ConnectionError`, but failed. I introduced the handling of this exception because the signal interrupted the reading inside redis.

My current idea is to use [`signal.siginterruot`](https://docs.python.org/3/library/signal.html#signal.siginterrupt) with flag=False, so no interrupts happen we we continue as described in my above comment https://github.com/certtools/intelmq/issues/630#issuecomment-239113339

What do you think of this?

**Comment by bernhardreiter** [comment]
@sebix: Which hotfix are you refering to?

Regarding the use case: 
* If this should be a graceful "restart" the bot should make sure that items in processing are handled
  before it reloads.
* If it is about reloading databases and for logfile rotation: what advantages has "reload" over "restart" (which also reloads everything)?
* (for logfile rotation I guess that there are better solutions than just stopping, rotating and restarting).

**Comment by aaronkaplan** [comment]
restart will pull in all feeds again.
Regarding log rotation: if you have a better idea, let us know ;)

**Comment by sebix** [comment]
> Which hotfix are you refering to?

The one you mentioned in your report:
> Possible hotfix: Check for
`if message is None`
and retry only once.

Have you applied it?

> If this should be a graceful "restart" the bot should make sure that items in processing are handled before it reloads.

Currently working on a better handling (for sleeps, blocking reads from redis etc). Not sure if I will be successful. Maybe we need to start process() in a thread to make it independent from these signals.

**Comment by bernhardreiter** [comment]
No, we did not apply (or attempt) the hot fix (so far).
We don't have the error condition permanently and did not try to reproduce it. 
So right now, this is not a blocker (as long as redis and is okay).

**Comment by sebix** [comment]
Ok, I can handle blocking redis-reads now. Won't be interrupted and we can handle the reload after reading.

Nevertheless, sleep gets interrupted :(

With a working solution for the sleep-interrupt, I think this is better than the current solution.

**Comment by sebix** [comment]
I think I have a working solution now: https://github.com/sebix/intelmq/commit/e202fbfefe699f7f67e59501c88d3fd13511fe1b

Needs to be tested in production.
