### ISSUE TITLE
Refactor Parameters

### ISSUE THREAD

**Issue by sebix** [certtools/intelmq#632]
Currently, the used `parameter` is a stupid dummy class, can be replaced by (customized) dictionaries or other solutions.

**Comment by wagner-certat** [comment]
see also: https://github.com/bitprophet/lexicon#attributedict

**Comment by wagner-certat** [comment]
see also #757

**Comment by wagner-certat** [comment]
IEP01 / IntelMQ 3.0.0 solved that
