### ISSUE TITLE
gethostbyname Bot - improvements

### ISSUE THREAD

**Issue by SYNchroACK** [certtools/intelmq#653]
I think make sense to change the gethostbyname bot code like the following:

```
       ......

            if event.contains(key_ip):
                continue
            try:
                ip = socket.gethostbyname(event.get(key_fqdn))
                if intelmq.lib.harmonization.IPAddress.is_valid(ip, sanitize=True):
                    event.add(key_ip, ip, sanitize=True)
            except socket.gaierror:
                pass

        self.send_message(event)
        self.acknowledge_message()

       ......
```

What do you guys think? No point to get errors from fqdn's that doesn't translate to an IP.

**Comment by sebix** [comment]
Should we ignore all errors? E.g. EAI_MEMORY is a valid one.

See https://github.com/python/cpython/blob/master/Modules/socketmodule.c#L7549 for a full list.

proposal:

 - `EAI_ADDRFAMILY`: raise
 - `EAI_AGAIN`: raise
 - `EAI_BADFLAGS`: raise
 - `EAI_FAIL`: pass (no record)
 - `EAI_FAMILY`: raise
 - `EAI_MEMORY`: raise
 - `EAI_NODATA`: pass (no record)
 - `EAI_NONAME`: pass (no record)
 - `EAI_OVERFLOW`: raise
 - `EAI_SERVICE`: raise
 - `EAI_SOCKTYPE`: raise
 - `EAI_SYSTEM`: pass (no record)

But as I do not have much experience with sockets, please correct me if I'm wrong :)

**Comment by kralca** [comment]
socket.gaierror is raised when the name resolution fails (which @SYNchroACK 's proposed code handles). Without the check, any attempt to resolve a domain that cannot be resolved causes the bot to crash. I'd suggest implementing @SYNchroACK's proposed solution in the first instance as this is the most likely error to occur.

**Comment by sebix** [comment]
@kralca There are different kinds of [gaierror](https://docs.python.org/3/library/socket.html?highlight=socket.gaierror#socket.gaierror). IMHO we should not treat a non-existing record the same way as a problem in our side (implementation, library, setup, etc.).

**Comment by SYNchroACK** [comment]
@sebix cool. In your perspective, how should be treat in this case?

**Comment by sebix** [comment]
@SYNchroACK above I listed all possible errors and how we could treat them (raising an error or treating as normal answer). Please review this list if you have more knowledge of sockets and dns answer codes.

**Comment by wagner-certat** [comment]
Still waiting for feedback here.

**Comment by SYNchroACK** [comment]
> proposal:
> 
> EAI_ADDRFAMILY: raise
> EAI_AGAIN: raise
> EAI_BADFLAGS: raise
> EAI_FAIL: pass (no record)
> EAI_FAMILY: raise
> EAI_MEMORY: raise
> EAI_NODATA: pass (no record)
> EAI_NONAME: pass (no record)
> EAI_OVERFLOW: raise
> EAI_SERVICE: raise
> EAI_SOCKTYPE: raise
> EAI_SYSTEM: pass (no record)
> But as I do not have much experience with sockets, please correct me if I'm wrong :)

Agree.

```
root@server:~# cat sockets-test.py 
import sys
import socket

host = sys.argv[1]

try:
    ip = socket.gethostbyname(host)
    print("%s - %s" % (host, ip))
except socket.gaierror as v:
    print(v.args)


root@server:~# python3 sockets-test.py www.cybergreen.net
www.cybergreen.net - 151.101.60.133

root@server:~# python3 sockets-test.py cybergreen.net
(-2, 'Name or service not known')

root@server:~# python3 sockets-test.py cybergreen.netxxxxxxxxxxxxxxxx
(-2, 'Name or service not known')

root@server:~# ufw enable
Firewall is active and enabled on system startup

root@server:~# python3 sockets-test.py www.cybergreen.net
(-3, 'Temporary failure in name resolution')

root@server:~# python3 sockets-test.py cybergreen.net
(-3, 'Temporary failure in name resolution')

root@server:~# python3 sockets-test.py cybergreen.netxxxxxxxxxxxxxxxx
(-3, 'Temporary failure in name resolution')
```


From [this](http://www.castaglia.org/proftpd/doc/devel-guide/src/lib/glibc-gai_strerror.c.html) reference:
```
# define EAI_BADFLAGS     -1    /* Invalid value for `ai_flags' field.  */
# define EAI_NONAME       -2    /* NAME or SERVICE is unknown.  */
# define EAI_AGAIN        -3    /* Temporary failure in name resolution.  */
# define EAI_FAIL         -4    /* Non-recoverable failure in name res.  */
# define EAI_NODATA       -5    /* No address associated with NAME.  */
# define EAI_FAMILY       -6    /* `ai_family' not supported.  */
# define EAI_SOCKTYPE     -7    /* `ai_socktype' not supported.  */
# define EAI_SERVICE      -8    /* SERVICE not supported for `ai_socktype'.  */
# define EAI_ADDRFAMILY   -9    /* Address family for NAME not supported.  */
# define EAI_MEMORY       -10   /* Memory allocation failure.  */
# define EAI_SYSTEM       -11   /* System error returned in `errno'.  */
```
