### ISSUE TITLE
[3] Shadowserver Parser, Classification.identifer for snmp

### ISSUE THREAD

**Issue by dmth** [certtools/intelmq#657]
The value of the `classification.identifier` of the snmp feed in the shadowserver parser does not follow the same pattern as the other identifiers for vulnerable services.

https://github.com/certtools/intelmq/blob/master/intelmq/bots/parsers/shadowserver/config.py#L530

is: `snmp`
expect: `opensnmp`

is there a reason for this?

**Comment by aaronkaplan** [comment]
you are right.

**Comment by aaronkaplan** [comment]
@dmth please be sure if you pull this in that you also update the values in the eventdb!
