### ISSUE TITLE
[?] deduplicator expert bot ignores most of the hash bits

### ISSUE THREAD

**Issue by bernhard-herzog** [certtools/intelmq#658]
The deduplicator expert bot uses Python's builtin hash mechanism. This has the downside that the number of bits in the hash value is platform dependent: 64 bits on a 64 bit system, 32 bits on a 32 bit system. On 32 bit systems this makes collisions very likely! On 64 bit systems collisions are probably sufficiently unlikely.

Internally, the Event class uses sha256 to compute the hash value but most of that is thrown away. E.g. on a 64 bit system:

```
>>> import intelmq.lib.message
>>> evt = intelmq.lib.message.Event()
>>> hex(hash(evt))
'0x28d5f96f155d335'
>>> hex(evt.__hash__())
'0xe3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855'
```

**Comment by sebix** [comment]
I never had a deep look into the hash-functionality yet and it might need some revisal. Why do we even use `hex()` instead of  hashlib's `.hexdigest()` method?

Whitewashing: But who does use 32bit? On servers?

**Comment by bernhard-herzog** [comment]
I've used `hex` in my demonstration but internally, `__hash__` uses the `hexdigest` method.
I've only used `hex` to make the bit patterns more obvious.

**Comment by bernhard-herzog** [comment]
The likelihood of collisions is probably higher than it may seem, because, strangely, `hex(hash(evt))` does not simply yield the lowest 64 bits of `hex(evt.__hash__())`. As it turns out, the return value of `__hash__` is hashed again, if it's not yet in the value range of 64 bit ints:

```
>>> hex(hash(evt))
'0x28d5f96f155d335'
>>> hex(evt.__hash__())
'0xe3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855'
>>> hex(hash(evt.__hash__()))
'0x28d5f96f155d335'
```

See the code in `slot_tp_hash` in Python's `Python-3.4.3/Objects/typeobject.c`.

This extra hash will not make collisions less likely.

**Comment by sebix** [comment]
@bernhard-herzog What do you propose?

**Comment by bernhard-herzog** [comment]
I propose to rename the `__hash__` method to e.g. `hash` and call that method directly instead of going through the built-in function `hash`. This way, the deduplicator will use all the hash bits.

A side-effect of this change would be that the `hash` built-in would not work anymore for Message instances and they could not be used as keys in dictionaries or stored in sets anymore. I don't think that use should be supported by the Message classes anyway, though: They are derived from `dict` which doesn't support it either and in general in Python hashing is not supported for mutable objects, which is a good rule of thumb to follow for custom classes.

I don't know whether there is any code that relies on the hashability of the instances of the Message classes.

**Comment by aaronkaplan** [comment]
Multiple thoughts:
* If the discussion is about which hash method to use in general: I am fine with with @bernhard-herzog 's proposal.
* I think if the discussion is about 32 bits: simple answer -> no support for 32 bits at the moment. I could not care less
* If the discussion is about the speed of the deduplicator and potential improvements: please see #613 . That is actually relevant when feeding in a lot of data.

**Comment by bernhard-herzog** [comment]
> I think if the discussion is about 32 bits: simple answer -> no support for 32 bits at the moment.

Agreed. I don't think it's likely that a production setup on IntelMQ will be done on a 32 bit system for various reasons, not least because the Redis database would be limited to just 4GB of memory.

> If the discussion is about the speed of the deduplicator and potential improvements

This issue isn't about the speed, but depending on how we resolve this, it may lead to speed improvements. For instance it might be a good idea to switch from sha256 to a faster hash function with fewer bits. The rest of this comment explores this.

## How many bits should be deduplicator use for the hashes?

The deduplicator now uses only 64 bits (limiting the discussion to 64 bit systems) for the hash values, more by accident than design, it seems, but in practice that is probably fine. Assuming the hash values are evenly distributed, the probability that there are collisions is less than 3e-6 even when processing 10 million events per day (roughly one collision every 1000 years, on average) which might be good enough (using the approximations given by [the Wikipedia article on the birthday paradox](https://en.wikipedia.org/wiki/Birthday_paradox#Cast_as_a_collision_problem)).

The actual probability is likely higher than this, though, due to the extra hashing step as mentioned in [a previous comment](https://github.com/certtools/intelmq/issues/658#issuecomment-244047842). I'm not sure at all how much worse this makes the problem, but it will not be problem any longer once we stop using the builtin hash function.

That still leaves the question of how many bits to use. Computing more bits than we actually use is pointless and only slows things down. 64 bits is perhaps is on the low side, but I don't think we really need 256 bits. So it might be good to use e.g. sha1 instead of sha256 and to use the full sha1 hash value.

**Comment by aaronkaplan** [comment]
okay. So should we do a PR for this?

**Comment by bernhard-herzog** [comment]
I'm already preparing a pull request for at least some of these changes because it turns out to overlap with a substantial speed improvement which interestingly is not due to using a different hash. See my comment in #613

**Comment by bernhard-herzog** [comment]
When using the full hash for deduplication, the memory allocated by Redis per hash increases, obviously, but not by much. With the method described in https://github.com/certtools/intelmq/issues/709#issuecomment-251739505 I get ~196 bytes per hash instead of 160.
