### ISSUE TITLE
[13] AlienVault OTX Parser - detected a possible issue in harmonization.py

### ISSUE THREAD

**Issue by SYNchroACK** [certtools/intelmq#660]
```
 0: 2016-08-31T19:11:58.046883 intelmq.lib.exceptions.InvalidValue: invalid value 'dns.websecexp.com:81' (<class 'str'>) for key 'source.url' :
```

Proposal:

```
...
    @staticmethod
    def sanitize(value):
        value = value.replace('hxxp://', 'http://')
        value = value.replace('hxxps://', 'https://')

        if "://" not in value:
            value = "http://" + value

...
```

**Comment by sebix** [comment]
In harmonization we can't assume http:// for all URLs as default, as we don't know the context. But in the bot this is totally possible, as the parser bot (could) know, that the URLs are HTTP if not given otherwise.

ping @aaronkaplan

**Comment by aaronkaplan** [comment]
I agree with @sebix here. I am for keeping a strict (as strict as possible) interpretation in the main bot harmonisation, but if the individual bot knows better, he is allowed to overwrite that check.

**Comment by bernhardreiter** [comment]
So the AlienVault OTX Parser  should be changed to add a "https://" or "http://" if missing?
Is my understanding correct?

**Comment by sebix** [comment]
@bernhardreiter Probably, but I don't know the kind of data.

**Comment by wagner-certat** [comment]
No response, closing.
