### ISSUE TITLE
Very long BOTS file

### ISSUE THREAD

**Issue by sykaeh** [certtools/intelmq#668]
I was just setting up IntelMQ and IntelMQ Manager on our servers and I think it is a great tool, so thank you! As I was adding new nodes I noticed that the list of collectors and parsers is really long. What are the guidelines (if there are any) to adding a new collector to the BOTS file? 

Should there be a new entry for each possible feed (like abuse.ch and blocklist.de)? Or only if there is a separate module for it (i.e. not just using "intelmq.bots.collectors.http.collector_http" with a different URL)?

If the decision is to have a new entry for each feed URL, then I would suggest organizing it in a clearer way (especially in IntelMQ Manager).

**Comment by dmth** [comment]
Hi @sykaeh thank you for bringing up this topic.
My personal preference is the configuration of a "generic" http-url fetcher which allows to copy and paste the URL into it, without the need of creating a seperate entry in the BOTS file.

**Comment by sykaeh** [comment]
That would be my preference as well. My suggestion would be to keep these generic collectors:
 * Fileinput
 * MISP Generic
 * Generic Mail URL Fetcher
 * Generic Mail Attachment Fetcher
 * Generic URL Fetcher **(new)**
 * Request Tracker
 * XMPP collector

And add only the specific collectors that have their own module:
 * AlienVault OTX
 * BitSight Ciberfeed Stream
 * Blueliv Crimeserver
 * N6stomp

I'd be happy to make the changes this is something that is wanted.

In order not to loose all of the feed URLs we could put them in a list in the documentation somewhere, so that everyone can choose themselves whether or not they are relevant for them.

**Comment by aaronkaplan** [comment]
Thanks Sybil for commenting.
I also agree.

We currently know that the config structure right now is sub-optimal.
We were discussing changing that into a bots.d/* kind of config snippet layout.
Similar to /etc/foobar.d/* where  you can have a small config file for each relevant bot.

Playing together with that is the concept of inheritance and having more abstract classes (like HTTP collector) and simply instantiating them with actual parameters. This will make the config much leaner.

However, we are not there yet and struggling to clean up the last bugs which stop us from putting a release 1.0 tag on it.
We will address these config layout issues in release 1.1

That being said, I agree with all your comments below and I'd love to hear good concrete suggestions on how we should structure things in 1.1

Best,
a.

**Comment by aaronkaplan** [comment]
Ha!

Saw your answer just now.

> On 08 Sep 2016, at 11:00, Sybil Ehrensberger <notifications@github.com> wrote:
> 
> That would be my preference as well. My suggestion would be to keep these generic collectors:
> 
> 	• Fileinput
> 	• MISP Generic
> 	• Generic Mail URL Fetcher
> 	• Generic Mail Attachment Fetcher
> 	• Generic URL Fetcher (new)
> 	• Request Tracker
> 	• XMPP collector
> And add only the specific collectors that have their own module:
> 
> 	• AlienVault OTX
> 	• BitSight Ciberfeed Stream
> 	• Blueliv Crimeserver
> 	• N6stomp
> I'd be happy to make the changes this is something that is wanted.

Sounds good!

How about taking it further and the following layout:

* collectors
  * Fileinput
  * MISP Generic
  * Generic Mail URL Fetcher
  * Generic Mail Attachment Fetcher
  * Generic URL Fetcher (new)
  * Request Tracker
  * XMPP collector
* parsers
  * Generic CSV parser
  * Generic JSON parser
  * intelmq JSON parser  (<-- essentially just checking if an event conforms to the DHO)
  * ... specific parsers
  * ...
* experts
  ... list of all of them.. don't know yet how to structure them
* output
  * Fileoutput
  * Databases
    * Postgres
    * Elastic Search
    * ...
  * Network
    * TCP
    * Syslog
    ...


> 
> In order not to loose all of the feed URLs we could put them in a list in the documentation somewhere, so that everyone can choose themselves whether or not they are relevant for them.
> 
Yes, a list of data feeds actually exists. It's just not in the doc/ directory. It's in an issue.

Best,
a.

**Comment by sykaeh** [comment]
I think your layout with the generic bots at the top of the list and the specific bots afterwards is a good idea (and is easily implemented). Are you suggesting another layer of nesting for the output bots (i.e. Databases, Network)? As far as I can tell that cannot be done with the current way the configuration is handled, but if change the way the configuration works, then sure, it sounds like a good idea.

I support splitting up the configuration into smaller bots.d/ like files, but agree that this is a bigger issue that needs some more discussion and coordination. 

Regarding the list of data feeds, am I right in assuming that the issue you are referring to is #384?

From a new user's point of view it would be nice to have an overview of all of the available feeds with the following information:
 * status (i.e. ready to use, in development, not implemented yet)
 * description
 * collector bot to use and parameters (such as the URL)
 * parser bot to use

If we put this in the doc/ directory it is easily accessible to all, whether they are using the IntelMQ Manager or running IntelMQ from the command line. Right now it is either hidden in an issue or in a file somewhere. 

My main question for now is whether I should clean up the BOTS file and create the documentation for the data feeds or whether you think that it is not worth doing that since all of it is going to be reworked soon anyways. It wouldn't take very long and I think it would help the usability a lot.

**Comment by aaronkaplan** [comment]
I think creating an inventory of data feeds in docs/ would be tremendously useful for usability. 

Big +1 from me. :)

---
Mobile

**Comment by dmth** [comment]
From my understanding we have three tasks here:

- [ ] Cleanup of the BOTS Files: Remove the collectors which are simply a copy of a HTTP collector with a different URL
- [ ] Creation of a "Generic" HTTP-Collector: This should be achievable by configuration only. Alteration of .py files should not be necessary
- [ ] Heavy enhancement of the documentation.

Benefits: Whilst this is done, It can also be checked if these HTTP-Feeds are still accessible and if their syntax has stayed the same.

**Comment by sebix** [comment]
The stomp-bot is currently called `n6`, but `n6` is a feed, while `stomp` is the protocol. Maybe separate them?

**Comment by aaronkaplan** [comment]
> On 09 Sep 2016, at 14:30, Sebastian <notifications@github.com> wrote:
> 
> The stomp-bot is currently called n6, but n6 is a feed, while stomp is the protocol. Maybe separate them?
> 

Good thinking. Yes, agreed.

**Comment by SYNchroACK** [comment]
Folks, I re-opened this issue because I would like to propose something which is related to this topic.

**Proposal:**
From my perspective, there is a need to have a similar file like BOTS to have the default/template configurations for each feed. I would have it with name FEEDS in the same location as BOTS.

**Reasons:**

1. Automatically generate Feeds.md documentation page (yes, the new FEEDS file will include all good work that @sykaeh did. Thank you!)

2. Fast configuration generation. IntelMQ-Manager can have a new option which give to users a quick way to configure a feed without having to add a collector and a parser one by one, and in addition, without the overhead of adding manually the required configurations like the feed url ('http_url').

**FEEDS File Example:**
```
{
    "Zeus Tracker IPs": {
        "status": True,
        "description": "This list only includes IPv4 addresses that are used by the ZeuS Trojan. It is the recommended list if you want to block only ZeuS IPs. It excludes IP addresses that ZeuS Tracker believes to be hijacked (level 2) or belong to a free web hosting provider (level 3). Hence the false positive rate should be much lower compared to the standard ZeuS IP blocklist."
        "collector": {
            "module": "intelmq.bots.collectors.http.collector_http",
            "parameters": {
                "feed": "Zeus Tracker IPs",
                "provider": "Abuse.ch",
                "http_url": "https://zeustracker.abuse.ch/blocklist.php?download=badips",
                "rate_limit": 3600
            }
        },
        "parser": {
            "module": "intelmq.bots.parsers.abusech.parser_ip",
            "parameters": {}
        }
    },
    "Zeus Tracker Domains": {
        "status": False,
        "description": "The ZeuS domain blocklist (BadDomains) is the recommended blocklist if you want to block only ZeuS domain names. It has domain names that ZeuS Tracker believes to be hijacked (level 2). Hence the false positive rate should be much lower compared to the standard ZeuS domain blocklist.",
        "collector": {
            "module": "intelmq.bots.collectors.http.collector_http",
            "parameters": {
                "feed": "Zeus Tracker Domains",
                "provider": "Abuse.ch",
                "http_url": "https://zeustracker.abuse.ch/blocklist.php?download=baddomains",
                "rate_limit": 3600
            }
        },
        "parser": {
            "module": "intelmq.bots.parsers.abusech.parser_domain",
            "parameters": {}
        }
    }
}
```

**Your feedback:** please give me your feedback and if everyone agree I will implement this in the next few days (including the new option/section on IntelMQ-Manager). @aaronkaplan @sebix @sykaeh @dmth

**Comment by SYNchroACK** [comment]
Folks, I re-opened this issue because I would like to propose something which is related to this topic.

**Proposal:**
From my perspective, there is a need to have a similar file like BOTS to have the default/template configurations for each feed. I would have it with name FEEDS in the same location as BOTS.

**Reasons:**

1. Automatically generate Feeds.md documentation page (yes, the new FEEDS file will include all good work that @sykaeh did. Thank you!)

2. Fast configuration generation. IntelMQ-Manager can have a new option which give to users a quick way to configure a feed without having to add a collector and a parser one by one, and in addition, without the overhead of adding manually the required configurations like the feed url ('http_url').

**FEEDS File Example:**
```
{
    "Zeus Tracker IPs": {
        "status": True,
        "description": "This list only includes IPv4 addresses that are used by the ZeuS Trojan. It is the recommended list if you want to block only ZeuS IPs. It excludes IP addresses that ZeuS Tracker believes to be hijacked (level 2) or belong to a free web hosting provider (level 3). Hence the false positive rate should be much lower compared to the standard ZeuS IP blocklist."
        "collector": {
            "module": "intelmq.bots.collectors.http.collector_http",
            "parameters": {
                "feed": "Zeus Tracker IPs",
                "provider": "Abuse.ch",
                "http_url": "https://zeustracker.abuse.ch/blocklist.php?download=badips",
                "rate_limit": 3600
            }
        },
        "parser": {
            "module": "intelmq.bots.parsers.abusech.parser_ip",
            "parameters": {}
        }
    },
    "Zeus Tracker Domains": {
        "status": False,
        "description": "The ZeuS domain blocklist (BadDomains) is the recommended blocklist if you want to block only ZeuS domain names. It has domain names that ZeuS Tracker believes to be hijacked (level 2). Hence the false positive rate should be much lower compared to the standard ZeuS domain blocklist.",
        "collector": {
            "module": "intelmq.bots.collectors.http.collector_http",
            "parameters": {
                "feed": "Zeus Tracker Domains",
                "provider": "Abuse.ch",
                "http_url": "https://zeustracker.abuse.ch/blocklist.php?download=baddomains",
                "rate_limit": 3600
            }
        },
        "parser": {
            "module": "intelmq.bots.parsers.abusech.parser_domain",
            "parameters": {}
        }
    }
}
```

**Your feedback:** please give me your feedback and if everyone agree I will implement this in the next few days (including the new option/section on IntelMQ-Manager). @aaronkaplan @sebix @sykaeh @dmth

**Comment by sykaeh** [comment]
TBH, I am not a fan of another file with a long list of configuration parameters that needs to be maintained. The reason for initially creating this issue was that the `BOTS` file had become (and still is) very long and unmanageable. There were also too many options in the IntelMQ Manager to effectively have an overview and to be able to easily configure the bots. Additionally, I would like to get rid of the `BOTS` file altogether (see issue #757). 

IMHO, there is no need for such a file as it just makes maintenance more cumbersome and the actual amount of time saved is not worth the effort. Often times you need to adjust the parameters anyway (adding an API Key or making sure the provider and feed name work for your system). Additionally, this would not take into account the cases where you use the same parser for multiple collectors.

**Comment by wagner-certat** [comment]
> TBH, I am not a fan of another file with a long list of configuration parameters that needs to be maintained.

As the Feeds.md will be generated from the machine-readable version there isn't more maintenance needed.

A machine-readable version would be great, but it's only useful if it's actually handled by the manger too!

**Comment by SYNchroACK** [comment]
> As the Feeds.md will be generated from the machine-readable version there isn't more maintenance needed.
>
> A machine-readable version would be great, but it's only useful if it's actually handled by the manger too!

Yap, useful to IntelMQ-Manager and also to automatically generate feeds documentation to the users.

so...I will work on that.

**Comment by wagner-certat** [comment]
@SYNchroACK can you please create a new issue with your proposal? The original suggestion has been implemented, so we are mixing topics here.

**Comment by wagner-certat** [comment]
Original request is done, https://github.com/certtools/intelmq/issues/668#issuecomment-269729474 (reopen) is done too. If something is missing, please open a new issue, we are already mixing topic a lot here.
