### ISSUE TITLE
What is the status with outputs/intelmqmailer

### ISSUE THREAD

**Issue by sykaeh** [certtools/intelmq#672]
From the name of the bot I assumed outputs/intelmqmailer to be a an output bot that mails the event to someone. However, upon closer inspection of the code it almost looks like a duplicate of the mongodb output bot. What is the status on this?

I am also not sure how this is related to https://github.com/certtools/intelmq-mailer.

I am looking for something similar to #272, i.e. grouping several events based on certain fields, possibly adjusting the format and then sending them in a regular time interval.

**Comment by aaronkaplan** [comment]
> On 08 Sep 2016, at 18:27, Sybil Ehrensberger <notifications@github.com> wrote:
> 
> From the name of the bot I assumed outputs/intelmqmailer to be a an output bot that mails the event to someone. However, upon closer inspection of the code it almost looks like a duplicate of the mongodb output bot. What is the status on this?
> 

Outdated. Simple as that.
We (certat) use a postgresql DB as an intermediate step before sending out events.
The intelmqcli tool (github.com/certat/intelmq repo) is used to fetch the data from the DB and connect to our ticket system to send it out.

Hope it helped.

**Comment by sebix** [comment]
I never touched the intelmq-mailer during my work on intelmq (in the last 13 months). I don't even know what it is for and what it does exactly.

Also have look at certbund's tool: https://github.com/Intevation/intelmq-mailgen

**Comment by dmth** [comment]
Mailgen is capable of grouping events based on the ASN and the feed they came from, in order to send these events, the certbund-contact bot (see intevation fork) is required. Contact me if you need some advice on that.

**Comment by sebix** [comment]
Deprecated
