### ISSUE TITLE
How to handle outdated/broken components

### ISSUE THREAD

**Issue by dmth** [certtools/intelmq#673]
How to handle outdated / broken components in IntelMQ?

As we are approaching 1.0: 
Should we remove outdated / broken components  to achieve a stable and "satisfying" 1.0 release?

**Comment by dmth** [comment]
this post is reserved for a list of broken / outdated components. It may be altered by others. Feel free to do so.
Please "check" the checkbox once the issue is resolved.

**Outdated**
 - [ ] Example...

**Broken**
 - [ ] Example...

**Comment by sebix** [comment]
Yep, just remove them. Already did this with Microsoft DCU a while ago.

A number of output bots is untested, we need to check if they work or not. Candidates for this are:
 * outoputs: intelmqmailer, mongodb, restapi, tcp
 * experts: maxmind expert bot? tests?
 * intelmqmailer

**Comment by aaronkaplan** [comment]
> On 09 Sep 2016, at 11:08, Sebastian <notifications@github.com> wrote:
> 
> Yep, just remove them. Already did this with Microsoft DCU a while ago.
> 
> A number of output bots is untested, we need to check if they work or not. Candidates for this are:
> 
> 	• outoputs: intelmqmailer, mongodb, restapi, tcp
> 	• experts: maxmind expert bot? tests?

maxmind-geoip works, I am using it all the time.

**Comment by dmth** [comment]
> maxmind-geoip works
confirmed

**Comment by sebix** [comment]
checked/fixed: restapi, tcp, stomp (not tested), mongodb, http stream coll

So, what to do with the mailer? Remove the output bot and deprecate the software?

**Comment by aaronkaplan** [comment]
> On 14 Sep 2016, at 13:23, Sebastian <notifications@github.com> wrote:
> 
> checked/fixed: restapi, tcp, stomp (not tested), mongodb, http stream coll
> 
> So, what to do with the mailer? Remove the output bot and deprecate the software?

+1

**Comment by dmth** [comment]
How did you test the stream collector?

> So, what to do with the mailer? Remove the output bot and deprecate the software?

I think that's the way to go.

**Comment by sebix** [comment]
> How did you test the stream collector?

local webserver witn a csv-file, limited the rate to 1KB/s and watched the lines coming :)

**Comment by dmth** [comment]
> local` webserver witn a csv-file, limited the rate to 1KB/s and watched the lines coming :)

I don't know why, but I have a different concept of streaming.
