### ISSUE TITLE
Rate limiting and cronjobs

### ISSUE THREAD

**Issue by sebix** [certtools/intelmq#675]
The current implementation of rate_limit is not very useful. It would be much better if we had a daemon starting the bots: cron

`rate_limit` is useful for collectors to adjust the time between observations (runs) and all other bots to limit the amount of processed data.

dropping rate_limit for collectors has a few advantages:
 - No restarts needed anymore for collectors, which has the big flaw that all resources are fetched again.
 - they are executed at the same time.
 - no idling

[This is a reminder to fix this in future version and discuss it]
EDIT 2016-09-09: clarified wording

**Comment by dmth** [comment]
`rate_limit` also has another use: 
some feeds exist which only update daily (look at the blocklists) if the rate is lower than daily, you will insert the events twice into the pipeline which is not necessary.

**Comment by dmth** [comment]
Links with: https://github.com/certtools/intelmq/issues/464

**Comment by sebix** [comment]
Actually it's a duplicate.
