### ISSUE TITLE
[11] RPM packages

### ISSUE THREAD

**Issue by sebix** [certtools/intelmq#681]
for all kinds of distros!
- OpenSUSE
  - [x] Tumleweed (for testing)
  - [x] Leap 42.2
  - [ ] SLES 12 SP1 (with openSUSE backports)
- [x] Fedora (for testing)
- [x] CentOS 7
- [x] RHEL 7

See https://build.opensuse.org/project/show/home:sebix:intelmq

**Comment by wagner-certat** [comment]
CentOS is now building too

**Comment by wagner-certat** [comment]
RHEL is building. SLES has some more packages missing, so postpone for now.
