### ISSUE TITLE
initdb: wrong field definitions

### ISSUE THREAD

**Issue by aaronkaplan** [certtools/intelmq#682]
IMHO the following fields as generated by initdb.py are currently wrong:
  * ``raw varchar (100000)``  -> should be ``raw text``
  * ``"source.geolocation.cc" text`` -> should be ``"source.geolocation.cc" varchar(2)``
  *  ``"destination.geolocation.cc" text`` -> should be ``"destination.geolocation.cc" varchar(2)``

**Comment by sebix** [comment]
The tool always reads your current configuration in `/opt/intelmq/etc/harmonization.conf`.

This is the current state of the initdb.sql script in master: https://github.com/certtools/intelmq/blob/master/intelmq/tests/bin/initdb.sql (output is compared with the tool when running the tests, so it is always up-to-date)

**Comment by sebix** [comment]
l
