### ISSUE TITLE
deduplicator is too slow

### ISSUE THREAD

**Issue by aaronkaplan** [certtools/intelmq#685]
The rate of the dedup expert is somehow very slow.

## Proposal
  * make a test case with thousands or a couple of million entries, test and identify the bottleneck independently.
  * Then patch

**Comment by dmth** [comment]
Did you check if your system started swapping?

**Comment by aaronkaplan** [comment]
> On 23 Sep 2016, at 14:53, Dustin Demuth <notifications@github.com> wrote:
> 
> Did you check if your system started swapping?

Yes, it does not since swapping was disabled and I knew that I had enough RAM.

**Comment by dmth** [comment]
btw. this is a duplicate of: https://github.com/certtools/intelmq/issues/613
