### ISSUE TITLE
[13] Tests: Skip if no redis or no internet

### ISSUE THREAD

**Issue by sebix** [certtools/intelmq#687]
If we have a confined build environment we have to skip all test requiring internet access.

Same for redis if we cannot start the service.

**Comment by sebix** [comment]
For redis this partially works:

    INTELMQ_SKIP_REDIS=1 test-command

And this in front of every class needing redis.

    @unittest.skipIf(os.environ.get('INTELMQ_SKIP_REDIS'), 'Skipping without running redis.')

TODO: Mock the cache.

**Comment by aaronkaplan** [comment]
seems very relevant for the unit tests?

**Comment by sebix** [comment]
What do you mean?

**Comment by aaronkaplan** [comment]
It was a question ;)
