### ISSUE TITLE
[5] CSV format for output bots

### ISSUE THREAD

**Issue by sebix** [certtools/intelmq#690]
Output formats csv for output bots:
- [ ] file
- [ ] restapi?
- [ ] tcp
- [ ] udp

See also discussion #503

**Comment by dmth** [comment]
For Reference, an alternative concept for different formats in Outputs can be found here : https://github.com/certtools/intelmq/issues/487

**Comment by wagner-certat** [comment]
Done in bc95ecdd13f421c0dcdcfbd120890394fc5d83b2
