### ISSUE TITLE
[13] intelmqctl check

### ISSUE THREAD

**Issue by sebix** [certtools/intelmq#692]
Checks syntax/consistence of configuration
- [x] syntax
- [x] all bots are configured in runtime, <del>startup</del> and pipeline
- [ ] all parameters in BOTS exist in runtime + defaults (no missing params)
- [x] required module exists
...

**Comment by bernhardreiter** [comment]
Is there an implementation strategy already for implementing such a checking tool?

**Comment by sebix** [comment]
> Is there an implementation strategy already for implementing such a checking tool?

No, not yet.

In future we could also implement an automatic fix mode for missing parameters.

**Comment by bernhardreiter** [comment]
Sounds like this is not strictly necessary for v1.0.

**Comment by sebix** [comment]
But very helpful for new users (as e.g. #736 shows)

**Comment by aaronkaplan** [comment]
> On 12 Oct 2016, at 14:09, Sebastian <notifications@github.com> wrote:
> 
> Is there an implementation strategy already for implementing such a checking tool?
> 
> No, not yet.
> 

Hang on... too quick. Actually I do have some ideas!

> In future we could also implement an automatic fix mode for missing parameters.
> 
I would not do that. Rather report errors and fail.

**Comment by aaronkaplan** [comment]
> On 12 Oct 2016, at 14:49, Bernhard E. Reiter <notifications@github.com> wrote:
> 
> Sounds like this is not strictly necessary for v1.0.

No

**Comment by sebix** [comment]
> all parameters in BOTS exist in runtime + defaults (no missing params)

only possible when we know which parameters are optional,  #757
