### ISSUE TITLE
[13] Manpages for all binaries

### ISSUE THREAD

**Issue by sebix** [certtools/intelmq#696]
Currently there are these binaries missing a manpage:
- [ ] intelmqctl
- [ ] update-asn-data
- [ ] intelmq_psql_initdb
- [ ] update-tor-nodes
- [ ] intelmqdump
- [ ] update-geoip-data

**Comment by wagner-certat** [comment]
Unless someone wants to do this, I close here. All programs have help pages and we now also have nice docs on readthedocs
