### ISSUE TITLE
[8] ctl: add option to only restart running bots

### ISSUE THREAD

**Issue by sebix** [certtools/intelmq#704]
E.g.

```
intelmqctl restart --only-running
```

or similar. Would be very handy in daily use :)

**Comment by dmth** [comment]
I agree, but `--only-running` should be default. Consequently the other way round `--all` should be a parameter

**Comment by bernhardreiter** [comment]
Would #715 (an activated/deactivated setting) be a better solution for determining which bots to restart?

Another method to design this would be to enable a list of bots for "stop", "start", "status",
"restart" for all bots. Then you could use a list of bots to do a manual #715.
Anyway why is this important for v1.0?

**Comment by sebix** [comment]
>  Anyway why is this important for v1.0?

We can always postpone it, but it's handy.

**Comment by bernhardreiter** [comment]
Once #715 would be implemented, you would have another possibility to do the same thing. So I suggest to either do #715 right away for v1.0 or later. And close this one in favor of #715.

**Comment by sebix** [comment]
operations on botnet do not affect disabled bots now. directly starting is still possible
