### ISSUE TITLE
fix outputs/postgresql docs in Bots.md and README.md

### ISSUE THREAD

**Issue by bernhardreiter** [certtools/intelmq#711]
Split out from #355 only for the output/postgresql bot.
I've started working on it.

**Comment by bernhardreiter** [comment]
@SYNchroACK was there a special reason for recommending at last Postgresql 9.4?

E.g. Ubuntu 14.04 LTS still has postgresql 9.3 and probably other stable server GNU distributions as well. So if there is no feature that we are using, which mandates a minimum required, I'd like to remove the recommendation entirely.

**Comment by aaronkaplan** [comment]
> On 26 Sep 2016, at 12:43, Bernhard E. Reiter <notifications@github.com> wrote:
> 
> @SYNchroACK was there a special reason for recommending at last Postgresql 9.4?
> 
> E.g. Ubuntu 14.04 LTS still has postgresql 9.3 and probably other stable server GNU distributions as well. So if there is no feature that we are using, which mandates a minimum required, I'd like to remove the recommendation entirely.

There were some timestamp issues. @sebix knows them.

**Comment by bernhardreiter** [comment]
My first improvements are in branch https://github.com/Intevation/intelmq/tree/dev-postgresql-docs-patch-04, e.g. see [the diff].(https://github.com/certtools/intelmq/compare/master...Intevation:dev-postgresql-docs-patch-04?expand=1)

**Comment by bernhard-herzog** [comment]
> was there a special reason for recommending at last Postgresql 9.4?

I guess that's for the postgresql-output bot. Another bot that uses PostgreSQL is certbund_contact which could profit from using PostgreSQL >= 9.4 because it supports GiST indexes for the cidr type which would make it easier to efficiently query for e.g. all networks containing a given IP-address. It's possible to work around it, though, so 9.4 is not really required.

**Comment by sebix** [comment]
> There were some timestamp issues. @sebix knows them.

No, 9.4 is not necessary for the output bot. The output formatting parameter timezone `OF` is only available in >= 9.4, that's all.
See: https://www.postgresql.org/docs/9.4/static/functions-formatting.html

**Comment by bernhardreiter** [comment]
@sebix what is the time-zone offset formatting used for? (Personally I believe that if a time-zone is needed, it should be the full tz name, because otherwise you cannot calculate time-zone related things like daylight saving time). 

Would it be okay to write something like:
_If you use v <=9.4 that gives you the possibility to use the time-zone output formatting for date-times and the GiST index for the cidr type._

**Comment by sebix** [comment]
On 09/27/2016 08:27 AM, Bernhard E. Reiter wrote:
>
> @sebix <https://github.com/sebix> what is the time-zone offset
> formatting used for?
>
We used it in out intelmqcli, but that's not at all related to the
output bot. But that's what @aaronkaplan meant.

I do not know why the limitation for the output bot exists, maybe it
hasn't been tested for <9.4?

The limitation has been added in
ad8711142c1a00a2d3cfdba2a35acf6d1c7438d5 by @SYNchroACK

**Comment by bernhardreiter** [comment]
Yes, I saw that @SYNchroACK added the recommendation, this is why I had asked him in my second commend above. :-) 

We run the output bot in some testing environments with Ubuntus 14.04 LTS Postgresql 9.3, 
and have not noticed a big problem so far.
