### ISSUE TITLE
[1] Separate stomp from n6

### ISSUE THREAD

**Issue by sebix** [certtools/intelmq#716]
Follow up of #668: https://github.com/certtools/intelmq/issues/668#issuecomment-245899429

> The stomp-bot is currently called n6, but n6 is a feed, while stomp is the protocol. Maybe separate them?

Could also be done in 1.0 if someone has time for it.

**Comment by dmth** [comment]
Can you explain the approach of separation a little bit? I think the n6stomp feed is very specific (custom ca, client certs, etc).
A "generic" Stomp collector would still require these configuartion parameters.
Isn't this just a rename of the collector?

**Comment by sebix** [comment]
>  Isn't this just a rename of the collector?

AFAI understand, yes.
