### ISSUE TITLE
[13] shadowserver parser: put less into the extra field

### ISSUE THREAD

**Issue by aaronkaplan** [certtools/intelmq#722]
At least our system needs to send out _less_ unneccessary info from the extra. field in the shadowserver feeds. Otherwise we risk to overwhelm recipients.
If the shadowsserver extra info contains **relevant** information for identifying a system (example SNMP `sysdesc` or openelasticsearch `clustername`) then include it. Otherwise exclude it.

**Comment by sebix** [comment]
I think this is not an issue of the parser, but concerns only the sending component. Independent of what receivers are allowed to see, we still want to have the full data in our database.

IMHO: -> certat

**Comment by aaronkaplan** [comment]
Yeah, but do you really want to clobber up the whole DB  with lots of identical infos?
Filtering out which (JSON) elements we want from the extra field will be cumbersome on the output side.
I'd rather opt for a specific filtering on the input side here.
@otmarlendl, what do you say?

**Comment by otmarlendl** [comment]
Only the parser is specific to the source. So I'd put the code in there. One *might* use a second bot after the parser to filter, but IMHO that's overkill. The sending component doesn't know about sources and their peculiarities.

What I'd like to see is a parser-bot config option listing the fields-names from the source that should be put into the extra (or whatever we chose to call it) field.

**Comment by aaronkaplan** [comment]
> On 05 Oct 2016, at 21:16, otmarlendl <notifications@github.com> wrote:
> 
> Only the parser is specific to the source. So I'd put the code in there. One might use a second bot after the parser to filter, but IMHO that's overkill. The sending component doesn't know about sources and their peculiarities.
> 
> What I'd like to see is a parser-bot config option listing the fields-names from the source that should be put into the extra (or whatever we chose to call it) field.
> 

It's actually there:
See https://github.com/certtools/intelmq/blob/master/intelmq/bots/parsers/shadowserver/config.py
That is a "config" but in the source code of the bot.

Do you mean an option for .../etc/runtime.conf?
(This would totally blow up the runtime.conf BTW).

**Comment by dmth** [comment]
> At least our system needs to send out less unneccessary info from the extra. field in the shadowserver feeds. Otherwise we risk to overwhelm recipients.
If the shadowsserver extra info contains relevant information for identifying a system (example SNMP sysdesc or openelasticsearch clustername) then include it. Otherwise exclude it.

Are you currently forwarding the whole event to your customers? We are only sending a subset of the event, and in some cases a subset of the extra field for some feeds. Nevertheless we collect everything.

I assume there is no way to tell which additional information can be dropped safely from the extras field. 

IMHO It's the task of the sending component to determine what has to be forwarded and what not.

**Comment by sebix** [comment]
On 10/06/2016 10:05 AM, Dustin Demuth wrote:
> Are you currently forwarding the whole event to your customers?
No, but one of the fields we send is the extra-field.
>
> I assume there is no way to tell which additional information can be
> dropped safely from the extras field.
>
Currently not. We can implement this on parser level and in the sending
component. The first can drop known unnecessary fields by explicitly
ignoring them or only including those explicitly defined. I'd vote for
the first, otherwise we are never get notified of changes in the format.
>
> IMHO It's the task of the sending component to determine what has to
> be forwarded and what not.
>
+1

**Comment by aaronkaplan** [comment]
> On 06 Oct 2016, at 10:29, Sebastian <notifications@github.com> wrote:
> 
> On 10/06/2016 10:05 AM, Dustin Demuth wrote:
> > Are you currently forwarding the whole event to your customers?
> No, but one of the fields we send is the extra-field.
> >
> > I assume there is no way to tell which additional information can be
> > dropped safely from the extras field.
> >
> Currently not. We can implement this on parser level and in the sending
> component. The first can drop known unnecessary fields by explicitly
> ignoring them or only including those explicitly defined. I'd vote for
> the first, otherwise we are never get notified of changes in the format.
> >

Exactly. So this IMHO speaks for having a lot of that logic in the parser.
The parser is responsible for handing over a solid, good and useable Event (dict()) to the following components.
Usually a parser will select fields from a source. See also for example the n6stomp parser. There are more fields there but we intentionally ignore some since they add little value.

However, I get it that what I think is relevant info in the extra field might not be exactly the same as what you or someone else needs.


So, this is a bit of a conundrum.

Don't know yet how to handle that. This smells like it should after all be a configurable option.
But I would hate to put such complex config options into runtime.conf (this would blow it up a lot ).

**Comment by sebix** [comment]
See also certat/intelmq#94

**Comment by bernhardreiter** [comment]
To me there should be a clear understanding what a complete event within intelqm is, including: Which fields do we want to have in there? All other fields should be dropped as early as possible, for speed and archive space reasons. Early as possible means: the parser.

If there are fields coming up often, they should become standard optional fields (as opposed to "extra" fields).

Some outputs may decide to not send out or need some of the event values, so there is a second
 line of filtering.

Just my 2 €-cents.

**Comment by wagner-certat** [comment]
> However, I get it that what I think is relevant info in the extra field might not be exactly the same as what you or someone else needs.

So how do you want to solve this?

> To me there should be a clear understanding what a complete event within intelqm is,

That's up to the user IMHO

**Comment by aaronkaplan** [comment]
okay, so after a lot of discussion here (a very long discussion) we'll go the way of the least unexpected behaviour for users of intelmq:
  *  the parser SHALL NOT filter out any extra.* fields intentionally. Since it does not know if these might be needed "downstream". 
  * If a setup does not want certain extra fields, it MAY filter these out via the field-reducer bot
  * In the case of certat: only the sending component knows what fields to send out to the constituency (in the certat case: the intelmqcli tool)


--> action items:
 - [ ] re-inspect the field-reducer bot if it can handle the extra.* fields
 - modify the certat installation so that we know which extra.* fields we actually want to show to the consituency.

**Comment by wagner-certat** [comment]
> re-inspect the field-reducer bot if it can handle the extra.* fields

-> #793 

>  modify the certat installation so that we know which extra.* fields we actually want to show to the consituency.

closed issue certat/intelmq#94 and merged pull request certat/intelmq#95

**Comment by dmth** [comment]
>  * the parser SHALL NOT filter out any extra.* fields intentionally. Since it does not know if these might be needed "downstream".
>  * If a setup does not want certain extra fields, it MAY filter these out via the field-reducer bot
> * In the case of certat: only the sending component knows what fields to send out to the constituency (in the certat case: the intelmqcli tool)

Thank you for discussing this issue throughly. This seems to be similar to our approach.
The configuration of Intelmq-Mailgen is also capable of filtering out the necessary information.
