### ISSUE TITLE
Extension of the DHO by a Field `feed.provider`

### ISSUE THREAD

**Issue by dmth** [certtools/intelmq#725]
Currently the DHO can only reflect the `Name`, `Url` and `Code` of a feed, it is not possible to store the provider / feeder of an information.

We think its necessary to extend the DHO by such a field, an also enhance the documentation how these fields are used.

For instance:

`feed.provider` : shadowserver <- Set by Parser
`feed.name`: Sinkhole-HTTP-DRONE <- Set by Parser
`feed.code`: MyTrustableSource <- Set by user in Runtime.conf
`feed.url`: url://to.feed.description <- Set by Parser

**Comment by sykaeh** [comment]
I think having a field `feed.provider` is a good idea, but shouldn't the `feed.provider`, `feed.name` and `feed.url` be set in the collector?

**Comment by dmth** [comment]
In the collector they have to be fields which are configurable by the user. As you can use collectors for different feeds. If those parameters are set in the parser, the user configuration is not necessary (at least for the specialised parsers like shadowserver), because these fields should be known by parser or its specific configuration.

One idea is that the field `feed.provider` is also available in the collector, but the parser would ensure, that the field is populated if no value was set in the collector.

The values of some parameters like `feed.name` are evaluated (at least in our use case) in later steps, for instance when generating e-mails, we rely on the fact that these values can always be determined. If they become a user-configurable parameter, it might happen, that the event cannot be processed at the end.

**Comment by sebix** [comment]
I think it boils down to: Can one collector collect only one feed or multiple?

**Comment by sykaeh** [comment]
It's actually both whether the collector and the parser can collect/parse one feed or multiple. 

For example in the Shadowserver case, it would be easy to use one collector to collect all feeds, but you could also use one collector per feed type. The same is true for the parser. You could use one Shadowserver parser to parse all of the feeds (assuming you know what the `feed.name` field is already filled out) or you could have a separate parser for each feed type.

It would be possible to have one collector per Shadowserver feed and then only one parser that relies on the `feed.name` to determine how to parse the feed. However, the opposite is not possible (one collector, many parsers).

IMHO, the information about the feed belongs in the collector, as that is where you are actually retrieving the feed. The parser only knows what the feed is based on the current configuration (or possibly based on values in the feed itself).
