### ISSUE TITLE
New Shadowserver Config breaks Compatibility

### ISSUE THREAD

**Issue by dmth** [certtools/intelmq#726]
The merge of https://github.com/certtools/intelmq/pull/648 has broken compatibility with our software.

This is mostly because the alteration of the field `feed.name`. See my comment https://github.com/certtools/intelmq/pull/648#issuecomment-251890931 for details.

**Comment by aaronkaplan** [comment]
> On 07 Oct 2016, at 13:18, Dustin Demuth <notifications@github.com> wrote:
> 
> The merge of #648 has broken compatibility with our software.
> 
> This is mostly because the alteration of the field feed.name. See my comment #648 (comment) for details.

As discussed in the phone call right now, will fix.
thx

**Comment by dmth** [comment]
This issue seems to be fixed in https://github.com/certtools/intelmq/pull/752

**Comment by sebix** [comment]
Is this still an issue @dmth?

**Comment by dmth** [comment]
as #752 was merged, I'll close this issue.
