### ISSUE TITLE
Extend intelmq_psql_initdb.py by indices

### ISSUE THREAD

**Issue by dmth** [certtools/intelmq#728]
In order to work with the EventDB resulting from the SQL generated by `intelmq_psql_initdb.py`, som indices a missing. It would be good if the script is extended in this way.

**Comment by aaronkaplan** [comment]
I can add the indices that we use as example. 
Ultimately it will depend on how you use the eventdb. 



---
Mobile

**Comment by aaronkaplan** [comment]
Would this work out for everyone?
If so, I'll create a PR.

```
CREATE INDEX "idx_classification.identifier" ON events USING btree ("classification.identifier");
CREATE INDEX "idx_classification.taxonomy" ON events USING btree ("classification.taxonomy");
CREATE INDEX "idx_classification.type" ON events USING btree ("classification.type");
CREATE INDEX "idx_feed.code" ON events USING btree ("feed.code");
CREATE INDEX "idx_feed.name" ON events USING btree ("feed.name");
CREATE INDEX idx_notify ON events USING btree (notify);
CREATE INDEX idx_sent_at ON events USING btree (sent_at);
CREATE INDEX "idx_source.abuse_contact" ON events USING btree ("source.abuse_contact");
CREATE INDEX "idx_source.asn" ON events USING btree ("source.asn");
CREATE INDEX "idx_source.fqdn" ON events USING btree ("source.fqdn");
CREATE INDEX idx_source_geolocation_cc ON events USING btree ("source.geolocation.cc");
CREATE INDEX idx_source_ip ON events USING btree ("source.ip");
CREATE INDEX "idx_time.observation" ON events USING btree ("time.observation");
CREATE INDEX "idx_time.source" ON events USING btree ("time.source");
```

**Comment by bernhard-herzog** [comment]
At a first glance, the choice of columns for which indexes are created seems OK, at least the ones which are properties of the observed event as opposed to meta data about notifications. But, assuming this is precisely what would end up in the PR:

 - The names of the indexes should also contain the table name, e.g. `"idx_events_feed.code"`.

 - The periods in the column names should be handled consistently. They should either always be converted to `_` in the index name or always be kept.

- `notify` and `sent_at` are not in harmonization.conf (I haven't checked the others)

**Comment by aaronkaplan** [comment]
> On 10 Oct 2016, at 16:53, Bernhard Herzog <notifications@github.com> wrote:
> 
> At a first glance, the choice of columns for which indexes are created seems OK, at least the ones which are properties of the observed event as opposed to meta data about notifications. But, assuming this is precisely what would end up in the PR:
> 
> 	• The names of the indexes should also contain the table name, e.g. "idx_events_feed.code".
> 
> 	• The periods in the column names should be handled consistently. They should either always be converted to _ in the index name or always be kept.
> 
> 	• notify and sent_at are not in harmonization.conf (I haven't checked the others)

True, nice catch. These are certat repo specifics.
Good. Will follow the advice and make a PR with the remaining indices.
