### ISSUE TITLE
Sanitizing JSON-type field

### ISSUE THREAD

**Issue by cert-lv** [certtools/intelmq#729]
Currently for a field **extra** we use type **JSON**. If a value contains non-english characters -  after **sanitize()** method we get something like `universit\u0101te` instead of `universitāte`.

This is done by `json` library's **json.dumps()** function (default settings). The solution is simple - in the `intelmq/lib/harmonization.py` replace a line
```python
return GenericType().sanitize(json.dumps(value, sort_keys=True))
```
with:
```python
return GenericType().sanitize(json.dumps(value, ensure_ascii=False, sort_keys=True))
```

**Comment by aaronkaplan** [comment]
> On 11 Oct 2016, at 10:42, cert-lv <notifications@github.com> wrote:
> 
> Currently for a field extra we use type JSON. If a value contains non-english characters - after sanitize() method we get something like universit\u0101te instead of universitāte.
> 
> This is done by json library's json.dumps() function (default settings). The solution is simple - in the intelmq/lib/harmonization.py replace a line
> 
> return GenericType().sanitize(json.dumps(value, sort_keys=True))
> with:
> 
> return GenericType().sanitize(json.dumps(value, ensure_ascii=False, sort_keys=True))

Thanks!!

**Comment by sebix** [comment]
Well, this is the same. It's just another representation.

```python
>>> 'universit\u0101te'
'universitāte'
>>> json.dumps('universit\u0101te')
'"universit\\u0101te"'
>>> json.loads(json.dumps('universit\u0101te'))
'universitāte'
```

The question is another one: which representation do we want? Redis supports both.

**Comment by cert-lv** [comment]
Yes, it's just a representation. If **ensure_ascii** is true (the default), all non-ASCII characters in the output are escaped with **\uXXXX** sequences, and the result is a **str** instance consisting of ASCII characters only.

So everywhere we want to display data or to store it in a readable format we'll need a conversion function to get "Unicode" strings. This small fix would solve the issue in one place globally. Or you have some plans to use ASCII only inside IntelMQ?

**Comment by sebix** [comment]
No, we basically want unicode as default. The message queue can do anything as long as input equals output.

Will arrange it.

**Comment by dmth** [comment]
I'm not quite sure about this, but when procession in "non-ASCI"-Mode it might be required to ensure the Event-DB is created with UTF-8 support.

**Comment by bernhard-herzog** [comment]
> So everywhere we want to display data or to store it in a readable format we'll need a conversion
> function to get "Unicode" strings.

What exactly is the problem? Initially you have a string containing a JSON representation. To show this to a user or store it in a different format, you always need to decode it first. Why does it matter here whether the JSON representation uses ASCII only?

One problem that might arise is what @dmth mentions: If it's not ASCII you may have to be careful about the encoding of the serialized JSON representation.

**Comment by cert-lv** [comment]
@bernhard-herzog, the problem is that in input you have a Unicode string, then IntelMQ converts it to the ASCII, then you have to convert it back to the Unicode. If we send Unicode to the IntelMQ - we would like to see Unicode in the output:

```'{"a": "universitāte"}'``` instead of ```'{"a": "universit\u0101te"}'```

**Comment by sebix** [comment]
@cert-lv could you please explain where the representation is a problem? Both are the same, and handled equally by python.

**Comment by cert-lv** [comment]
@sebix, when human sees the whole **extra** as one string, for example, it's not readable. Ofcourse you can convert it later everywhere you want - 15 output bots could have their own 15 converters, but why? It's a good thing to solve a problem in one place, and Unicode's transparent support is an even better thing

**Comment by sebix** [comment]
@cert-lv So it's only about readability of debug log messages?

**Comment by cert-lv** [comment]
We have realized, that JSON format requires backslashes. Otherwise something else can break if people/libraries expect ASCII only. We'll try to update our outputs instead of IntelMQ core. This issue can be closed

**Comment by sebix** [comment]
>  if people/libraries expect ASCII only

Are there any know components expecting ASCII only which affect us?

**Comment by cert-lv** [comment]
It's hard to say, but it is possible that some IntelMQ users have them, and everything is fine until you get new issues about unexpected characters in **extra** field. So lets do nothing with this issue. As for us, at the moment it is a representation question only, which will be fixed in the Output bots
