### ISSUE TITLE
feed.* naming: clean up after PR #648

### ISSUE THREAD

**Issue by aaronkaplan** [certtools/intelmq#733]
#648 added a "feed.name" to the config.py. However, as it turned out with a discussion between @dmth and me, we actually had two different concepts in mind:
- feeder (i.e. the source of the data feed) - let's call it now "feed.provider"
  and
- one or multiple feeds ("feed.name") that a "feed.provider" might provide.

We need to separate these concepts.

Action items:
- [x] revert back the addition of "feed.name" to config.py
- [ ] add a "feed.provider" to the DHO
- [ ] clarify DHO description
- [ ] add a "feed.provider" to the config.py  to the collector
- [ ] adapt test cases

**Comment by sykaeh** [comment]
A separate issue for `feed.provider` has been opened, see #725.
