### ISSUE TITLE
contact lookups: need a way to decide which abuse contact to use based on the ASN

### ISSUE THREAD

**Issue by aaronkaplan** [certtools/intelmq#734]
One client gave us feedback that they want to be in the CC: of outgoing emails, but want us to sent to the RIPE whois abuse_c of the netblock/IP address directly as well.
They intentionally register the client in the RIPE DB 

This should be supported by any contact db

**Comment by wagner-certat** [comment]
I'm not sure if this should/could be solved by intelmq itself

**Comment by wagner-certat** [comment]
https://intelmq.readthedocs.io/en/maintenance/user/abuse-contacts.html guides through various abuse contact-lookup approaches
IntelMQ supports multiple ways to lookup that data now
