### ISSUE TITLE
Add client side certificate to HTTP collector

### ISSUE THREAD

**Issue by sykaeh** [certtools/intelmq#737]
To be able to use the generic HTTP collector with the N6 HTTP feeds, we need to be able to specify the client side certificate. Currently there is no parameter for that. The `requests` library supports two methods:

> You can also specify a local cert to use as client side certificate, as a single file (containing the private key and the certificate) or as a tuple of both file's path.

For our use case a single file is enough, but maybe we should allow the tuple as well? 

It also begs the question if we should refactor the collectors that make HTTP requests so that there is less duplicated code and more consistent support for the various options (basic authentication, proxies, headers, SSL cert verification). Currently the following collectors make HTTP requests:
- HTTPCollectorBot
- HTTPStreamCollectorBot
- MailURLCollectorBot
- RTCollectorBot

**Comment by cert-lv** [comment]
It would be great to have universal HTTP Collector, but currently `requests` library doesn't support certificates with a password, so there is no easy place to type a password in if you have that. Be ready to implement a temporary workaround.

More info: https://github.com/kennethreitz/requests/issues/1573

Another option is to use `pycurl` library.

**Comment by sebix** [comment]
How important are password-protected for your current needs? File passwords needs to be placed in the config anyway.

Providing client certificates can be implemented very easily. One method is enough - they are equivalent anyway.

**Comment by sykaeh** [comment]
We do not need support for password-protected certificates.

**Comment by aaronkaplan** [comment]
I agree with @sykaeh here. For now IMHO it is enough to support password-less client certificates.
You can convert a password protected client certificate via openssl to a password-less. one.
I 100% agree with @sykaeh approach here. Let's add it in a generic way.
