### ISSUE TITLE
n6stomp parser classification

### ISSUE THREAD

**Issue by sykaeh** [certtools/intelmq#738]
While trying to create a parser for the n6 HTTP report, I was looking at the n6stomp parser. I thought that I would be able to re-use much of the parser since the format looks to be the same (although I don't know if/where there is any documentation available).

However, the classification seems to introduce a couple of new `classification.type` that are not defined in the [Data-Harmonization](https://github.com/certtools/intelmq/blob/master/docs/Data-Harmonization.md):
- account numbers
- leak
- proxy
- tor
- ignore
- other

My understanding was that the Data-Harmonization was an exhaustive list of all possible values for `classification.type`. Is that not correct? 

According to Harmonization-fields.md:

> Furthermore, the value data set should be kept as minimal as possible to avoid “type explosion”, which in turn dilutes the business value of the dynamic typing. 

So, if the Data-Harmonization is not a complete list, can we have a complete list somewhere?

**Comment by aaronkaplan** [comment]
> On 12 Oct 2016, at 17:44, Sybil Ehrensberger <notifications@github.com> wrote:
> 
> While trying to create a parser for the n6 HTTP report, I was looking at the n6stomp parser. I thought that I would be able to re-use much of the parser since the format looks to be the same (although I don't know if/where there is any documentation available).
> 
> However, the classification seems to introduce a couple of new classification.type that are not defined in the Data-Harmonization:
> 
> 	• account numbers
> 	• leak
> 	• proxy
> 	• tor
> 	• ignore
> 	• other

Ahm... "type" is always free text form - also already in the original eCSIRT II taxonomy.

> My understanding was that the Data-Harmonization was an exhaustive list of all possible values for classification.type. Is that not correct?
> 
Nope.

taxonomy == fixed. There are exactly 11 values according to the eCSIRT II taxonomy
type == example values in the eCSIRT II taxonomy.

> According to Harmonization-fields.md:
> 
> Furthermore, the value data set should be kept as minimal as possible to avoid “type explosion”, which in turn dilutes the business value of the dynamic typing.
> 
of course this still holds. But I guess that more or less expressed a wish Tomas and me had some time ago.
For sure the type field is not an exhaustive list

> So, if the Data-Harmonization is not a complete list, can we have a complete list somewhere?

Very good point!
But where to start and end?
I guess the best thing here would be to have a standardisation body (IANA, FIRST, ...) which defines these and there is a process to add new values to this list.

**Comment by sykaeh** [comment]
> Ahm... "type" is always free text form - also already in the original eCSIRT II taxonomy.

I guess the thing that confused me was that in the Harmonization field names, the field type for `classification.type` is not `String` but instead `ClassificationType` (implying that it can't just be any string) and the field type for `classification.taxonomy` is `String`. I suggest we change the documentation to make it clearer.

**Comment by aaronkaplan** [comment]
> On 12 Oct 2016, at 18:46, Sybil Ehrensberger <notifications@github.com> wrote:
> 
> Ahm... "type" is always free text form - also already in the original eCSIRT II taxonomy.
> 
> I guess the thing that confused me was that in the Harmonization field names, the field type for classification.type is not String but instead ClassificationType (implying that it can't just be any string) and the field type for classification.taxonomy is String. I suggest we change the documentation to make it clearer.

Nice catch. I agree.

Thanks.

**Comment by dmth** [comment]
Am Mittwoch 12 Oktober 2016 17:44:52 schrieb Sybil Ehrensberger:

> * leak
> * proxy
> * tor
> * ignore
> * other

If those keys get into the taxonomy expert, the expert will fail.

-- 
dustin.demuth@intevation.de  https://intevation.de/   OpenPGP key: B40D2EFF
Intevation GmbH, Neuer Graben 17, 49074 Osnabrück; AG Osnabrück, HR B 18998
Geschäftsführer:   Frank Koormann,  Bernhard Reiter,  Dr. Jan-Oliver Wagner

**Comment by wagner-certat** [comment]
Proposal for type -> taxonomy:
- [ ] account numbers: information content security?
- [ ] leak: information content security
- [x] proxy: other, see #800
- [ ] tor: other
- [ ] ignore: should be ignored outright?!
- [ ] other: other

Does anyone have documentation for the cert.pl feed?

**Comment by wagner-certat** [comment]
Btw, With #836 the taxonomy expert no longer fails, it defaults to other and unknown.

**Comment by wagner-certat** [comment]
If there's no feedback for the proposal in https://github.com/certtools/intelmq/issues/738#issuecomment-276056068 I'll have to postpone this to 1.1

**Comment by dmth** [comment]
> Does anyone have documentation for the cert.pl feed?

What do you need?

**Comment by wagner-certat** [comment]
> What do you need?

To check which types are allowed.

**Comment by wagner-certat** [comment]
The category `account numbers` is not documented in n6.

There are some more strange mappings:
* [ ] other is mapped to vulnerable: https://github.com/certtools/intelmq/blob/master/intelmq/bots/parsers/n6/parser_n6stomp.py#L62
* [ ] dns-query has the identifier `ignore-me` https://github.com/certtools/intelmq/blob/master/intelmq/bots/parsers/n6/parser_n6stomp.py#L23
* [ ] sandbox-url has the invalid taxonomy `ignore`: https://github.com/certtools/intelmq/blob/master/intelmq/bots/parsers/n6/parser_n6stomp.py#L46

**Comment by wagner-certat** [comment]
ping @aaronkaplan 

I still need feedback on https://github.com/certtools/intelmq/issues/738#issuecomment-297994771 and https://github.com/certtools/intelmq/issues/738#issuecomment-276056068

**Comment by wagner-certat** [comment]
moving this to 1.1
