### ISSUE TITLE
Shadowserver parser additional configs

### ISSUE THREAD

**Issue by cert-lv** [certtools/intelmq#746]
Are you interested in Shadowserver's configs for:
- Compromised-Website
- Open-Netis
- NTP-Version
- Sandbox-URL
- Spam-URL
- Open-Proxy
- Sinkhole-HTTP-Referer
- Vulnerable-ISAKMP
- Botnet-CCIP
- Accessible-RDP
- Open-mDNS

For **mDNS** you have `# TODO Check implementation`, so we can show our version too.

**Comment by sykaeh** [comment]
We would be very interested in those configs.

**Comment by cert-lv** [comment]
As pull request or in this issue will be enough?

**Comment by sebix** [comment]
If you only paste it in here, I'll created one for you so the commit is attributed to you. The PR makes reviews much easier.

**Comment by cert-lv** [comment]
@sebix, what Git branch should get this pull request?

**Comment by sebix** [comment]
Create an extra branch in your fork, commit and push the changes, and the create the PR to certtools/master.

**Comment by sebix** [comment]
I have documented it here: https://github.com/certat/intelmq/blob/master/docs/Developers-Guide.md#workflow

**Comment by cert-lv** [comment]
Thanks, done, please check https://github.com/certtools/intelmq/pull/748

**Comment by dmth** [comment]
Thank you for contributing this!

**Comment by sebix** [comment]
As we have the PR #748 closing this one here.
