### ISSUE TITLE
display a list of events on the web

### ISSUE THREAD

**Issue by bernhardreiter** [certtools/intelmq#760]
When an operator wants to examine a list of events as part of data exploration or a request by someone who got notified she needs a way to display one or many events. Given that a "single page application" for webs is a common way to implement such user interfaces, it is useful to have a web "component" for use in javascript to display 1 - 100,000 events (or even more).

Probably we want stuff like raw to be hidden by default and extra to be folded first.

Changing the size of colums, pagination, sorting of columns, searching and filtering all look like sensible base functions.

In order to build a prototype what kind of javascript components are out there.
Here are a couple of suggestions that I'd received:
 * https://datatables.net/
 * https://www.dynatable.com/

A list can be found at https://github.com/FancyGrid/awesome-grid

E.g. for extending the vue2 prototype at https://github.com/Intevation/intelmq-mailgen/tree/master/extras/checkticket-spa I'm probably looking into the 
 * https://github.com/ratiw/vuetable-2
 * https://github.com/matfish2/vue-tables-2
 * https://github.com/vue-comps/vue-data-table
 * https://github.com/gurghet/vue-smart-table

or others listed at https://github.com/vuejs/awesome-vue#libraries--plugins

**Comment by bernhardreiter** [comment]
Do we necessarily need pagination? 
(https://github.com/vue-comps/vue-clusterize shows that many lines in the browser are no principle problem 500.000 lines would work from the speed size.)

Let me assume that transferring one event would be 2 KBytes, compressed to 200 Bytes when using gzip. So 100.000 events would need to transfer 20 000 000 Bytes aka 20 MBytes, that should be doable in under 10 seconds. Conclusion with a solution like vue-clusterize pagination may not be necessary for browser or loading speed.

**Comment by dmth** [comment]
> Do we necessarily need pagination? 

Pagination makes interfaces more complex. But to be honest: It's necessary when serving large amounts of data. I know of applications which have a severe impact on your Browser with only 2,5 MB of data (< 20K Lines).

**Comment by bernhardreiter** [comment]
> It's necessary when serving large amounts of data. 

This general rule does not seem to apply to our application,
as my calculation showed.

> I know of applications which have a severe impact on your Browser 
> with only 2,5 MB of data (< 20K Lines).

It seems those applications did not use a "clusterize" rendering algorithm.
(I know worse applications. This is not an argument, though.
If you see one application that does it, it proofs that it is possible. )

**Comment by bernhardreiter** [comment]
Learned yesterday when looking at a number of datatable implementations:
* the bigger ones like datatables.net und dynatables draw in a lot of libraries and often
depend on larger libraries like jquery or style/css frameworks bootstrap or semanic UI.
*  the clusterize.js approach can be interesting for us (it would avoid pagination), which puts  https://github.com/vue-comps/vue-data-table high on the list right now.
* it is unclear how we filter and load parts of the data if it gets really large. In the https://github.com/Intevation/intelmq-mailgen/tree/master/extras/checkticket-spa example I am using a brute-force python algorithm to determine the table columns that are actually filled, such an approach will not be nice once we go large (~100k events). Should we do it with database queries, in the python layer or in the frontend?
* a development workflow with webpack and other npm tools promises to be much faster then restarting manually and manually collecting dependencies. It is an open question if it is really helpful, I'm personally lacking experience.

My (personal) next steps, some planning:
 * will checkout how theming of https://github.com/vue-comps/vue-data-table or other tables would work
 * try the vue-cli/ webpack /vue-loader workflow with nodesjs-development-tools to get a feel for it

**Comment by dmth** [comment]
> It seems those applications did not use a "clusterize" rendering algorithm.

No they did not.

Nevertheless, I vote for server-side paging approach:
 1) It reduces the amount of data which is transported, although it might not be needed.
 2) How many Items can the User handle?
 3) Do your really want to cache > 20 MB Data in your browser for each request?

**Comment by bernhardreiter** [comment]
> I vote for server-side paging approach

Being aware of possible drawbacks, I will not decide now, but try creating something simpler and gather experience. I prefer this design approach, because it avoids putting energy in something that you may not need in the end.

**Comment by bernhardreiter** [comment]
Tried https://github.com/vue-comps/vue-data-table: it is not compatible with vue2.0 right now -> unsuitable. Trying https://github.com/ratiw/vuetable-2 next.
## still in the ring:
 * https://github.com/ratiw/vuetable-2
 * https://github.com/matfish2/vue-tables-2
 * https://github.com/vuikit/vuikit
 *  https://github.com/fundon/vue-admin  compiles a lot of elements, including tables (simple and handsontable) and charts. Maybe a good example to build a rich interface.
 * https://github.com/vue-bulma/handsontable Xorg style license, but future is limited by the business model that will implement some features only in the "pro"rietary version.
 * https://github.com/ElemeFE/element, general purpose, looks big, some docs not in English
 * https://github.com/bootstrap-vue/bootstrap-vue, general purpose, may not have advances table functions like filters
 * https://github.com/quasarframework/quasar, general purpose, seems to only "style" tables

## unsuited, explicit table 
 * https://github.com/galenyuan/vue-datatable , no vue2, though planned
 *  https://github.com/vue-comps/vue-data-table, no vue2
 * https://github.com/gurghet/vue-smart-table, no vue2 (see http://archive.forum.vuejs.org/topic/4140/vue-smart-table/21)
 * https://github.com/jbaysolutions/vue-bootstrap-table, no vue2
 * https://github.com/echoVic/vue-table-pagination, based on vue-table, no docs, so probably no vue2

## unsuited, popular general components
 * https://github.com/airyland/vux , no table
 * https://github.com/ElemeFE/mint-ui , no table
 * https://josephuspaye.github.io/Keen-UI/, no table
 * http://posva.net/vue-mdl, no table
* https://github.com/FE-Driver/vue-beauty, no vue2

**Comment by bernhardreiter** [comment]
## Layout idea
To document a layout idea initially by @dmth from yesterday.
How to display a list of events from 1 to 1500:

Show the most important columns and make the rest visible as details on demand. (This can be done by expanding when clicking onto the row or by an explicit icon/link).
 
State when unexanded.
```
source.ip | source.port | classification    | obs timestamp   |
(->dst)   | (->dst)     | tax   | type | id | (-> source)     |
---------------------------------------------------------------
127.0.0.1 |     4711    |       | Malware | | 2016-10-15 11:37| (details)
127.0.0.2 |     4811    |       | Malware | | 2016-10-16 12:37| (details)
```

The `(->dst)` would switch to display destination.ip instead, etc.

Now with the first event row expanded:
```
source.ip | source.port | classification    | obs timestamp   |
(->dst)   | (->dst)     | tax   | type | id | (-> source)     |
---------------------------------------------------------------
127.0.0.1 |     4711    |       | Malware | | 2016-10-15 11:37|
---------------------------------------------------------------
| Details about the event                                     | (hide)
|         more                                                |
|         more                                                |
|         more                                                |
---------------------------------------------------------------
127.0.0.2 |     4811    |       | Malware | | 2016-10-16 12:37| (details)
```

**Comment by bernhardreiter** [comment]
What I've currently learned from of the evaluation of vue and general datatable implementations. It resulted in a vue simple prototype using a semantic ui table in https://github.com/Intevation/intelmq-mailgen/tree/51a5e608a3f385f045b349144696c43167eda076/extras/checkticket-spa

 * a usual Botnet-Drone event has too many columns and contents to put them in a simple table. 
 -> needs some details to be only shown on demand
 * once you want to use one of the more interesting vue2 components, you will need to employ a bundling/dependency handling toolschain. The more popular one is based on webpack. 
 * Many components external to vue use jquery. JQuery manipulates the DOM directly, you can integrated it with vue2, but some vue-components try a cleaner way to do the transitions and animations directly in vue.
 * https://github.com/ratiw/vuetable-2 is designed to get data from the server and integrates "semantic ui" or "bootstrap ui". A server data request is done when switching to a different page (paginated output) or when doing a search (server based search). Because I wanted less restrictions on the server I've tried https://github.com/matfish2/vue-tables-2 (which only give you the bootstrap choice).

**Comment by bernhardreiter** [comment]
https://github.com/Intevation/intelmq-fody implements a prototype of a ticket view that has a https://vuejs.org/ and https://datatables.net/ integration of a table with details view.

![fody-20161130-1](https://cloud.githubusercontent.com/assets/8190008/20760225/b2c83b80-b71f-11e6-98a0-f141f23b28c6.png)

Each row can be expanded to show a "childrow" with details. The state of each row will be kept.

![fody-20161130-2](https://cloud.githubusercontent.com/assets/8190008/20760242/bf9230d2-b71f-11e6-8569-648a3975e268.png)

There is a simple grid and responsive definitions that will make it work on smaller devices as well, details will be shown in one column then.

![fody-20161130-3](https://cloud.githubusercontent.com/assets/8190008/20760245/c2aa5678-b71f-11e6-920e-548d2e275c8e.png)

The detail view dynamically shows all columns, except the ones used in the main table and raw.
(The screenshots where taken from an intelmq with mailgen setup, using the checkticket.py prototype for serving ticket data.)

**Comment by wagner-certat** [comment]
existing interface-tools:
* [Xataface](https://github.com/shannah/xataface) only supports MySQL
* [Team postgresql](http://www.teampostgresql.com/) has ~50MB and is written in Java :/
* [vfront](http://www.vfront.org/) has a problem with our table names...

**Comment by bernhardreiter** [comment]
@wagner-certat 
Given the amount of data we want to process with intelmq I believe that we need a tool that is adapted to the special needs of Intelmq and its events. https://github.com/Intevation/intelmq-fody is a good start, so is there is the need it can be improved to:
 1. work on general output/postgresql tables (right now it has many functions for [intelmq-cb-mailgen](https://github.com/Intevation/intelmq-mailgen-release) setups.)
 2. provide a better representation, considered more values and a better display of `extras`.

**Comment by wagner-certat** [comment]
> https://github.com/Intevation/intelmq-fody is a good start,

When I looked at it, it was impossible to use fody without mailgen. Probably this has changed now.

**Comment by bernhardreiter** [comment]
Fody has several components, the stats subpage can display graphs and a details table (the older screenshots at https://github.com/Intevation/intelmq-fody/issues/49 show only the graph), it only depends on the `events_api` of the [fody-backend](https://github.com/Intevation/intelmq-fody-backend/). `events_api` can be used as a separate submodule that **does not depend on intelmq-mailgen**. Turn off the other subpages and you have a generic events viewer.

**Comment by wagner-certat** [comment]
can be closed, as there's fody
