### ISSUE TITLE
postgresql-output fails to recover from temporary connection failure

### ISSUE THREAD

**Issue by swilde** [certtools/intelmq#780]
On a production system the Postgresql Output had stoped to write to
the Database, the log showed the following error:

```
  2016-11-18 07:41:04,311 - postgresql-output - ERROR - Executed rollback command after failed query execution.
  Traceback (most recent call last):
    File "/usr/lib/python3/dist-packages/intelmq/bots/outputs/postgresql/output.py", line 64, in process
      self.cur.execute(query, values)
  psycopg2.OperationalError: SSL connection has been closed unexpectedly
```

The error was loged every few milliseconds which made the log grow
about 90GiB over the weekend...

However, the main problem is, that connecting to the DB _was_
possible (so this really should have been only a temporary failure).
But even after restarting the postgres db the bot still continued
throwing above error...  After restarting the bot everything worked
ell again.

**Comment by sebix** [comment]
I pushed a fix which initializes the bot after OperationalError
