### ISSUE TITLE
`update-asn-data` does not work

### ISSUE THREAD

**Issue by ondj** [certtools/intelmq#781]
The command `update-asn-data` does not work:

```
# update-asn-data /tmp/asn.db
/usr/local/bin/update-asn-data: line 41: pyasn_util_convert.py: command not found
```

It is because `pyasn_util_convert.py` command is by default installed in `/usr/local/bin/` directory (at least in Ubuntu 14.04), but in `update-asn-data` is specified this:

```
PATH=/bin:/usr/bin
```

I think this PATH definition can be removed or add to end also `/usr/local/bin/` directory

**Comment by dmth** [comment]
The file in question can be found here: https://github.com/certtools/intelmq/blob/master/intelmq/bots/experts/asn_lookup/update-asn-data

**Comment by sebix** [comment]
> It is because `pyasn_util_convert.py` command is by default installed in `/usr/local/bin/` directory (at least in Ubuntu 14.04), but in `update-asn-data` is specified this:

Depends on the installation method. For packages, `/usr/bin` is correct. If you installed via pip or setup.py (don't do that please), `/usr/local/bin/` is correct if `--install-option ="--install-scripts=/usr/local/bin"` is not used.

Until we have stable packages for intelmq and dependencies, we could add `/usr/local/bin` to PATH in this script.

**Comment by ondj** [comment]
> If you installed via pip or setup.py (don't do that please)

I know, but in Ubuntu 14.04 is pyasn in version 0.1.7-1, but in bot [REQUIREMENTS.txt](https://github.com/certtools/intelmq/blob/2e207341337c5487201e4292caff8ffb5bb33e94/intelmq/bots/experts/asn_lookup/REQUIREMENTS.txt) file is required version 1.5.0b7. And pyasn installation through pip is described in bot [README.md](https://github.com/certtools/intelmq/blob/master/intelmq/bots/experts/asn_lookup/README.md). So I think `update-asn-data` can support this installation method.
