### ISSUE TITLE
Make the usage of extra field easier

### ISSUE THREAD

**Issue by sebix** [certtools/intelmq#793]
I just noticed that I haven't created an issue for this yet, had it in mind since the creation of this field...

It's easier to write e.g.:

```
event.add('extra.foo') = 'bar'
```

**Comment by dmth** [comment]
Would be of great use in the Generic CSV parser in case a column cannot be mapped to the dho, but should be processed afterwards.

**Comment by dmth** [comment]
> Would be of great use in the Generic CSV parser in case a column cannot be mapped to the dho, but should be processed afterwards.

Since the merge of https://github.com/certtools/intelmq/pull/935 this function is available for the generic csv-parser.
