### ISSUE TITLE
Single parser doing multiple feeds

### ISSUE THREAD

**Issue by jgedeon120** [certtools/intelmq#799]
The developers guide has a section in it under Directory layout in the repository that discusses having multiple parsers for the different feeds coming from the same root source.  The example given is Abusech and the different types of feeds for Zeus.  Recently using the IntelMQ Manager UI started getting a little long on the parsers.  I started to start combining parsers into a single parser for the different types of feeds within the same root source.  Is this not advisable or wanted? Looking at the experts they seem to be created using if key in event so combining the feeds and then having the expert after the parser will add a little overhead if multiple collectors are pointed to the same parser.  An example of this is displayed below in the screen shot.

![screen shot 2016-11-23 at 7 52 29 pm](https://cloud.githubusercontent.com/assets/8508738/20775898/54e9d26a-b72b-11e6-8ab2-346705109fe4.png)

**Comment by sebix** [comment]
This is very feasible to have, yes. We already have some parsers which process different feeds with the same provider, as the format, data and thus processing is very similar. We also have generic parsers (currently only a minimal json and a quite sophisticated csv) which could be used in more places, at least if we do not need to convert data - which is often the case.

**Comment by dmth** [comment]
The approach is similar to approach 2) sketched in https://github.com/certtools/intelmq/pull/752#issuecomment-259384416

**Comment by sykaeh** [comment]
Since this is generally already possible, are there any specific parsers that you were thinking of combining (that haven't been done already)? Otherwise I think we could close this issue.

**Comment by wagner-certat** [comment]
Are there any open questions here?
