### ISSUE TITLE
Abuse.ch Palevo and spyeye discontinued

### ISSUE THREAD

**Issue by sebix** [certtools/intelmq#801]
* https://spyeyetracker.abuse.ch/
* https://palevotracker.abuse.ch/

should be removed

**Comment by jgedeon120** [comment]
It looks like Dragon Research may also need to be added since the feeds for ssh and VNC have not been updated since 5/18/2016.

**Comment by dmth** [comment]
@jgedeon120 with "added" you mean: added to the list above?

**Comment by jgedeon120** [comment]
@dmth Yes, sorry I should have been more clear about that.
