### ISSUE TITLE
Copyright Notices

### ISSUE THREAD

**Issue by sykaeh** [certtools/intelmq#802]
We receive notices about copyright infringements in our network and would like to process these automatically using IntelMQ. The notices are in the [Automated Copyright Notice System (ACNS)](http://acns.net/index.html) format. This would require writing a parser for this format and also adding `copyright` as a `classification.type` in the data harmonization and in the taxonomy expert (`classification.taxonomy` would be `Fraud`).

Is anyone else interested in this? Are there any objections to the addition of `copyright` to the DHO and the taxonomy expert?

**Comment by dmth** [comment]
Also we've no use case for this, yet, I think it is a good idea.

**Comment by SYNchroACK** [comment]
I think makes sense. +1

@aaronkaplan what's your feedback mate?

**Comment by aaronkaplan** [comment]
Agreed. Might be very useful for network operators using intelmq. 

Sybil: 100% agree. Please make a PR with what you need. 

Thx for bringing this up!

---
Mobile

**Comment by SYNchroACK** [comment]
@sykaeh this issue will stays open waiting for your pull request ;) Thank you! Cheers

**Comment by wagner-certat** [comment]
Fixed by 7438b41058 - copyright is in the REFERENCE TAXONOMY INCIDENT Taxonomy, see https://github.com/enisaeu/Reference-Security-Incident-Taxonomy-Task-Force/blob/master/working_copy/humanv1.md
