### ISSUE TITLE
Configuration of own bots (outdated documentation)

### ISSUE THREAD

**Issue by Flo1895** [certtools/intelmq#803]
Hallo,

I created a few expert bots for my own special purposes. Since one of the last commits, I get an error message (`FileNotFoundError: [Errno 2] No such file or directory: 'intelmq.bots.experts.xxx.expert'`) when starting my pipeline with `intelmqctl start`. I already added the bots to `intelmq/bots/BOTS` and included the BOT variable in the expert.py files. However, starting a single bot with `intelmqctl run xxx` works as expected. Therefore, I am wondering if I am missing some changes or if starting the whole pipeline might contain a problem. Unfortunately, the documentation is a bit outdated (configuration via `startup.conf` for example) and doesn't provide details about the new configuration (I am for instance not sure if I have to add parameters in `runtime.conf` or in BOTS).

**Comment by sebix** [comment]
Install intelmq (ie upgrade it), then the executable `intelmq.bots.experts.xxx.expert` will be created.

**Comment by Flo1895** [comment]
I am not sure what you mean by "install or upgrade intelmq". I run intelmq in a virtual machine managed by vagrant [1], i.e., I created a new virtual machine with a freshly installed intelmq. Previously, I checked out intelmq, installed it according to the documentation and copied my self-written bots to "/usr/local/lib/python3.5/dist-packages/intelmq/bots/experts/". Even if I copy the expert bots to the checked out folder before I install intelmq, I still get the same error. Additionally, I am actually not sure what you mean by "the executable will be created". Is this step new?

[1] https://www.vagrantup.com/

**Comment by sebix** [comment]
Run `pip3 install -U intelmq` to update the installation.

In `/usr/local/bin` you can find executables for all bots. These and the entry-points are created during installation.

**Comment by Flo1895** [comment]
Thank you for your reply. However, there are no executables created for my bots in /usr/local/bin/, even if I run pip3 install -U intelmq right after the installation. Therefore, I suppose, I have to add my bots not only to the BOTS file but in some other place as well?!

**Comment by sebix** [comment]
> Thank you for your reply. However, there are no executables created for my bots in /usr/local/bin/, even if I run pip3 install -U intelmq right after the installation.

Probably in `/usr/bin`? They should be somewhere in $PATH.

> Therefore, I suppose, I have to add my bots not only to the BOTS file but in some other place as well?!

No, that's enough.

**Comment by sebix** [comment]
> Unfortunately, the documentation is a bit outdated (configuration via startup.conf for example)

We are still compatible to the old format using this file, but I removed it now from docs.

I also mentioned the executables, which was unclear here.

Do you still experience problems?
