### ISSUE TITLE
Feeds.md - missing fields

### ISSUE THREAD

**Issue by SYNchroACK** [certtools/intelmq#828]
**Note:** this issue is related to #668

The Feeds.md document needs at least per each feed the following fields as an example/suggestion to help new users:

- rate_limit: depending on the feed, the value can be greater or lower
- provider
- feed
- id

I would like to include to a configuration (json) sample per each one like:
```
        "parameters": {
            "feed": "Malware Domain List",
            "http_url": "http://www.malwaredomainlist.com/updatescsv.php",
            "rate_limit": 3600
        }

```

@sykaeh need your help. Could you post here on this issue a comment explaining the difference between the configuration field 'provider' and 'feed'? I think in Feeds.md doc there is a need for examples to give a better understanding for the new users. :)

**Comment by sykaeh** [comment]
`provider` is the organization that provides the feed (e.g. Shadowserver) whereas `feed` is the name of the feed (e.g. Accessible/Open MongoDB). For providers that only have one feed, the distinction is not that important, but it is relevant for providers with multiple feeds. `provider` maps to the field `feed.provider` and `feed` to the field `feed.name` in the DHO.

**Comment by SYNchroACK** [comment]
Thank you @sykaeh.

This issue is waiting for #668
