### ISSUE TITLE
'Read the Docs' and 'pypi' have broken links

### ISSUE THREAD

**Issue by SYNchroACK** [certtools/intelmq#843]
**Read the Docs**
Issue: main page [here](http://intelmq.readthedocs.io/en/latest/) does not exists. Currently we are using docs/README.rst and all other docs are in markdown format.

**pypi**
Issue: links related to User-Guide, etc are broken. Check [here](https://pypi.python.org/pypi/intelmq/1.0.0.dev6)

**Comment by SYNchroACK** [comment]
Related issue: #807

**Comment by wagner-certat** [comment]
Duplicate

**Comment by SYNchroACK** [comment]
> Duplicate

Can you share the original issue or its not important?
