### ISSUE TITLE
Review: `enabled` parameter

### ISSUE THREAD

**Issue by SYNchroACK** [certtools/intelmq#845]
Concept/architecture review

**Comment by wagner-certat** [comment]
Please give more details...

**Comment by aaronkaplan** [comment]
@SYNchroACK means "reviewing how it was implemented"

**Comment by aaronkaplan** [comment]
@SYNchroACK is this still coming? Should we postpone this to 1.1?

**Comment by wagner-certat** [comment]
moving this to 1.1

**Comment by wagner-certat** [comment]
no feedback, closing

please reopen if needed
