### ISSUE TITLE
Review: ParserBot Class Arch

### ISSUE THREAD

**Issue by SYNchroACK** [certtools/intelmq#850]
* Review the ParserBot class arch
* Review the `ignore_lines_starting` and `csv_params` utilization from user point-of-view
* Evaluate the need/possibility/coherence of having on bot.py a class per each type of bot (currently there is only for CollectorBot and ParserBot)

Related pull request #821

**Comment by aaronkaplan** [comment]
@SYNchroACK is this still coming? Should we postpone this to 1.1?

**Comment by wagner-certat** [comment]
moving this to 1.1

**Comment by wagner-certat** [comment]
no feedback, closing

please reopen if needed
