### ISSUE TITLE
Generic Mail URL Fetcher hangs forever on Downloading report

### ISSUE THREAD

**Issue by swilde** [certtools/intelmq#854]
On our customers production system it was discovered today, that some of the collector_mail_url bots were hanging (four out of 19).  The symptoms were Identical in all cases:

* The last log message was:
  ```INFO - Downloading report from https://example.com/valid/download/url```
* intelmqctl status showed the bot as "is running"
* stracing the hanging bots process showed an read in progress:  ```read(7,```
* `ss -tpn` showed an hanging connection:
   ```CLOSE-WAIT 97     0             10.0.0.1:60822        10.0.0.2:993    users:(("python3",5627,5))```
  but as you can see this is IMAP, not the download, I suspect the imap part of the bot was waiting for the dl to finish.

Maybe the bots should get a hard timeout for all network operations, so that if something gets stuck they get restarted (some kind of watchdog).?

**Comment by bernhardreiter** [comment]
While general measures (for all network connections) may be a good idea, we should also try to analyse this problem in more detail. The next step would probably be trying to recreate it. @swilde what do you think a network connection should do to get into this state?

**Comment by dmth** [comment]
I'm looking into this issue. Maybe timeouts are the way to go.

**Comment by dmth** [comment]
This might easily be fixed with https://requests.readthedocs.io/en/master/user/quickstart/#timeouts

Nevertheless, as already noted in https://github.com/certtools/intelmq/issues/666#issuecomment-254208759, this timeout does not effect very slow downloads.

**Comment by dmth** [comment]
Current approach: Add a timeout, retry connection three times, if retry without succes, pasue processing and start againg when the `rate_limit` was reached. That apporach looks like this:
```
2017-01-23 13:06:47,494 - TIMEOUT - INFO - Downloading report from http://192.168.56.1:8080/timeout
2017-01-23 13:07:17,527 - TIMEOUT - WARNING - Timeout whilst downloading the report.
2017-01-23 13:07:47,559 - TIMEOUT - WARNING - Timeout whilst downloading the report.
2017-01-23 13:08:17,593 - TIMEOUT - WARNING - Timeout whilst downloading the report.
2017-01-23 13:08:17,595 - TIMEOUT - ERROR - Request timed out three times in a row. 
2017-01-23 13:08:17,596 - TIMEOUT - INFO - Idling for 300.0s now.
2017-01-23 13:13:17,666 - TIMEOUT - INFO - Downloading report from http://192.168.56.1:8080/timeout
2017-01-23 13:13:47,698 - TIMEOUT - WARNING - Timeout whilst downloading the report.
2017-01-23 13:14:17,730 - TIMEOUT - WARNING - Timeout whilst downloading the report.
2017-01-23 13:14:47,763 - TIMEOUT - WARNING - Timeout whilst downloading the report.
2017-01-23 13:14:47,763 - TIMEOUT - ERROR - Request timed out three times in a row. 
2017-01-23 13:14:47,763 - TIMEOUT - INFO - Idling for 300.0s now.
```

**Comment by wagner-certat** [comment]
As requested in https://github.com/certtools/intelmq/pull/835#discussion_r96223317 I added HTTP timeouts to this PR. Does not affect slow downloads as I described in #666 

Is this just a duplicated of #666 or are there any other issues not covered by this ticket and PR #835?

**Comment by dmth** [comment]
Basically I did the same thing today for collector_http and collector_mail_url, because it was not stated in https://github.com/certtools/intelmq/issues/666 that someone was working on it :-(

**Comment by dmth** [comment]
My fix is available here: https://github.com/Intevation/intelmq/tree/dev-collector-timeout

**Comment by dmth** [comment]
Nevertheless this does not cover the case if an empty body is sent (which I've seen happening when downloading shadowserver data 0Byte files ftw)

How does the collector deal with this (Example / Test):
```
2017-01-23 16:10:18,863 - generic-mail-url-fetcher-collector - INFO - Bot will continue in 15 seconds.
2017-01-23 16:10:33,969 - generic-mail-url-fetcher-collector - INFO - Downloading report from 'http://192.168.56.1:8080/slow'.
```

from the "server log"

```
192.168.56.13 - - [23/Jan/2017 16:10:54] "GET /slow HTTP/1.1" 200 0
/slow
127.0.0.1 - - [23/Jan/2017 16:11:05] "GET /slow HTTP/1.1" 200 0
/slow
192.168.56.13 - - [23/Jan/2017 16:11:16] "GET /slow HTTP/1.1" 200 0
/slow
192.168.56.13 - - [23/Jan/2017 16:11:27] "GET /slow HTTP/1.1" 200 0
/slow
192.168.56.13 - - [23/Jan/2017 16:11:38] "GET /slow HTTP/1.1" 200 0
/slow
192.168.56.13 - - [23/Jan/2017 16:11:49] "GET /slow HTTP/1.1" 200 0
/slow
192.168.56.13 - - [23/Jan/2017 16:12:00] "GET /slow HTTP/1.1" 200 0
/slow
192.168.56.13 - - [23/Jan/2017 16:12:11] "GET /slow HTTP/1.1" 200 0
/slow
192.168.56.13 - - [23/Jan/2017 16:12:23] "GET /slow HTTP/1.1" 200 0
/slow
192.168.56.13 - - [23/Jan/2017 16:12:34] "GET /slow HTTP/1.1" 200 0
/slow
192.168.56.13 - - [23/Jan/2017 16:12:45] "GET /slow HTTP/1.1" 200 0
/slow
192.168.56.13 - - [23/Jan/2017 16:12:56] "GET /slow HTTP/1.1" 200 0
/slow
192.168.56.13 - - [23/Jan/2017 16:13:07] "GET /slow HTTP/1.1" 200 0
/slow
192.168.56.13 - - [23/Jan/2017 16:13:18] "GET /slow HTTP/1.1" 200 0
/slow
192.168.56.13 - - [23/Jan/2017 16:13:29] "GET /slow HTTP/1.1" 200 0
/slow
192.168.56.13 - - [23/Jan/2017 16:13:40] "GET /slow HTTP/1.1" 200 0
/slow
192.168.56.13 - - [23/Jan/2017 16:13:51] "GET /slow HTTP/1.1" 200 0
/slow
192.168.56.13 - - [23/Jan/2017 16:14:02] "GET /slow HTTP/1.1" 200 0
/slow
192.168.56.13 - - [23/Jan/2017 16:14:13] "GET /slow HTTP/1.1" 200 0
/slow
```

The "Server":
```
import time
from bottle import HTTPResponse, run, route


@route('/timeout')
def timeout():
    print('/timeout')
    time.sleep(31)
    return HTTPResponse(body='', status=200)


@route('/slow')
def slow():
    print('/slow')
    def bodygenerator():
        i = 0
        while i <= 10:
            i +=1
            time.sleep(1)
            yield ''
    return HTTPResponse(body=bodygenerator(), status=200)

run(host='0.0.0.0', port=8080)
```

**Comment by dmth** [comment]
https://github.com/certtools/intelmq/issues/854#issuecomment-274515559 The error in here was due to an infinitve loop I caused.

**Comment by dmth** [comment]
@wagner-certat what is your opinion on this?
Should a create a PR with this solution, or are you planning to continue and enhance the timeouts from #835 ?

**Comment by wagner-certat** [comment]
@dmth While I just provided an ability to set timouts, you are handling them by doing retries. I would appreciate a PR to discuss this approach.
