### ISSUE TITLE
Generic CSV Parser IPv4/IPv6 Matching

### ISSUE THREAD

**Issue by mf370** [certtools/intelmq#855]
I was running some tests with the generic csv parser and I noticed when the parser does the matching of IP address to check whether it is IPv4 or IPv6, some IPv4 addresses will lose the last two or the last number.
For example, on my csv file I had the IPv4 address in the following format aaa.bb.cc.ddd and after the parsing  it transforms into aaa.bb.cc.d.

**Comment by wagner-certat** [comment]
Which parser does have this problems? Can you show some example data?

**Comment by mf370** [comment]
I have a CSV file where the header is: 
classification.type, destination.ip, source.abuse_contact, source.ip and time.source. (These fields are used to configure the generic csv parser bot).
And an example of a row in my CSV file: 
phishing, 178.3.85.161, foo@bar.com, 194.239.167.7, 2010-02-18T00:00:00+00:00.

On the above example row, after the generic csv parser bot check if the IP addresses are IPv4 or IPv6, the IP address on the destination.ip field will go from 178.3.85.161 to 178.3.85.1.

**Comment by SYNchroACK** [comment]
Indeed, is a bug.

```
root@server:~# cat issue855.py 
import re

value = "178.3.85.161"

value = re.compile(
'(([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])'
'\.){3}([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0'
'-5])|(([a-zA-Z]|[a-zA-Z][a-zA-Z0-9\-]*[a-zA-Z0-9])'
'\.)*([A-Za-z]|[A-Za-z][A-Za-z0-9\-]*[A-Za-z0-9])|'
'\s*((([0-9A-Fa-f]{1,4}:){7}([0-9A-Fa-f]{1,4}|:))|('
'([0-9A-Fa-f]{1,4}:){6}(:[0-9A-Fa-f]{1,4}|((25[0-5]'
'|2[0-4]\d|1\d\d|[1-9]?\d)(\.(25[0-5]|2[0-4]\d|1\d'
'\d|[1-9]?\d)){3})|:))|(([0-9A-Fa-f]{1,4}:){5}(((:['
'0-9A-Fa-f]{1,4}){1,2})|:((25[0-5]|2[0-4]\d|1\d\d|['
'1-9]?\d)(\.(25[0-5]|2[0-4]\d|1\d\d|[1-9]?\d)){3})|'
':))|(([0-9A-Fa-f]{1,4}:){4}(((:[0-9A-Fa-f]{1,4}){1'
',3})|((:[0-9A-Fa-f]{1,4})?:((25[0-5]|2[0-4]\d|1\d'
'\d|[1-9]?\d)(\.(25[0-5]|2[0-4]\d|1\d\d|[1-9]?\d)){'
'3}))|:))|(([0-9A-Fa-f]{1,4}:){3}(((:[0-9A-Fa-f]{1,'
'4}){1,4})|((:[0-9A-Fa-f]{1,4}){0,2}:((25[0-5]|2[0-'
'4]\d|1\d\d|[1-9]?\d)(\.(25[0-5]|2[0-4]\d|1\d\d|[1-'
'9]?\d)){3}))|:))|(([0-9A-Fa-f]{1,4}:){2}(((:[0-9A-'
'Fa-f]{1,4}){1,5})|((:[0-9A-Fa-f]{1,4}){0,3}:((25[0'
'-5]|2[0-4]\d|1\d\d|[1-9]?\d)(\.(25[0-5]|2[0-4]\d|1'
'\d\d|[1-9]?\d)){3}))|:))|(([0-9A-Fa-f]{1,4}:){1}(('
'(:[0-9A-Fa-f]{1,4}){1,6})|((:[0-9A-Fa-f]{1,4}){0,4'
'}:((25[0-5]|2[0-4]\d|1\d\d|[1-9]?\d)(\.(25[0-5]|2['
'0-4]\d|1\d\d|[1-9]?\d)){3}))|:))|(:(((:[0-9A-Fa-f]'
'{1,4}){1,7})|((:[0-9A-Fa-f]{1,4}){0,5}:((25[0-5]|2'
'[0-4]\d|1\d\d|[1-9]?\d)(\.(25[0-5]|2[0-4]\d|1\d\d|'
'[1-9]?\d)){3}))|:)))(%.+)?').match(value).group()

print(value)

root@server:~# python3 issue855.py 
178.3.85.1
```

**Comment by dmth** [comment]
Now is a perfect moment to get rid of this regex.... in all bots.

**Comment by dmth** [comment]
Examples: 

```
import socket

value = "178.3.85.161"

value6 = "2001::1"

v4 = socket.AF_INET
v6 = socket.AF_INET6

#IP v4
print(socket.inet_aton(value))
# or
print(socket.inet_pton(v4, value))


#IP v6
print(socket.inet_pton(v6, value6))
```

**Comment by dmth** [comment]
I suggest the following:

- [ ] Find out where this regex is used
- [ ] Provide a central utility which provides the tests stated in my example above
- [ ] Replace the regex-tests with the utility test

**Comment by dmth** [comment]
The generic CSV Parser seems to be the only parser using this regex.

**Comment by aaronkaplan** [comment]
> On 27 Jan 2017, at 12:31, Dustin Demuth <notifications@github.com> wrote:
> 
> Now is a perfect moment to get rid of this regex.... in all bots.
> 

+1

**Comment by SYNchroACK** [comment]
> On 27 Jan 2017, at 12:31, Dustin Demuth ***@***.***> wrote:
> 
>  Now is a perfect moment to get rid of this regex.... in all bots.

+1

**Comment by wagner-certat** [comment]
I think you misunderstood what the regex is supposed to do. This regex is used to find an IP inside a string, not to validate it!

The proposed code by @dmth is not *not* a replacement, it's another way of what we are doing in `lib/harmonization.py` already.

ping @robcza

**Comment by dmth** [comment]
> I think you misunderstood what the regex is supposed to do. This regex is used to find an IP inside a string, not to validate it.

Is this "smart" behaviour necessary? why? 


> The proposed code by @dmth is not not a replacement, it's another way of what we are doing in lib/harmonization.py already.

Yes, I also figured this out in https://github.com/certtools/intelmq/issues/855#issuecomment-275664158 . That's why I proposed to remove the Regex without replacement.

**Comment by SYNchroACK** [comment]
@dmth you are probably right. Lets wait for @robcza feedback to understand if there is any use-case where is makes sense to use the code like the current way. ;)

**Comment by robcza** [comment]
@wagner-certat is right, thank you. This regex serves the purpose, where data in the csv is not directly consumable by IntelMQ data types. Eg. ```ftp://1.2.3.4```, or ```1.2.3.4/32``` and similar. I have seen more sources, that were not parsable without extracting ip out of the string, but otherwise it was plain csv.

The issue with the regex seems serious (truncating the information is much worse than just dropping the whole line). However I'd like to stay if it could be fixed.

Usage could be configurable with boolean parameter ```fuzzy```

**Comment by wagner-certat** [comment]
> @wagner-certat is right, thank you. This regex serves the purpose, where data in the csv is not directly consumable by IntelMQ data types. Eg. ftp://1.2.3.4, or 1.2.3.4/32 and similar. I have seen more sources, that were not parsable without extracting ip out of the string, but otherwise it was plain csv.

Your code uses `match`, not `search`. So that's not possible anyway:

```
>>> ip.match(',127.0.0.100,')
>>> ip.search(',127.0.0.100,')
<_sre.SRE_Match object; span=(1, 10), match='127.0.0.1'>
```

**Comment by wagner-certat** [comment]
@robcza Do you have any example where this feature is really needed?

> Eg. ```ftp://1.2.3.4```, or ```1.2.3.4/32``` and similar.

The first is a URL, the second is a network.

**Comment by dmth** [comment]
How to continue on this one?

The current approach falsifies data with a feature which might not be necessary.

I vote for a removal of this regex, as we want to use this parser in production and do not want to create wrong data.

@robcza do you want to fix the regex? 

In the meantime, I'm removing the broken regex from our setup and will create a PR for this.

**Comment by bernhardreiter** [comment]
As someone who is fluend in regular expressions, here is a candidate for a fix:
```python
import re

value = "178.3.85.161"

value = re.compile(
'(([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])'
#'\.){3}([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0'
'\.){3}(1[0-9]{2}|2[0-4][0-9]|25[0'
#'-5])|(([a-zA-Z]|[a-zA-Z][a-zA-Z0-9\-]*[a-zA-Z0-9])'
'-5]|[1-9][0-9]|[0-9])|(([a-zA-Z]|[a-zA-Z][a-zA-Z0-9\-]*[a-zA-Z0-9])'
'\.)*([A-Za-z]|[A-Za-z][A-Za-z0-9\-]*[A-Za-z0-9])|'
'\s*((([0-9A-Fa-f]{1,4}:){7}([0-9A-Fa-f]{1,4}|:))|('
'([0-9A-Fa-f]{1,4}:){6}(:[0-9A-Fa-f]{1,4}|((25[0-5]'
'|2[0-4]\d|1\d\d|[1-9]?\d)(\.(25[0-5]|2[0-4]\d|1\d'
'\d|[1-9]?\d)){3})|:))|(([0-9A-Fa-f]{1,4}:){5}(((:['
'0-9A-Fa-f]{1,4}){1,2})|:((25[0-5]|2[0-4]\d|1\d\d|['
'1-9]?\d)(\.(25[0-5]|2[0-4]\d|1\d\d|[1-9]?\d)){3})|'
':))|(([0-9A-Fa-f]{1,4}:){4}(((:[0-9A-Fa-f]{1,4}){1'
',3})|((:[0-9A-Fa-f]{1,4})?:((25[0-5]|2[0-4]\d|1\d'
'\d|[1-9]?\d)(\.(25[0-5]|2[0-4]\d|1\d\d|[1-9]?\d)){'
'3}))|:))|(([0-9A-Fa-f]{1,4}:){3}(((:[0-9A-Fa-f]{1,'
'4}){1,4})|((:[0-9A-Fa-f]{1,4}){0,2}:((25[0-5]|2[0-'
'4]\d|1\d\d|[1-9]?\d)(\.(25[0-5]|2[0-4]\d|1\d\d|[1-'
'9]?\d)){3}))|:))|(([0-9A-Fa-f]{1,4}:){2}(((:[0-9A-'
'Fa-f]{1,4}){1,5})|((:[0-9A-Fa-f]{1,4}){0,3}:((25[0'
'-5]|2[0-4]\d|1\d\d|[1-9]?\d)(\.(25[0-5]|2[0-4]\d|1'
'\d\d|[1-9]?\d)){3}))|:))|(([0-9A-Fa-f]{1,4}:){1}(('
'(:[0-9A-Fa-f]{1,4}){1,6})|((:[0-9A-Fa-f]{1,4}){0,4'
'}:((25[0-5]|2[0-4]\d|1\d\d|[1-9]?\d)(\.(25[0-5]|2['
'0-4]\d|1\d\d|[1-9]?\d)){3}))|:))|(:(((:[0-9A-Fa-f]'
'{1,4}){1,7})|((:[0-9A-Fa-f]{1,4}){0,5}:((25[0-5]|2'
'[0-4]\d|1\d\d|[1-9]?\d)(\.(25[0-5]|2[0-4]\d|1\d\d|'
'[1-9]?\d)){3}))|:)))(%.+)?').match(value).group()

print(value)
```

The problem is is the fourth block of the ipv6 address, where the alternatives are not greedy, but are tried from left to right (see '|' in https://docs.python.org/3.5/library/re.html#regular-expression-syntax ). So we just try the longer alternatives first.

**Comment by bernhardreiter** [comment]
Okay @dmth pointed another two bad cases out to me, here is the first fix for ipv4:
```python
import re

reg = re.compile(
'(([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])'
#'\.){3}([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0'
'\.){3}(1[0-9]{2}|2[0-4][0-9]|25[0'
#'-5])|(([a-zA-Z]|[a-zA-Z][a-zA-Z0-9\-]*[a-zA-Z0-9])'
'-5]|[1-9][0-9]|[0-9])(?![0-9])|(([a-zA-Z]|[a-zA-Z][a-zA-Z0-9\-]*[a-zA-Z0-9])'
'\.)*([A-Za-z]|[A-Za-z][A-Za-z0-9\-]*[A-Za-z0-9])|'
'\s*((([0-9A-Fa-f]{1,4}:){7}([0-9A-Fa-f]{1,4}|:))|('
'([0-9A-Fa-f]{1,4}:){6}(:[0-9A-Fa-f]{1,4}|((25[0-5]'
'|2[0-4]\d|1\d\d|[1-9]?\d)(\.(25[0-5]|2[0-4]\d|1\d'
'\d|[1-9]?\d)){3})|:))|(([0-9A-Fa-f]{1,4}:){5}(((:['
'0-9A-Fa-f]{1,4}){1,2})|:((25[0-5]|2[0-4]\d|1\d\d|['
'1-9]?\d)(\.(25[0-5]|2[0-4]\d|1\d\d|[1-9]?\d)){3})|'
':))|(([0-9A-Fa-f]{1,4}:){4}(((:[0-9A-Fa-f]{1,4}){1'
',3})|((:[0-9A-Fa-f]{1,4})?:((25[0-5]|2[0-4]\d|1\d'
'\d|[1-9]?\d)(\.(25[0-5]|2[0-4]\d|1\d\d|[1-9]?\d)){'
'3}))|:))|(([0-9A-Fa-f]{1,4}:){3}(((:[0-9A-Fa-f]{1,'
'4}){1,4})|((:[0-9A-Fa-f]{1,4}){0,2}:((25[0-5]|2[0-'
'4]\d|1\d\d|[1-9]?\d)(\.(25[0-5]|2[0-4]\d|1\d\d|[1-'
'9]?\d)){3}))|:))|(([0-9A-Fa-f]{1,4}:){2}(((:[0-9A-'
'Fa-f]{1,4}){1,5})|((:[0-9A-Fa-f]{1,4}){0,3}:((25[0'
'-5]|2[0-4]\d|1\d\d|[1-9]?\d)(\.(25[0-5]|2[0-4]\d|1'
'\d\d|[1-9]?\d)){3}))|:))|(([0-9A-Fa-f]{1,4}:){1}(('
'(:[0-9A-Fa-f]{1,4}){1,6})|((:[0-9A-Fa-f]{1,4}){0,4'
'}:((25[0-5]|2[0-4]\d|1\d\d|[1-9]?\d)(\.(25[0-5]|2['
'0-4]\d|1\d\d|[1-9]?\d)){3}))|:))|(:(((:[0-9A-Fa-f]'
'{1,4}){1,7})|((:[0-9A-Fa-f]{1,4}){0,5}:((25[0-5]|2'
'[0-4]\d|1\d\d|[1-9]?\d)(\.(25[0-5]|2[0-4]\d|1\d\d|'
'[1-9]?\d)){3}))|:)))(%.+)?')

print (reg.match("178.3.85.161").group())
try:
    print (reg.match("0.1.85.256").group())
except:
    pass

try:
    print (reg.match("2001::beeg").group())
except:
    pass
```

**Comment by bernhardreiter** [comment]
"2001::beeg" to match "2001::bee" seems okay as the latter is a regular ipv6 address.

**Comment by dmth** [comment]
> "2001::beeg" to match "2001::bee" seems okay as the latter is a regular ipv6 address.

No its not ok. The parser is creating valid data from obviously invalid data in this case.
This does result in wrong data, and finally in notifications which are sent to the wrong persons.

**Comment by bernhardreiter** [comment]
Am Montag 13 Februar 2017 15:40:20 schrieb Dustin Demuth:
> No its not ok. The parser is creating valid data from obviously invalid
> data in this case.

Well, if the data was invalid to begin with, it is a problem of the feed.
Something like      XXXXXXX2001::beeXXXXXXXXXXXXXXXXXXXX looks like 
an embedded ipv6 address to me?

What is a proper condition for the end of the field to be matched then?
Next character !=[0-9a-zA-Z] ?

(I could make an attempt to fix the regex if this is helpful, but I would need 
to have a good description of what it aims to do. Overall the regex seems to 
be a bit strange anyway).

**Comment by wagner-certat** [comment]
It's now guaranteed that there's no bogus data being passed by this parser. This is what the bug report was about. I thus consider this as fixed.

If someone wants fuzzy parsing, please open an appropriate issue.
