### ISSUE TITLE
New bot creation

### ISSUE THREAD

**Issue by shirio57** [certtools/intelmq#856]
I try to create a new bot. When I start it I have the error :

```
Traceback (most recent call last):
  File "./intelmq.bots.outputs.csv.output", line 9, in <module>
    load_entry_point('intelmq==1.0.0.dev6', 'console_scripts', 'intelmq.bots.outputs.csv.output')()
  File "/usr/lib/python3/dist-packages/pkg_resources.py", line 351, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python3/dist-packages/pkg_resources.py", line 2362, in load_entry_point
    raise ImportError("Entry point %r not found" % ((group,name),))
ImportError: Entry point ('console_scripts', 'intelmq.bots.outputs.csv.output') not found
```

How can I solve it ?

**Comment by dmth** [comment]
Hi @shirio57,

did you have a look at the other output bots?
Can you share the code of your bot with us and tell us how your are starting your bot?

**Comment by shirio57** [comment]
Hello

I re-used the code of the output file, I change the process, added some things in init() then I created the file intelmq.bots.outputs.csv.output under /usr/local/bin.
I try to start it with the web manager or with intelmqctl, it starts and then stop directly, no log files created, etc.
And when I start  intelmq.bots.outputs.csv.output, I have the error I mentioned in the previous post.


Code of intelmq.bots.outputs.csv.output:

__requires__ = 'intelmq==1.0.0.dev6'
import sys
from pkg_resources import load_entry_point

if __name__ == '__main__':
    sys.exit(
        load_entry_point('intelmq==1.0.0.dev6', 'console_scripts', 'intelmq.bots.outputs.csv.output')()
    )


The code of the output bot:

# -*- coding: utf-8 -*-
import io

from intelmq.lib.bot import Bot


class CsvBot(Bot):

    def init(self):
        self.keys = self.parameters.keys.split(',')
        self.substitutes = self.parameters.substitutes.split(',')

    def process(self):
        event = self.receive_message()

        open(self.parameters.file, 'a').close()

        with open(self.parameters.file, 'r+') as f:
            if f.read() == '':
                self.logger.info('Root does not exists, writting it.')
                f.write(self.parameters.root)
                f.write('\n')
                f.flush()

        with open(self.parameters.file, 'a+') as f:
            line = ''
            full_line = True
            for i in range(0, len(self.keys)):
                if event.contains(self.keys[i]):
                    value = event.get(self.keys[i])
                elif self.substitutes[i] != 'false' and event.contains(self.substitutes[i]):
                    value = event.get(self.substitutes[i])
                else:
                    full_line = False
                    break

                line = line + str(value) + ','

            if full_line:
                f.write(line)
                f.write("\n")
                f.flush()

        self.acknowledge_message()

BOT = CsvBot

**Comment by dmth** [comment]
Thanks for sharing this with us.
Can you reformat your post, please? 

You can add "code-blocks" like this: 

    ```
        MY CODE 
    ```

Also see https://guides.github.com/features/mastering-markdown/#GitHub-flavored-markdown

**Comment by shirio57** [comment]
Yes sorry, it is done now

**Comment by wagner-certat** [comment]
So you have created the executable `intelmq.bots.outputs.csv.output` manually? Then you also need to add the entry point.

Otherwise use pip to install the new codebase.

**Comment by dmth** [comment]
when installing it with `pip3 install . --upgrade`
your code can be started.

What do you need `self.parameters.root` for?

**Comment by shirio57** [comment]
Can you describe me a little bit more the step ? it is the first time I am using the new version of the code, I had a last version from one year ago :/

What I called ```self.parameters.root``` is the first line with the column names.
I am using as parameters:
```
"file": "<file_name>",
"keys": "souce.ip,classification.taxonomy,time.source,time.observation",
"substitutes": "false,false,time.observation,false",
"root": "IP addresse,Taxonomy,Score,Time source,Time observation,"
```

Keys are the part of the event to use.
Substitutes are the keys to use in case of one is not present, false means that the normal key had to be in the event
Root is the first line of the CSV, with the names of each columns

**Comment by dmth** [comment]
ok, I assume you have a recent copy of intelmq and read the instructions? 
https://github.com/certtools/intelmq/blob/master/docs/User-Guide.md#install

the parameter `--upgrade` forces pip3 to install even if it thinks the version-number is the same. This is very handy for development.

**Comment by dmth** [comment]
@wagner-certat 
>  Then you also need to add the entry point.

Can you explain how this 'entry_point' needs to be added in this case, or have I overlooked documentation?

**Comment by shirio57** [comment]
@dmth sorry I chedk in both user guide and developer guide and I didn't found something related to --upgrade :/

**Comment by dmth** [comment]
> @dmth sorry I chedk in both user guide and developer guide and I didn't found something related to --upgrade :/

no problem, does my explanation help you?
Also make sure you are using the python3 version of pip (`pip3` on some systems) because it might happen that you are having both python2.7 and python3 installed. Simply using `pip` might use python2.7

**Comment by shirio57** [comment]
No sorry I don't see.
I am using python and pip3 for sure, in which folder should I run the command ```pip3 install . --upgrade``` ?
Should I replaced the "." by something else ?

**Comment by wagner-certat** [comment]
You need to give the path where the setup.py of your project is.

**Comment by dmth** [comment]
>  in which folder should I run the command pip3 install . --upgrade

oh, I see. Use the folder to which you've cloned intelmq (a file `setup.py` can be found in there)
Maybe you even need to be root in order to install.

**Comment by shirio57** [comment]
Still not working, how can I make the entry_point manually ?

**Comment by wagner-certat** [comment]
How did you install intelmq? What OS do you use?

You can also join us at IRC on #intelmq at freenode

> @dmth sorry I chedk in both user guide and developer guide and I didn't found something related to --upgrade :/

Now it's there :) https://github.com/certtools/intelmq/blob/c0a7b77e6874bc6a5fcfd980d8c9ae535dce78a9/docs/Developers-Guide.md#installation

**Comment by dmth** [comment]
> Still not working, how can I make the entry_point manually ?

did you add your bot to `intelmq/bots/BOTS`?

**Comment by shirio57** [comment]
okay, issue solved : I found the entry_point.txt file and added ```intelmq.bots.outputs.file.output = intelmq.bots.outputs.file.output:BOT.run```

**Comment by dmth** [comment]
I could resolve this problem see: http://pastebin.com/KiWAft3f (will exist for one other week)

**Comment by dmth** [comment]
@shirio57 can you tell us exactly which commands you ran (from which path on your system) when the installation failed? This might help us to improve documentation and the setup process.

**Comment by wagner-certat** [comment]
For all others: Please just use pip to install intelmq as documented, **not** this broken `python3 setup.py` way.
