### ISSUE TITLE
Decide on docstring style for sphinx-apidoc / autodoc

### ISSUE THREAD

**Issue by bernhardreiter** [certtools/intelmq#857]
Intelmq is implemented in python3 thus I consider it agreeable that we use www.sphinx-doc.org as processor to generate our code documentation. (As opposed to the overview documentation which is independent and currently done in some Markdown variant.)

There seem be several styles for docstrings around (see http://www.sphinx-doc.org/en/stable/ext/autodoc.html#module-sphinx.ext.autodoc)
 * reStructuredText (the default of sphinx)
 * NumPy style
 * Google style

http://www.sphinx-doc.org/en/stable/ext/napoleon.html#module-sphinx.ext.napoleon is the sphinx plugin adding the two additional styles and comparing them. As we are python3, **my proposal is:**

 * Declare **module-sphinx.ext.napoleon "google style"** the default autodoc style for intelmq
 * Declare **python3 type annotations** as the way types SHOULD be documented

**Comment by bernhardreiter** [comment]
Up to now there are not many autodoc docstrings in the codebase (I have looked at a small sample of files). However it has been discussed as a way to document bots in the future in the comments of https://github.com/certtools/intelmq/pull/706 .

**Comment by wagner-certat** [comment]
I guess this is the doumentation for the Goolge style? https://google.github.io/styleguide/pyguide.html?showone=Comments#Comments

I'm fine with porting the docstrings to this style and then generate a proper configuration using sphinx.

Yet I used the numpy style for the libs because I know it (I simply used it in previous projects related to numpy/scipy).

**Comment by bernhardreiter** [comment]
@wagner-certat this is the link to the general description. While we shall more specifically use "sphinx-napoleon-google-type-annotation" style as described in: http://www.sphinx-doc.org/en/stable/ext/napoleon.html#type-annotations

(The first part of the description you've linked is a python standard recommendation anyway.)

I don't know how many docstrings we'll have to convert, but we'll certainly should say which is the prefered style (and put this in the right place for coding conventions).

What do others think?

**Comment by dmth** [comment]
I don't have a favourite style, but I concur we should agree on one style, and define this in the Contributing-Guidelines.

If in doubt, we should stick to the style which is already used (it's numpy, isn't it?)

**Comment by wagner-certat** [comment]
> If in doubt, we should stick to the style which is already used (it's numpy, isn't it?)

It's numpy yes, but it doesn't matter. There are only a few docstrings, which can easily be converted.

> While we shall more specifically use "sphinx-napoleon-google-type-annotation" style as described in: http://www.sphinx-doc.org/en/stable/ext/napoleon.html#type-annotations

I see examples with two sections: `Args:` and `Returns:`. Is a section like `Raises:` supported too?

**Comment by bernhardreiter** [comment]
>  Is a section like `Raises:` supported too?

http://www.sphinx-doc.org/en/stable/ext/napoleon.html#docstring-sections 
has "Raises", too.  (It will be the same sections as the ones supported for 
numpy-style).

**Comment by bernhard-herzog** [comment]
Both google-style and numpy-style seem fine to me. Just out of interest: is there a particular reason to prefer google-style? Also, the purpose of type annotations is more than just documentation. If we start using type annotations we need to decide how to specify those types, which is somewhat outside of the immediate purpose of this issue.

**Comment by bernhardreiter** [comment]
### google-style vs numpy-style
I've suggested google-style over numpy-style because I believe most of the docstrings for intelmq will shorter than longer and for shorter comments google-style reads better and saves some space. 

### Type hints
We should specify "Type Hints" like [PEP 484](https://www.python.org/dev/peps/pep-0484/), I've did some experiments yesterday and the drawback is that we would require the module ["typing"](https://pypi.python.org/pypi/typing/3.5.3.0) for more complex types. Typing comes with the standard library of Python 3.5, but is also available as "backport".

**Comment by wagner-certat** [comment]
Type hints are not possible in 3.3 and 3.4 which are still supported by intelmq :/

**Comment by bernhardreiter** [comment]
@wagner-certat they are possible since python 3.0. Only if we want to use the more complex types from PEP 484, we need to use the backport of "typing" for the python version 3.3 and 3.4.

**Comment by wagner-certat** [comment]
Could you have a look at c4dcf7773a4c85d4aa9c54ec24c460b2da82b682 and check if this is the correct style?

**Comment by bernhardreiter** [comment]
@wagner-certat I've looked at the first function, see my comment there. Overall I think that you've matched the style description, minus that you can leave out the types in the docstrings where they are already given in type hints. However we probably have to think about type hints in a larger context and do a test. I think that correct style would be if sphinx produces something sensible.

So regarding type hints:
 * If we give types at all, a type hint is the better place compared to the docstring parameter. It is the better place, because it will partially be checked by the compiler (of the python3 binary, which will check that it is a valid expression) and it can be checked by additional type checkers. 
 * The problem arises for more complex types like ```Union[bytes, str]``` which would the right type for decode(text) in the mentioned diff. Union comes from the module typing. Beside that we could make this module a dependency, it also takes time for developers to learn how to write more complex type hints.

A potential solution is: we only give simple types in the type hints and more complex types as description in the docstrings. For this to work we should check if sphinx will create a nice documentation when mixing those two "substyles" within in one function definition.

**Comment by wagner-certat** [comment]
I pushed an updated commit: 660fb82
It now uses typing, can you have a look if it's correctly used?

**Comment by bernhardreiter** [comment]
@wagner-certat briefly lookint at https://github.com/certtools/intelmq/commit/660fb829f29b7c1532065dc0ad52fa9eb5cff16d, it looks good. Now I recommend letting sphinx run on it to see if it produces the expecting results. (And possibly one of the optional type checkers.)

**Comment by wagner-certat** [comment]
Thanks.

As I'd need to look up how to set up sphinx, and it's not important for the next days/weeks, this will take some time now.

**Comment by bernhardreiter** [comment]
Same here. But I believe it is good that we have a candidate style.

**Comment by swilde** [comment]
FWIW: I do support the idea of using google style doc strings.  I prefer google over numpy for being more concise.  Using type anotiation (as opposed to only documenting them in the doc string)  would be good, too.  I support the idea of static type checking, but as @bernhard-herzog pointed out, this will need some more thinking, which is basically orthogonal to the documentation issue.
