### ISSUE TITLE
Shadowserver Open-LDAP key mapping

### ISSUE THREAD

**Issue by dmth** [certtools/intelmq#864]
Whilst looking at shadowserver's Open-LDAP we discovered that the mapping  `dns_host_name` to `destination.local_hostname` might not be optimal. `source.local_hostname` would be a better choice for this feed.

https://github.com/certtools/intelmq/blob/master/intelmq/bots/parsers/shadowserver/config.py#L1171

We are going to provide a PR for this.

Slightly relates to #833

**Comment by wagner-certat** [comment]
You are right, this should be attributed to the source.

**Comment by dmth** [comment]
Migrations required for installations of IntelMQ after this Change:

1) Modify EventDB in order to move all events which were classified the old way.
2) Update Filter-Experts which depend on this Key.

We are also going to provide a statement for 1)

**Comment by swilde** [comment]
You can fix existing event databases with this statement:
```
UPDATE events
   SET "source.local_hostname"="destination.local_hostname",
       "destination.local_hostname"=DEFAULT
 WHERE "feed.name"='Open-LDAP' AND "source.local_hostname" IS NULL;
```
