### ISSUE TITLE
TCP Output

### ISSUE THREAD

**Issue by rmsferreira** [certtools/intelmq#881]
I`m having the next error, can you help me please:

```
File "/usr/local/lib/python3.5/dist-packages/intelmq/lib/bot.py", line 145, in start
    self.process()
  File "/usr/local/lib/python3.5/dist-packages/intelmq/bots/outputs/tcp/output.py", line 18, in process
    data = event.to_json(hierarchical=self.parameters.hierarchical_output)
AttributeError: 'Parameters' object has no attribute 'hierarchical_output'
```

EDIT 2017-02-13T14:34 by @wagner-certat: syntax

**Comment by SYNchroACK** [comment]
hierarchical_output parameter is indeed missing on docs/Bots.md. Please, add to your bot configuration that parameter like `hierarchical_output=false`

Thank for raising this one, is at least a bug in documentation.

**Comment by wagner-certat** [comment]
Thanks, fixed.
