### ISSUE TITLE
Strip API Keys from feed URLs in parsers

### ISSUE THREAD

**Issue by wagner-certat** [certtools/intelmq#889]
Follow up of #796 

There are some feeds which use API keys in URLs:

 - [x] ~~Alienvault OTX~~ (does not save the key at all)
 - [x] AnubisNetworks Cyberfeed
 - [x] MalwarePatrol Dans Guardian
 - [x] PhishTank

According to my colleagues, they should not end up in the events itself. Do you agree?

**Comment by dmth** [comment]
> According to my colleagues, they should not end up in the events itself. Do you agree?

Yes.

**Comment by wagner-certat** [comment]
- [ ] Spamhaus CERT
