### ISSUE TITLE
useability: add an "enable" command in intelmqctl

### ISSUE THREAD

**Issue by aaronkaplan** [certtools/intelmq#897]
It would be very easy for the shell scripters and orchestrators amongst us, to have an "intelmqctl {enable, disable} <bot>" command.

This shall set or clear the enable parameter of the bot (if the bot exists).

this is similar to the update-d.rc enable <service> in init.d

**Comment by wagner-certat** [comment]
This is part of #846

**Comment by SYNchroACK** [comment]
@wagner-certat as far I can see, the documentation does not say that and at least me did not have the opportunity to discuss a final proposal from your side regarding enable/disable etc...

**Comment by wagner-certat** [comment]
> as far I can see, the documentation does not say that

https://github.com/certtools/intelmq/blob/master/docs/User-Guide.md#command-line-interface-intelmqctl
The docs/intelmqctl.md was created after that PR/code has been created, I will update that file.

> and at least me did not have the opportunity to discuss a final proposal from your side regarding enable/disable etc...

See #846. It only set's the already existing parameters in runtime.conf. There's no "new" behavior regarding the "enabled" flag.

**Comment by wagner-certat** [comment]
>  The docs/intelmqctl.md was created after that PR/code has been created, I will update that file.

done
