### ISSUE TITLE
New Modify Bot Format

### ISSUE THREAD

**Issue by mf370** [certtools/intelmq#900]
This is not an issue, is a doubt regarding the new Modify Bot Format.
Is it possible add another pair of "if-then" in the same rule? For example:
```
[
    {
        "rule": "others",
        "if": {
            "source.asn": "regex"
        },
        "then": {
            "event_description.target": "others"
        },
       "if":
           "destinations.asn": "regex"
        },
        "then": {
            "event_description.target": "others"
        }
    }
]
```
Thank you.

**Comment by aaronkaplan** [comment]
> On 02 Mar 2017, at 11:34, mf370 <notifications@github.com> wrote:
> 
> This is not an issue, is a doubt regarding the new Modify Bot Format.
> Is it possible add another pair of "if-then" in the same rule? For example:
> 
> [
>     {
>         "rule": "others",
>         "if": {
>             "source.asn": "regex"
>         },
>         "then": {
>             "event_description.target": "others"
>         },
>        "if":
>            "destinations.asn": "regex"
>         },
>         "then": {
>             "event_description.target": "others"
>         }
>     }
> ]
> 

Currently not, but it's an idea that should not be that hard to implement.
Looks like an inner for loop for all the if-conditions.


Best,
a.

**Comment by aaronkaplan** [comment]
> On 02 Mar 2017, at 12:16, L. Aaron Kaplan <aaron@lo-res.org> wrote:
> 
> 
(...)

sorry, I was unprecise.

> Currently not,

--> Currently this is not possible

> but it's an idea that should not be that hard to implement.
> Looks like an inner for loop for all the if-conditions.
> 
> 
> Best,
> a.

**Comment by wagner-certat** [comment]
> Is it possible add another pair of "if-then" in the same rule?

What would be the difference between two rules and one rule with two conditions.

> Currently not, but it's an idea that should not be that hard to implement.

Dictionaries with duplicate key names are not possible.
