### ISSUE TITLE
n6 parser: mapping is modified within each run

### ISSUE THREAD

**Issue by wagner-certat** [certtools/intelmq#905]
I'm not sure what this code means but it looks very much like a code smell/bug:
```python
        if ("name" in dict_report):
            mapping['bots']['identifier'] = dict_report["name"]
        else:
            mapping['bots']['identifier'] = "generic-n6-drone"
```
https://github.com/certtools/intelmq/blob/476c8980b551212728b31a11fc4ca0ffc83ee94f/intelmq/bots/parsers/n6/parser_n6stomp.py#L113

**Comment by aaronkaplan** [comment]
confirmed, it's a bug.
