### ISSUE TITLE
Parameter from BOTS does'nt passed to a new bot

### ISSUE THREAD

**Issue by kitophe** [certtools/intelmq#908]
Hi,

I'm trying to develop a new bot as collector for Censys source.
I would like to put API ID & secret directly in BOTS file instead of runtime.conf (as a template), but it's not interpreted by lib (in runtime.conf it's works).

```python
intelmqctl: Running intelmqctl as root is highly discouraged!
intelmqctl: Starting censys...
censys: CensysCollectorBot initialized with id censys and version 3.4.2 (default, Oct  8 2014, 10:45:20) as process 8944.
censys: Bot is starting.
censys: Bot initialization failed.
Traceback (most recent call last):
  File "/usr/local/lib/python3.4/dist-packages/intelmq/lib/bot.py", line 78, in __init__
    self.init()
  File "/usr/local/lib/python3.4/dist-packages/intelmq/bots/collectors/censys/collector.py", line 25, in init
    print(self.parameters.secret)
AttributeError: 'Parameters' object has no attribute 'secret'
censys: Bot stopped.
censys: Exiting.
Bot exited with code 1.
```

in BOTS:
```json
    "Collector": {
        "Censys": {
            "description": "Censys acess",
            "module": "intelmq.bots.collectors.censys.collector",
            "parameters": {
                "feed": "Censys",
                "provider": "Censys",
                "api_id": "retest",
                "secret": "test",
                "rate_limit": 5
            }
        },
```

Runtime.conf:
```json
   "censys": {
        "parameters": {
            "query": "keyword"
        },
        "group": "Collector",
        "name": "Censys",
        "module": "intelmq.bots.collectors.censys.collector",
        "description": "Censys"
```

In the collector.py:
```python
# -*- coding: utf-8 -*-
"""
CENSYS collector bot

Parameters:
api_id: string
secret: string
http_verify_cert: boolean
    default: True
http_username, http_password: string
http_proxy, https_proxy: string
http_timeout: tuple of two floats or float
"""
import json

from intelmq.lib.bot import CollectorBot

from .censys import CENSYS

class CensysCollectorBot(CollectorBot):

    def init(self):
        self.set_request_parameters()
        print(self.parameters.secret)
```

Do you have any idea ?

Regards,

Christophe

EDIT by @wagner-certat on 2017-03-07T11:17+01: markup

**Comment by wagner-certat** [comment]
> I would like to put API ID & secret directly in BOTS file instead of runtime.conf (as a template), but it's not interpreted by lib (in runtime.conf it's works).

The BOTS file is never read by the bots, it's contains the templates for configuration. So if you update the BOTS, but not the runtime.conf, the bot will not be aware of it. The values in BOTS are (currently!) not read as default values (we want to change this in the near future #757 ).

What are you trying to achieve?

**Comment by kitophe** [comment]
Thanks for your quick response.
I would like to add new collector with Censys API (Shodan like) to set keywords to search and provide results in IntelMQ.

**Comment by wagner-certat** [comment]
>  I would like to add new collector with Censys API (Shodan like) to set keywords to search and provide results in IntelMQ.

To configure the bot "censys" in your setup, set the parameter values (api_id, secret, etc) accordingly in your `runtime.conf`(you only have `query` there).

Please consider using the IRC or mailinglist for questions, not the bug tracker.

**Comment by einar-lanfranco** [comment]
Hi @kitophe did you write it?
