### ISSUE TITLE
Tutorial VM with shadowserver demo data

### ISSUE THREAD

**Issue by aaronkaplan** [certtools/intelmq#948]
- [ ] make a VM which has a demo intelmq instance.
- [ ] upload the demo VM to the intelmq homepage / github
- [ ] Debian VM shall contain
    - [x] file input collector with dummy data for selected shadowserver feeds
    - [ ] local postresql DB for contact lookups (ASN to email address). Attendees might want to change this  (in case there is internet access)
    - [x] mail client & server to accept locally sent emails to local addresses (see above)
    - [x] ASN lookups via fixed downloaded IP2ASN DB (no updates needed)
    - [ ] fixed set of maxmind IP 2 country lookup DB
    - [x] Mail output bot (#946)
    - [x] default config files which are tailored to the tutorial.
    - [ ] users need to follow the tutorial to turn on/off certain config options in intelmq in order to succeed.
    - [x] success will be the reception of emails from the demo VM with the enriched shadowserver data

- [ ] tutorial text developed by SS

**Comment by dmth** [comment]
> mail client & server to accept locally sent emails to local addresses (see above)

have a look at "dsmtp" (as described in https://github.com/Intevation/intelmq-mailgen#testing) this will drop all mails into a Mail-Dir. You can browse this dir with mutt, or other software.

**Comment by aaronkaplan** [comment]
Cool! Thanks for the hint

---
Mobile

**Comment by wagner-certat** [comment]
we now have a working VM which has all features except for:
* local postgres db lookup, we send to `intelmq+[asn]@localhost` anyway
* maxmind lookup: I don't have any data to share

**Comment by wagner-certat** [comment]
Done
