### ISSUE TITLE
codestyle: avoid 'bare excepts'

### ISSUE THREAD

**Issue by bernhardreiter** [certtools/intelmq#959]
Python's PEP8 style guide recommends to avoid 'bare excepts', see the quote in https://github.com/PyCQA/pycodestyle/issues/579 .

Pycodestyle's E722 warns against bare excepts.
Here is a run with 9ae778cff9363e85b24ae4e1928fd4fd222c220e
and pycodestyle v2.3.1:
```
pycodestyle --select=E722
./intelmq/bots/parsers/shadowserver/parser.py:137:21: E722 do not use bare except'
./intelmq/bots/outputs/postgresql/output.py:46:9: E722 do not use bare except'
./intelmq/bots/outputs/redis/output.py:26:9: E722 do not use bare except'
./intelmq/bots/outputs/udp/output.py:48:9: E722 do not use bare except'
./intelmq/bots/outputs/tcp/output.py:35:9: E722 do not use bare except'
./intelmq/bots/experts/cymru_whois/lib.py:131:13: E722 do not use bare except'
./intelmq/bots/experts/ripencc_abuse_contact/expert.py:49:9: E722 do not use bare except'
./intelmq/bots/experts/generic_db_lookup/expert.py:40:9: E722 do not use bare except'
./intelmq/bots/experts/abusix/lib.py:30:9: E722 do not use bare except'
./intelmq/lib/bot.py:65:9: E722 do not use bare except'
./intelmq/lib/bot.py:259:9: E722 do not use bare except'
./intelmq/lib/bot.py:393:9: E722 do not use bare except'
```

The code should be more clear and indicate if the bare except is on purpose or not
by using the explicit Exception or BaseException classes as indicated in pep8 and some comments
why this is the wanted behaviour I guess. :)

**Comment by wagner-certat** [comment]
Already on my agenda too :)

**Comment by bernhardreiter** [comment]
@wagner-certat good! Then we can remove the ignore-E722-setting for pycodestyle.  
(I had pondered if I should directly proposes changes while preparing https://github.com/certtools/intelmq/pull/960 but felt that I do not understand the structure well enough to come up with the right meaning.)
