### ISSUE TITLE
AlienVaultOTX api key invalid

### ISSUE THREAD

**Issue by Roslekas** [certtools/intelmq#964]
Hi,

several times tried to regenerated API KEY, but same error:

![image](https://cloud.githubusercontent.com/assets/16913780/25740742/72bdd00e-3190-11e7-8812-05c5ebe8d7d7.png)

Have any thoughts ?
Thanks

**Comment by Roslekas** [comment]
Also tried :/
![image](https://cloud.githubusercontent.com/assets/16913780/25740963/68903710-3191-11e7-9f7a-17ddf566db84.png)

**Comment by wagner-certat** [comment]
If you can't connect with curl too, it's probably not the bot's fault.

**Comment by Roslekas** [comment]
Yes, seems problem is with bot, tried another api key and it worked.
Thanks

**Comment by wagner-certat** [comment]
Let me try to understand your setup:
You have 2 API keys. We name them key 1 and key 2
You tried key 1 with the bot and you got 403. You tried key 1 with curl and you got.
You tried key 2 with the bot or curl and it worked.
Is this correct?

P.S.: The api key in your screenshot is poorly obfuscated.

**Comment by Roslekas** [comment]
Yes its correct, something wrong was with api key, not a bot, my fault.
Sorry
