### ISSUE TITLE
Can't Install IntelMQ on CentOS7

### ISSUE THREAD

**Issue by mf370** [certtools/intelmq#978]
I'm trying to install IntelMQ on a CentOS7, but I'm having some issues. 

I installed all the dependencies without any problems. Then I followed the exact instructions for the installation as native deb/rpm package. And I got the following errors:

```
Error: Package: python3-intelmq-1.0.0.dev7-1.1.noarch (home_sebix_intelmq)
           Requires: python3-dateutil >= 2.5.0
Error: Package: python3-requests-2.11.1-53.3.noarch (home_sebix_intelmq)
           Requires: python3-py
Error: Package: python3-intelmq-1.0.0.dev7-1.1.noarch (home_sebix_intelmq)
           Requires: python3-redis
Error: Package: python3-intelmq-1.0.0.dev7-1.1.noarch (home_sebix_intelmq)
           Requires: python3-psutil
```

I've looked for these packages everywhere but they don't seem to exist.. I mean, I found them but under a different name, and even if try to install them, it still gives me these errors.

Then I tried the other two installations: Pypi and the local repository, once again, I followed the exact same instructions but the paths `/opt/intelmq/etc/` and `/opt/intelmq/var/ `are not created.

**Comment by wagner-certat** [comment]
Thanks for reporting this. I see that dateutil and py are called `python34-...` in EPEL. And I need to package redis and psuti.

**Comment by wagner-certat** [comment]
It should work now.
I don't have CentOS here, but the installation of intelmq works in the build environment for intelmq-manager, so the dependencies do work.

> Then I tried the other two installations: Pypi and the local repository, once again, I followed the exact same instructions but the paths /opt/intelmq/etc/ and /opt/intelmq/var/are not created.

That's tracked in #819
