### ISSUE TITLE
Bots Started by IntelMQ Manager Won't Stop

### ISSUE THREAD

**Issue by mf370** [certtools/intelmq#981]
I managed to install IntelMQ in a CentOS 7. And I used the following commands:
```
yum install epel-release
yum install python34 python34-devel
yum install git gcc gcc-c++
yum install redis
curl "https://bootstrap.pypa.io/get-pip.py" -o "/tmp/get-pip.py"
python3.4 /tmp/get-pip.py
systemctl enable redis
systemctl start redis
pip3 install typing

git clone https://github.com/certtools/intelmq.git /tmp/intelmq
cd /tmp/intelmq
sudo -s

pip3 install -r REQUIREMENTS
pip3 install .

useradd -d /opt/intelmq -U -s /bin/bash intelmq
chmod -R 0770 /opt/intelmq
chown -R intelmq.intelmq /opt/intelmq
cd /opt/intelmq/etc
cp -a examples/* .
```
Then I had to copy the files `.bashrc` and ` .bash_profile` from the directory `/root` to the directory `/opt/intelmq/` because everytime I tried to change to the intelmq user, instead of appearing `[intelmq@localhost]$` it would appear `bash-4.2$`.

After this I installed IntelMQ Manager with the following commands:
```
yum install git httpd php
systemctl enable httpd
systemctl start httpd

git clone https://github.com/certtools/intelmq-manager.git /tmp/intelmq-manager
cp -R /tmp/intelmq-manager/intelmq-manager/* /var/www/
chown -R apache.apache /var/www/html/
```
```
sed -i 's|Defaults    requiretty|Defaults    !requiretty|g' /etc/sudoers

usermod -a -G intelmq apache
```

I added this line to the visudo file:
`apache ALL=(intelmq) NOPASSWD: /usr/bin/intelmqctl`

```
sed -i 's|#!/usr/bin/env python|#!/usr/bin/env python3.4|g' /usr/bin/intelmqctl
sed -i 's|SELINUX=enforcing|SELINUX=disabled|g' /etc/selinux/config

firewall-cmd --add-service http
firewall-cmd --add-service http --permanent

reboot
```

And the problem is: if I start/stop the bots using` intelmqctl ` it works perfectly, but if I start the bots using IntelMQ Manager they will start normally, but if I try to stop them it won't do anything. I also tried to stop them with `intelmqctl` after they were started by IntelMQ Manager and this is what happens:

```
[intelmq@localhost intelmq]$ intelmqctl stop ip-fileinput-collector
intelmqctl: Stopping ip-fileinput-collector...
intelmqctl: ip-fileinput-collector is still running.
```
And if I go to the `intelmqctl `log file it shows this:
```
2017-05-26 11:49:10,969 - intelmqctl - INFO - Stopping ip-fileinput-collector...
2017-05-26 11:49:11,472 - intelmqctl - ERROR - ip-fileinput-collector is still running.
```

Do you know what may be causing this? Have I failed something during the installation?

**Comment by wagner-certat** [comment]
Are the bots running with the user intelmq or something else if started by the manager?
As user apache, can you stop the bots with this manually? `sudo -u intelmq /usr/bin/intelmqctl stop bot-id`.

Does the managers's config.php have the correct path to your intelmqctl?

**Comment by mf370** [comment]
> Are the bots running with the user intelmq or something else if started by the manager?

Yes, they are running with the intelmq user

> As user apache, can you stop the bots with this manually? `sudo -u intelmq /usr/bin/intelmqctl stop bot-id`.

No, with the user apache it gives me the following error: 
```
Traceback (most recent call last):
  File "/usr/lib64/python3.4/site-packages/psutil/__init__.py", line 1231, in _send_signal
    os.kill(self.pid, sig)
PermissionError: [Errno 1] Operation not permitted

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/bin/intelmqctl", line 11, in <module>
    load_entry_point('intelmq==1.0.0.dev7', 'console_scripts', 'intelmqctl')()
  File "/usr/lib/python3.4/site-packages/intelmq/bin/intelmqctl.py", line 866, in main
    return x.run()
  File "/usr/lib/python3.4/site-packages/intelmq/bin/intelmqctl.py", line 512, in run
    results = args.func(**args_dict)
  File "/usr/lib/python3.4/site-packages/intelmq/bin/intelmqctl.py", line 534, in bot_stop
    return self.bot_process_manager.bot_stop(bot_id, getstatus)
  File "/usr/lib/python3.4/site-packages/intelmq/bin/intelmqctl.py", line 185, in bot_stop
    proc.send_signal(signal.SIGINT)
  File "/usr/lib64/python3.4/site-packages/psutil/__init__.py", line 343, in wrapper
    return fun(self, *args, **kwargs)
  File "/usr/lib64/python3.4/site-packages/psutil/__init__.py", line 1253, in send_signal
    self._send_signal(sig)
  File "/usr/lib64/python3.4/site-packages/psutil/__init__.py", line 1242, in _send_signal
    raise AccessDenied(self.pid, self._name)
psutil.AccessDenied: psutil.AccessDenied (pid=2459)
```
But with the user intelmq it does the following:
```
[intelmq@localhost log]$ sudo -u intelmq /usr/bin/intelmqctl stop abusech-ip-parser
intelmqctl: Stopping abusech-ip-parser...
intelmqctl: abusech-ip-parser is still running
```
> Does the managers's config.php have the correct path to your intelmqctl?

Yes, it has.

So, I think I'm having some problems with permissions, the file intelmqctl.py was owned by the root user, and I changed it to the intelmq user, but it didn't solve the problem.

**Comment by wagner-certat** [comment]
That's interesting, so even when using `sudo -u intelmq` the `apache`-user is not allowed to kill processes owned by `intelmq`.

Is this behavior specific to intelmq? You could test that by spawning a process like netcat as user intelmq and try to kill it the same way you would kill the intelmq bots.

**Comment by mf370** [comment]
> Is this behavior specific to intelmq? You could test that by spawning a process like netcat as user intelmq and try to kill it the same way you would kill the intelmq bots.

I think it is, I've used IntelMQ in Ubuntu14/16 and I never had a problem like this before.. 
I've never used netcat, but I'll install it and try a few tests. Thank you :)

**Comment by dmth** [comment]
Not sure if relevant, but does CentOS 7 use SELinux which might cause this?

**Comment by wagner-certat** [comment]
According to the explanations above, it has been deactivated in `/etc/selinux/config`, then a reboot.

Anyway, can you show the output of `sestatus`?

**Comment by mf370** [comment]
Here it is:
```
[intelmq@localhost ~]$ sestatus
SELinux status:                 disabled
```

**Comment by mf370** [comment]
I restarted `apache` and tried again the command `sudo -u apache /usr/bin/intelmqctl start abusech-ip-parser` and it worked, the bot started running. Then I tried to stop it using IntelMQ Manager and it gave me the following error:

`Error stopping bot: SyntaxError: JSON.parse: unexpected end of data at line 1 column 1 of the JSON data`

**Comment by dmth** [comment]
> According to the explanations above, it has been deactivated in /etc/selinux/config, then a reboot.

Oh, sorry I just skimmed through the text and did not see that line.

**Comment by mf370** [comment]
I restarted `apache` and tried again the command `sudo -u apache /usr/bin/intelmqctl start abusech-ip-parser` and it worked, the bot started running. Then I tried to stop it using IntelMQ Manager and it gave me the following error:

`Error stopping bot: SyntaxError: JSON.parse: unexpected end of data at line 1 column 1 of the JSON data`

**Comment by dmth** [comment]
> ```Error stopping bot: SyntaxError: JSON.parse: unexpected end of data at line 1 column 1 of the JSON data```

Does `/var/log/apache2/error.log` contain any useful information?

**Comment by wagner-certat** [comment]
@mf370 That's most probably due to the `PermissionError` not caught by the intelmqctl. But if we caught it, you coulnd't stop it either.

Did you try to kill another process (!= intelmq) as user apache? I think something on your system is prohibits sending signals as user apache.

**Comment by wagner-certat** [comment]
> I think it is, I've used IntelMQ in Ubuntu14/16 and I never had a problem like this before..

Which proves it could be CentOS-specific.

> I've never used netcat, but I'll install it and try a few tests. Thank you :)

You can anything which is killable by SIGiNT and does wait. I suspect that sleep may be more sensible to signals, but maybe that's not true for the shell.

**Comment by mf370** [comment]
@dmth I'm looking at the log files now and I found these two messages:

```
[Mon May 29 11:49:27.064013 2017] [core:notice] [pid 938] AH00094: Command line: '/usr/sbin/httpd -D FOREGROUND'
AH00558: httpd: Could not reliably determine the server's fully qualified domain name, using localhost.localdomain. Set the 'ServerName' directive globally to suppress this message
```

**Comment by wagner-certat** [comment]
On 05/30/2017 10:00 AM, mf370 wrote:
>
> @dmth <https://github.com/dmth> I'm looking at the log files now and I
> found these two messages:
>
> |[Mon May 29 11:49:27.064013 2017] [core:notice] [pid 938] AH00094:
> Command line: '/usr/sbin/httpd -D FOREGROUND' AH00558: httpd: Could
> not reliably determine the server's fully qualified domain name, using
> localhost.localdomain. Set the 'ServerName' directive globally to
> suppress this message |
|Nothing related here :/|

**Comment by dmth** [comment]
> |Nothing related here :/|

yes, unfortunate....

@mf370 thanks for looking.

**Comment by mf370** [comment]
@wagner-certat I can't kill other processes as `apache` it says: `Operation not permitted`

Do you have any guidelines on how to install IntelMQ Manager on a CentOS 7? I'm pretty sure that something went wrong during the installation. Thank you!

**Comment by wagner-certat** [comment]
> @wagner-certat I can't kill other processes as `apache` it says: `Operation not permitted`

Then it is probably not related to IntelMQ. I'd recommend to ask this question in CentOS communities, they do know this system much better than I do. If a change in IntelMQ is needed, we can implement that.

> Do you have any guidelines on how to install IntelMQ Manager on a CentOS 7? I'm pretty sure that something went wrong during the installation. Thank you!

Not more than we have in the documentation (which you posted above), no. I basically have no experience with this system. I'd welcome any improvements!

**Comment by mf370** [comment]
Alright! Thank you for your help @wagner-certat :)

**Comment by wagner-certat** [comment]
I opened certtools/intelmq-manager#103 for this. Closing here.
